### ISSUE TITLE
Multi Select on last version layout issue

### ISSUE THREAD

**Issue by trippo** [PH7-Jack/livewire-ui#103]
The remove button of selected options are a mini input field.
You can test also on demo doc page https://livewire-wireui.com/docs/select 

![image](https://user-images.githubusercontent.com/497169/138047310-48029031-d70c-4efd-939a-4024a51b029d.png)

**Comment by ph7jack** [comment]
Thanks for reporting this

**Comment by ph7jack** [comment]
It is now fixed, thanks
