### ISSUE TITLE
Change z-index

### ISSUE THREAD

**Issue by aliqasemzadeh** [PH7-Jack/livewire-ui#112]
Hi 
When I want to use select in livewireui/modal it hide dropdown items and select option.
This happen becasue of z-index.
Please check it.

**Comment by ph7jack** [comment]
@alighasemzadeh can you give one screenshot or example?

**Comment by aliqasemzadeh** [comment]
![16352489245352156622473411209047](https://user-images.githubusercontent.com/26847446/138871894-44a1d060-d7b9-49be-a66e-9785a9f7c6b5.jpg)
@PH7-Jack 
Check it please items of select hided in modal.

Note: I am using livewire-ui/modal

**Comment by ph7jack** [comment]
@alighasemzadeh I think that the problem is the `overflow-hidden` class in this modal. Can check it for me? Remove this class in the "inspect element"
https://github.com/livewire-ui/modal/blob/main/resources/views/modal.blade.php#L46

**Comment by aliqasemzadeh** [comment]
It works.
![16353332051542096999757434530787](https://user-images.githubusercontent.com/26847446/139055170-9a4b3f7d-89ef-4657-adc5-11a2aa650bb2.jpg)
@PH7-Jack 
How to fix this for any people?

**Comment by ph7jack** [comment]
@alighasemzadeh open a pull request removing this class into **livewire-ui/modal** or use the WireUI modal instead

**Comment by aliqasemzadeh** [comment]
@PH7-Jack I like your package just modal should be like livewire-ui/modal.
And also persian datepicker.

**Comment by ph7jack** [comment]
I'm closing it because is a WireElements issue

**Comment by byrmylmz** [comment]
> @alighasemzadeh I think that the problem is the `overflow-hidden` class in this modal. Can check it for me? Remove this class in the "inspect element" https://github.com/livewire-ui/modal/blob/main/resources/views/modal.blade.php#L46

Thank you so much.
