### ISSUE TITLE
acceptLabel doesn't work on confirm dialog simple syntax

### ISSUE THREAD

**Issue by trippo** [PH7-Jack/livewire-ui#113]
**Describe the bug**
In the simple syntax of confirm dialog, the acceptLabel doesn't work and only the cancel button appears.
With the full syntax work fine

**To Reproduce**
```php
$this->dialog()->confirm([
            'title'       => 'Are you Sure?',
            'description' => 'Save the information?',
            'acceptLabel' => 'Yes, save it',
            'method'      => 'save',
            'params'      => 'Saved',
        ]);
```

**Comment by ph7jack** [comment]
@trippo can check if has any error in the console or the network?

**Comment by trippo** [comment]
Sorry for delay i think it was a browser cache problem
