### ISSUE TITLE
Bootstrap Support

### ISSUE THREAD

**Issue by aliqasemzadeh** [PH7-Jack/livewire-ui#119]
Hi
What do you think about bootstrap UI?

**Comment by ph7jack** [comment]
Hello @alighasemzadeh 

I like the bootstrap, is a good CSS framework, but, tailwind is better in my opinion. 
The WireUI will officially support only the Tailwind CSS

I'm closing this issue because bootstrap not will be supported. 
If you want to talk more about this, open a discussion

**Comment by aliqasemzadeh** [comment]
@PH7-Jack 
Yes tailwind is good.
But boostrap have better templates around the web.
