### ISSUE TITLE
Problema no Currency Input

### ISSUE THREAD

**Issue by Tiagospem** [PH7-Jack/livewire-ui#123]
Estou utilizando o **[currency input](https://livewire-wireui.com/docs/currency-input)** para valores em reais

`<x-inputs.currency thousands="." precision="2" decimal="," wire:model.lazy="auction.tax" />`

Ao digitar o valor **R$ 1.250,20**, dentro do input é exibido  conforme o esperado.

O campo envia a informação sem a formatação: `$this->auction->tax = 1250.20 `

Quando eu busco o valor **1250.20** através do `wire:model.lazy="auction.tax"`

A formatação no input é exibida da seguinte forma **R$ 125.050**

**Comment by ph7jack** [comment]
Thanks for reporting this. It is now fixed. Enjoy the Wireui
