### ISSUE TITLE
masked input does not play well with Danish hardware keyboard on IPad

### ISSUE THREAD

**Issue by rabol** [PH7-Jack/livewire-ui#128]
**Describe the bug**
When using the masked input, with an IPad and a Danish keybord, one cannot used the + sign.
when the + sign is pressed a ( appears

go to the examples page and use IPad with non english hardware keyboard and try to enter + in one of the masked input controls

**Expected behavior**
Expected that a + appeard instead of a (

**Screenshots**

 - OS: Ios 15.1
 - Browser safari
 - Version

**Comment by ph7jack** [comment]
@rabol Can you create a video with this issue?
Show the maskable input code too

**Comment by rabol** [comment]
here is the code

```

<x-inputs.maskable
    label="Maskable Input"
    mask="['(###) ###-####', '+# ### ###-####', '+## ## ####-####']"
    placeholder="Phone number"
/>

```

from your dokumentation page

https://livewire-wireui.com/docs/maskable-inputs

I’ll try to see how I can make a video

**Comment by ph7jack** [comment]
@rabol you can use the https://www.loom.com to record a video

**Comment by rabol** [comment]
hope this is ok

https://www.loom.com/share/da42284e0eeb4b3e84ff9dfd0af69491

**Comment by ph7jack** [comment]
@rabol this video is private?

**Comment by rabol** [comment]
https://www.loom.com/share/da42284e0eeb4b3e84ff9dfd0af69491 -  it should be public as far as I can see

**Comment by ph7jack** [comment]
You are clicking in one number, and only the "(" is inserted?

**Comment by rabol** [comment]
yes, but I'm actually pressing the + (plus sign) on the keyboard and ( is displayed

**Comment by ph7jack** [comment]
You don't need to add any formatting value. Try press only numbers to see the dynamic formatting 

Ex: 1234...

**Comment by rabol** [comment]
aha... got it now, the formatting will change depending on the number of digits entered
![Screen Shot 2021-11-16 at 14 50 52](https://user-images.githubusercontent.com/1177191/141997603-09f75b01-6383-48fb-a9b4-6bd60eded336.png)
