### ISSUE TITLE
WireUiAssetsController::scripts()  Return value must be of type BinaryFileResponse

### ISSUE THREAD

**Issue by labomatik** [PH7-Jack/livewire-ui#132]
**Describe the bug**
The error encountered in production:
`TypeError: WireUi\Controllers\WireUiAssetsController::scripts(): Return value must be of type Symfony\Component\HttpFoundation\BinaryFileResponse, Illuminate\Http\Response returned
`
**To Reproduce**
No idea on how to reproduce

Do you have any idea what could be the cause? a user logged out?

**Comment by ph7jack** [comment]
Hello @labomatik 
What's the WuireUi version in your production?
This bug was fixed in past releases

**Comment by labomatik** [comment]
0.11.6  🤦‍♂️
