### ISSUE TITLE
wireui_inputs_currency is not defined

### ISSUE THREAD

**Issue by sw1tchmx** [PH7-Jack/livewire-ui#134]
![image](https://user-images.githubusercontent.com/33660133/142688922-c01f9e90-fbbd-49a7-ad91-023a097da0ac.png)

**Comment by sw1tchmx** [comment]
was the alpine.js version i updated to the last one, and it works!

**Comment by ingangelbaeza** [comment]
not working!

**Comment by ph7jack** [comment]
@ingangelbaeza try updating the alpinejs version, if it's not work, create a new issue
