### ISSUE TITLE
Select and date picker input issue with a slightly dynamic form.

### ISSUE THREAD

**Issue by mwamodo** [PH7-Jack/livewire-ui#137]
**Describe the bug**
I am trying to create a step form with livewire where I have a step counter on the livewire class like below.

```php
class ApplicationForm extends Component
{
	public int $step = 0;
	public $date_of_birth;
	public $agent;

	public function decreaseStep()
    {
        $this->step--;
    }

    public function increaseStep()
    {
        $this->step++;
    }
}
```

on the front-end file I have a date picker and a select just like examples on the doc website, but have a check to see the value of step, like below. with two buttons to add or reduce the step.

```blade
<div>
	@if($step == 0)
		<div>
			<x-select
		        label="Select Status"
		        placeholder="Select one status"
		        :options="['Active', 'Pending', 'Stuck', 'Done']"
		        wire:model.defer="model"
		    />
		<div>
	@endif

	@if($step == 1)
		<div>
			<x-select
		        label="Select Status"
		        placeholder="Select one status"
		        :options="['Active', 'Pending', 'Stuck', 'Done']"
		        wire:model.defer="model"
		    />
		<div>
	@endif

	<x-button x-show="show" wire:click="decreaseStep" type="button" label="Previous Step" />
	<x-button x-show="show" wire:click="IncreaseStep" type="button" label="Next Step" />

</div>
```

After filling the form and adding the step counter the form shows content for the next step, the problem is when I click the previous step the select input becomes undefined. Same thing happens to dateselect inputs.

Am I doing something wrong? How do I fix this?
Thanks!

**Comment by Reex11** [comment]
I've had similar issue.
I think the problem is that the datepicker must be initialized with the page load.

So, my work around was letting livewire render both and hide one of them using alpine.

**Comment by ph7jack** [comment]
@mwamodo @Reex11 
Update to the new version and add a **wire:key** on the component
https://github.com/PH7-Jack/wireui/releases/tag/v0.14.2

```
<x-select
   ...
    wire:key="steps.1"
   ... 
/>
```

The livewire has a bug when the component is rendered conditionally, adding a wire:key fix it

**Comment by mwamodo** [comment]
@PH7-Jack Thank you! Works for me now
