### ISSUE TITLE
Wireui styles break my standar tailwind

### ISSUE THREAD

**Issue by jubagg** [PH7-Jack/livewire-ui#140]
I have a project since last year with tailwind, when i discover wireui, Pedro you are awesome!, I added that on my project, but the class grid of tailwind break and reorganizate all my components different.

This is the difference

without styles of wireui

![Captura de pantalla 2021-11-30 a la(s) 16 08 37](https://user-images.githubusercontent.com/50118474/144111669-74fb7e40-d9b3-4ba6-8006-30928372cbce.png)

with styles of wireui

![Captura de pantalla 2021-11-30 a la(s) 16 08 50](https://user-images.githubusercontent.com/50118474/144111692-9456274d-3c16-4304-856f-c3476820ff8c.png)

i sure i have modiffied something on tailwind config but what is the question.

Thank you so match!
Good coding for all!

**Comment by ph7jack** [comment]
Try using 
```
// tailwind.config.js
plugins: [
 require("@tailwindcss/forms")({
   strategy: 'base',
 }),
],
```

**Comment by jubagg** [comment]
hello Pedro, I found my mistach, I'm loading yours style after tailwind's style default. Thanks for your help.

I added on component select  an $dispatch event for listening on other alpine components, if you want, i can share you, it's a simple $dispatch on input search component in the component select .

**Comment by ph7jack** [comment]
@jubagg ok, show me :)

**Comment by jubagg** [comment]
I add this line on select

![Captura de pantalla 2021-12-01 a la(s) 14 37 11](https://user-images.githubusercontent.com/50118474/144284727-6c695bf6-7a62-4431-a6a8-25ab2fbbebff.png)

So the $dispath method fire an event called search-event with the objetc search with parameter

on my definition of componenet select create a alpine component that listen the fire event

![Captura de pantalla 2021-12-01 a la(s) 14 37 42](https://user-images.githubusercontent.com/50118474/144285170-18e5723d-5f63-4d82-b17d-930ad2581419.png)


and after that i use an Alpine Script that shoot the event on Livewire for search on DB

![Captura de pantalla 2021-12-01 a la(s) 14 38 11](https://user-images.githubusercontent.com/50118474/144285663-48e11088-0c0e-4613-9b25-4a65998b7f95.png)

and that's all

**Comment by ph7jack** [comment]
It is good, I will create a simple way to get dynamic data into one select

**Comment by ph7jack** [comment]
Close this issue if your problem was solved
