### ISSUE TITLE
Change classes and attributes condicionally

### ISSUE THREAD

**Issue by jubagg** [PH7-Jack/livewire-ui#141]
When I use Livewire I recicle the components and I use the same for edit and create. On my custom components I pass a state prop with the condition of component on new/edit/view, in case i choice view, all inputs config with readonly prop and change the config of tailwind classes to other color. In WireUi I cann't put readonly condicionally. Do you know if we can make anithing with this? I can help you if you wish

**Comment by ph7jack** [comment]
Hello @jubagg 
Show me how you are importing the component?
The wireui components has disabled and readonly attributes conditionally
The input color will be gray when disabled, and normal in readonly
readonly != disabled
![image](https://user-images.githubusercontent.com/38913462/144422529-1d0de950-acf1-4a5a-89ee-884628dd5afd.png)

```
<x-datetime-picker
      label="Appointment Date"
      placeholder="Appointment Date"
      wire:model.defer="date"
      disabled
  />

  <x-datetime-picker
      label="Appointment Date"
      placeholder="Appointment Date"
      wire:model.defer="date"
      readonly
  />

  <x-input :disabled="true" value="disabled" />
  <x-input :readonly="$readonly" value="readonly" />
```

**Comment by jubagg** [comment]
Hello @PH7-Jack , ok, i test like this, because I injected a condition like this. 

`  <x-input :readonly="$action == 'ver' ? true : false" :class="$action == ver ? 'bg-blue-200 border-0' : ' ' " value="readonly" />`

but doesn't work, I will test your method. 
thanks

**Comment by ph7jack** [comment]
@jubagg still having a problem?

**Comment by jubagg** [comment]
No, i don't have this problem, we can close the issue
