### ISSUE TITLE
Primitive components work, but datepicker, currency, etc. throwing "Entangle" error.

### ISSUE THREAD

**Issue by slakbal** [PH7-Jack/livewire-ui#142]
**Describe the bug**

Using "base (primitive) components" i.e. select, input, text-area, etc. works 100% and values are posted throught to the Livewire server-side component. But using Datepicker, Currency and Phone creates an error and does not submit through on the request and produces errors on die client-side saying that the livewire property can't be found.

**To Reproduce**

Using the latest versions of Laravel, WireUI, Alpine 3 and TailwindCss 2

```
    "devDependencies": {
        "@tailwindcss/forms": "^0.3.4",
        "@tailwindcss/typography": "^0.4.1",
        "alpinejs": "^3.7.0",
        "autoprefixer": "^10.4.0",
        "axios": "^0.21",
        "laravel-mix": "^6.0.39",
        "lodash": "^4.17.19",
        "postcss": "^8.4.4",
        "postcss-import": "^14.0.2",
        "tailwindcss": "^2.2.19"
    },
```

![component](https://user-images.githubusercontent.com/4387265/144393416-9c409460-06bb-48f4-9724-576058766b83.png)

Note the component is making use of a **public $state = []** property.

![problem](https://user-images.githubusercontent.com/4387265/144388966-5d079dab-1288-417f-8f66-284574955530.png)

As can be noticed above, I've tried **wire:model** directly also tried **wire:model.defer**, etc. Further also applied **wire:key**

**Expected behavior**

I suspect when the entanglement errors are resolved, the components will actually post through to the backend. And like mentioned the select and normal input components works correctly.

**Screenshots**

![posterror](https://user-images.githubusercontent.com/4387265/144389693-5a06357c-012e-4ce7-9581-a0c727bf94f2.png)

**Additional context**

Would appreciate some guidance on this matter.

**Comment by ph7jack** [comment]
@slakbal hello
This is not a wireui bug, is a livewire error message
Add the **opening**, **number**, and **date** keys into your array as null to solve.
Your initial array must be
```
[
'opening' => null,
'number' => null,
.... every key as null or with value
]
```

Need to initialize the key, because the alpine cant find the key if not exists

**Comment by slakbal** [comment]
@PH7-Jack  wow it worked!

Strange that it works with

`public $state = []`

for the "normal" fields.

Thanks for the help!!!! 

Is this in the documentation, had a quick scan but couldn't see it. Otherwise we should actually document this also and save you potential future queries/time. :)

Thanks again!

**Comment by ph7jack** [comment]
@slakbal The entangle has this bug, every key must exist to work.
