### ISSUE TITLE
WireUiScripts issue

### ISSUE THREAD

**Issue by TheoBarberet** [PH7-Jack/livewire-ui#144]
My VSC doesn't recognize the tag for wireui script in the blade as he normally do for the livewire one.

I had all the requirements needed, ran composer require wireui/wireui and added the settings to tailwind.config.js
I get this : 
![image](https://user-images.githubusercontent.com/56026906/145603639-71017085-fe54-48dd-b9bc-ff255ad4e335.png)
![image](https://user-images.githubusercontent.com/56026906/145604052-48584ab3-ebc8-4101-b224-de755eb82937.png)

So I can't use it to format a phone input.

 - OS - Windows10 version : 20H2
 - Browser - Edge
 - Version 96.0.1054.43

**Comment by ph7jack** [comment]
Not is a WireUI bug, the Visual Studio Code doesn't recognize this directive, but it works.
What's the phone input error?
Share the console log error if exists, record a video with this error

**Comment by TheoBarberet** [comment]
I have those 3 errors when I try to had the script
![image](https://user-images.githubusercontent.com/56026906/145623638-477c3ca7-8eb6-47b8-acb1-36ed227a067c.png)
![image](https://user-images.githubusercontent.com/56026906/145623692-27c7d69b-96cf-41a9-bb09-e98b3ade4b2a.png)

**Comment by ph7jack** [comment]
You must replace this `<script src="alpine.js"></script>` with your alpine js file
If you dont have, add this `<script src="//unpkg.com/alpinejs" defer></script>`

**Comment by TheoBarberet** [comment]
I tried with <script src="//unpkg.com/alpinejs" defer></script>
but I have those errors each time I add a number
![image](https://user-images.githubusercontent.com/56026906/145648578-0ece7b0c-0f0f-4a9f-a63b-9685e97b1fca.png)
![image](https://user-images.githubusercontent.com/56026906/145648625-7f84db1f-9306-4083-92b9-8fd1a710bf8a.png)

**Comment by ph7jack** [comment]
@TheoBarberet Can you try using google chrome?

**Comment by TheoBarberet** [comment]
It works thank you

**Comment by ph7jack** [comment]
@TheoBarberet I will check why in the edge don't work
