### ISSUE TITLE
Unable to install the package - Conflict with symfony/event-dispatcher

### ISSUE THREAD

**Issue by nocodelab** [PH7-Jack/livewire-ui#145]
**Describe the bug**
I'm unable to install the package on Laravel 8.75.0.
The version of symfony/event-dispatcher  and friendsofphp/php-cs-fixer budled in the latest version of Laravel is not compatible.

**To Reproduce**
composer require wireui/wireui

**Expected behavior**
Install the package

**Screenshots**
<img width="1791" alt="Screenshot 2021-12-10 at 20 24 05" src="https://user-images.githubusercontent.com/4540118/145630260-f0f2042c-92ef-453e-916a-a431faacdfc9.png">

`Problem 1
    - friendsofphp/php-cs-fixer[v3.1.0, ..., v3.3.1] require symfony/event-dispatcher ^4.4.20 || ^5.0 -> found symfony/event-dispatcher[v4.4.20, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - friendsofphp/php-cs-fixer v3.3.2 requires symfony/event-dispatcher ^5.0 -> found symfony/event-dispatcher[v5.0.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.0.1 (lock file version) by a partial update a

nd that version does not match. Make sure you list it as an argument for the update command.
    - wireui/wireui v0.14.3 requires friendsofphp/php-cs-fixer ^3.1 -> satisfiable by friendsofphp/php-cs-fixer[v3.1.0, ..., v3.3.2].
    - Root composer.json requires wireui/wireui ^0.14.3 -> satisfiable by wireui/wireui[v0.14.3].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
`

**Comment by ph7jack** [comment]
Show me your composer.json

**Comment by nocodelab** [comment]
Here you go

`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "akaunting/laravel-money": "^1.2",
        "barryvdh/laravel-translation-manager": "^0.5.10",
        "blade-ui-kit/blade-heroicons": "^1.2",
        "diglactic/laravel-breadcrumbs": "^7.0",
        "faisal50x/blade-ionicons": "^0.0.3",
        "fattureincloud/fattureincloud-php-sdk": "^2.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "itsmalikjones/blade-iconic": "^1.2",
        "laravel/framework": "^8.40",
        "laravel/jetstream": "^2.3",
        "laravel/sanctum": "^2.9",
        "laravel/tinker": "^2.5",
        "livewire/livewire": "^2.0",
        "maatwebsite/excel": "^3.1",
        "rappasoft/laravel-livewire-tables": "^1.10",
        "simplesoftwareio/simple-qrcode": "^4.2",
        "spatie/laravel-permission": "^3.17",
        "staudenmeir/laravel-adjacency-list": "^1.0",
        "stidges/laravel-country-flags": "^2.0",
        "wire-elements/modal": "^1.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.6",
        "barryvdh/laravel-ide-helper": "^2.10",
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "itsgoingd/clockwork": "^5.1",
        "laravel/sail": "^1.8",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}`

**Comment by ph7jack** [comment]
@nocodelab try to update your` friendsofphp/php-cs-fixer` package

**Comment by ph7jack** [comment]
Hello @nocodelab , this issue was inactive for a long time, I'm closing it now.
If this bug still happening, tag me with the "RE-OPEN" comment to let me know.

The WireUI requires the laravel 8.80 as the minimal version. Update to the minimal version or newer
