### ISSUE TITLE
Breaking changes on Tailwind v3

### ISSUE THREAD

**Issue by greenspace10** [PH7-Jack/livewire-ui#146]
the tailwind config breaks with upgrade to v3.

 ```
theme: {
  extend: {
    colors: {
      blueGray: colors.blueGray,  //new colour blueGray: colors.slate
    }
  }
}
```

also by having the following in my tailwind config it breaks my content/purge property 
```
  presets: [
        require('./vendor/wireui/wireui/tailwind.config.js')
    ],
```

**Comment by ph7jack** [comment]
Hello @greenspace10 
In this week i will up a new version of the wireui, that version will support the tailwind v3

**Comment by ph7jack** [comment]
@greenspace10 The latest version of WireUI supports now the tailwind v3
Thanks
