### ISSUE TITLE
Notification hook not working

### ISSUE THREAD

**Issue by bernhardh** [PH7-Jack/livewire-ui#150]
**Describe the bug**
I am trying to create a notification from JS (based on laravel session data). See also #8

**To Reproduce**

Just to test it, I created the following:

```html
<script>
Wireui.hook('notifications:load', () => {
    $wireui.notify({
        title: 'Profile saved!',
        description: 'Your profile was successfull saved',
        icon: 'success'
    })
})
</script>
```
and its not working (no notification is show, but now error on console as well).

When adding a short delay it works:

```html
<script>
Wireui.hook('notifications:load', () => {
   setTimeout(function (){
    $wireui.notify({
        title: 'Profile saved!',
        description: 'Your profile was successfull saved',
        icon: 'success'
    })
 }, 200);
})
</script>
```

**Expected behavior**
The notification should be shown.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 96

**Comment by REJack** [comment]
I can confirm this bug, the hook should be delayed by 1ms then it's fixed 😄 I open a PR for it

**Comment by ph7jack** [comment]
It was fixed [here](https://github.com/wireui/wireui/pull/274). The problem was the nextTick in the alpine v3
Thanks for reporting
