### ISSUE TITLE
Select option hidden

### ISSUE THREAD

**Issue by visoftdev** [PH7-Jack/livewire-ui#155]
select option hidden on modal. I use wire-elements/modal to create model. please, help me!

https://drive.google.com/file/d/1tfkJ6HrdAHZ6pBhiO4dlfQ0uaOeKEdv-/view?usp=sharing

**Comment by ph7jack** [comment]
Access denied to the link.
Could you explain more your issue?

**Comment by ph7jack** [comment]
Old issue, closing it.Issue related https://github.com/wireui/wireui/issues/130
