### ISSUE TITLE
Encoding problem with the Datepicker

### ISSUE THREAD

**Issue by ghost** [PH7-Jack/livewire-ui#157]
Hello !

I use your datepicker in french and the button "today" (Aujourd'hui in french) doesn't display well.

![encodage](https://user-images.githubusercontent.com/61461416/147688186-3627bfa2-4100-431b-844a-7001f157c3f9.PNG)

Thank's

**Comment by ph7jack** [comment]
Thanks a lot for reporting, my apologies for the long time to fix it.
