### ISSUE TITLE
wireui_dialog is not defined 

### ISSUE THREAD

**Issue by adinata-id** [PH7-Jack/livewire-ui#159]
**Describe the bug**
I Am Use Wire UI Dialog but when i am load dialog component 

i am always get this error : 

Alpine Expression Error: wireui_dialog is not defined

Expression: "wireui_dialog({ id: 'dialog' })"

i am use alpine js V3.7.1

Thanks

**Comment by ph7jack** [comment]
@adinata-id 
Are you importing the WireUI scripts before the alpinejs?

**Comment by adinata-id** [comment]
i will check and test again thanks

**Comment by Uhasith** [comment]
This is the order in which I’m importing Wireui scripts. In the local environment, everything works fine, but on the production server, I’m seeing many error messages in the console, such as “dialog is not defined,” etc. @PH7-Jack 

```
    @filamentStyles
    @livewireStyles
    @wireUiScripts
    <!-- Scripts -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    @stack('styles')
 ```
 
![Screenshot 2024-10-24 at 1 36 40 PM](https://github.com/user-attachments/assets/7e1c31ac-a2bc-4242-a632-bbe71c84d6b7)


WireUI Version - 2.2.1
Livewire Version - 3.5.12
