### ISSUE TITLE
Select components to allow remote data

### ISSUE THREAD

**Issue by putera** [PH7-Jack/livewire-ui#164]
**Is your feature request related to a problem? Please describe.**
I have a **more than 10k data** to load on the select component.

**Describe the solution you'd like**
It would be great if the select component can **load data as we type on the remote data**

**Describe alternatives you've considered**
Example of select 2 load data from remote

Thank you !

**Comment by Krato** [comment]
Yes, this will help when dealing with big datasources

**Comment by cloudstudio** [comment]
This could be awesome

**Comment by madurapa** [comment]
A much-needed feature!

Basically, we need the same replica of what [Select2](https://select2.org/data-sources/ajax) does.

**Comment by ph7jack** [comment]
It's is now released https://livewire-wireui.com/docs/select#async-search 
Thanks @putera

**Comment by putera** [comment]
I love this features a lot. Async search is awesome. Thanks bro.

**Comment by madurapa** [comment]
This is awesome! Thank you! I hope you have a plan to add more customizing parameters such as pagination, minimum characters to search, etc... those are handy when dealing with a bunch of data.

**Comment by ph7jack** [comment]
@madurapa You are free to create your APIs as you wish. The pagination is not the best choice for async search data.
See the WireUI API guide as an example and implement it in your project.
The basics are explained here https://livewire-wireui.com/docs/select

Just add a query limit, a search, and a way to retrieve the data.
You're free to extend the select and modify as you wish too.


https://github.com/wireui/docs/blob/main/app/Http/Controllers/Api/Users/Index.php
https://github.com/wireui/docs/blob/main/tests/Feature/Controllers/Api/Users/IndexTest.php

![image](https://user-images.githubusercontent.com/38913462/169465512-05a0e558-50e5-4c40-a9a3-6f4aac3096b2.png)

**Comment by madurapa** [comment]
Great! Thanks for the explanation.
