### ISSUE TITLE
Notification emit on Event

### ISSUE THREAD

**Issue by putera** [PH7-Jack/livewire-ui#178]
I have this idea to improve on the notification, but i dont know typescript :p

Usually we use this to fire event and its awesome.
```php
public function save(): void
   {
      // ...
         $this->notification()->notify([
            // ...
           'onClose' => [
               'method' => 'firedEvent',
               'params' => 'onClose',
         ],

       ]);
    }
```

It would be great if we can emit from the Livewire.emit() event and listen from component.

```php
'onClose' => [
     'emit' => 'testMethod',  // just example to emit
     'params' => 'mydata',
],
```

on notifications event typescript ( i do know typescript, so.. :p )

`
Livewire.emit(options?.emit, ...params)
`

And listen from the component.

`protected $listeners = ['testMethod'];`

Thank you.

**Comment by ph7jack** [comment]
@putera Thanks a lot for creating the PR to solve this issue.
