### ISSUE TITLE
Online documentation: error on datetimepicker min-max filter dates

### ISSUE THREAD

**Issue by jcerdan** [PH7-Jack/livewire-ui#185]
Hi,

I wanted to check new features at the wireui documentation but time-pciker min-max filter does not work fine. It returns a JS error
I have checked that with last version of Firefox under Archlinux.
I post a screenshot.

Regards
![Captura de pantalla -2022-01-23 11-07-51](https://user-images.githubusercontent.com/532007/150673699-1cd22d38-6530-43b6-98ed-ed294cc13c9a.png)

**Comment by ph7jack** [comment]
@jcerdan thanks for reporting this. I'm checking it now. In the firefox are breaking

**Comment by ph7jack** [comment]
@jcerdan it is now fixed, i will release it yet. Thanks so much
