### ISSUE TITLE
Unable to locate a class or view for component [dynamic-component].

### ISSUE THREAD

**Issue by diazsasak** [PH7-Jack/livewire-ui#187]
**Describe the bug**
Hi, I just installed wireui. And I got this error, it cannot run blade dynamic component inside notifications.blade.php

![image](https://user-images.githubusercontent.com/7880137/150906298-763476a8-765f-4743-a0b6-05a893702882.png)
![image](https://user-images.githubusercontent.com/7880137/150906326-5878d0fc-ebb8-4403-888c-30b8a4f8bf55.png)

Any help for a clue what wrong?
Thank you for your attention

**Comment by ph7jack** [comment]
@diazsasak Thanks for reporting. What is your:
Laravel version: ?
Livewire version: ?

**Comment by diazsasak** [comment]
@PH7-Jack This is the versions:

laravel: 8.80.0
livewire: 2.10.1
wireui: 0.16.2

Additional information is I am using bagisto v1.3.2 . 

Thank you..

**Comment by ph7jack** [comment]
Can you clear the view?
`php artisan view:clear`

And test if the laravel dynamic components are working https://laravel.com/docs/8.x/blade#dynamic-components

**Comment by diazsasak** [comment]
i did artisan view:clear sir, but still same error. 

Yes, looks like the laravel dynamic components on my project is not working. Any idea how can that possible?

**Comment by ph7jack** [comment]
@diazsasak can you try it in a new project? I don't have any idea about your project doesn't have dynamic components.
Can you reinstall the composer dependencies?
```
rm -rf vendor
composer install
```

**Comment by diazsasak** [comment]
hi @PH7-Jack , i found the workaround. i manually register it on AppServiceProvider and it work. 
https://laravel.com/docs/8.x/blade#manually-registering-components.

`
Blade::component('dynamic-component', DynamicComponent::class);
`

 I think something different on how bagisto manage the provider. not sure. Thank you for your assist!

**Comment by ph7jack** [comment]
Good! @diazsasak . I'm closing this issue now
