### ISSUE TITLE
 Error: wireui_dropdown is not defined

### ISSUE THREAD

**Issue by rowino** [PH7-Jack/livewire-ui#189]
I'm getting the error  `wireui_dropdown is not defined` when using the dropdown feature. I'm using a clean laravel installation

Here's the code

```
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">

</head>
<body class="antialiased">

    <div class="text-center h-40 bg-gray-300 flex justify-center items-center w-full">
        <x-dropdown>
            <x-slot name="trigger">
                <x-button label="Options" primary/>
            </x-slot>

            <x-dropdown.item label="Help Center"/>
            <x-dropdown.item separator label="Live Chat"/>
            <x-dropdown.item separator label="Logout"/>
        </x-dropdown>
    </div>
    <wireui:scripts />
    <script src="//unpkg.com/alpinejs"></script>
</body>
</html>

```

**Comment by ph7jack** [comment]
@rowino Please, follow the WireUI install guide. https://livewire-wireui.com/docs/get-started#installation
These scripts are added on head
```
<wireui:scripts />
<script src="//unpkg.com/alpinejs"></script>
```

**Comment by rowino** [comment]
Thanks @PH7-Jack, what got it working finally was
```
    <wireui:scripts />
    <script src="//unpkg.com/alpinejs" defer></script>
 ```
since it's in the head, alpine gives a warning without `defer` and the error still occurs

**Comment by gbrits** [comment]
Hi guys, sorry to re-open this. But I have noticed if you are using Laravel Jetstream (possibly Breeze alternatively) as well as Livewire there seems to be an unavoidable inclusion of AlpineJS and in a modular way so you can't just remove it from a particular app.js etc... then that clashes with WireUI and you have this error again.

I'm guessing others are on earlier versions of Livewire/Jetstream and aren't encountering this just yet?

I'd be really happy if it's only me and I've done something wrong?
