### ISSUE TITLE
Problemas ao ativas as Opções do Modal

### ISSUE THREAD

**Issue by joaonivaldo** [PH7-Jack/livewire-ui#192]
**Describe the bug**
Estou tentanto personalizar o componente Modal, mas qualquer opção que eu ponho ela so funciona como ativo ou não

**To Reproduce**
se eu escrevo desta forma por exemplo: <x-modal.card title="Termos e Condições" blur="xl" wire:model.defer="termosModal" max-width="sm"> Ele não executa o blur e o tamanho do modal fica no maximo coforme imagem abaixo

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4040086/151561284-1381f289-e64f-4eff-904f-daebd057b22d.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 97

**Smartphone (please complete the following information):**

**Comment by ph7jack** [comment]
@joaonivaldo Can you write it in English? Wireui is correctly installed? Follow the [install guide](https://livewire-wireui.com/docs/get-started), check if the tailwind is correct installed

**Comment by joaonivaldo** [comment]
There was an error in the compilation of tailwind. Thanks a lot for the help
