### ISSUE TITLE
Datetime picker showing 24 time in search and 0:00 instead of 12:00

### ISSUE THREAD

**Issue by jordan-price** [PH7-Jack/livewire-ui#196]
**Describe the bug**
The datetime picker is showing 24 hour time in the time search input and it's not formatting 0:00 to 12:00. 

**To Reproduce**
1. Go to [https://livewire-wireui.com/docs/datetime-picker](https://livewire-wireui.com/docs/datetime-picker)
2. Click on any DateTime picker input field
3. Click a day
4. You will see 24 hour time displayed in the search input
5. When you try to search for 12 it won't be there
6. You will find 0:00 instead of 12:00

**Expected behavior**
It should display 12:00 instead of 0:00 in the time select dropdown.
it should display 1:00 instead of 13:00 in the search input.

**Screenshots**
<img width="450" alt="Screen Shot 2022-01-30 at 3 10 58 PM" src="https://user-images.githubusercontent.com/11284852/151718196-d8df9a65-36d0-46d1-aff3-1f23030f6013.png">

**Desktop (please complete the following information):**
 - OS: iOS, MacOs
 - Browser chrome
 - Version 97.0.4692.99 

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15
 - Browser safari

**Comment by putera** [comment]
Yes. I got the same bug.
