### ISSUE TITLE
Datepicker with time-format 24 set 12 format on model

### ISSUE THREAD

**Issue by trippo** [PH7-Jack/livewire-ui#198]
**Describe the bug**
When do you have a date picker with 24-time format and save 13:30 the model has a 1:30 value.

**To Reproduce**
1. Use a datepicker with  ` time-format="24"` config
2. Select 13:30 time on every date
3. The result is 1:30 on model

**Expected behavior**
Pass to livewire the correct date selection

**Screenshots**
<img width="452" alt="Schermata 2022-01-31 alle 11 17 52" src="https://user-images.githubusercontent.com/497169/151776115-cbbaf42e-29ae-4458-8e41-e9eb90617e15.png">

**Comment by trippo** [comment]
I found the error... was mine :)

i setted the parse-format option to 
`parse-format="YYYY-MM-DD hh:mm:ss"`
instead
`parse-format="YYYY-MM-DD HH:mm:ss"`

**Comment by trippo** [comment]
After that change the Select time interface shows me a input instead the times list
![image](https://user-images.githubusercontent.com/497169/151784624-eeb3da81-48a9-4a61-bd12-32d5c88ce0e2.png)
![image](https://user-images.githubusercontent.com/497169/151784717-240bd80e-9ab1-4247-be4d-7a22a1618ec3.png)

Another bug is the label "Select Time" not translated

**Comment by trippo** [comment]
Another bug on datepicker:
![image](https://user-images.githubusercontent.com/497169/152759285-d87ffaf2-4f87-437f-a050-a3ffc57ccd14.png)

If the first field of row contain datepicker the modal is cutted

**Comment by ph7jack** [comment]
@trippo 
I have fixed the label bug, but I cant reproduce the UI bug
Could you give-me a code example?

**Comment by trippo** [comment]
@PH7-Jack  You need to have the date picker on the first column of a columns layout like this:
![image](https://user-images.githubusercontent.com/497169/169773157-7af28ac2-0cba-459d-ae50-d67e7856b8e7.png)
The picker dialog is anchored to the right of the input field so if the input field is smaller than the picker dialog, the picker dialog escapes from the left side of the monitor.

**Comment by ph7jack** [comment]
@trippo This screen overflow bug was fixed in the release v1.8.0 https://github.com/wireui/wireui/releases/tag/v1.8.0

**Comment by trippo** [comment]
Thanks a lot
