### ISSUE TITLE
include more icons

### ISSUE THREAD

**Issue by joaonivaldo** [PH7-Jack/livewire-ui#200]
**Is your feature request related to a problem? Please describe.**
Heroicons has very little icon available for use.

**Describe the solution you'd like**
One of the best solutions for this would be to use Font Awesome 5 as a group of icons in the components.

**Describe alternatives you've considered**

**Additional context**

**Comment by REJack** [comment]
I would more like a compatibility to blade-icons :D like I did it on my project, so I can choose any svg font like materialdesignicons or others.

**Comment by emiliosh** [comment]
You can add them in /resources/views/vendor/wireui/icons/outline or solid.  I did it like this.

**Comment by REJack** [comment]
> You can add them in /resources/views/vendor/wireui/icons/outline or solid. I did it like this.

Yeah one by one :D but with blade icons I've added 4000+ icons in 2mins of setup config and placing the svgs in the right folder, thats a real game changer 🤣

**Comment by joaonivaldo** [comment]
An excellent suggestion. Where did you get the 4000 icons? If possible, can you share your blade icons folder? Thank you very much

**Comment by REJack** [comment]
> An excellent suggestion. Where did you get the 4000 icons? If possible, can you share your blade icons folder? Thank you very much

I use Templarian's [MaterialDesign icons](https://github.com/Templarian/MaterialDesign), were I contributed some icons too.

**Comment by joaonivaldo** [comment]
Thanks
