### ISSUE TITLE
Make components be usable even without livewire

### ISSUE THREAD

**Issue by bernhardh** [PH7-Jack/livewire-ui#202]
In some situations, there is no need for the livewire overhead and I wanna use the components just as blade components.

For example the modal: If I use it somewhere in blade, I should be able to use it, without nesting it inside a livewire component. This actually "works":

```html
    <button type="button" onclick="$openModal('showModal')">Open</button>

    <x-wire-modal wire:model.defer="showModal">
        <x-card title="Consent Terms">
            <p class="text-gray-600">
                Lorem Ipsum...
            </p>
        </x-card>
    </x-wire-modal>
```

The modal is shown on click. BUT I get the error `ivewire Entangle Error: Livewire property 'showModal' cannot be found`, because `showModal` isn't a livewire component classs property, since its not inside a livewire component.

It should be allowed to use the component inside a regular blade template, plus the "modal name" should be allowed to explizitly set, so that I can have multiple modals on a page.

**Comment by ph7jack** [comment]
@bernhardh Good.
I'm refactoring the components to be used without a livewire component.
The select component can be used outside a livewire now

**Comment by deshiloh** [comment]
> @bernhardh Good. I'm refactoring the components to be used without a livewire component. The select component can be used outside a livewire now

So how can I do selected value outside livewire component ? I tried : 
```
<x-select
                label="Secrétaire"
                placeholder="Sélectionner une secrétaire"
                :async-data="route('api.users')"
                option-label="full_name"
                option-value="id"
                name='user_id'
                option-description="entreprise.nom"
                value="{{ old('user_id') }}"
            />
```

but this doesn't work, even with `value="1"`

**Comment by michele-widesrl** [comment]
> @bernhardh Good. I'm refactoring the components to be used without a livewire component. The select component can be used outside a livewire now

I often use the select without Livewire for the convenient async-data but I'm having a problem displaying the selected field. It appears that the value is never selected in the dropdown. When instead I click the reset button (x) the value in the dropdown appears as selected. Like he's always one step behind. could you help me?

**Comment by joaopalopes24** [comment]
The new version 2, which is now available in beta, does not depend on Livewire. Therefore, I am closing this Issue.
