### ISSUE TITLE
Select detect on change

### ISSUE THREAD

**Issue by netopvh** [PH7-Jack/livewire-ui#203]
I'm using the select component, but I couldn't perform the onchange function, I don't know if this function is available, I would like to clear this doubt and if not, develop this functionality.

**Comment by trippo** [comment]
How can you try to detect change? wire:change, x-on:change or other?

**Comment by REJack** [comment]
Checkout the docs, https://livewire-wireui.com/docs/select#select-events

**Comment by netopvh** [comment]
Thank you guys! i will solved.

**Comment by SDJeff** [comment]
I tried all in a project, never an alert is coming up! Any Ideas why? Other Alpine Syntax is running:

`x-on:open="alert('openned select')"
    x-on:close="alert('closed select')"
    x-on:select="alert('selected/unselected option')"
    x-on:clear="alert('cleared select')"`

**Comment by t1m0t** [comment]
@SDJeff I'm having the same issue. Select events mentionned in the documentation don't trigger.
