### ISSUE TITLE
Doubt about masking Brazilian phones

### ISSUE THREAD

**Issue by joaonivaldo** [PH7-Jack/livewire-ui#213]
I'm having trouble making this mask, "['####-####', '#### ###-####', '(##) ####-# ###','(##) ###-####']", work correctly with all standard Brazilian phone numbers. Does anyone know how to solve?
It gives a problem when I type the number 40040000.
Current Brazilian telephone prefix standards: 0800 XXX XXXX, 4004 XXXX, (XX) XXXX-XXXX and (XX) 9XXXX-XXXX).

Thanks

**Comment by ph7jack** [comment]
@joaonivaldo 
Try using this mask for brazilian phones
`mask="['####-####', '#####-####', '#### ### ####', '(##) ####-####', '(##) #####-####']"`

The WireUI can't handle masks of the same size (only characters), the dynamic mask works with different mask size
###, ## ##, (###) ##, ...
