### ISSUE TITLE
Tailwind Jit Mode Not Syncing the classes. 

### ISSUE THREAD

**Issue by lathindu1** [PH7-Jack/livewire-ui#215]
Hello Guys,

I see the tailwind jit mode not syncing the default classes correctly. I have done everything you mentioned in the document. after that, I have looked deeply. As I got. JIT mode does not sync classes in the configs. 

Faced This issue with dialogs, notifications. Didn't check the rest of the components.

Below I will attach screenshots.

<img width="2351" alt="Screenshot 2022-02-20 at 14 20 19" src="https://user-images.githubusercontent.com/16050349/154835308-b81821f0-ce46-4459-8c7f-f2a6ea2eaf50.png">

<img width="1564" alt="Screenshot 2022-02-20 at 14 19 25" src="https://user-images.githubusercontent.com/16050349/154835315-fb03c526-2eb2-44fc-bf82-cf78085fb45d.png">

**Comment by ph7jack** [comment]
@lathindu1 
Have you added the content paths?
![image](https://user-images.githubusercontent.com/38913462/169245241-95417f0e-e3ea-4f70-bae8-f763c3521c8b.png)

**Comment by gbrits** [comment]
I have the same issue as the OP & I have the content paths as suggested...

**Comment by gbrits** [comment]
Also.. getting this when trying to republish vendor items:
```
  [60] Tag: wireui.config
  [61] Tag: wireui.lang
  [62] Tag: wireui.resources
 > 61

Can't locate path: </Users/name/company/project-name/vendor/wireui/wireui/src/Providers/../../resources/lang>
Publishing complete.
```
