### ISSUE TITLE
On deployment server: Alpine Expression Error: isSelected is not defined

### ISSUE THREAD

**Issue by diazsasak** [PH7-Jack/livewire-ui#216]
**Describe the bug**
Hi, on local my code is working fine. But on server, I got server after livewire update. Any idea on my case?

![image](https://user-images.githubusercontent.com/7880137/154895263-72090a64-0bbb-404e-811c-cb989d13c3e1.png)
![image](https://user-images.githubusercontent.com/7880137/154895551-fd6535e0-9538-4f15-96b3-92b3a82f3a85.png)

System:
Ubuntu 16.04.7 LTS

**Comment by ph7jack** [comment]
@diazsasak Hello. Are you importing the alpine after the wireui?

**Comment by diazsasak** [comment]
Hi @PH7-Jack, Yes 

![image](https://user-images.githubusercontent.com/7880137/155070431-bb079d4f-d5d0-43cb-bb81-47f618bc06e5.png)

**Comment by mfazail** [comment]
Try initializing the variable on mount method than it should work.

```
<x-select label="Type" wire:model.lazy="item.type"  :options="['service','product']" />

public function mount()
{
   $this->item = SysItem::make();
}
```

**Comment by ph7jack** [comment]
@diazsasak Use the latest alpine from the node modules.
Closing it now. If you're getting the same error, tag me to re-open
