### ISSUE TITLE
Unable to locate a class or view for component [button.circle]

### ISSUE THREAD

**Issue by diazsasak** [PH7-Jack/livewire-ui#217]
**Describe the bug**
Hi admin, i can use all other components as fine. But when I try to use button circle. I got this error. 

![image](https://user-images.githubusercontent.com/7880137/155070996-636ec96b-79bc-4ae6-9f93-7093a3e7c19e.png)
![image](https://user-images.githubusercontent.com/7880137/155070914-82b5bc28-acf6-418f-8800-f41330dc744d.png)

**Comment by sharathdn1** [comment]
add the missing button.circle component in the config/wireui.php 
<img width="434" alt="image" src="https://user-images.githubusercontent.com/12691864/155072590-48a66083-53ca-4027-95d5-894d44733b81.png">

**Comment by diazsasak** [comment]
Hi @sharathdn1 , 

i try your suggestion, but it can't find & import that class. i check the version of my wireui is 0.15.0, I try to update to v1.0.0 but need PHP 8? 

![image](https://user-images.githubusercontent.com/7880137/155095162-e61dcb60-5d17-4380-ad2a-41a20bbe15f0.png)

If so, I need to wait until I upgrade my server to PHP 8. Thank you for suggestion

**Comment by sharathdn1** [comment]
Yes, you need PHP 8.x
Pease see the WireUI Requirements:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/12691864/155115676-e7ad2a01-ed5c-4f42-91f4-64ea737b9f36.png">

**Comment by sharathdn1** [comment]
Try WireUI version 0.17, it might support PHP 7.x and in that button.circle was introduced.
https://github.com/wireui/wireui/compare/v0.16.0...v0.17.0

**Comment by ph7jack** [comment]
The @sharathdn1 resolved this issue
Thanks, @sharathdn1
