### ISSUE TITLE
Select stops working with conditional rendering

### ISSUE THREAD

**Issue by epuluikis** [PH7-Jack/livewire-ui#218]
**Describe the bug**
Hi, I've two select elements who are shown or hidden based on two radio inputs. On the initial load, only one select is shown and everything works. Switching radio hides the first select element and shows the second one. It still works after first switch to second one. But switching back to the first radio and select throws a lot of errors and select becomes unresponsive. 

**Screenshots** (in sequence)
1. Initial page
![image](https://user-images.githubusercontent.com/57572283/155147122-4f3276f3-264e-4a3b-b93a-df6c40ddf05b.png)
2. Switched radio to 2nd
![image](https://user-images.githubusercontent.com/57572283/155147274-6db88e87-f7c0-491d-af67-d2b7645def45.png)
3. Switched radio to 1st
![image](https://user-images.githubusercontent.com/57572283/155147347-92d0e61c-d513-4c1e-9755-6afdd0da35a4.png)
![image](https://user-images.githubusercontent.com/57572283/155147407-b0ed3b41-725e-489b-87c2-fa6b36aec648.png)
![image](https://user-images.githubusercontent.com/57572283/155147466-66a2c3c9-3179-4fea-b950-9953621e4ad8.png)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 1.0.0 (same behavior on 0.17.0)

**Additional context**
One of the selects:
```           
@if ($round['rolesType'] == 'round')
    <div class="mb-3 flex">
        <div class="w-full">
            <x-select
                label="Roles"
                placeholder="Select roles"
                multiselect
                wire:model.defer="rounds.{{ $roundIndex }}.roles"
            >
                @foreach ($roles as $role)
                    <x-select.user-option img="{{ $role->icon }}" label="{{ $role->title }}"
                                          value="{{ $role->id }}"/>
                @endforeach
            </x-select>
        </div>
    </div>
@endif
```

**Comment by ph7jack** [comment]
@EPuluikis Hello. can you test adding a `wire:key`?
**ALWAYS** you need to add a key to conditional elements or elements in a loop

```
@if ($round['rolesType'] == 'round')
    <div class="mb-3 flex">
        <div class="w-full">
            <x-select
                label="Roles"
                placeholder="Select roles"
                multiselect
                wire:model.defer="rounds.{{ $roundIndex }}.roles"
                wire:key="rounds.{{ $roundIndex }}..select"
            >
                @foreach ($roles as $role)
                    <x-select.user-option img="{{ $role->icon }}" label="{{ $role->title }}"
                                          value="{{ $role->id }}"/>
                @endforeach
            </x-select>
        </div>
    </div>
@endif
```

**Comment by epuluikis** [comment]
It worked, must have missed that one. Although when select is being hidden, it throws one error. Doesn't break anything.

![image](https://user-images.githubusercontent.com/57572283/155272897-39001aca-ef44-4fcc-8348-5ddc25db8a3a.png)
