### ISSUE TITLE
Allow growing selected tags in the multiselect

### ISSUE THREAD

**Issue by Raqwelly** [PH7-Jack/livewire-ui#219]
Because the select component resolves using the input component, it makes using many tags in a multiple select situation difficult as input fields do not automatically grow to fill content as a standard select field does. This limits the use of it for tags that extend beyond one line.

![select component](https://user-images.githubusercontent.com/38297079/155456923-9ee424c3-64d8-4736-bebc-12ff283c6a55.jpg)

**Comment by tariktokic** [comment]
Hi @PH7-Jack ! 
Thank you very much for this great package! 
I am also having the same problem as @Raqwelly. As soon as more than X items are selected, they are not visible any more.

Do you have any idea, if this will be - and if when - implemented?

Thank you!

**Comment by spardobo** [comment]
I'm having the same issue here, by selecting many items the x-select hide them instead of occupy a new row

**Comment by joaopalopes24** [comment]
There are no plans to implement this solution. We are updating the status of the Issues and if you want to contribute to this solution, it's welcome.

You can use `shift + scroll`.
