### ISSUE TITLE
searchable select keyboard down and up keys

### ISSUE THREAD

**Issue by behvandi11** [PH7-Jack/livewire-ui#220]
**Describe the bug**
Hi. it seems on select component when use search for filter results, then press down key to select an option there is some bug and no work correct. selector some times no work and some times just it comes down to some options and does not come lower options. to better understand please see official demo at under link:

1. Go to 'https://livewire-wireui.com/docs/select#slot-options'
2. Open select
3. In search place type 'e'
4. Now use down key on keyboard and try go to third option , now you see the bug 

 - OS: Windows, Linux
 - Browser: Chrome, Firefox
 - Version:  98
 - Wire Ui: 1.0.0

Thanks

**Comment by ph7jack** [comment]
@behvandi11 It's now fixed in the latest WireUI version, could you update and test it?
If the error still persisting for you, tag me to reopen the issue
Thanks for your report
