### ISSUE TITLE
datetimepicker first day of week

### ISSUE THREAD

**Issue by jouniikaheimo** [PH7-Jack/livewire-ui#226]
Hi
 it is possible for the first day of the week to be Monday?

**Comment by haringsrob** [comment]
Looking for this as well. Not sure how to go with it.

**Comment by haringsrob** [comment]
Added a pr here: https://github.com/wireui/wireui/pull/319

**Comment by silviokennecke** [comment]
As the last PR was closed due to incompletness, I implemented it myself today. See #540 (documentation https://github.com/wireui/docs/pull/40)

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

This feature was added in stable version 2. Check our documentation at: https://wireui.dev.
