### ISSUE TITLE
Undefined variable $classes

### ISSUE THREAD

**Issue by elfeffe** [PH7-Jack/livewire-ui#229]
**Describe the bug**
I get 
`Undefined variable $classes
`
Here

```
     <button {{ $attributes->merge([

            'class' => $classes,

            'type'  => 'button'

        ]) }}
```

**To Reproduce**
I just have a button as I had before, and then I upgraded to L9, and I get the error.

**Comment by mckenziearts** [comment]
![Screenshot from 2022-03-29 12-10-51](https://user-images.githubusercontent.com/14105989/160598923-424f225b-6e81-43f6-a4b7-3a16516565c6.png)

Any update on this ? @PH7-Jack i have the same problem

**Comment by REJack** [comment]
Did you both updated to wireui to v1?

**Comment by mckenziearts** [comment]
Yes. I updated to Laravel 9 and v1.0. And as soon as I refresh my page without touching anything I got this error

**Comment by REJack** [comment]
did you created a modified button class?

**Comment by mckenziearts** [comment]
No, I don't use button components in my application, which is what attracts my attention even more. Otherwise the button show on screen should not be displayed

 It's much more on pages where I have dropdown, datepicker

**Comment by REJack** [comment]
the dropdown uses the buttons too, if I'm not wrong. May reset the components in the config can help.

**Comment by mckenziearts** [comment]
I have just started a new laravel 9 project and I don't have this error. But when you upgrade from Laravel 8 to Laravel 9 you get this error.

**Comment by jcvjunior** [comment]
I have the same one who noticed the problem, doing the update to laravel 9, I was using laravel 8 but the wireui version was very old (v0.11.0).
Anyone any tips? I've been stuck on this problem for two days.

**Comment by ph7jack** [comment]
Hello Guys, I'm seeing it now.
The button component doesn't have the $classes variable.
If did you publish the resources, publish again and update your blades
If you do a package upgrade, update your published views and delete your laravel cache.

https://github.com/wireui/wireui/blob/main/resources/views/components/button.blade.php

If you think that it's is really a bug, show me more details and tag me to reopen the issue

**Comment by ph7jack** [comment]
@jcvjunior @elfeffe @mckenziearts See my answer
