### ISSUE TITLE
Unable to use DateTime Picker Component

### ISSUE THREAD

**Issue by eunicevassoa** [PH7-Jack/livewire-ui#230]
I'm trying to use the datetime picker component for wireui but it just gives me an undefined value in the field (screenshot 1) and I'm getting lots of console warnings and errors (screenshots 2 & 3 are some of the examples)
Also when I try to click the input it gives me more warnings and errors (screenshot 4)

***Screenshot 1***
![Screenshot from 2022-03-22 22-18-59](https://user-images.githubusercontent.com/45620682/159569046-fe94cd96-be85-44e7-9cf2-2da411eddf01.png)

***Screenshot 2***
![Screenshot from 2022-03-22 22-17-43](https://user-images.githubusercontent.com/45620682/159569017-c0c03dd7-4bfa-473b-b860-00ead6f059e7.png)

***Screenshot 3***
![Screenshot from 2022-03-22 22-18-20](https://user-images.githubusercontent.com/45620682/159569036-8ddf1bd3-2950-4be4-a992-7ba2836df1a1.png)

***Screenshot 4***
![Screenshot from 2022-03-22 22-18-45](https://user-images.githubusercontent.com/45620682/159569962-5b636090-2fd0-4633-ac07-e3ea77ecaceb.png)

Here is the sample code that I'm trying to use for the datetime picker field:

```php
class HomeSearchForm extends Component
{
    public $pickup_location, $pickup_datetime, $drop_location, $drop_datetime;

    public function render()
    {
        $locations = BookingLocation::all();

        return view('livewire.home-search-form', compact(['locations']));
    }
}
```

```html
<x-datetime-picker label="Date & time" placeholder="Date & time" without-timezone :min="now()" parse-format="DD-MM-YYYY HH:mm" interval="30" wire:model.defer="pickup_datetime" />
```

These are the versions of the packages related to wire ui:
- `laravel`: 8.75
- `wireui`: 1.0
- `livewire`: 2.10
- `tailwindcss`: 3.0.23
- `@tailwindcss/aspect-ratio`: 0.4.0
- `@tailwindcss/forms`: 0.4.1
- `@tailwindcss/typography`: 0.5.2
- `alpinejs`: 3.9.2 (tried previous versions, importing it via CDN and npm but just got different errors in some cases)

Best regards

**Comment by ph7jack** [comment]
@4inka Thanks for reporting. Do you have the wireui lang? I'm seeing in your **Screenshot 2**, the translation is missing

**Comment by eunicevassoa** [comment]
I am unable to publish the lang files, it gives me the following error:
![Screenshot from 2022-03-23 15-06-28](https://user-images.githubusercontent.com/45620682/159706477-8194c0de-7cee-41e3-b98c-15d9cfd63f45.png)

I was able to publish the other files

**Comment by joelhmetz** [comment]
Put in this order:

<wireui:scripts />
<script src="//unpkg.com/alpinejs" defer></script>
<script src="{{ asset('js/app.js') }}" defer></script>

**Comment by eunicevassoa** [comment]
I've already tried it

also tried adding alpine as a npm dependency but still got no sucess. The screenshots bellow are the latest version of  what I tried to use in order to solve this issue but nothing works

***layout.blade.php***
![Screenshot from 2022-03-23 20-25-26](https://user-images.githubusercontent.com/45620682/159769989-2c5e7b5c-5189-4f08-bfcc-8f5379f2d60d.png)

***app.js***
![Screenshot from 2022-03-23 20-27-45](https://user-images.githubusercontent.com/45620682/159770393-bc1dbd6e-013f-4b59-ba54-dd923093df84.png)

I've already tried a lot of different ways and versions of alpine and nothing seems to work properly.

**Comment by eunicevassoa** [comment]
I was able to use it in a fresh project. Don't understand what was wrong with my old one, but I'll stick to the new one and transfer the things that are already done to the new one and see if it doesn't break it.

But thank you for the attention 

## Edit
Unfortunatelly it did it again.
I created a fresh project, added the first 2 migrations and some styles and everything was working, but after adding some more data it did the same thing.
I didn't add any other dependency beside the ones related to wireui and still got the error out of nowhere

## Edit 2
I created a [git repo](https://github.com/4inka/wireui_test) that has a sample project with the bug that I'm facing. I tested it in another computer and got the same result.
Hope this helps

**Comment by mckenziearts** [comment]
I already had this problem, but you have to look in the `.env` file to see if your APP_URL is the same one that is returned by your project.

I work with Laravel Valet in https and my `APP_URL` was not https so I had this error.

Empty the cache where you display the url of this error is because it can not load the js of wireui

**Comment by eunicevassoa** [comment]
Corrected that and still no result.

**Comment by joelhmetz** [comment]
wireui_test/tailwind.config.js

check your file, the form plugin is missing

**Comment by eunicevassoa** [comment]
I removed it by mistake from this project but already added it back and updated the sample project.
But in my original project I have the forms plugin there and it's still doing the same.

**Comment by eunicevassoa** [comment]
Hi

Any update on this

## Edit

I was finally able to find out what the issue was.
I was getting the undefined error because I changed the 'locale' and 'fallback_locale' to 'en_US' instead of 'en' inside config/app.php and didn't create a folder named 'en_US' under lang/vendor/wireui. After creating the folder inside the mentioned directory everything started working fine again.
