### ISSUE TITLE
Ability to have a theme provider for colors

### ISSUE THREAD

**Issue by ainesophaur** [PH7-Jack/livewire-ui#234]
**Is your feature request related to a problem? Please describe.**
I use wireui's functionality in combination with daisy-ui for themeability. I prefer to use daisy ui for the automatic handling of dark mode as well as my color/utility classes and I love the livewire integration provided by wireui. However, I run into a clash in coloring as daisy ui avoids the route of "stepped" colors (eg, primary-100, primary-200) and provides a base of ~9 colors.

**Describe the solution you'd like**
A contract interface would allow advanced package integration by mapping base colors in wireui to an external package. Something like this
```php
interface WireUiColorManifest {
  public registerColor(string $wireElement, string $class, string $errorClass);
  public color(string $wireElement, ?bool $hasError = null);
}
```

Which could theoretically be consumed in the blade templates with a helper function to call a provider like `WireUiColorSelector->color()` within the wireui components

```php
<label {{ $attributes->class([
        0 => colorSelector('label', $hasError)
        'block text-sm font-medium',       
    ]) }}>
    {{ $label ?? $slot }}
</label>
```
A default provider for wireui would register a mapping for the `Label` component like this

```php
//...some provider
WireUiColor::registerColor('label', 'text-secondary-700 dark:text-gray-400', 'text-negative-600');
```

and on my side (using wireui and daisyui)
```php
//...some provider
WireUiColor::registerColor('label', 'text-secondary', 'text-error');
```

**Describe alternatives you've considered**

Ive gone down the route of publishing and override the wireui view files in order to have a unified color theme.

For example, the original label blade file from wireui
```php
<label {{ $attributes->class([
        'block text-sm font-medium',
        'text-negative-600'  =>  $hasError,
        'text-secondary-700 dark:text-gray-400' => !$hasError,
    ]) }}>
    {{ $label ?? $slot }}
</label>
```
and my modified version

```php
<label {{ $attributes->class([
        'block text-sm font-medium',
        'text-error'  =>  $hasError,
        'text-secondary' => !$hasError,
    ]) }}>
    {{ $label ?? $slot }}
</label>
```

It would be beneficial to avoid overriding the themes for just coloring as I would be able to keep up with the latest and greatest that wireui publishes without merging in changes (which has proven to be taxing)

**Additional context**
I'm able to work on this and submit a PR if it's a feature that is deemed to be beneficial.

**Comment by 627426p** [comment]
Is there any news about this? The ability to use custom non-stepped colours would be great, without having to resort to modifying the original view files.

**Comment by ph7jack** [comment]
@ainesophaur @627426p 
For now, the wireui only supports the tailwind way to modify the theme colors 
https://livewire-wireui.com/docs/colors
Just add the preferred color on the tailwind config and all UI elements will use the new color.
Also is possible to edit by publishing the assets (I don't like this way)

I understand your opinion about the theme provider, but I believe that creating a service to map the colors can add unnecessary complexity to the wireui. We need to make simple things 

You can generate your custom colors using this website https://javisperez.github.io/tailwindcolorshades

If you want to discuss more about it, just tag me to re-open the issue
