### ISSUE TITLE
Lock background scrolling while modal is open

### ISSUE THREAD

**Issue by notscottsmith** [PH7-Jack/livewire-ui#236]
I have got several modals I'm using which take up more than the viewport height on mobile as well as a signature pad in some others - in both cases using the thumb to move the modal up and down can occasionally scroll the background and when trying to sign the signature pad, the background will also scroll (making it extremely difficult to sign the signature pad).

Is there a way to lock the background so that this doesn't happen? Or, are these two separate issues displaying as a similar problem?

**Comment by ph7jack** [comment]
@notscottsmith The wireui by default blocks the scroll only in the body element, but I've implemented the block scroll to all elements using the **main-container** attribute. Just add the attribute into the element.

PS: only available in the release v1.10

`<div main-container> ...`
