### ISSUE TITLE
datetime-picker throws js errors

### ISSUE THREAD

**Issue by patrickweh** [PH7-Jack/livewire-ui#239]
**Describe the bug**
when i use the datetime-picker component i get about 38 alpine warnings. The messages start with »unexpected token ':'« on the wireui_datetime_picker. That only happens on a productive machine.

**To Reproduce**
i have no idea

**Expected behavior**
no errors ;)

**Screenshots**
see attached

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser chrome
 - Version latest

**Additional context**
im loading the wireui scripts before alpine, alpine is loaded via mix not cdn.

thats the first error:

`scripts:1263 Alpine Expression Error: Unexpected token ':'

Expression: "wireui_datetime_picker({
        model: window.Livewire.find('QkreSDvGDyyX9VWMPMtt').entangle('projectEdit.release_date').defer,
        config: {
            interval: 10,
            is12H:    true,
            readonly: false,
            disabled: false,
            min: null,
            max: null,
        },
        withoutTimezone: false,
        timezone:      'Europe/Berlin',
        userTimezone:  '',
        parseFormat:   '',
        displayFormat: 'DD.MM.YYYY',
        weekDays:   wireui::messages.datePicker.days,
        monthNames: wireui::messages.datePicker.months,
        withoutTime: true,
    })"`

the component is used like this:
`<x-datetime-picker wire:model.defer="projectEdit.release_date" withoutTime="true" display-format="DD.MM.YYYY" label="{{__('Erscheinungstermin')}}" />`

i have also tried to just use the simple example from the docu, same problem.
all other components work just fine, including notifications and so on…

**Comment by NkrumahAlipio** [comment]
I have the same probem

**Comment by ph7jack** [comment]
@NkrumahAlipio @patrickweh Your problem is because you don't have the updated wireui lang.
Update your assets and it will be fixed.
Is missing the **wireui::messages.datePicker.days** and **wireui::messages.datePicker.months** lang options
