### ISSUE TITLE
Datepicker not working well with timezone

### ISSUE THREAD

**Issue by eunicevassoa** [PH7-Jack/livewire-ui#244]
Hi

I am trying to use the datetime picker component and I've set the global timezone in `config/app.php` to `Africa/Maputo` and all the variables give me the right time but the datetimepicker component is giving me the time with -2 hours (screenshot 1). The plain date is the correct one and it's variable is the same that I'm using to set the date in the component.
I've already tried to use all the parameters that are related to timezone from the component, but I get no success.

Screenshot 1
![Screenshot from 2022-04-21 09-28-17](https://user-images.githubusercontent.com/45620682/164400790-236f6c99-0b8d-4ebe-b8af-19c968a2537e.png)

Here's the code that I'm trying to use to set the date
`vehicle.blade.php`
``` php
{{ $booking->pickup_datetime }}
 
<x-datetime-picker placeholder="{{ __('Pickup date & time') }}" class="mt-1"
    :min="now()" parse-format="YYYY-MM-DD HH:mm" display-format="DD/MM/YYYY HH:mm"
    interval="30" wire:model.defer="booking.pickup_datetime" :without-tips="true" time-format="24" />
```

`Vehicle.php`
```php
$this->booking->pickup_datetime = Carbon::now();
```

Can I get some help with this, because I didn't want to have to force the original hour to +2 everytime.

**Comment by deshiloh** [comment]
I have the same, please any help

**Comment by arimolzer** [comment]
I'm getting the same issue:

```
<x-datetime-picker
        placeholder="Schedule a callback"
        wire:model.defer="call.scheduled_at"
        :min="now()->subHours(3)"
        :max="now()->addDays(28)"
        :timezone="Auth::user()?->timezone ?? 'Australia/Melbourne'"
        :user-timezone="Auth::user()?->timezone ?? 'Australia/Melbourne'"
>
</x-datetime-picker>
```

In the example above, all the users have the same Melbourne timezone. 

The label value is what the datetime should be, but the input shows the UTC time still. 
![Screen Shot 2022-06-28 at 11 39 31 am](https://user-images.githubusercontent.com/22068367/176068657-840052ea-17d3-4765-9007-316cb5deabe0.png)

![Screen Shot 2022-06-28 at 11 39 53 am](https://user-images.githubusercontent.com/22068367/176068664-4d42b0bf-291a-4200-a82e-27488c94e637.png)

**Comment by deshiloh** [comment]
Can you test again and also by setting the without timezone mode ? I don't have any problem as far as I can see. 
(Don't forget to update with composer update)

**Comment by ph7jack** [comment]
Is everyone with the same error?

@4inka @deshiloh @arimolzer

**Comment by joaopalopes24** [comment]
Does the error persist?

@4inka @deshiloh @arimolzer

**Comment by ph7jack** [comment]
Old issue, closing it now. Feel free to tag me to reopen
