### ISSUE TITLE
Date Time Picker - Daylight Savings / Standard Time Issues

### ISSUE THREAD

**Issue by keldon2295** [PH7-Jack/livewire-ui#249]
Seems like when you go between a daylight savings time and standard time, the time picker starts to change to what the "local timezone" is of the user, even though the settings I set are for UTC.

**Comment by ph7jack** [comment]
Could you provide more information about your app config and your bug?

Laravel Version:
Livewire Verion:
Alpinejs Verion:
Wireui Verion:

Your datetime-picker component config

Explain more your bug, please

**Comment by ph7jack** [comment]
Closing this issue now. The issue is stale for a long time
