### ISSUE TITLE
Silent error on base button if no size set

### ISSUE THREAD

**Issue by spubr** [PH7-Jack/livewire-ui#250]
**Describe the bug**

On the button component, a silent error is raised because a PHP method `explode()` receives a `null` value.

[Link to the location that triggers the error](https://github.com/wireui/wireui/blob/main/src/View/Components/BaseButton.php#L145).

This is because we are looking to see if the value `$modifier` exists in the array `$this->smartAttributes` but `$modifier` is `null` if no size set (xs or md or...), which has the effect of passing `$this->smartAttributes` from an array to `null` instead of `default`.

We noticed this because we are using WireUI ❤️ on our project and we also plugged in [honeybadger.io](https://www.honeybadger.io) which reported us this error.

Thank you and have a good day !

**To Reproduce**
1. Create a view with a button but without size on it.
2. Connect your app on HoneyBadger.
3. See error

**To Fix**
- Replace [this line](https://github.com/wireui/wireui/blob/main/src/View/Components/BaseButton.php#L145) with `if (null === $modifier && !in_array($modifier, $this->smartAttributes)) {`.
- If you're OK with this, can I create a PR ?

**Desktop**
 - OS: MacOS Monterey
 - Browser: Chrome
 - Version: 100.0.4896.127

**Comment by ph7jack** [comment]
@LeBarbuCodeur 
Sorry for my long time to see your issue.
Of course, you are free to create a PR.
Could you provide the error log?

**Comment by gps-dev-team** [comment]
I am facing the same issue:
Log :
[2022-06-06 15:01:49] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [deprecations] is not defined. at /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:207)
[stacktrace]
#0 /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(132): Illuminate\\Log\\LogManager->resolve('deprecations', NULL)
#1 /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(119): Illuminate\\Log\\LogManager->get('deprecations')
#2 /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(108): Illuminate\\Log\\LogManager->driver('deprecations')
#3 /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(122): Illuminate\\Log\\LogManager->channel('deprecations')
#4 /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(71): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleDeprecationError('explode(): Pass...', '/Volumes/Applic...', 280, 8192)
#5 /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8192, 'explode(): Pass...', '/Volumes/Applic...', 280)
#6 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(8192, 'explode(): Pass...', '/Volumes/Applic...', 280)
#7 /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(280): explode('.', NULL)
#8 /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(150): Illuminate\\Support\\Arr::forget(Array, Array)
#9 /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/View/ComponentAttributeBag.php(103): Illuminate\\Support\\Arr::except(Array, Array)
#10 /Volumes/Applications/apps/pgs/portal/vendor/wireui/wireui/src/View/Components/BaseButton.php(79): Illuminate\\View\\ComponentAttributeBag->except(Array)
#11 /Volumes/Applications/apps/pgs/portal/vendor/wireui/wireui/src/View/Components/BaseButton.php(68): WireUi\\View\\Components\\BaseButton->mergeData(Array)
#12 /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/View/Component.php(83): WireUi\\View\\Components\\BaseButton->WireUi\\View\\Components\\{closure}(Array)
#13 /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(187): Illuminate\\View\\Component->Illuminate\\View\\{closure}(Array)
#14 /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesComponents.php(97): value(Object(Closure), Array)
#15 /Volumes/Applications/apps/pgs/portal/storage/framework/views/75f2c92a3eac874952385839acf88f0579a83565.php(24): Illuminate\\View\\Factory->renderComponent()
#16 /Volumes/Applications/apps/pgs/portal/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(83): include('/Volumes/Applic...')
#17 /Volumes/Applications/apps/pgs/portal/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(84): App\\Http\\Livewire\\Products\\ProductList->Livewire\\ComponentConcerns\\{closure}()
#18 /Volumes/Applications/apps/pgs/portal/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(59): Livewire\\LivewireViewCompilerEngine->evaluatePath('/Volumes/Applic...', Array)
#19 /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get('/Volumes/Applic...', Array)
#20 /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#21 /Volumes/Applications/apps/pgs/portal/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#22 /Volumes/Applications/apps/pgs/portal/vendor/livewire/livewire/src/Component.php(235): Illuminate\\View\\View->render()
#23 /Volumes/Applications/apps/pgs/portal/vendor/livewire/livewire/src/HydrationMiddleware/RenderView.php(14): Livewire\\Component->output()
#24 /Volumes/Applications/apps/pgs/portal/vendor/livewire/livewire/src/LifecycleManager.php(141): Livewire\\HydrationMiddleware\\RenderView::dehydrate(Object(App\\Http\\Livewire\\Products\\ProductList), Object(Livewire\\Response))

**Comment by gps-dev-team** [comment]
```
<x-button dark icon="cloud-download" name="export-products" href="{{route('products.export')}}">
                Export Products
            </x-button>
```

**Comment by gps-dev-team** [comment]
This error appears on PHP 8.1 and works fine with PHP 8.0

**Comment by ph7jack** [comment]
PR related https://github.com/wireui/wireui/pull/317

**Comment by ph7jack** [comment]
Closing it. If the error still persists, just tag me to re-open
