### ISSUE TITLE
Add CSP Nonce option

### ISSUE THREAD

**Issue by EthosLuke** [PH7-Jack/livewire-ui#254]
This package has a lot of inline scripts and styling but no way to apply a nonce attribute, meaning you have to leave your website insecure by allowing unsafe-inline or use a different UI framework.

It would be good to have the ability to pass a nonce attribute through to WireUI which could then be applied to all inline styles and scripts to resolve this security issue. Livewire have this functionality @livewireScripts(['nonce' => csp_nonce('script')]) and it would be good if this could be implemented similarly with WireUI e.g. @wireUiScripts('nonce' => csp_nonce('script')])

As it stands this is the only package I'm using which is leaving my project insecure and would like to avoid having to replace it.

**Comment by ph7jack** [comment]
Good catch @EthosLuke . Thanks for reporting

**Comment by ph7jack** [comment]
@EthosLuke It's now implemented. Update to the latest release version
