### ISSUE TITLE
Undefined variable $optionComponent

### ISSUE THREAD

**Issue by 7met** [PH7-Jack/livewire-ui#263]
I did a composer update and wireUI went from version 1.0.0 to 1.1.2. After that the whole application has broken. I have tried cache:clear and view:clear as well as republishing the assets and stopping sail and bringing it back up. The only thing that fixes it is to revert to 1.0.0. I am running Laravel 9.12 on a PHP 8.1 Sail Container.

1. Run version 1.0.0
2. Run ```composer update```
3. Wireui upgrades to v1.1.2
4. Go to any page in my application and it breaks
5. The error blames ```resources/views/vendor/wireui /components / select.blade.php:127``` but my investigation 

I should be able to composer update and not have an issues since this is not a major release.

**Comment by ph7jack** [comment]
Did you publish the resources? The **$optionComponent** is changed to **$template**

**Comment by 7met** [comment]
yes with ```php artisan vendor:publish --tag='wireui.resources'```

**Comment by ph7jack** [comment]
So, you need to update the resources to match the wireui select content

**Comment by ph7jack** [comment]
Closing it now because it's not a wireui bug, you need to publish the resources again.
If you think that it's a wireui bug, tag me to re-open the issue
