### ISSUE TITLE
Input list retornando vaziu

### ISSUE THREAD

**Issue by Tiagospem** [PH7-Jack/livewire-ui#265]
E ai tudo bom?

depois da última atualização os campos de lista pararam de funcionar, todos eles retornam "Empty Options",

nenhuma mensagem de erro é exibida no console.

**Comment by ph7jack** [comment]
Hello @Tiagospem 
Could you describe more your bug? 
Describe your project versions to:
- livewire
- laravel
- alpine
- wireui

**Comment by Tiagospem** [comment]
Vou mandar em português porque meu inglês é péssimo

livewire: 2.10.5
laravel: 9.12.2
alpine: 3.0.6
wireui: 1.1.2

estava utilizando a versão 1.0 do wireUI, como o projeto ainda está em desenvolvimento tento manter todas as dependências atualizadas, verifiquei que tinha uma atualização da lib então efetuei o update dela.

reinstalei o projeto, limpei o cache etc, agora está aparecendo o seguinte

`scripts?id=235d0d74c5081c338eaa35da561bae9d:1 
       Uncaught TypeError: Cannot read properties of undefined (reading 'innerText')
    at Proxy.initOptionsObserver (scripts?id=235d0d74c5081c338eaa35da561bae9d:1:26958)
    at Proxy.init (scripts?id=235d0d74c5081c338eaa35da561bae9d:1:25276)
    at app.js?id=351d6f53835bd40715299117df3aac35:1:4640
    at D (app.js?id=351d6f53835bd40715299117df3aac35:1:4435)
    at app.js?id=351d6f53835bd40715299117df3aac35:1:33449
    at Function.<anonymous> (app.js?id=351d6f53835bd40715299117df3aac35:1:14347)
    at n (app.js?id=351d6f53835bd40715299117df3aac35:1:8461)
    at app.js?id=351d6f53835bd40715299117df3aac35:1:8487
    at ke (app.js?id=351d6f53835bd40715299117df3aac35:1:8491)
    at app.js?id=351d6f53835bd40715299117df3aac35:1:17605`


[Print da página](https://ibb.co/f2VbPxj)

**Comment by ph7jack** [comment]
@Tiagospem Could you test the latest release? https://github.com/wireui/wireui/releases/tag/v1.1.3 
Update your alpine version to the latest version https://github.com/alpinejs/alpine/releases/tag/v3.10.2

**Comment by ph7jack** [comment]
Another question, did you publish the resources?

**Comment by Tiagospem** [comment]
> Another question, did you publish the resources?
@PH7-Jack 
sim, ainda verifiquei essa questão, eu tinha componentes customizados, apaguei e republiquei os originais, o erro persistiu.
ainda ressalto que a publish de lang está com erro.
Can't locate path: </var/www/html/vendor/wireui/wireui/src/Providers/../../resources/lang>

**Comment by Tiagospem** [comment]
Após a atualização do alpine e wireUI o erro persiste.

`Uncaught TypeError: Cannot read properties of undefined (reading 'innerText')
    at Proxy.initOptionsObserver (scripts?id=9d225009069d65aea9807fdaf173cfe7:1:27062)
    at Proxy.init (scripts?id=9d225009069d65aea9807fdaf173cfe7:1:25276)
    at app.js?id=351d6f53835bd40715299117df3aac35:1:4640
    at D (app.js?id=351d6f53835bd40715299117df3aac35:1:4435)
    at app.js?id=351d6f53835bd40715299117df3aac35:1:33449
    at Function.<anonymous> (app.js?id=351d6f53835bd40715299117df3aac35:1:14347)
    at n (app.js?id=351d6f53835bd40715299117df3aac35:1:8461)
    at app.js?id=351d6f53835bd40715299117df3aac35:1:8487
    at ke (app.js?id=351d6f53835bd40715299117df3aac35:1:8491)
    at app.js?id=351d6f53835bd40715299117df3aac35:1:17605`

**Comment by ph7jack** [comment]
Could you test in the google chome?

**Comment by WeedTest** [comment]
hello friends i got the same problem.
"wireui scripts:1 Uncaught TypeError: Cannot read properties of undefined (reading 'innerText')"
when i make a request with livewire to show a form that contains <x-select /> tag
