### ISSUE TITLE
New validateConfig() in native select breaks option-key-value functionality

### ISSUE THREAD

**Issue by babist** [PH7-Jack/livewire-ui#267]
**Describe the bug**
I cannot use `option-key-value` anymore in selects.

**To Reproduce**
1. Add `<x-select>`
2. Add `:option-key-value="true"`
3. Do NOT add `option-value`
4. Add `option-label`
5. Try to render

**To Solve**
Fix `validateConfig()` in `NativeSelect.php` to take `option-key-value` into account.

**Comment by ph7jack** [comment]
Hello @babist 
It's the expected behavior. You must use the option label and value together.
The **option-key-value** is only for an array of primitive values, like string, number...

**Comment by babist** [comment]
I do not understand why **option-key-value** should only be used with primitive values. Please take a look at my case:

I have this array in my app's config:

```php
[
    // ...

    'statuses' => [
        'confirmed' => [
            'label' => 'Confirmed',
        ],
        'awaiting_payment' => [
            'label' => 'Awaiting Payment',
        ],
        'paid' => [
            'label' => 'Paid',
            'warning' => 'Some warning...',
        ],
        'shipped' => [
            'label' => 'Shipped',
            'warning' => 'Another warning',
        ],
    ],

]
```

The options' values need to be the keys of the `statuses` array, but their label should be the `label` key of each element.

**Comment by ph7jack** [comment]
@babist Interesting...

**Comment by babist** [comment]
Is this going to be fixed? Should I try to create a PR?

PS. sorry for the late response, I was on holiday.

**Comment by ph7jack** [comment]
@babist it's going to be released today. I was fixing a performance issue before fix it

**Comment by babist** [comment]
Wow, already?! That's awesome, thanks!

**Comment by ph7jack** [comment]
@babist Thanks for changing my opinion about that. You're right, thanks.

**Comment by ph7jack** [comment]
Update to the latest release to see the changes

**Comment by babist** [comment]
Yaay! Thanks for the update!
