### ISSUE TITLE
Can no longer slot custom html into select options

### ISSUE THREAD

**Issue by EthosLuke** [PH7-Jack/livewire-ui#269]
**Describe the bug**
Prior to the recent update that introduced the async select options, when using the slot options you could insert custom elements into the options list, for example you could add a button to the bottom of the list to allow the user to add a new entry.

**To Reproduce**
Put anything other than `<x-select.option>` or `<x-select.user-option>` inside the `<x-select>` element and it will be ignored. For example in the below code the `<div>` and `<x-button>` elements are now missing in the rendered output:

```
<x-select
    {{ $attributes }}
>
    @php
        $contacts = auth()->user()->company->contacts()
            ->where('user_id', '=', auth()->user()->id)
            ->orWhere('shared', '=', true)->get();
    @endphp
    <div class="text-ethos-gray p-2 w-full bg-slate-100">Internal Contacts</div>
    @foreach(auth()->user()->company->users as $user)
        <x-select.user-option
            img="{!! $user->profile_photo_url !!}"
            label="{{ $user->display_name }}"
            value='users:{{ $user->id }}'
        />
    @endforeach
    <div class="text-ethos-gray p-2 w-full bg-slate-100">External Contacts</div>
    @foreach($contacts as $contact)
        <x-select.user-option
            img="https://ui-avatars.com/api/?name={{urlencode($contact->name)}}&color=ffffff&background=bec923"
            label="{{ $contact->name }}"
            value='contacts:{{ $contact->id }}'
        />
    @endforeach
    <x-button class="w-full" label="Add Contact" icon="user-add" wire:click="$emit('openModal', 'modal.create-contact')" />
</x-select>
```

**Expected behavior**
I understand this was probably not intentional functionality however in the past this did work and would enable to customise the options extensively. For my use case I just need to be able to add headings and a button at the bottom of the options however I'm sure there are numerous other use-cases for being able to insert custom elements.

**Comment by ph7jack** [comment]
@EthosLuke thanks for reporting it
I will added the slots top/bottom to allow this modification

**Comment by ph7jack** [comment]
It's now implemented in https://github.com/wireui/wireui/pull/310
