### ISSUE TITLE
Select Component options detected as null

### ISSUE THREAD

**Issue by allanpusta13** [PH7-Jack/livewire-ui#273]
Options has value like previously on other versions was working.

Upon update options on dropdown is not rendering and errors occur like it said.
"Uncaught TypeError: Cannot convert undefined or null to object"

Laravel 9
Latest WireUi

**Comment by ph7jack** [comment]
Are you using the latest alpinejs version?

**Comment by allanpusta13** [comment]
yes

**Comment by ph7jack** [comment]
Could you show me your select config? 
i.g 
`<x-select .... />`

**Comment by allanpusta13** [comment]
![image](https://user-images.githubusercontent.com/35389430/168520907-e1e41223-33f5-45dc-9d04-37d13c641028.png)
![image](https://user-images.githubusercontent.com/35389430/168520977-de6f09b1-b609-43d5-8741-4a9a82be1361.png)

**Comment by allanpusta13** [comment]
![image](https://user-images.githubusercontent.com/35389430/168521268-7c83faeb-d860-4d1b-95b0-7a70c674c794.png)

**Comment by ph7jack** [comment]
@allanpusta13 if you use the WireUI example, does it's work?
```
<x-select
    label="Select Status"
    placeholder="Select one status"
    :options="[
        ['name' => 'Active',  'id' => 1],
        ['name' => 'Pending', 'id' => 2],
        ['name' => 'Stuck',   'id' => 3],
        ['name' => 'Done',    'id' => 4],
    ]"
    option-label="name"
    option-value="id"
    wire:model.defer="model"
/>
```

**Comment by allanpusta13** [comment]
Also tried it sir but it won't work

**Comment by ph7jack** [comment]
Could you set the default model value to null?

**Comment by allanpusta13** [comment]
I'll try

**Comment by allanpusta13** [comment]
it has the same error

**Comment by ph7jack** [comment]
Or try to delay the alpine starts, use the WireUI load hook to start the alpinejs, I think is something with the alpine js
But, make sure if your wireui, alpine and livewire are updated, and the scripts are in the correct order in your layout
https://livewire-wireui.com/docs/get-started

```
import Alpine from 'alpinejs'

window.Alpine = Alpine

window.Wireui.hook('load', () => Alpine.start())
```

**Comment by allanpusta13** [comment]
I tried it Sir but more errors came up

**Comment by Tiagospem** [comment]
@PH7-Jack same problem

**Comment by ph7jack** [comment]
Could you reproduce this error in a new project and put it on GitHub?
Without the full context is hard to know what is firing this error

**Comment by allanpusta13** [comment]
@PH7-Jack Sir I have the sample here, cheers to your work and I love wireui, it would really help me a lot if this would be solved.

All in the composer packages are on their latest versions.

https://github.com/allanpusta13/wireui-select-component-bug

**Comment by ph7jack** [comment]
@allanpusta13 Good, looking at it now.

**Comment by allanpusta13** [comment]
Noted and looking forward to your feedback!

**Comment by ph7jack** [comment]
@allanpusta13 The bug only happens when the powergrid scripts is added to the layout

**Comment by allanpusta13** [comment]
@PH7-Jack so I have to remove the powergrid script on every form?

**Comment by ph7jack** [comment]
I understand this problem now. Your project was not configured properly with the PowerGrid
See this guide
Just configure correctly your project. WireUI + PG is a good choice
https://livewire-powergrid.com/#/get-started/configure?id=_22-as-a-module

![image](https://user-images.githubusercontent.com/38913462/169463450-354565dd-75e8-4ddc-9d0b-db653e91bc4e.png)
![image](https://user-images.githubusercontent.com/38913462/169463505-9de6ddd3-d228-42a0-89bb-deb160fe64ac.png)

**Comment by ph7jack** [comment]
Remember to use the lastest Alpinejs version

**Comment by ph7jack** [comment]
![image](https://user-images.githubusercontent.com/38913462/169463719-7c71f957-1b7f-43b8-ad89-971004d9fc4f.png)

**Comment by ph7jack** [comment]
Closing this issue now. 

@allanpusta13 @Tiagospem 
Only for reference:
This error happens because the alpine js is loaded in the script and in the PG CDN. Use only one of these.
Import the pg scripts in the app.js module
Is better to set the alpine_cdn to null

If this error still happening, tag me with the "RE-OPEN" comment.

**Comment by allanpusta13** [comment]
@PH7-Jack worked like a charm!
Thanks so much for the tips and solution!

I didn't seem to try to config the powergrid previously because it was working well with the previous versions of wireui.

Again Thanks a lot!!!
