### ISSUE TITLE
JavaScript error causes all JS to not work

### ISSUE THREAD

**Issue by eswachsman** [PH7-Jack/livewire-ui#275]
I am getting the following Javascript error, and I'm not sure what is causing it. 

Styles are working perfectly, but anything that uses JavaScript is not working.

`Uncaught TypeError: Cannot read properties of undefined (reading 'hook')`

![2022-05-16 10_21_26-Grapevine](https://user-images.githubusercontent.com/6518373/168614652-52292987-4b19-47e1-85c0-26e6f507d1e8.png)

**Comment by ph7jack** [comment]
How is your script importing order?

**Comment by eswachsman** [comment]
I started with a basic Laravel Breeze installation and added the WireUI import right before `app.js` import in `app.blade.php`

![image](https://user-images.githubusercontent.com/6518373/168619546-31acc282-da77-4e6c-b218-ac593f5f8739.png)

**Comment by eswachsman** [comment]
And alpine gets imported in app.js

![image](https://user-images.githubusercontent.com/6518373/168620013-a7b275f4-8cd0-44eb-81b3-f68259b7d64c.png)

**Comment by eswachsman** [comment]
I tried changing around the order to all different ways, I still have the same issue.

**Comment by eswachsman** [comment]
I see now that I had simply not imported the livewire scripts, which was the reason I was getting the errors. Some JS seems to now work but I am now getting other errors. Does this have anything to do?

![image](https://user-images.githubusercontent.com/6518373/168648181-4f69df0a-03b5-40bb-a8f3-3c4294a555b5.png)

**Comment by eswachsman** [comment]
If anyone lands here for the same issue:

You need to include `<livewire:scripts />` if you haven't yet.
You need to include AlpineJS if you haven't yet.

And your `<wireui:scripts />` needs to be sandwiched in between them.

**Comment by mrinmaisharma** [comment]
I am having this issue.

![image](https://user-images.githubusercontent.com/32324606/176884114-a772b14f-4654-4208-b256-d782df807db9.png)

I have loaded the wireUiScripts like this:

![image](https://user-images.githubusercontent.com/32324606/176884206-15f45ee0-903d-440c-84b3-5d297538f3ec.png)

Alpine js is loaded in app.js like this:

![image](https://user-images.githubusercontent.com/32324606/176884271-d8d908e9-1068-4745-9f40-d7bce2e30ea5.png)

Not sure what is the issue. Please help me out, if anyone knows what's wrong.
