### ISSUE TITLE
Overllapping Values in Select

### ISSUE THREAD

**Issue by itsvivek-in** [PH7-Jack/livewire-ui#276]
**Describe the bug**
I updated the wire UI with my latest Laravel 9 and PHP 8 but when I am using select, while showing the selected value, as option-label, it overlaps with its option-value which doesn't look good. I know I might be missing something but what, I literally have no idea. Can anybody help please?

**Expected behaviour**
Like earlier versions, when I select a value, it should only show "option-label" and "option-description".

**Screenshots**
Before selecting any value:
![without-selecting-any-value](https://user-images.githubusercontent.com/26052569/168663245-aeea487c-0c11-4291-9285-eb408df06db9.png)

After selecting a value: You can see the id which is "option-value" is showing in the background.
![after-selecting-a-value](https://user-images.githubusercontent.com/26052569/168663292-2fdc258f-b95c-4556-ae96-079ed164dc67.png)

**Comment by ph7jack** [comment]
Could you check your tailwind css config? Try to see in the documentation, is wrong in your browser?

**Comment by itsvivek-in** [comment]
Hi, thank you so much for replying. I checked the tailwind CSS config but couldn't find anything.

TailwindCSS config file
![tailwind-configuration](https://user-images.githubusercontent.com/26052569/168740077-0c59a3f8-9f5d-4ce5-a547-6234da86c8f0.png)

Composer Json file
![composer-json](https://user-images.githubusercontent.com/26052569/168740131-5f6e2b77-2d2c-41ae-af6d-cca89c0e5b47.png)

**Comment by ph7jack** [comment]
Could you update your tailwind css? You app is not compiling properly the assets

**Comment by itsvivek-in** [comment]
Hi, I found a solution. I don't know if this is the "perfect one".

I checked all the classes in the wireui select component and noticed that "text-transparent" wasn't working. I tried to make it "important" but still it didn't work. 

So, I made a class with same name and assigned the color transparent CSS.

`.text-transparent {
    color: transparent !important;
}`

Suddenly, everything started working.

@PH7-Jack Thanks a lot for your support.

**Comment by ph7jack** [comment]
It's weird, how many CSS are you using in your project? Only tailwind CSS? Do you have custom CSS classes to conflict with the text-transparent? Or the tailwind is updated? 
Are a lot of questions, haha, but I really want to understand them to resolve it

**Comment by itsvivek-in** [comment]
Tailwind and all its dependencies are already updated to their latest version.

The first and only custom CSS code written by me in the project is ".text-transparent { color: transparent !important; }" only. But I use an external CSS for sidebar navigation. I think this external CSS is the culprit.

So, now I strongly believe that this issue was not related to the WireUI or Tailwind CSS, but to the external CSS.

**Comment by ph7jack** [comment]
@itsvivek-in could you confirm if the external CSS is the problem? So I can add the text-transparent as important by default

**Comment by putera** [comment]
@PH7-Jack , I got the same issue of overlapping, but only if select component has no label on it.

![](https://i.ibb.co/PZ48Qs9/bug.png)

Blade :
```blade
<form wire:submit.prevent="save">

        <x-select
            {{-- label="Search a User"  // dont put label on the component --}}
            wire:model.defer="user"
            placeholder="Select some user"
            :async-data="route('get.users')"
            option-label="name"
            option-value="id"
            option-description="email"
        />

        <x-button dark lg class="mt-10" label="Save" type="submit"/>

    </form>
```

Component
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Welcome extends Component
{
    public $user;

    protected $rules = [
        'user' => 'required|exists:users,id'
    ];

    public function save()
    {
        $this->validate();

        dd($this->user);
    }

    public function render()
    {
        return view('livewire.welcome');
    }
}
```

**Comment by ph7jack** [comment]
@putera are you still having this error?

**Comment by putera** [comment]
> @putera are you still having this error?

Yes brother. Still. Dont know y..

**Comment by ph7jack** [comment]
@putera could you try using the dev-main version?

**Comment by putera** [comment]
> @putera could you try using the dev-main version?

Problem solved ! This issue can be closed.

**Comment by ph7jack** [comment]
@putera Nice, I think it is a conflict with another CSS lib, the class text-transparent. I added the **!important** attribute to the class
