### ISSUE TITLE
On Child Modal on press Escape close all modals

### ISSUE THREAD

**Issue by trippo** [PH7-Jack/livewire-ui#277]
**Describe the bug**
When you have a modal inside another modal if you press Esc, all modals will be closed

**To Reproduce**
Open a modal inside another modal

**Expected behavior**
Close only active modal or have an option to disable Esc event

**Comment by ph7jack** [comment]
@trippo It's now fixed. I've also fixed the tab navigation too. Update to the latest version v1.12.1
