### ISSUE TITLE
Select with error showing text in input behind span

### ISSUE THREAD

**Issue by greenspace10** [PH7-Jack/livewire-ui#287]
**Describe the bug**
when using x-select with array and you validate the underlaid textbox shows the array value behind the span value.

![image](https://user-images.githubusercontent.com/55725358/169703739-bbfd0a1d-dfb5-4683-bcb7-cdc0286cdc76.png)

seems the input error classes are overriding the select text-transparent classes after validation.

Possible solution is to change the class in the select blade to;
```
 <x-dynamic-component
            :component="WireUi::component('input')"
            class="cursor-pointer overflow-hidden !text-transparent !dark:text-transparent"
            x-ref="input"
            x-on:click="togglePopover"
           ...
```
note the addition of ! to the text-transparent classes to mark them as important

**Comment by ph7jack** [comment]
I think that it is related https://github.com/wireui/wireui/issues/276#issuecomment-1133918640

**Comment by greenspace10** [comment]
you are correct, I didn't see that one. 

further I can confirm the issue as I am not using an external css at all in my project.
