### ISSUE TITLE
Import alpine 3 breaks wireui

### ISSUE THREAD

**Issue by willmkt** [PH7-Jack/livewire-ui#289]
When I install Alpine via NPM and impor from app.js it breaks all components.

npm install alpinejs@3 --save-dev

app.js
import Alpine from "alpinejs";

window.Alpine = Alpine;
Alpine.start();

after that all components get undefined.

If I use link in the admin it works, but I need to use imported because using link breaks dropzone.js component.

Is there a way to use it imported?

Thanks

**Comment by ph7jack** [comment]
@willmkt Are you importing the scripts in the correct order?

**Comment by willmkt** [comment]
@PH7-Jack  I have tried in all the possible ways, can you give an example of the correct way?

**Comment by ph7jack** [comment]
Follow this install guide
https://livewire-wireui.com/docs/get-started#installation

wireui
alpine
other js

**Comment by ph7jack** [comment]
Could you provide me the versions of your alpinejs and livewire?

**Comment by joelhmetz** [comment]
In my project, I imported by npm and not by script and it worked.

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">

    
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">

    @livewireStyles

    <wireui:scripts />
    <script src="{{ mix('js/app.js') }}" defer></script>

</head>


And app.js

require('./bootstrap');

import Alpine from 'alpinejs';

window.Alpine = Alpine;

//Alpine.start();

window.Wireui.hook('load', () => Alpine.start());

**Comment by ph7jack** [comment]
@joelhmetz nice, prefer the NPM to the CDN. Is working for you?

**Comment by joelhmetz** [comment]
> 

With Laravel Jetstream it was the only way I could run.

**Comment by ph7jack** [comment]
Great. Thanks for reporting @joelhmetz

**Comment by willmkt** [comment]
I have tried all possible ways to import alpine, but it always breaks with wireui.

After @joelhmetz mention Jetstream, I tried and it works fine.

@PH7-Jack can you check why there is this problem? 

Thanks.

**Comment by ph7jack** [comment]
@willmkt the CDN is complicated to manage, sometimes the alpine load first of wireui.
Glad to know that is working, thanks
