### ISSUE TITLE
Select Options no longer supports integers

### ISSUE THREAD

**Issue by EthosLuke** [PH7-Jack/livewire-ui#295]
**Describe the bug**
Existing edit forms that have integers as the option values no longer work without first converting the integer to a string. For example a user edit form where we would have a select drop-down to select their role, the values being the role id, their existing role is no longer automatically selected unless we first convert the role id variable to a string.

**To Reproduce**
Create an edit modal/form for one of your models, if a select drop-down has integer values it will not default to the value the model already has

A simple form for editing the user's role:
![image](https://user-images.githubusercontent.com/98974453/170242717-3c765463-f0e5-4aab-907a-8217c0afff58.png)

Setting the value from database: 
![image](https://user-images.githubusercontent.com/98974453/170243425-2f336ce0-e544-4a85-b4c0-b28a81a92ac3.png)

Doesn't pre-select the value when opening form:
![image](https://user-images.githubusercontent.com/98974453/170242995-9f59d2fc-9ab0-4a81-96fb-99ab82db97f0.png)

Convert value from database to string:
![image](https://user-images.githubusercontent.com/98974453/170243076-4cb6ab31-9b5b-483c-b4fe-2d6c21ab10bd.png)

Value is now selected when opening form:
![image](https://user-images.githubusercontent.com/98974453/170243176-d766d257-142d-46db-aa58-dcc6e9566e4d.png)

**Comment by KevinEscobarV** [comment]
I have already reported this bug too but no one has replied yet #278
transform arrays like this to solve it, when is multiselect:
$array = array_map('strval', $array);

**Comment by ph7jack** [comment]
@EthosLuke 
The `value="1"` is a string, but `:value="1"` is a number
The WireUI Select is strict to types of comparison

**Comment by ph7jack** [comment]
Could you test it by passing a value as a number?

**Comment by EthosLuke** [comment]
@PH7-Jack Thank you, I can confirm that changing to :value resolves the issue. This never used to be required so may be worth mentioning in the docs?

**Comment by ph7jack** [comment]
@EthosLuke I can add it to the [Troubleshooting](https://livewire-wireui.com/docs/troubleshooting#troubleshooting), passing values to the blade using the **":"** is a common way, it's is found in the laravel documentation https://laravel.com/docs/9.x/blade#component-attributes

**Comment by ph7jack** [comment]
Your problem is now fixed?

**Comment by EthosLuke** [comment]
Resolved
