### ISSUE TITLE
alpine error in searchable x-select

### ISSUE THREAD

**Issue by behvandi11** [PH7-Jack/livewire-ui#301]
Hello. thanks for lovely wireui.
I have a small error in console log.
in x-select when items count is more than 10 search appears on select and I want it, that's great.
but when I use search and then select an item I give Alpine error
`Alpine Expression Error: can't access property "length", c is undefined
Expression: "displayOptions"`

I don't want use async feature.

my syntax : `<x-select
    label="Select Status"
    placeholder="Select one status"
    :options="[
        ['name' => 'Active',  'id' => 1],
        ['name' => 'Pending', 'id' => 2],
        ['name' => 'Stuck',   'id' => 3],
        ['name' => 'Done',    'id' => 4],
        ... ,
       ['name' => 'John',    'id' => 12]
    ]"
    option-label="name"
    option-value="id"
    wire:model.defer="model"
/>`

livewire: 2.10.5
Alpine: 3.10.2
wireui: 1.5

![select](https://user-images.githubusercontent.com/75178945/171149426-e93587cb-8248-41e4-8513-abc9705bb454.JPG)

**Comment by ph7jack** [comment]
@behvandi11 I cant reproduce this bug here. Could you update your dependencies and try again?

**Comment by behvandi11** [comment]
> 

thanks for answer. I create a blank project for test this case. and see alert in console again. this is an alert and has no detrimental effect on select work. notice to important tip: just when you type some thing in search input then choose an option this alert appears on console and I don't  use async mode
