### ISSUE TITLE
Input text with prefix + right-icon bad render

### ISSUE THREAD

**Issue by trippo** [PH7-Jack/livewire-ui#303]
**Describe the bug**
Input text with prefix + right-icon render bad

**To Reproduce**
`<x-input prefix="Importo" wire:model="state.payments[0].price" right-icon="currency-euro"  />`

**Expected behavior**
Distance between prefix and input text

**Screenshots**
<img width="545" alt="image" src="https://user-images.githubusercontent.com/497169/171369032-0e17ee09-f71b-4a1f-b23a-c5756a6e060b.png">

**Comment by ph7jack** [comment]
@trippo You need to add a custom padding when using the prefix
`<x-input class="pl-20" prefix="Importo" wire:model="state.payments[0].price" right-icon="currency-euro" />`

**Comment by trippo** [comment]
I think it is convenient to use flex and prevent use of custom padding

**Comment by rabol** [comment]
the issues is also if the icon is to the left:
<img width="390" alt="Screenshot 2022-06-04 at 19 51 29" src="https://user-images.githubusercontent.com/1177191/172019624-e1a6c379-7e6c-407a-9a4f-826c71805247.png">

```
<x-input wire:model="url" icon="globe" class="pl-20" label="Playlist url" placeholder="your-website.com" prefix="https://www." />
```
