### ISSUE TITLE
Unable to locate color-picker

### ISSUE THREAD

**Issue by gbrits** [PH7-Jack/livewire-ui#306]
A standard installation following the documentation doesn't seem to include the color picker's support out the box?

```
Unable to locate a class or view for component [color-picker].
```

*Reproduce steps:*
1.) Install wireui
2.) Test & verify `x-select` works
3.) Add `<x-color-picker label="Background colour" placeholder="Select the colour" />` and refresh to the error above

**Comment by gbrits** [comment]
It may be because I'm on php7.4
I noticed a new version came out 3 days ago `1.5.0` but that requires `8.0`

I will attempt to upgrade and confirm.

**Comment by gbrits** [comment]
Upgraded to PHP `8.0` & WireUI `1.5.0` and now I get this error:
```
Class "WireUiComponent" not found
```

**Comment by gbrits** [comment]
> Upgraded to PHP `8.0` & WireUI `1.5.0` and now I get this error:
> 
> ```
> Class "WireUiComponent" not found
> ```

I deleted my wireui vendor folder and did an `optimize:clear` and now I'm back to square one where it says the color picker doesn't exist, despite upgrades...

**Comment by gbrits** [comment]
I had to add 
```
'color-picker' => [
    'class' => Components\ColorPicker::class,
    'alias' => 'color-picker',
],
```
into `config/wireui.php`

**Comment by chapdel** [comment]
> 'color-picker' => [
>     'class' => Components\ColorPicker::class,
>     'alias' => 'color-picker',
> ],

Same issue here

**Comment by ph7jack** [comment]
When the config or resources is published, you need to publish again or update your code with the changes on every wireui update
