### ISSUE TITLE
Class "WireUiComponent" not found

### ISSUE THREAD

**Issue by chapdel** [PH7-Jack/livewire-ui#308]
After updating wireui/wireui to its latest version, after the installation it is impossible to launch the application. 

The component that seems to cause the problem is input. 
Do you have any idea how to solve this problem?

**Screenshots**
![Capture d’écran (181)](https://user-images.githubusercontent.com/20987014/172189903-9ca11f88-1a13-4411-846d-f6855d11dcb4.png)

**Desktop:**
 - OS: Windows 11
 - Browser : Chrome
 - Version: 101

**Comment by bhuebschen** [comment]
You need to clear the laravel cache

**Comment by chapdel** [comment]
I did it but it still doesn't work

**Comment by willmkt** [comment]
I had the same issue, just see if you published the components in the views\vendor\wireui folder and delete.

Mine worked after i delete the folder.

**Comment by chapdel** [comment]
@willmkt Thanks
