### ISSUE TITLE
Currency Input Custom Format not readable

### ISSUE THREAD

**Issue by SDJeff** [PH7-Jack/livewire-ui#309]
`<x-inputs.currency thousands="." precision="2" decimal=","
                                label="{{ __('Agency Fee') }}" corner-hint="%"
                                wire:model="agency_fee" />`

You can input for example 5,00 as value in Germany. But if you reload the page the decimal/float of the database will be rendered as 500 even if in the field was saved 5.00 in the correct way.

So in my view the custom format needs to be read and write in the correct way. I am using V1.5 of wireui under L9.17

**Comment by SDJeff** [comment]
Okay seems to be solved if you typecast the field in the eloquent model:

`protected $casts = ['agency_fee' => 'float',]`

Little bit confusing because it ist already defined as 

` $table->decimal('agency_fee')
                ->nullable()
                ->default(0.0);`

**Comment by ph7jack** [comment]
@SDJeff Are you sill with this bug?

**Comment by SDJeff** [comment]
@PH7-Jack Not checked after this workaround.

**Comment by racerguy** [comment]
> @PH7-Jack Not checked after this workaround.

I am seeing the same problem. Have to force it with protected $cast 

I understand some people store decimal as integer and just divide by 100 however could we get a boolean on the currency option for unmodified input or something like that. I think it would help people who store as decimal

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
