### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by showFocus** [PH7-Jack/livewire-ui#316]
**Describe the bug**
Date time component is using 8MB ram for each component I add. When updating the form I ran out of memory, have 512MB in php.ini.

It also loads at least 50 partial views.

**To Reproduce**
1. Adda date time component
2. Check debug bar

**Expected behavior**
Not to use so much RAM

**Screenshots**

**Desktop (please complete the following information):**
 - OSX
 - Chrome

**Additional context**
Laravel 9 & PHP 8.1

`<x-datetime-picker
            label="Appointment Date"
            placeholder="Appointment Date"
            wire:model.defer="appointment_date"
        />`

`<?php

namespace App\Http\Livewire\HousingDisrepair;

use App\Models\HousingDisrepair;
use Livewire\Component;

class Edit extends Component
{
    public HousingDisrepair $housingDisrepair;

    public function mount(HousingDisrepair $housingDisrepair)
    {
        $this->housingDisrepair = $housingDisrepair;
    }

    public function submit()
    {
        $this->validate();

        $this->housingDisrepair->save();

        return redirect()->route('housing-disrepair.edit', $this->housingDisrepair);
    }

    protected function rules(): array
    {
        return [
            'housingDisrepair.appointment_date' => ['nullable', 'date'],
        ];
    }

    public function render()
    {
        return view('livewire.housing-disrepair.edit');
    }
}
`

**Comment by ph7jack** [comment]
@showFocus Which tools you are using to test the memory usage? Is the js or the PHP using much memory?

**Comment by Krato** [comment]
Is happening me too but when rendering multiple icons. I'm using a table with around 600 rows with one trash icon for each row and the page takes to load about 8s. 1s for queries and 7s rendering.

When I to remove the trash icon page loads normally.

Maybe will be great to add cache on icons.

**Comment by joaopalopes24** [comment]
Hey there, thanks for reporting this issue.

Laravel already caches views, it is up to developers to know how to deal with the volume of HTML on pages.
