### ISSUE TITLE
async-data gives errors when using wire:model

### ISSUE THREAD

**Issue by markgoedegebure** [PH7-Jack/livewire-ui#321]
**Describe the bug**
When using async-data option in x-select it works as expected, untill i add a wire:model. At that point i get alot of errors in the console.

**To Reproduce**
1. Add an x-select with async-data option and wire:model option

**Expected behavior**
The model defined in wire:model contains the value of the selected option without any errors

**Screenshots**
![image](https://user-images.githubusercontent.com/44771394/174049219-2bb58790-1710-4a80-9431-d6ab378fee85.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version: 102.0.5005.115

**Additional context**
Laravel v9.17.0
Alpine v3.10.2
Livewire v2.10.5
WireUI v1.6

**Comment by markgoedegebure** [comment]
the problem seems to occur in all wire:model in all selects, with or without async-data option...

**Comment by ph7jack** [comment]
@markgoedegebure Share your component code and the wire model value in the PHP class

**Comment by markgoedegebure** [comment]
Hello @PH7-Jack ,
Thanks for your reply.

My component code:

`
<x-select
                        wire:model.defer="user"
                        :async-data="[
                                'api' => route('api.users.index'),
                                'method' => 'POST',
                                'params' => [] 
                                ]"
                                option-label="name"
                                option-value="id"
                                label="Gebruikers"
                                :wire:key="'select'.now()"
                    />`

My Livewire class:
`
class UserForm extends Component
{
    public User $user;

    public function mount(User $user)
    {
            $this->fill($this->user);
    }

    public function render()
    {
        return view('livewire.users.user-form');
    }
}
`
