### ISSUE TITLE
MS Edge browser support

### ISSUE THREAD

**Issue by augustineasante88** [PH7-Jack/livewire-ui#324]
**Describe the bug**
when using async data x-select to connect to api, it displays empty option but the route works well when tested in postman

**To Reproduce**
1. Add an x-select with async search and connect to api endpoint

**Expected behavior**
it should display a dropdown list of items queried from database

**Screenshots**
this is the results am getting
![git](https://user-images.githubusercontent.com/63601885/174160798-2bf58975-d179-4e7c-a937-8b1ed9ebb445.PNG)

but it should be populated with the array below
![list](https://user-images.githubusercontent.com/63601885/174161774-99c8e310-4ba9-4c07-a569-ecf7c2b09491.PNG)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome, ms edge
 - Version 120.2212.4170.0

**Additional context**
   Laravel v9.11.0
   Alpine v3.10.2
   Livewire v2.5
   WireUI v1.6

**Comment by augustineasante88** [comment]
It works fine on chrome browser but doesn't work on Ms edge

**Comment by cbaconnier** [comment]
I have a select using async data and I didn't encountered any issues with Microsoft Edge on Windows 10.
It would be surprising as Edge is Chromium based.

Could you add more details?

**Comment by ph7jack** [comment]
@augustineasante88 I didn't find issues with the latest versions of alpinejs, livewire, and wireui.
I recommend you to use the latest version of alpinejs, wireui, and livewire
Your livewire version doesn't is supported by wireui
![image](https://user-images.githubusercontent.com/38913462/184062004-f28f13be-44a5-45ce-89fd-1d6c79f1bbc9.png)
https://livewire-wireui.com/docs/get-started

I found only performance issues in the edge, it's solved now
