### ISSUE TITLE
Validate Datetime Picker on livewire component

### ISSUE THREAD

**Issue by yassermohammad** [PH7-Jack/livewire-ui#329]
Hi, I have a Datetime Picker form component like this:
![Screenshot from 2022-06-20 17-51-40](https://user-images.githubusercontent.com/34732441/174611988-fb23778e-7873-40f2-a259-5026ecff5f34.png)
It is the code on backend:
![Screenshot from 2022-06-20 17-53-53](https://user-images.githubusercontent.com/34732441/174612043-306db8ef-41a5-447b-856b-a392ac3fb9b1.png)

but the end.0 field always got required validate even after filling the field. how to come?

**Comment by yassermohammad** [comment]
when I change the wire:model="end.0" to wire:model="end", the data pass to back but it doesn't send data since field has wire:model="end.0" property, I have dynamic Datepicker field they have wire:model="end.*" property which they need validate too

**Comment by ph7jack** [comment]
@yassermohammad I don't understand it. Could you explain more about this issue?

**Comment by yassermohammad** [comment]
I have dynamic fields, a button will add a Datetime Picker component to page:
![Screenshot from 2022-07-05 14-15-29](https://user-images.githubusercontent.com/34732441/177300741-20645a52-8f05-4b2d-b088-5a52956e7628.png)
and delete button will remove it
I defined a rules validation same this:
![Screenshot from 2022-07-05 14-23-11](https://user-images.githubusercontent.com/34732441/177302011-b03dfb06-40e5-4380-8d02-2ae3297993f1.png)
I want to take required validation but it does not work!!!

**Comment by yassermohammad** [comment]
@PH7-Jack Did u understand me?

**Comment by ph7jack** [comment]
@yassermohammad You need to ensure that the model is an array, and have the necessary values/keys to be set.
The validation is working.
Your rules should be. Remember, your `start_date` and `start_start` properties must be an array and have the * keys with a value, it's a livewire limitation
```
protected $rules = [
     'start_date.*' => 'required',
      'start_start.*' => 'required',
];
```

![image](https://user-images.githubusercontent.com/38913462/178130885-29f50732-5171-4f38-a4cd-14fa74607628.png)
![image](https://user-images.githubusercontent.com/38913462/178130887-3ebf975f-2356-4a8d-9c62-b630cd2006ed.png)
![image](https://user-images.githubusercontent.com/38913462/178130891-8e6a6810-1733-4c74-9803-d1e15973dad7.png)

**Comment by yassermohammad** [comment]
@PH7-Jack It worked for me, thank you.
