### ISSUE TITLE
select with async-data doesn't work on Update

### ISSUE THREAD

**Issue by MarigonaHoxhaj** [PH7-Jack/livewire-ui#331]
Hi,

I use select component for gender in Create/Update Person, but unfortunately in Update the selected value is not what is fetched from database, but it selects automatically the first option.

![image](https://user-images.githubusercontent.com/78410229/174626783-df4e4d7b-10d8-4f82-b4d4-85cf0c5aa4de.png)

Looking forward for your feedback.

**Comment by ph7jack** [comment]
@MarigonaHoxhaj Your endpoint have the **selected**  scope?
The wireui will send a request to the api with the selected id/ids

**Comment by MarigonaHoxhaj** [comment]
@PH7-Jack 
Thank you for your feedback. Now, after your answer, I could find the solution.
I recommend to add  an example in the documentation related to these kind of cases.

**Comment by ph7jack** [comment]
@MarigonaHoxhaj I'm now fixing a bug when using the async select without the livewire. What kind of solution did you found? Could you share?

**Comment by MarigonaHoxhaj** [comment]
I check what comes from request, so when request has 'selected', I give this selected id to my filter, and return an array of the results.

**Comment by ph7jack** [comment]
@MarigonaHoxhaj Could you test if this bug is now fixed? If not, let me know

**Comment by MarigonaHoxhaj** [comment]
Hi @PH7-Jack,
Thank you for your fix.
I saw your changes, and unfortunately, my problem is completely something else.

**Comment by ph7jack** [comment]
Interesting, could you record a video or we can go a call to understand it and fix
@MarigonaHoxhaj

**Comment by MarigonaHoxhaj** [comment]
Hi @PH7-Jack ,

Sorry, I have found the solution sending the selected in my GetGenders method, I just said you need to mention in the documentation this:
"@MarigonaHoxhaj Your endpoint have the selected scope?
The wireui will send a request to the api with the selected id/ids"

I created an other issue facing problem with select again, but different from this one.
[https://github.com/wireui/wireui/issues/339](url)
