### ISSUE TITLE
Modal Edit

### ISSUE THREAD

**Issue by joelhmetz** [PH7-Jack/livewire-ui#337]
What is the right way to use the modal, to edit the data?
When I create it to register, everything is working fine.
Below the way I add a modal, I don't know how to retrieve the id to mount it in the edit.

`<x-dropdown.item label="Adicionar Marca do Produto" wire:loading.attr="disabled" wire:loading.class="!cursor-wait" type="button" onclick="$openModal('addModalBrand')" />`

**Comment by ph7jack** [comment]
@joelhmetz 
You can use the modal card example https://livewire-wireui.com/docs/modal#modal-card

I like to create a livewire component with the modal inside. Then open the modal by an event or a button that changes the modal model value.
