### ISSUE TITLE
Select don't display correctly 

### ISSUE THREAD

**Issue by mckenziearts** [PH7-Jack/livewire-ui#338]
In my laravel shopper package that uses wireui components, I have a problem with select on almost all forms. 
I copy and paste a code example on the doc but the result is not the same. And I have no error in console but I can't select a value using select input

<img width="377" alt="Screen Shot 2022-06-23 at 7 05 26 AM" src="https://user-images.githubusercontent.com/14105989/175227639-61fcc190-0a1f-4826-aefa-c841a220b0d1.png">

The option `option-description` is false by default but every time on all select it is displayed.

Since I'm in a package I don't know if I need to add a specific config for it to work properly. Because it is with this new api that I noticed this problem. Before everything was working correctly

Thanks.

**Comment by joelhmetz** [comment]
Updated the package? 
Check if you haven't published the assets, if so, make a backup and delete them, to get the current ones from the package.

**Comment by mckenziearts** [comment]
I am on the latest version. My Laravel package uses wireui as a dependency. So I always update to the latest version. I don't have any error but when I take a code from the doc and publish it I automatically have this behavior

**Comment by ph7jack** [comment]
@mckenziearts Could you show how you are using the select component?

**Comment by mckenziearts** [comment]
I just copied and pasted a code on the doc to see if I was doing a bad implementation but I always had the same problem.. Here a preview https://share.vidyard.com/watch/gPccDR9badM12q4QcDVotf?

**Comment by mrkera** [comment]
I have the same problem

**Comment by REJack** [comment]
There are 3 points to check where I had on this bug.
1. If you have published the views, remove them and republish
2. If you customized the classes/created your own component classes, replace them with original componets in the config or update the code according to the updated WireUI components
3. Check that you load AlpineJS before the WireUI scripts and it need to be v3.x+ 

Sometimes `artisan optimize:clear` helps too 😄

**Comment by mckenziearts** [comment]
I develop a laravel package. So I can't publish the views or make commands inside the project. I just require the package, copy and paste a code from the documentation and I have this result

**Comment by joelhmetz** [comment]
Shows console error.
Shows the order of alpine and wireui calls.

**Comment by mckenziearts** [comment]
There are no errors in the console. I have already shown the result in this comment

> I just copied and pasted a code on the doc to see if I was doing a bad implementation but I always had the same problem.. Here a preview https://share.vidyard.com/watch/gPccDR9badM12q4QcDVotf?

**Comment by ettiennelouw** [comment]
I also had the same problem a while back, and i updated to the lates alpine version and everything was working as expected.

**Comment by ph7jack** [comment]
@mckenziearts Can you show me your app dependencies versions?
- laravel
- livewire
- wireui
- alpinejs

**Comment by mckenziearts** [comment]
> I also had the same problem a while back, and i updated to the lates alpine version and everything was working as expected.

I think this may be my problem. I just checked my dependencies and I'm pretty far behind I will update and test again

**Comment by mckenziearts** [comment]
Fix by upgrading all dependencies in package.json. Thanks
