### ISSUE TITLE
Select doesn't load data

### ISSUE THREAD

**Issue by MarigonaHoxhaj** [PH7-Jack/livewire-ui#339]
Hi @PH7-Jack ,

I am using x-modal to add three different addresses for created organisation, but I am having difficulties with Country select.
Firstly, I can see it loads data, but the select shows "No data", even the arrow in the select(which should open dropdown) doesn't work.
Even if I successfully created the first address(with the country,)when I open the second one, the select show the country of the first one, and doesn't let me to change it.

My select:
![Screenshot 2022-06-23 at 08 53 19](https://user-images.githubusercontent.com/78410229/175234515-35beb512-ace8-4755-873d-4bb0096c3c52.png)

Also below you can find a video I made, to describe the issue I have:

https://user-images.githubusercontent.com/78410229/175230630-96fa049e-b1cb-472a-a9e5-6aefb82bcca1.mp4

**Comment by ph7jack** [comment]
@MarigonaHoxhaj Strange behavior, did you publish the assets? Are you using the latest wireui version?

**Comment by bhuebschen** [comment]
Hello @PH7-Jack,

we found out that the problem is not the assets that are not freshly publishes (we learned from the last problems, that we should do that first).

We tryed to "reuse" the components inside of an wireui-modal, by binding wire:modal to another model, by using  a blade-variable inside of it... the first time (we have multiple openers for the modal) works fine ... the second time you see the problems from the video... and the third time ends in an javascript error-desater.

If you want to reproduce what we have done:

```
                <x-select
                    :label="__('Land')"
                    :placeholder="__('Bitte auswählen...')"
                    :async-data="[
                    'api' => url('/some-url-to-data'),
                    'method' => 'POST'
                    ]"
                    option-label="name"
                    option-value="id"
                    wire:model.defer="address.{{$addressModalType}}.country_id"
                />
```

add to a livewire-component (the form is one): 
```
   public $addressModalType = 'postal';
 
    public array $address = [
        'postal' => [
            'hv_id' => '',
            'entity_hv_id' => '',
            'address_line_1' => '',
            'address_line_2' => '',
            'postal_code' => '',
            'city' => '',
            'country_id' => '',
        ],
        'invoice' => [
            'hv_id' => '',
            'entity_hv_id' => '',
            'address_line_1' => '',
            'address_line_2' => '',
            'postal_code' => '',
            'city' => '',
            'country_id' => '',
        ],
        'delivery' => [
            'hv_id' => '',
            'entity_hv_id' => '',
            'address_line_1' => '',
            'address_line_2' => '',
            'postal_code' => '',
            'city' => '',
            'country_id' => '',
        ],
    ];
```

and change $addressModalType dynamicly to "invoice" for example.. 

if you want, i can provide you an full working example.

**Comment by cbaconnier** [comment]
I suppose that's an issue related with the use of `@entangle` in the Select and Livewire unable to keep track of the changes.
If that's the case, I believe that using `wire:key="address.{{$addressModalType}}.country_id"` would solve the issue.

**Comment by ph7jack** [comment]
@bhuebschen @MarigonaHoxhaj Hummmm, I understand now. As the @cbaconnier said, the `@entangle` is limited to one property. You can use the `wire:key` to reset the component as well.

**Comment by MarigonaHoxhaj** [comment]
@cbaconnier @PH7-Jack 
Thank you for your help. It solved our issue.

**Comment by ph7jack** [comment]
@MarigonaHoxhaj I'm glad to know
