### ISSUE TITLE
Adding alerts as new UI component 

### ISSUE THREAD

**Issue by kai0310** [PH7-Jack/livewire-ui#343]
I want to create an alert UI component like this screenshot.
<img src="https://i.gyazo.com/11e8a1df22a4790cd340a60d822236e6.png" />

**Comment by dominikgeimer** [comment]
You are free to create a pull request. Maybe you are looking for notifications? https://livewire-wireui.com/docs/notifications

This is not a issue, maybe a discussion...

**Comment by ettiennelouw** [comment]
Hi I made a pull request for adding alert #373

**Comment by joaopalopes24** [comment]
This was added in version 2, thanks!
