### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'api')

### ISSUE THREAD

**Issue by Piket564** [PH7-Jack/livewire-ui#344]
Describe the bug
I put a select inside a modal [(wire-elements/modal)](https://github.com/wire-elements/modal),
but on loading the modal, in the console AlpineJS triggers an error:

```

scripts:2 Uncaught TypeError: Cannot read properties of undefined (reading 'api')
    at Proxy.syncProps (scripts:2:43459)
    at Proxy.init (scripts:2:40393)
    at app.js:471:23
    at evaluate (app.js:448:32)
    at app.js:2606:27
    at Function.<anonymous> (app.js:1166:55)
    at flushHandlers (app.js:560:46)
    at stopDeferring (app.js:565:5)
    at deferHandlingDirectives (app.js:568:3)
    at initTree (app.js:778:3)
    
Here the select:

```

```html
<x-select
                    label="Utenti"
                    placeholder="Utenti assegnati"
                    :options="$users"
                    option-label="name"
                    option-value="id"
                    multiple="true"
                    wire:model.defer="sel_users"
                />
```
    
To Reproduce
Can't open the select. Single errror:
Uncaught TypeError: Cannot read properties of undefined (reading 'api')

Expected behavior
Open the modal.

Screenshots
![image](https://user-images.githubusercontent.com/19176918/175988283-efb61ba4-284d-483f-95ac-e03cc4b2a07c.png)

Desktop (please complete the following information):

OS: Microsoft Windows 11 Pro - 10.0.22000 build 22000
Browser: Google Chrome
Version 102.0.5005.115
Smartphone (please complete the following information):

None
Additional context

None

**Comment by PH7-Jack** [comment]
@Piket564 Could you test using google chrome? Has the same error in any browser?

**Comment by ph7jack** [comment]
@Piket564 It happens when using outside a wire-elements modal?
The **multiple="true"** doest not take effect. The correct name is **multiselect**

**Comment by Piket564** [comment]
@PH7-Jack yes, outside wire-elements, and multiple="true" is a mystake, i've also tried with the example select, no results

**Comment by MltStephane** [comment]
I have the same issue.

The undefined property seems to be `props.asyncData` in the `syncProps` method (`ts/components/select/index.ts`) in my case.

**Comment by Piket564** [comment]
Yes, exactly.
Same here, seems some errors with AlpineJs, I'm using webpack.mix.js:

```javascript
require('./bootstrap');
//
import Alpine from 'alpinejs';
import lozad from 'lozad';
import lightGallery from 'lightgallery';
import lgThumbnail from 'lightgallery/plugins/thumbnail'
import lgZoom from 'lightgallery/plugins/zoom'
import lgMediumZoom from 'lightgallery/plugins/mediumZoom'
import lgFullscreen from 'lightgallery/plugins/fullscreen'
import lgAutoplay from 'lightgallery/plugins/autoplay'
import lgShare from 'lightgallery/plugins/share'
import lgVideo from 'lightgallery/plugins/video'
import axios from 'axios'


window.Alpine = Alpine;

Alpine.start();

const observer = lozad();
observer.observe();
```

**Comment by MltStephane** [comment]
I'm using laravel-vite, the latest version of wireui, livewire v2.10.6, alpinejs v3.10.2

**Comment by Piket564** [comment]
Currently I'm using Laravel Mix with:

```
├── @tailwindcss/aspect-ratio@0.4.0
├── @tailwindcss/forms@0.4.1
├── @tailwindcss/typography@0.5.2
├── alpinejs@3.10.2
├── autoprefixer@10.4.5
├── axios@0.25.0
├── flowbite@1.4.7
├── laravel-mix@6.0.49
├── lightgallery@2.5.0
├── lodash@4.17.21
├── lozad@1.16.0
├── postcss-import@14.1.0
├── postcss@8.4.14
└── tailwindcss@3.1.4
```

Npm: 8.9.0
Node: 17.7.1


Do you suggest to go with laravel-vite?

**Comment by saulens22** [comment]
Deleting `resources/views/vendor/wireui` folder helped me. Package was updated, but `publish` command doesn't overwrite existing 'old' components.

**Comment by MltStephane** [comment]
I had the same problem in another project, with almost the same packages. It happened after the wireui upgrade

I already tried to remove the published assets. It still doesn't work, I think this issue is related to a new version of another package (alpine ? livewire ?)

I downgraded to v1.5.0 for now (everything works fine in this version), next week I'll have more time to investigate.

**Comment by Piket564** [comment]
> I had the same problem in another project, with almost the same packages. It happened after the wireui upgrade
> 
> I already tried to remove the published assets. It still doesn't work, I think this issue is related to a new version of another package (alpine ? livewire ?)
> 
> I downgraded to v1.5.0 for now (everything works fine in this version), next week I'll have more time to investigate.

Ok, i will downgrade to keep production "ok", feel free to ask me questions

**Comment by ph7jack** [comment]
@Piket564 Inside a wireui modal it works?

**Comment by Piket564** [comment]
> @Piket564 Inside a wireui modal it works?

Haven't tried, will update the comment asap

**Comment by Piket564** [comment]
I tried wit v1.5.0 but still there are some errors:

![image](https://user-images.githubusercontent.com/19176918/178206807-998f6843-56fc-4d3c-9e10-d7dbabfa96cb.png)


Here the blade:

```php
<x-select
label="Select Statuses"
placeholder="Select many statuses"
multiselect
:options="['Active', 'Pending', 'Stuck', 'Done']"
/>
```

This error is without WireUi Modal, i'm using a simple livewire page for this.


> Edit: adding wire:model now it works properly.

**Comment by ph7jack** [comment]
@Piket564 If you are using an outdated wireui version, try updating to the latest version. Is the bug still happening in the latest wireui version?
If did you publish the resources, will need to update them

**Comment by Piket564** [comment]
> @Piket564 If you are using an outdated wireui version, try updating to the latest version. Is the bug still happening in the latest wireui version? If did you publish the resources, will need to update them

With 1.5 WireUi is working fine, i've also deleted the resources.
With 1.7.0 the error persist

**Comment by ph7jack** [comment]
@Piket564 Try using this https://github.com/wireui/wireui/releases/tag/v1.12.1
If the error persist let me know, will be easier to find the bug

**Comment by MarceloZapatta** [comment]
I had the same issue when using select in a modal. But when removing resources/views/vendor/wireui the problem was fixed.

**Comment by ph7jack** [comment]
@Piket564 I'm closing this issue now, if your problem still persisting, tag me to reopen

**Comment by affektde** [comment]
Hello we have upgraded to version 1.15.0 and now some selects do not work.

![image](https://user-images.githubusercontent.com/5022192/187093537-debe2e69-d49b-4dfd-99a4-84ca5c08854b.png)

We use latest Laravel Vite and our AlpineJs is loaded at the end of our app.js. This worked until now:

```
// lastly alpinejs
window.Alpine = Alpine
Alpine.plugin(mask)
Alpine.plugin(intersect)
Alpine.plugin(persist)
Alpine.plugin(focus)
Alpine.plugin(collapse)
Alpine.plugin(morph)
Alpine.start()

livewire_hot_reload();
```

And there is a problem with multiselect. `multiselect` is not defined in our HTML template. But the first item of the select ist preselected and if you choose another one, two are selected.

![image](https://user-images.githubusercontent.com/5022192/187093810-018f296d-4885-49a5-8a94-abd7d15a1b92.png)

```
<x-select
            label="Catalog label"
            wire:model.debounce="state.label_id"
            placeholder="Select catalog label"
            :async-data="route('api.labels.options')"
            :template="[
                                    'name'   => 'user-option',
                                    'config' => ['src' => 'logo']
                                ]"
            option-label="name"
            option-value="id"
            :clearable="false"
            hint="Only record labels with track catalog prefix and release catalog prefix defined."
        />
```

This is also new and same code worked in older versions. Testing older versions now to verify.

**Comment by affektde** [comment]
Version 1.13.3 is the latest version working for us without problems. Higher versions produce screenshots above.

**Comment by saulens22** [comment]
@affektde  Please try this: https://github.com/wireui/wireui/issues/344#issuecomment-1177236512

Also @PH7-Jack , maybe it should be documented? It happens quite frequently after updates if you have published blade views.

**Comment by gbrits** [comment]
> Deleting `resources/views/vendor/wireui` folder helped me. Package was updated, but `publish` command doesn't overwrite existing 'old' components.

I had a different error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'interval')
    at Proxy.syncProps (scripts?id=3c15fb3b36f54e2baae1e97b6eb0015e:1:28995)
    at Proxy.init (scripts?id=3c15fb3b36f54e2baae1e97b6eb0015e:1:28286)
    at app.js?ver=2023-11-14:471:23
    at evaluate (app.js?ver=2023-11-14:448:32)
    at app.js?ver=2023-11-14:2662:27
    at Function.<anonymous> (app.js?ver=2023-11-14:1179:55)
    at flushHandlers (app.js?ver=2023-11-14:575:46)
    at stopDeferring (app.js?ver=2023-11-14:580:5)
    at deferHandlingDirectives (app.js?ver=2023-11-14:583:3)
    at initTree (app.js?ver=2023-11-14:792:3)
```

And taking your advice solved the problem:
```
rm -rf resources/views/vendor/wireui
```

**Comment by hebertreis** [comment]
I encountered the same issue with Laravel 11 and WireUI 2.2.1. The problem was related to the <label> tag. Removing the <label> resolved the error for me.

### From:
```blade
<div class="space-y-2">
    <label for="representative_occupation" class="block font-medium">Ocupação</label>
    <x-select
        :async-data="route('ocupacoes.search')"
        wire:model.defer="formData.representative_occupation"
        option-label="title"
        option-value="title"
    />
</div>
``` 

### To:
```blade
<div class="space-y-2">
    
    <x-select
        label="Ocupação"
        :async-data="route('ocupacoes.search')"
        wire:model.defer="formData.representative_occupation"
        option-label="title"
        option-value="title"
    />
</div>
``` 

Removing the <label> tags helped avoid conflicts within the component layout. Hope this helps others facing similar issues!

![2024-11-12_17-20](https://github.com/user-attachments/assets/c4200826-280f-487e-b56e-51e002d680b3)

```shell
$composer show  awk '{print $1 "@" $2}' 

beste/clock@3.0.0
beste/in-memory-cache@1.3.1
beste/json@1.5.0
brianium/paratest@7.6.0
brick/math@0.12.1
carbonphp/carbon-doctrine-types@3.2.0
dflydev/dot-access-data@3.0.3
doctrine/deprecations@1.1.3
doctrine/inflector@2.0.10
doctrine/lexer@3.0.1
dragonmantank/cron-expression@3.4.0
egulias/email-validator@4.0.2
fakerphp/faker@1.24.0
fidry/cpu-core-counter@1.2.0
fig/http-message-util@1.1.5
filp/whoops@2.16.0
firebase/php-jwt@6.10.1
fruitcake/php-cors@1.3.0
google/auth@1.43.0
google/cloud-core@1.60.0
google/cloud-storage@1.44.0
google/common-protos@4.8.3
google/gax@1.35.0
google/grpc-gcp@0.4.0
google/longrunning@0.4.4
google/protobuf@4.28.3
graham-campbell/result-type@1.1.3
grpc/grpc@1.57.0
guzzlehttp/guzzle@7.9.2
guzzlehttp/promises@2.0.4
guzzlehttp/psr7@2.7.0
guzzlehttp/uri-template@1.0.3
hamcrest/hamcrest-php@2.0.1
jean85/pretty-package-versions@2.0.6
kreait/firebase-php@7.15.0
kreait/firebase-tokens@5.2.0
laravel/breeze@2.2.5
laravel/framework@11.31.0
laravel/pail@1.2.1
laravel/pint@1.18.1
laravel/prompts@0.3.2
laravel/sail@1.38.0
laravel/serializable-closure@1.3.6
laravel/tinker@2.10.0
lcobucci/jwt@5.4.2
league/commonmark@2.5.3
league/config@1.2.0
league/flysystem@3.29.1
league/flysystem-local@3.29.0
league/mime-type-detection@1.16.0
livewire/livewire@3.5.12
livewire/volt@1.6.6
mockery/mockery@1.6.12
monolog/monolog@3.8.0
mtdowling/jmespath.php@2.8.0
myclabs/deep-copy@1.12.1
nesbot/carbon@3.8.2
nette/schema@1.3.2
nette/utils@4.0.5
nikic/php-parser@5.3.1
nunomaduro/collision@8.5.0
nunomaduro/termwind@2.2.0
pestphp/pest@3.5.1
pestphp/pest-plugin@3.0.0
pestphp/pest-plugin-arch@3.0.0
pestphp/pest-plugin-laravel@3.0.0
pestphp/pest-plugin-mutate@3.0.5
phar-io/manifest@2.0.4
phar-io/version@3.2.1
phpdocumentor/reflection-common@2.2.0
phpdocumentor/reflection-docblock@5.6.0
phpdocumentor/type-resolver@1.10.0
phpoption/phpoption@1.9.3
phpstan/phpdoc-parser@2.0.0
phpunit/php-code-coverage@11.0.7
phpunit/php-file-iterator@5.1.0
phpunit/php-invoker@5.0.1
phpunit/php-text-template@4.0.1
phpunit/php-timer@7.0.1
phpunit/phpunit@11.4.3
psr/cache@3.0.0
psr/clock@1.0.0
psr/container@2.0.2
psr/event-dispatcher@1.0.0
psr/http-client@1.0.3
psr/http-factory@1.1.0
psr/http-message@2.0
psr/log@3.0.2
psr/simple-cache@3.0.0
psy/psysh@0.12.4
ralouphie/getallheaders@3.0.3
ramsey/collection@2.0.0
ramsey/uuid@4.7.6
rize/uri-template@0.3.8
sebastian/cli-parser@3.0.2
sebastian/code-unit@3.0.1
sebastian/code-unit-reverse-lookup@4.0.1
sebastian/comparator@6.2.1
sebastian/complexity@4.0.1
sebastian/diff@6.0.2
sebastian/environment@7.2.0
sebastian/exporter@6.1.3
sebastian/global-state@7.0.2
sebastian/lines-of-code@3.0.1
sebastian/object-enumerator@6.0.1
sebastian/object-reflector@4.0.1
sebastian/recursion-context@6.0.2
sebastian/type@5.1.0
sebastian/version@5.0.2
symfony/clock@7.1.6
symfony/console@7.1.7
symfony/css-selector@7.1.6
symfony/deprecation-contracts@3.5.0
symfony/error-handler@7.1.7
symfony/event-dispatcher@7.1.6
symfony/event-dispatcher-contracts@3.5.0
symfony/finder@7.1.6
symfony/http-foundation@7.1.7
symfony/http-kernel@7.1.7
symfony/mailer@7.1.6
symfony/mime@7.1.6
symfony/polyfill-ctype@1.31.0
symfony/polyfill-intl-grapheme@1.31.0
symfony/polyfill-intl-idn@1.31.0
symfony/polyfill-intl-normalizer@1.31.0
symfony/polyfill-mbstring@1.31.0
symfony/polyfill-php80@1.31.0
symfony/polyfill-php83@1.31.0
symfony/polyfill-uuid@1.31.0
symfony/process@7.1.7
symfony/routing@7.1.6
symfony/service-contracts@3.5.0
symfony/string@7.1.6
symfony/translation@7.1.6
symfony/translation-contracts@3.5.0
symfony/uid@7.1.6
symfony/var-dumper@7.1.7
symfony/yaml@7.1.6
ta-tikoma/phpunit-architecture-test@0.8.4
theseer/tokenizer@1.2.3
tijsverkoyen/css-to-inline-styles@2.2.7
vlucas/phpdotenv@5.6.1
voku/portable-ascii@2.0.1
webmozart/assert@1.11.0
wireui/heroicons@2.7.0
wireui/wireui@2.2.1
```
