### ISSUE TITLE
Select não trazendo opção selecionada

### ISSUE THREAD

**Issue by Tiagospem** [PH7-Jack/livewire-ui#346]
Eu fiz o update para versão 1.7, estou utilizando a lib em um projeto desde a 0.16.

Após o update o select utilizando slots parou de trazer os dados selecionados

```
$model = 1;

<x-select label="Select Status" placeholder="Select one status" wire:model.defer="model">
    <x-select.option label="Pending" value="1" />
    <x-select.option label="In Progress" value="2" />
</x-select>

```
Retorna o campo em branco, todos os formulários de alterar estão com os campos não selecionados.

Já o exemplo abaixo funciona perfeitamente:

```
$model = 1;

<x-select label="Select Status" placeholder="Select one status" wire:model.defer="model"
    :options="[
        ['name' => 'Pending',  'id' => 1],
        ['name' => 'In Progress', 'id' => 2]
    ]"
    option-label="name"
    option-value="id"
/>
```

Nenhuma mensagem de erro é exibida

"laravel/framework": "^9.0"
"wireui/wireui": "^1.7"
"tailwindcss": "^3.0.0"
"alpinejs": "^3.10.2"
"livewire/livewire": "^2.10"

**Comment by willmkt** [comment]
Updated to 1.7 today and I'm having the same problem

**Comment by joelhmetz** [comment]
https://github.com/wireui/wireui/issues/295

**Comment by willmkt** [comment]
@joelhmetz I did like you showed, but it is not showing the selected value once it loads

The value is saved, but if I reload the value is not selected anymore.

The native select works fine, but the select withe slot is not

This issue started after the package update

**Comment by Tiagospem** [comment]
@joelhmetz The only solution is to review all the code and put the correct typing in the value parameter

**Comment by Tiagospem** [comment]
@joelhmetz @PH7-Jack thanks, solved.
