### ISSUE TITLE
Strict types for radio and checkbox and update changelog

### ISSUE THREAD

**Issue by Tiagospem** [PH7-Jack/livewire-ui#347]
The select component is now restricted to comparison types, and my project code had to be refactored. 

The checkbox and radio fields only accept string type, most of the cases it is necessary to use a boolean or integer, in these cases I have to use $model = 'true' or $model = '1', it would be interesting to be restricted to types too. 

Another suggestion is update the changelog in the documentation, some functions are deprecated and I only noticed because my IDE notified them.

**Comment by ph7jack** [comment]
Which page in the documentation has deprecated function usage?

**Comment by ph7jack** [comment]
About the strict types, the select component is not fully strict, is possible to have a model with a value = '1' and options with the value 1 or '1', both will work.
Give me an example of if the component has strict behavior in your project. Tag me to re-open the issue

**Comment by Tiagospem** [comment]
@PH7-Jack 

don't work
```
$model = true
<x-radio name="open" value="true"  wire:model="model" />
<x-radio name="open" value="false"  wire:model="model" />
```
don't work
```
$model = true
<x-radio name="open" :value="true"  wire:model="model" />
<x-radio name="open" :value="false"  wire:model="model" />
```
works
```
$model = 'true'
<x-radio name="open" value="true"  wire:model="model" />
<x-radio name="open" value="false"  wire:model="model" />
```
 "alpinejs": "^3.10.2",
  "wireui/wireui": "^1.7"

**Comment by ph7jack** [comment]
@Tiagospem It's a livewire limitation. The WireUI checkbox and the radio are simple HTML elements, doest have any alpine data inside them
If you use the native checkbox or the input will get the same behavior
