### ISSUE TITLE
Wire UI Script isn't working and causing errors

### ISSUE THREAD

**Issue by mrinmaisharma** [PH7-Jack/livewire-ui#351]
I am having this issue.

![image](https://user-images.githubusercontent.com/32324606/176884616-fd53ce7c-4f32-4fd7-ab11-f87c110f47ff.png)

I have loaded the wireUiScripts like this:

![image](https://user-images.githubusercontent.com/32324606/176884666-8ecb3d11-e3b3-467c-be7d-af66c3008223.png)

Alpine js is loaded in app.js like this:

![image](https://user-images.githubusercontent.com/32324606/176884696-ddbcf8ba-7915-494a-8c06-451a698df139.png)

Not sure what is the issue. Please help me out, if anyone knows what's wrong.

**Comment by ph7jack** [comment]
@mrinmaisharma Please, follow the wireui install guide to fix this problem. 
You can follow the wireui docs example too
- https://livewire-wireui.com/docs/get-started
- https://github.com/wireui/docs/blob/main/resources/views/layouts/clean.blade.php
- https://github.com/wireui/docs/blob/main/resources/js/alpine.js

**Comment by ph7jack** [comment]
The wireui script must be before the alpinejs scripts, and the livewire script
For more reference, the laravel jetstream also follow the script importing order
```
head
    alpine
body
   livewire
```
https://github.com/laravel/jetstream/blob/2.x/stubs/livewire/resources/views/layouts/app.blade.php
