### ISSUE TITLE
Passing options in x-select with first key 0 with option-key-value results in first item being selected but not displayed in the field

### ISSUE THREAD

**Issue by modrictin** [PH7-Jack/livewire-ui#362]
Passing options in x-select with first key 0 with option-key-value results in first item being selected but not displayed in the field

**To Reproduce**

Implement code below
```

<x-select
                                    label="Test"
                                    wire:model="testing"
                                    :options="[0=>'lets',1=>'test',2=>'this']"
                                    option-key-value
                                />
```
![image](https://user-images.githubusercontent.com/31577031/177874848-31e785fe-9b15-4eeb-8aef-22ceb000ae71.png)

![image](https://user-images.githubusercontent.com/31577031/177874720-016c3972-8284-4981-a5bd-02e62c9cf074.png)

**Comment by ph7jack** [comment]
@modrictin Thanks for reporting. Fixed. Update to the latest version

**Comment by modrictin** [comment]
@PH7-Jack 

I tried to fix it myself but did not find a way :/ 

I would like to learn how you built it so I can help more. Awesome package!
