### ISSUE TITLE
Some components broken after update to v1.12.1

### ISSUE THREAD

**Issue by Tiagospem** [PH7-Jack/livewire-ui#368]
After update to latest version some components like select, datetime was broken, the directive @wireUiScripts has syntax error and had to be replaced by <wireui:scripts />

<img width="1245" alt="CleanShot 2022-07-11 at 10 28 15@2x" src="https://user-images.githubusercontent.com/8459781/178275875-5607800c-3676-4423-bf2f-e7e5d8871514.png">

<img width="1231" alt="CleanShot 2022-07-11 at 10 21 39@2x" src="https://user-images.githubusercontent.com/8459781/178275959-7da1eda0-cba1-4e05-a4a5-a45b76b01ff9.png">

<img width="1014" alt="CleanShot 2022-07-11 at 10 50 19@2x" src="https://user-images.githubusercontent.com/8459781/178279537-5d6d723b-f536-4f65-9d72-a9360aef3194.png">

**Comment by Tiagospem** [comment]
Solve problem back to wire ui v1.11.3

**Comment by Tiagospem** [comment]
looks like a problem with the edge browser, on chrome works fine

**Comment by Tiagospem** [comment]
clear edge cache and problem is done

**Comment by ph7jack** [comment]
@Tiagospem after clearing the cache it works in the Microsoft edge?

**Comment by Tiagospem** [comment]
@PH7-Jack yes, all works fine after clearing cache in ms edge, except @wireUiScripts directive has a php syntax error "unexpected token ")"

**Comment by ph7jack** [comment]
@Tiagospem it was fixed in the latest release version
v1.12.2
