### ISSUE TITLE
wireUiScripts broken after latest attribute changes

### ISSUE THREAD

**Issue by jksteelman** [PH7-Jack/livewire-ui#369]
**Describe the bug**
Latest commit breaks wireUiScripts blade directive

**To Reproduce**
1. Grab latest commit
2. run `php artisan view:clear`
3. load a page calling @wireUiScripts
4. see error: `Syntax error, unexpected token )` 
5. replace `@wireUiScripts` with `{!! WireUi::directives()->scripts() !!}`, see error goes away

Occurs on php8.0 and php8.1.

**Additional context**
Reverting this line to its previous commit resolves the issue https://github.com/wireui/wireui/blob/e5a734f88d4973f6fe437d667e2c53b1150422e3/src/Providers/WireUiServiceProvider.php#L84

**Comment by ph7jack** [comment]
@jksteelman Thanks for reporting it
