### ISSUE TITLE
Related selects

### ISSUE THREAD

**Issue by ettiennelouw** [PH7-Jack/livewire-ui#372]
**Is your feature request related to a problem? Please describe.**
When you have a select (not the native one) <x-select label="Foo" wire:model="foo" :options="$fooValues" /> and you select a value and use the livewire event updatedFoo($value) { $this->bar = $value } function to set the value of another select <x-select label="Bar" wire:model="bar" :options="$barValues" /> it does not update. It works fine if you use the second select at <x-native-select/>

**Describe the solution you'd like**
To be able to use <x-select/> everywhere.

**Describe alternatives you've considered**
Use <x-select/> as first and <x-native-select/> as second related

Or am I just missing something that needs to be done.

**Comment by ph7jack** [comment]
@ettiennelouw The livewire side updates not working?

**Comment by ettiennelouw** [comment]
Working solution with banks being `<x-select/>` and branch being `<x-native-select/>`

No data in branch as banks needs to be selected first.
<img width="791" alt="Screenshot 2022-07-14 at 13 20 23" src="https://user-images.githubusercontent.com/1754421/178972046-ca4e74f3-4af1-42c8-9889-67be6c173cfd.png">

Select bank
<img width="789" alt="Screenshot 2022-07-14 at 13 20 28" src="https://user-images.githubusercontent.com/1754421/178972039-31baf218-db03-45a1-9a31-3e45c13525a7.png">

Branch and branch code and branch list updated and branch set to selected id
<img width="762" alt="Screenshot 2022-07-14 at 13 20 34" src="https://user-images.githubusercontent.com/1754421/178972016-fea43ddc-0a84-444f-b689-c4c199e1ec80.png">

Has list of branches
<img width="800" alt="Screenshot 2022-07-14 at 13 20 43" src="https://user-images.githubusercontent.com/1754421/178971997-b3cf1487-76f0-4e39-a59b-f2dd16abceae.png">

Using `<x-select/>` for banks and `<x-select/>` for branch

Initial load no data
<img width="760" alt="Screenshot 2022-07-14 at 13 21 40" src="https://user-images.githubusercontent.com/1754421/178972535-190d5609-dffa-40b3-97e3-647c088c81c8.png">

Selected bank, branch code has been updated but branch list update and branch has a selected id but the dropdown still has no values in.
<img width="787" alt="Screenshot 2022-07-14 at 13 21 51" src="https://user-images.githubusercontent.com/1754421/178972521-8a60b3e4-89de-470d-8b5c-b22cb18d123c.png">

I hook into the livewire event

```
public function updatedBank($value)
{
    $this->branches = $this->getBankBranches(['bank_id' => $value]);
    $bank = $this->getBank($value);

    $this->branch_code = $bank->default_branch_code;
    $this->branch = $this->getBankBranchByCode($this->branch_code)?->id;
}
```

**Comment by ph7jack** [comment]
@ettiennelouw I tested here and it worked. 
What is your browser? Have errors on console.log()?
Could you show me the select code snippet?

**Comment by ettiennelouw** [comment]
Hi, I have tested the related dropdown and it works perfectly, I have too many records in the related dropdown so I'm going to change it to an async dropdown and I'm almost sure that will sort out the issue. Thanks
