### ISSUE TITLE
Select async icon

### ISSUE THREAD

**Issue by Krato** [PH7-Jack/livewire-ui#374]
**Describe the bug**
When using select with async and left icon, the selected value is not being shown.

**To Reproduce**
1. Create a select with async and icon
2. Select a value
3. Selected value is not shown

**Expected behavior**
Shoule be shown as the normal select

**Desktop (please complete the following information):**
Is not desktop related

**Smartphone (please complete the following information):**
Is not smartphone related

**Additional context**
Thanks for the components :D

**Comment by ph7jack** [comment]
@Krato Could you add the code snippet of the select component?

**Comment by Krato** [comment]
> @Krato Could you add the code snippet of the select component?

Sure! Check:

```blade
<x-select wire:model="warehouse.branch.id"
    label="Branch" placeholder="Choose the branch"
    :async-data="route('selects.branches')"
    option-label="name"
    option-value="id"
    icon="library"
    :clearable="false"
/>
```

WIthout the icon works:

```blade
<x-select wire:model="warehouse.branch.id"
    label="Branch" placeholder="Choose the branch"
    :async-data="route('selects.branches')"
    option-label="name"
    option-value="id"
    :clearable="false"
/>
```

**Comment by ph7jack** [comment]
@Krato thanks for reporting. It's now fixed

**Comment by Krato** [comment]
> @Krato thanks for reporting. It's now fixed

Thank you to fix it. Amazing 😄
