### ISSUE TITLE
Select cannot clicked

### ISSUE THREAD

**Issue by adhisuranto** [PH7-Jack/livewire-ui#384]
I use select but after updating composer & npm, select can't be clicked and an error message appears like this, how to solve it?
thanks

![image](https://user-images.githubusercontent.com/19567262/179401662-d25e0612-b6da-40fc-afe8-ca02f1b292ae.png)

**Comment by ph7jack** [comment]
@adhisuranto You've published the assets? If so, update them

**Comment by adhisuranto** [comment]
@PH7-Jack I've done it, but it's still the same

**Comment by ph7jack** [comment]
@adhisuranto are you using the latest version? This method doesn't exist

**Comment by adhisuranto** [comment]
@PH7-Jack Yes, so do i have to downgrade the version?
this is my code select

![image](https://user-images.githubusercontent.com/19567262/179446310-9e41ac66-6813-4bf0-9102-71ca3c1e7492.png)

**Comment by adhisuranto** [comment]
resolved,
i deleted wireui assets in resource>views>vendor
and run
build vendor php:publish --tag='wireui.resources'

thanks @PH7-Jack

**Comment by ph7jack** [comment]
@adhisuranto If you don't have changed anything in the vendor assets, you don't need to publish

**Comment by l0gical** [comment]
The togglePopover is also persistent in the errors I have for which I opened an issue on here.
Guessing your dropdown link on the top right of dashboard page is broken too?
