### ISSUE TITLE
Datepicker Safari position

### ISSUE THREAD

**Issue by trippo** [PH7-Jack/livewire-ui#385]
**Describe the bug**
Datepicker position on Safari is different than Chrome.
On Chrome on the bottom , Safari on top.

**To Reproduce**
Use date picker with Safari

**Screenshots**
Chrome
<img width="398" alt="image" src="https://user-images.githubusercontent.com/497169/179491633-ab4988d6-0462-4cad-908a-692c5ddeba68.png">
Safari
<img width="370" alt="image" src="https://user-images.githubusercontent.com/497169/179491660-c9d193a0-fd72-4255-a44e-52df17e0e925.png">

**Comment by ph7jack** [comment]
@trippo Which safari version are you using?

**Comment by trippo** [comment]
the last one on mac

**Comment by ph7jack** [comment]
@trippo The page has space to the bottom? the popover will open to the top if the bottom doesn't have space.

**Comment by trippo** [comment]
Yes is on the top
<img width="343" alt="image" src="https://user-images.githubusercontent.com/497169/180245682-e4f4bf6f-9411-43bf-b0d9-e6e0484db429.png">

**Comment by ph7jack** [comment]
@trippo It's fixed, Let me know if you still have this error

**Comment by trippo** [comment]
Work like a charm thank you so much
<img width="334" alt="image" src="https://user-images.githubusercontent.com/497169/186654416-12cc9b0d-4be6-4e54-8996-369145f02d63.png">
