### ISSUE TITLE
Another bug in select list

### ISSUE THREAD

**Issue by Tiagospem** [PH7-Jack/livewire-ui#390]
When you use model like $active = 0; the list is no longer selected, it was working before.

```
$active = 0;

wont work
<x-select
    label="Select Status"
    placeholder="Select one status"
    wire:model.defer="active">
    <x-select.option label="Not active" :value="0" />
    <x-select.option label="Active" :value="1" />
</x-select>

works
 <x-w.select  label="Select Status" placeholder="Select one status" wire:model="active"     
  :options="[
      ['name' => 'Not active',  'value' => 0],
      ['name' => 'Active', 'value' => 1]]"
  option-label="name"
  option-value="value" />
```

https://user-images.githubusercontent.com/8459781/180061570-44e418bf-0ce5-4f83-b230-17cd00bdec45.mp4

**Comment by ph7jack** [comment]
@Tiagospem You need to update to the latest version, it was a bug in the options map, falsy values were removed from the option object
PR https://github.com/wireui/wireui/pull/364
Release https://github.com/wireui/wireui/releases/tag/v1.11.2

**Comment by ph7jack** [comment]
@Tiagospem Update to the latest release, this bug is now fixed. Let me know if your problem persists
