### ISSUE TITLE
problem in display select results at mobile view

### ISSUE THREAD

**Issue by behvandi11** [PH7-Jack/livewire-ui#396]
Hello
in select component please checkout display results for mobile view(both chrome and firefox)
the results container fixed at bottom the page
thanks

livewire 2.10.6
wireui 1.12.5

![Screen Shot 2022-07-26 at 22 10 31](https://user-images.githubusercontent.com/75178945/181074606-9262e13b-dc55-4cc6-9bed-56d07a892b12.png)

**Comment by ph7jack** [comment]
@behvandi11 Could you explain more about this issue?
The selected option is shown in the mobile view
![image](https://user-images.githubusercontent.com/38913462/181152575-0ee65968-bf96-4613-9be6-865232881212.png)

**Comment by behvandi11** [comment]
@PH7-Jack  dear Pedro please see this url of wireui docs in a real mobile device:
[https://livewire-wireui.com/docs/select](url)

in real mobile (I checked chrome & firefox in android 11) when click on select element, first problem is keyboard opens:
![photo_2022-07-27_12-08-10](https://user-images.githubusercontent.com/75178945/181189855-b77446f2-1537-45cb-ba0f-433314a12e40.jpg)

and on push down keyboard, options fixed at bottom of page:
![photo_2022-07-27_12-08-21](https://user-images.githubusercontent.com/75178945/181190023-9f9405f7-575a-47d4-aa07-709e795a7863.jpg)

**Comment by joaopalopes24** [comment]
@behvandi11 I was able to catch the problem using the phone. I can try to verify @PH7-Jack .

**Comment by ph7jack** [comment]
@behvandi11 I understand the problem, it's because the topbar is shown dynamically. I'm trying a solution with `-webkit-fill-available`

**Comment by Krato** [comment]
Any update? Thanks! 😄

**Comment by ph7jack** [comment]
@Krato @joaopalopes24 @behvandi11 @vlados Fixed, thanks for waiting

**Comment by ph7jack** [comment]
Let me know if you still have this error

**Comment by racerguy** [comment]
Hey @PH7-Jack looks like this problem is fixed on a regular page for me. However when having a modal that is scrollable the option displays off the current scroll position and at the bottom of the modal (which is off the current view position).

Could we get a force-relative option which would fix the select in a scrollable modal and keep it under the select option like on desktop?

For modals I am using the wire-elements/modal package because for the children modal functionality.  I am using the latest version of wireui with this update in it.

**Comment by ph7jack** [comment]
@racerguy could you open an issue and add images/videos about it? 
About modals, the WireUI modal supports nesting modal, you can use unlimited children modals inside the WireUI modal

**Comment by racerguy** [comment]
@PH7-Jack Sure thing will open another tonight and include images/screen caps. 

Thanks for that information I will look into trying the wireui modals and post both incase it is strictly an issue with the wire elements package
