### ISSUE TITLE
Custom params for async select search not working with arrays

### ISSUE THREAD

**Issue by Alph44rchitect** [PH7-Jack/livewire-ui#404]
**Describe the bug**
Hey, might be a special case but in my case I'm using the [async select search](https://livewire-wireui.com/docs/select#async-search) with **custom array parameters**.
I'm trying to filter the fields of the result with the following parameters.
`'params' => ['sort' => 'name', 'fields' => ['users' => 'id,name']],`

The sort parameter works as expected but the **fields** property **is not converting** into a correct url encoded **array**.
Instead it creates this query `?search=&sort=name&fields=%5Bobject+Object%5D` for the request.

Greetings
Lars

**To Reproduce**
```blade
<x-select ...  :async-data="[
    'api' => route('api.users.index'),
    'params' => ['sort' => 'name', 'fields' => ['users' => 'id,name']]
]" />
```

**Expected behavior**
I'm expecting an api request with this `?search=&sort=name&fields[users]=id,name` query string.

~~**Screenshots**
If applicable, add screenshots to help explain your problem.~~

**Desktop:**
 - any

**Smartphone:**
 - any

~~**Additional context**
Add any other context about the problem here.~~

**Comment by ph7jack** [comment]
@Alph44rchitect Thanks for reporting. It's now fixed. Update to the release https://github.com/wireui/wireui/releases/tag/v1.13.3
