### ISSUE TITLE
Found new bug with select input

### ISSUE THREAD

**Issue by Tiagospem** [PH7-Jack/livewire-ui#405]
```
    public $color_selected = 1;

    public $colors = [
        ['name' => 'blue', 'id' => 1],
        ['name' => 'red', 'id' => 2],
        ['name' => 'green', 'id' => 3],
    ];

    public function updateColors()
    {
        $this->colors = [
            ['name' => 'pink', 'id' => 4],
            ['name' => 'gray', 'id' => 5],
            ['name' => 'orange', 'id' => 6],
        ];
        $this->color_selected = 6;
    }
```

```
<div>
    <div class="mt-2">
        <x-w.select label="Colors" wire:model="color_selected" placeholder="Select a color" :options="$colors"
            option-label="name" option-value="id" />
    </div>
    <div class="mt-2">
        <x-w.button secondary label="updateColors" wire:click="updateColors" />
    </div>
</div>
```

At first load the component renders correctly, the blue color become selected as the model

<img width="489" alt="CleanShot 2022-07-28 at 16 20 56@2x" src="https://user-images.githubusercontent.com/8459781/181620486-b994d260-f061-4d76-8f95-adb1474abf50.png">

when click to update Colors the list options updates but the old selected option aren't cleared, it still selected. maybe a re-render bug.

<img width="531" alt="CleanShot 2022-07-28 at 16 27 12@2x" src="https://user-images.githubusercontent.com/8459781/181622161-08ab40a5-7507-4e02-809c-e78c6210787c.png">

https://user-images.githubusercontent.com/8459781/181622462-172e0ab9-8934-45f5-88d5-13aa826c3b2b.mp4

Other example using native select, it works as expect 

https://user-images.githubusercontent.com/8459781/181623494-6785b78c-9aab-4964-9198-185b18f938f5.mp4

**Comment by ph7jack** [comment]
@Tiagospem fixed, update to the latest release https://github.com/wireui/wireui/releases/tag/v1.13.2
