### ISSUE TITLE
Vite always reloading files on page with "x-select"

### ISSUE THREAD

**Issue by LaMance22** [PH7-Jack/livewire-ui#406]
Hello, i have problem.

When I add the "<x-select" option to my blade (in livewire), vite reloads all of them. Using "<x-native-select" everything works fine.

![ss1](https://user-images.githubusercontent.com/49619616/181649747-f418ceaa-430c-467c-bf1d-aa0a3b2580fb.jpg)

My composer.json.
```
    "require": {
        "php": "^8.0.2",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^9.19",
        "laravel/jetstream": "^2.10",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.7",
        "livewire/livewire": "^2.5",
        "power-components/livewire-powergrid": "^3.2",
        "psr/simple-cache": "1.0",
        "wireui/wireui": "^1.13"
    },
```

Thanks for working on this project - good job.

**Comment by ph7jack** [comment]
@LaMance22 
Could you share your vite config?

**Comment by LaMance22** [comment]
Sure,

`import { defineConfig } from 'vite';
import laravel, { refreshPaths } from 'laravel-vite-plugin';
export default defineConfig({
plugins: [
laravel({
input: [
'resources/css/app.css',
'resources/js/app.js',
],
refresh: [
...refreshPaths,
'app/Http/Livewire/**',
],
}),
],
});`

@Update
With "<x-datetime-picker" is the same problem.

**Comment by ph7jack** [comment]
@LaMance22 Your config likes normal for me. I don't know what is causing this bug. I can use the wireui with vite. Try updating the dependencies

**Comment by LaMance22** [comment]
I did not add the most important point. Everything works fine after executing "npm run build", but if it works on the "npm run dev" environment, vite will reload the page every time if it is "<x-datetime-picker", "<x-select". It does not require urgent repair, but I do report it.

**Comment by ph7jack** [comment]
Could you record a video showing this behavior?

**Comment by racerguy** [comment]
I am also having this problem. Seems to come up with x-selects in WireUI modals for me.

**Comment by racerguy** [comment]
> Could you record a video showing this behavior?
![Screenshot 2022-08-16 032236](https://user-images.githubusercontent.com/64607188/184849478-05e8f379-61b1-435f-b6df-37cd812f63d6.png)
![Screenshot 2022-08-16 032214](https://user-images.githubusercontent.com/64607188/184849491-0fd781f5-614f-4096-bf79-3aac643d2a08.png)

**Comment by ph7jack** [comment]
@racerguy Could you share your vite config? 
Could you record a video on [loom](https://www.loom.com/)?
I cant reproduce this behavior

**Comment by racerguy** [comment]
> @racerguy Could you share your vite config? Could you record a video on [loom](https://www.loom.com/)? I cant reproduce this behavior

I think I just figured it out. This isn't happening when I remove   @livewire('livewire-ui-modal') from wire-elements/modal

**Comment by racerguy** [comment]
I will try to get a video of it. It tends to cause a meltdown of vite and crashes chrome and node. 

`import { defineConfig } from 'vite';
import laravel, { refreshPaths } from 'laravel-vite-plugin';

export default defineConfig({
    server: {
        hmr: {
            host: 'localhost',
        },
    },
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
            ],
            refresh: [
                ...refreshPaths,
                'app/Http/Livewire/**',
            ],
        }),
    ],
});`

**Comment by racerguy** [comment]
I think it maybe looping because some function from wire-elements is also found in wireui

**Comment by racerguy** [comment]
It's an error with the laravel vite auto refresh, using https://github.com/def-studio/vite-livewire-plugin gives me no problems

**Comment by ph7jack** [comment]
@racerguy Nice finding. Interesting plugin

**Comment by ph7jack** [comment]
I believe it can be closed since it's not a wireui issue. If I'm wrong, just tag me to reopen the issue

**Comment by racerguy** [comment]
@PH7-Jack Still having problems with this. Plugin seemed to help and so did using incognito window for about a day. Something weird is going on. I have 4 selects, 1 date input, 3 text inputs loading on a modal.

I am on WSL using sail

**Comment by racerguy** [comment]
Is there any possibility that wireui is modifying files in a way that Vite is picking it up as a change?

**Comment by ph7jack** [comment]
@racerguy As I said before, record a video that shows your problem, I cant reproduce it.
I can also use wireui with vite with no problem, the wireui scripts don't need to use the vite build, they are a build.
Try to update your vite config https://github.com/laravel/jetstream/blob/2.x/stubs/livewire/vite.config.js
I believe the vite is listening for the laravel blade cache

**Comment by minhtamwebmaster** [comment]
> I did not add the most important point. Everything works fine after executing "npm run build", but if it works on the "npm run dev" environment, vite will reload the page every time if it is "<x-datetime-picker", "<x-select". It does not require urgent repair, but I do report it.

I also encountered a similar problem
