### ISSUE TITLE
Modal set focus on open

### ISSUE THREAD

**Issue by ph7jack** [PH7-Jack/livewire-ui#411]
### Discussed in https://github.com/wireui/wireui/discussions/388

<div type='discussions-op-text'>

<sup>Originally posted by **dominikgeimer** July 20, 2022</sup>
Hi,

I have a Modal with in input inside of it and I am opening the Modal with Livewire `wire:model.defer="openSearchModal"`.

Is there a way with the Modal Events

```
<x-modal
    ...
    x-on:open='...'
    x-on:close='...'>
 
</x-modal>
```

To set the focus to the input element?</div>

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
