### ISSUE TITLE
Erro flatpicker

### ISSUE THREAD

**Issue by galegobr01** [PH7-Jack/livewire-ui#412]
Adicionei 2 DateTime-Picker e um botão, esse botão chama o Powergrid com alguns parametros. Quando clico no botão ele dá um erro do flatpicker

![image](https://user-images.githubusercontent.com/5103771/181846552-c6806106-1952-46c8-b322-cb03d5b52f18.png)

 - OS: Windows / Php 8.1 / Laravel 9.18
 - Chrome/ Edge

Seria alguma configuração por usar dois DateTimer-Picker?

**Comment by joaopalopes24** [comment]
Try showing some code

**Comment by galegobr01** [comment]
Blade que chama o componente livewire com o campos para a busca

![image](https://user-images.githubusercontent.com/5103771/181909279-ee9ee3c9-5e2a-4ed3-bf94-66d67a3d54a6.png)

Aqui o formulário do componente livewire acima

![image](https://user-images.githubusercontent.com/5103771/181909331-16255e00-1669-416b-ae1e-3dfbf08d74e0.png)
![image](https://user-images.githubusercontent.com/5103771/181909340-4d7247ab-7963-408d-baf9-8e3edd09aac9.png)

Aqui como fica ele renderizado

Antes de clicar em Relatório
![image](https://user-images.githubusercontent.com/5103771/181909366-1e174cd4-864a-4b18-8be9-9e611de98815.png)

Validação funcionando 
![image](https://user-images.githubusercontent.com/5103771/181909403-2c102e96-e67d-4af4-b767-2bf879ecfa7c.png)

Ao clicar em relatório informando as datas ai ocorre o erro
![image](https://user-images.githubusercontent.com/5103771/181909453-2afdccaf-5444-4548-b40c-eefc242709d6.png)

**Comment by ph7jack** [comment]
@galegobr01 
Thanks for reporting. 

I believe this bug is referent to the PowerGrid table component, and not to wireui select, the wireui select doesn't use the flatpickr. 
Try to use a static `wire:key` instead of using a random id, maybe the livewire is broken when the conditional element is showing because the `wire:key` is randomly

Question: The table component works when you're not using the wireui components on the same page?

Tip: You're using a **blade/livewire** component in your blade page, so you can pass the attributes using `:user="$user"`, it will pass the `$user` variable without encoding it and giving it as a parameter. Use the `{{ $variable }}` only to render data, to give parameters to a **blade/livewire** component just prefix the parameter name with ":" (colon).

**Comment by galegobr01** [comment]
Opa Pedrão

Question: The table component works when you're not using the wireui components on the same page?
Sim funcionam sim.

Fiz a alteração proposta e realmente o erro do flatpicker sumiu.

![image](https://user-images.githubusercontent.com/5103771/182028101-2674de7e-523b-4e38-af8c-3e4b59a315e8.png)
Selecionando a Data Inicial

![image](https://user-images.githubusercontent.com/5103771/182028118-e7771695-1540-40c3-926b-7dc09bb0ed62.png)
Selecionando a Data Final

![image](https://user-images.githubusercontent.com/5103771/182028133-80b97e44-cc60-4b81-aad0-ffdcf724f008.png)
Selecionei a Data Final, mas o datetime-picker não fechou (Não sei se é esse realmente o comportamento dele).

![image](https://user-images.githubusercontent.com/5103771/182028155-12483de6-17ce-459f-a93f-923a3a2eb52b.png)
Cliquei em relatorio, ai fechou o datetime-picker e abriu normal o PowerGrid

Caso eu tente mudar a Data Inicial ou Final o datetime-picker aparece da seguinte forma ( o primeiro que eu clicar)
![image](https://user-images.githubusercontent.com/5103771/182028192-ab8b8623-f5c1-4ee9-ad52-f6b090cf0c99.png)

O segundo já abre normalmente
![image](https://user-images.githubusercontent.com/5103771/182028217-01d5a77e-1724-4068-b762-99c1ed40ca1f.png)

Mas se eu mudar a data (Mudei de 31 para 30) ocorre o mesmo
![image](https://user-images.githubusercontent.com/5103771/182028239-575cc1d2-3938-42da-a39e-9373aeb1078a.png)

Grato pela atenção e respostas.

**Comment by galegobr01** [comment]
Para desencargo da consciencia e tira teima rsrrsrsr, adicionei um wire:key nos dois datetime-picker e o problema aparentemente foi sanado, não apresentando o comportamento do comentário acima.

Novamente grato pela atenção

**Comment by galegobr01** [comment]
Para desencargo da consciencia e tira teima rsrrsrsr, adicionei um wire:key nos dois datetime-picker e o problema aparentemente foi sanado, não apresentando o comportamento do comentário acima logo na segunda mudança, mas após algumas tentativas o problema do datetime-picker ocorreu novamente.

![image](https://user-images.githubusercontent.com/5103771/182028670-a6345807-2f6c-4b39-8732-382e16314548.png)

ao clicar pra o proximo mes ou anterior aparece assim
![image](https://user-images.githubusercontent.com/5103771/182028764-ce778d36-58d7-4fb3-9d57-d2cbeea74c2b.png)

Ai se eu selecionar uma data nessa imagem acima monta o datetime-picker novamente

Novamente grato pela atenção

**Comment by ph7jack** [comment]
@galegobr01 Maybe if you wrap the power grid component into a div with `wire:key` it will work. 
I believe this problem will be solved with `wire:key`. If it still persists we can schedule a meet to look it

PS: the **datepicker** component doesn't uses the debounce in the `wire:model`, only the defer modifier is supported.

**Comment by joaopalopes24** [comment]
@galegobr01 Does the error persist?

**Comment by joaopalopes24** [comment]
Old issue, closing it now. Feel free to tag me to reopen.
