### ISSUE TITLE
Hello, amazing job here, it is possible to use the "selected" attribute in a Multi Select Input form component? 

### ISSUE THREAD

**Issue by jorgevespa** [PH7-Jack/livewire-ui#413]

**Comment by ph7jack** [comment]
@jorgevespa Thank you. 
Could you explain better your problem?

**Comment by jorgevespa** [comment]
Sure, thanks for your time, i need to show selected items when the blade is loaded for the first time, some predefined values selected.

Thanks.

**Comment by ph7jack** [comment]
I understand, if you're using it inside a livewire component, just add a `wire:model` and set the model value in the livewire component
If you're using it outside the livewire, pass the selected value into the **value** attribute
