### ISSUE TITLE
Async Select blink options

### ISSUE THREAD

**Issue by Krato** [PH7-Jack/livewire-ui#416]
**Describe the bug**
When click on a select with a right icon, if you click aoutside the name, the options blink (show and hide). Maybe adding width 100% to the absolute will fix it.

**To Reproduce**
1. Create a async select component with a right icon
2. Click on space between selected value and rignt icon
4. See optons being showing and disappearing.

**Expected behavior**
Should work as normal select

**Video**

https://user-images.githubusercontent.com/74367/182102648-6f61c09e-0841-4c2c-a14a-f9355aae4dfd.mov

**Desktop (please complete the following information):**
Error tested on chrome an safari

**Comment by ph7jack** [comment]
@Krato Could you test again and verify if it still happens?
I can't reproduce.
I don't have the red line and the ghost square

**Comment by Krato** [comment]
Is not happening now. Maybe some update. Thanks 😄
