### ISSUE TITLE
When I reset properties of component the JS broken

### ISSUE THREAD

**Issue by jubagg** [PH7-Jack/livewire-ui#417]
**Describe the bug**
I prevent in a form a reload of page, but when I save the form and reset to null the components, it's broken something on alpine JS. Also when I use an contitional if on a input, it's crash and not working. For example when I have a user from a x-select, we load a datepicker, well, the datepicker crash.

**To Reproduce**
1. Load somethigs inputs form like selects or datepickers
2. Add an anction, when I run the action reset the properties
3. The error is here

**Expected behavior**
I expected when I reset the entangle property of Livewire not crash the JS

Im working with Microsoft Edge on Linux Ubuntu
![Captura de pantalla de 2022-08-02 08-25-20](https://user-images.githubusercontent.com/50118474/182363570-be7b7b0b-a8e7-4d7b-94ee-c93cd3eadf2b.png)

**Comment by Tiagospem** [comment]
@jubagg Can you post print of your livewire component?

**Comment by jubagg** [comment]
yes of course, you want the blade file or a component logic? @Tiagospem

**Comment by ph7jack** [comment]
@jubagg I believe your problem will be solved if you add a `wire:key` in the conditional elements or elements inside a loop
https://laravel-livewire.com/docs/2.x/troubleshooting#dom-diffing-cures

All conditional elements should have a `wire:key` to prevent js errors from livewire

**Comment by Tiagospem** [comment]
@jubagg follow @PH7-Jack tip, it works for me

**Comment by jubagg** [comment]
@PH7-Jack @Tiagospem I will test this solution and after I will return here to told how work the solution

**Comment by ph7jack** [comment]
@jubagg Any news?

**Comment by ph7jack** [comment]
Closing this issue now, I believe it was fixed using the wire:key
