### ISSUE TITLE
Password Input

### ISSUE THREAD

**Issue by EthosLuke** [PH7-Jack/livewire-ui#422]
It would be nice to have a password input component (using existing input component with a boolean called "password" would make sense) which has a right-icon (eye & eye-off icons) for toggling type="text" and type="password" on the input to show/hide the password

**Comment by ettiennelouw** [comment]
Hi, There is a pull request for a password component [https://github.com/wireui/wireui/pull/395](https://github.com/wireui/wireui/pull/395), which should be available in the next couple of releases.

**Comment by aliqasemzadeh** [comment]
Also input we action button is very good idea.

**Comment by EthosLuke** [comment]
This has been added in v1.15.0
