### ISSUE TITLE
Related Async Selects Not Updating Child Select On Parent Change

### ISSUE THREAD

**Issue by racerguy** [PH7-Jack/livewire-ui#424]
**Describe the bug**
Related Async selects not updating child select on parent change

**To Reproduce**
Create two async selects as parent and child

Child has a parent_id

Selecting Parent then selecting child shows that the API request was made and has the children in the select belonging to the parent

Changing Parent then clicking the child select shows previous parent_id children options and does not fire another API request.

I am sending the parent_id under params.  Is there any way to force a API call on updating the parent_id.

**Expected behavior**
Changing Parent should modify child select values if parent_id changes

**Comment by racerguy** [comment]
Update when searching it will update.

Believe the problem lies here

 `this.$watch('popover', (state: boolean) => {
      if (state) {
        if (this.asyncData.api && this.options.length === 0) {
          this.fetchOptions()
        }
        this.$nextTick(() => {
          setTimeout(() => this.$refs.search?.focus(), 100)
        })
      }
      this.$refs.input.dispatchEvent(new Event(state ? 'open' : 'close'))
    })
`


Is there a way to add a boolean that can turn the  "this.options.length === 0" part off

**Comment by ph7jack** [comment]
@racerguy It is now supported. See the **always-fetch** option at the doc 
You can pass this option to always fetch the options
https://livewire-wireui.com/docs/select#select-options

**Comment by racerguy** [comment]
@PH7-Jack Thank you for the quick addition of this. Really appreciating the project, it makes development 10x easier!
