### ISSUE TITLE
icon variant not found!

### ISSUE THREAD

**Issue by shinya-dono** [PH7-Jack/livewire-ui#427]
hi and thanks for your wonderful package. 

the following code produces this error:
![image](https://user-images.githubusercontent.com/44931353/183587288-9193f546-9236-440d-9d5b-aebe8a3945b6.png)
![image](https://user-images.githubusercontent.com/44931353/183587453-d0408366-bae4-4fd7-9aee-bbbcbad73392.png)

code: 
![image](https://user-images.githubusercontent.com/44931353/183587667-2b4e3e8d-f664-4132-894a-a8aea0d82d18.png)

i tried to execute the code directly inside the console, still the same error:

![image](https://user-images.githubusercontent.com/44931353/183587863-e7be620e-d33c-4960-9d8f-40d3dea7a2f6.png)

i did try to change icon variant to sth like 'bold' (which seems to work) but it seems like the config file has no effect whats so ever.
![image](https://user-images.githubusercontent.com/44931353/183588146-879b534a-9428-4bde-8f33-ba508b7ac2a6.png)
(i did run ```php artisan clear && php artisan view:clear && php artisan config:clear && php artisan cache:clear```, still no change.)

i even override default icon resolver like:
![image](https://user-images.githubusercontent.com/44931353/183588456-87beb0e8-6def-4433-8f77-17acea31ec7f.png)
![image](https://user-images.githubusercontent.com/44931353/183588494-b8fe0681-6da6-4583-9543-4fae20fc133a.png)
but the dd never got fired...
changing dialog icon field also doesn't fix it, theme changes, icon url changes but the error still exists.

i tried to publish phosphoicons views and add ```outline``` folder with all the views (copy paste), still no luck.
![image](https://user-images.githubusercontent.com/44931353/183589087-812ca96c-9a49-45c9-b75c-e5fcbccf26ef.png)

**Comment by ph7jack** [comment]
@shinya-dono I don't know what things you've changed, but the icons route is not the correct route. Your icon route is `icons/check/outline`, the wireui icons route is `icons/outline/check`
Are you using the latest wireui release or the v2 in progress branch?

**Comment by ph7jack** [comment]
@shinya-dono I'm closing this issue, I don't know how you did it, but it's not the wireui behavior. 
If I'm wrong, let me know to reopen the issue
