### ISSUE TITLE
Notifications are not working

### ISSUE THREAD

**Issue by tariktokic** [PH7-Jack/livewire-ui#429]
**Describe the bug**
I try to use the notification component. I added the `<x-notifications />` into my layout on the first line after the body open tag. In my LiveWire Component I added the `Actions` trait and then called the example code into a form submit method (which is also sending an email, which I get so the method is called):

```
$this->notification()->success(
    $title = 'Profile saved',
    $description = 'Your profile was successfull saved'
);
```
But when I call the notification over the browser console with:

```
window.$wireui.notify({
    title: 'Profile saved!',
    description: 'Your profile was successfull saved',
    icon: 'success'
})
```
then I can see the notification and everything ist working fine.

My current wireui package version is 1.13.3

Thank you!

**Comment by ph7jack** [comment]
@tariktokic 
You can see the notification if calling it from the console via JS?

**Comment by tariktokic** [comment]
Yes @PH7-Jack , as I wrote in my initial comment, it works in the JS console. That it is, what is so strange. 
I am using also Laravel Jetstream, if this helps to narrow down the issue. 

Greetings!

**Comment by ph7jack** [comment]
@tariktokic 
What versions of livewire and alpine are you using?
Could you check if the event is present in the livewire request?
![image](https://user-images.githubusercontent.com/38913462/184873491-ff86c0c1-bb90-4ede-9346-86d9dd8bc2ae.png)

**Comment by tariktokic** [comment]
Hi @PH7-Jack !

livewire is on version 2.10.7
and alpine.js is on 3.10.3, being loaded via `resources/js/app.js` with

```
import Alpine from 'alpinejs';
window.Alpine = Alpine;
Alpine.start();
```

I have been trying to find the event in the livewire request, but there is no sign of it. 
Perhaps I am not looking in the right place. Can you give me one more hint beside the screenshot?

**Comment by tariktokic** [comment]
After updating to wire version 1.14.1 it is working now.
Thank you for this package and your help!
