### ISSUE TITLE
Tab on a selected component displays 2 values

### ISSUE THREAD

**Issue by labomatik** [PH7-Jack/livewire-ui#432]
**Describe the bug**
When hitting tab on a select component 2 values are displayed

**To Reproduce**
Create a select component like this:
`<x-select
                                label="Statut"
                                placeholder="Sélectionnez un statut"
                                wire:model.defer="status"
                            >
                                <x-select.option label="Disponible" value="disponible"/>
                                <x-select.option label="Caché" value="cache"/>
                            </x-select>
`
hit tab to select the content of the select

**Expected behavior**
Only one value should be displayed

**Screenshots**
Here is the result
<img width="380" alt="Capture d’écran 2022-08-11 à 11 36 40" src="https://user-images.githubusercontent.com/179987/184106306-fcd48f64-cffb-46e8-bf94-1c68f99896a9.png">

**Desktop (please complete the following information):**
 - OS: MacosX 12.4
 - Browser Chrome

**Additional context**
Last version of wireui  v1.14.0

**Comment by ph7jack** [comment]
@labomatik Fixed. Thanks for reporting

**Comment by notscottsmith** [comment]
Hi, I'm seeing this problem in my current project. Running v1.15

![image](https://user-images.githubusercontent.com/51853082/188391396-522e69f0-10af-4e83-bccf-d06164c64e30.png)

Desktop (please complete the following information):

    OS: Windows 11
    Browser Firefox

<x-select
                label="State"
                placeholder="Choose a state"
                wire:model="state"
            >
                @foreach ($states as $index => $name)
                    <x-select.option value="{{ $index }}" label="{{ $name }}" />
                @endforeach
</x-select>

**Comment by ph7jack** [comment]
@notscottsmith Is your CSS configured and with a correct build using the wireui content paths? I believe your CSS is wrong
