### ISSUE TITLE
Add the X-Requested-With header

### ISSUE THREAD

**Issue by pablomadariaga** [PH7-Jack/livewire-ui#433]
Hello, it is a very specific situation, but at the moment I am needing a custom header for the asynchronous search in the select component or they should simply add the X-Requested-With header with the XMLHttpRequest value in the ajax requests, this does not affect the operation current, but if you allow laravel to identify that the request is ajax with $request->ajax().

![image](https://user-images.githubusercontent.com/69119357/184392153-6fc4d773-8218-438a-96b9-6910514fa50a.png)

**Comment by ph7jack** [comment]
@pablomadariaga What is the error you receive when sending the request without the **X-Requested-With**?

**Comment by pablomadariaga** [comment]
I have a middleware that validates ajax requests.

![image](https://user-images.githubusercontent.com/69119357/184427383-0141e918-7a0f-4322-bdd7-a5aeaf85ffb3.png)

Laravel has the function $request->ajax() "Determine if the request is the result of an AJAX call.", but what this function does is check if the X-Requested-With header exists with the XMLHttpRequest value.

![image](https://user-images.githubusercontent.com/69119357/184427883-ce92ef3e-17b9-49bb-970c-6cadd69f28e8.png)

I simply need to add the header in the js that is in charge of doing the effect to our route in the async-data parameter of our wire ui select component.

As I said before, the addition of this header does not affect the current operation, it only improves the understanding of the request for Laravel for validation purposes.

**Comment by ph7jack** [comment]
@pablomadariaga Added. Update to the latest release

**Comment by pablomadariaga** [comment]
Thanks a lot @PH7-Jack
