### ISSUE TITLE
Version 1.14.1 breaks the select => multiselect component

### ISSUE THREAD

**Issue by tariktokic** [PH7-Jack/livewire-ui#435]
After updating from v1.13.3 to 1.14.1 the multiselect component is broken and produces the error message

`Undefined variable $optionsToJson`.

Event the example from the wireui docs

**Multiselect**
```
<x-select
    label="Select Statuses"
    placeholder="Select many statuses"
    multiselect
    :options="['Active', 'Pending', 'Stuck', 'Done']"
    wire:model.defer="model"
/>

```
produces the same error. 

Here is the screenshot with more information:

<img width="901" alt="Bildschirmfoto 2022-08-16 um 15 15 30" src="https://user-images.githubusercontent.com/22153538/184888788-52e76de7-7788-4dd8-b9ae-3e7a7ed7b320.png">

**Comment by ph7jack** [comment]
You need to clear the view cache.
Run: `php artisan view:clear`

**Comment by tariktokic** [comment]
I just did, but I still get the same ErrorException `Undefined variable $optionsToJson` but now it is pointing to another line in the code (see screenshot). Even `php artisan cache:clear` did not help.

<img width="818" alt="Bildschirmfoto 2022-08-16 um 16 18 10" src="https://user-images.githubusercontent.com/22153538/184903162-fb7db08b-2cd5-4309-868b-85e6e987ce42.png">

**Comment by tariktokic** [comment]
It seems like the problem was that I had published the files via

`php artisan vendor:publish --tag='wireui.resources'`

so my version under `[resources/views/vendor/wireui]` was with errors and the recently updated version under
`[vendor/wireui/wireui/resources/views]` was OK.

Publishing the files again did fix the error.

**Comment by ph7jack** [comment]
@tariktokic If you never will modify the published files, you don't need to publish them.
