### ISSUE TITLE
Update async-data parameters

### ISSUE THREAD

**Issue by pablomadariaga** [PH7-Jack/livewire-ui#436]
I have 2 select, but the loading of one depends on the option that is selected in the other

![image](https://user-images.githubusercontent.com/69119357/184995882-319c5a2e-222a-4a61-9258-f4d9c4e46a67.png)

This is the select that depends on the country selection

`<x-select label="{{ __('Bank') }}" wire:model="bank" :always-fetch="true" id="bank" name="bank" :async-data="route('banks', ['country' => $country])" option-label="name" option-value="id" />`

But I can't find a solution to update the async-data parameter.

Is there any solution for this?

**Comment by racerguy** [comment]
I would define your route in async-data by itself and use the params feature like this


<x-select  

    label="{{ __('Bank') }}"
    always-fetch="true"
    id="bank" 
    name="bank"
    option-label="name"
    option-value="id"
    :async-data="[
        'api' => route('banks'),
        'method' => 'GET', 
        'params' => ['country' => '$country'] 
    ]"
/>

This with always-fetch="true" works for me

**Comment by ph7jack** [comment]
@pablomadariaga Thanks for reporting. Now the URL search parameters and the params will be merged as well
