### ISSUE TITLE
Date Picker (disable dates)

### ISSUE THREAD

**Issue by binaryruel** [PH7-Jack/livewire-ui#440]
Would love to have a date picker where you can feed an array of dates as options.

Just like in here: https://github.com/Pikaday/Pikaday/issues/34#issuecomment-241179425

**Comment by silviokennecke** [comment]
We just wanted this feature, too. I’ll create a PR until tomorrow….

**Comment by silviokennecke** [comment]
Feature PR: https://github.com/wireui/wireui/pull/537

Docs: https://github.com/wireui/docs/pull/39

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

This feature was added in stable version 2. Check our documentation at: https://wireui.dev.
