### ISSUE TITLE
No checklist mark when edit existing data in multi select

### ISSUE THREAD

**Issue by jonathanoeijoeng** [PH7-Jack/livewire-ui#442]
**Describe the bug**
When create new data, there are check mark show when we choose item in drop down list.
Everything run well.
But when we want to edit that data, we can see the selected data in input field but when we cannot see check mark in selected data in drop down

**To Reproduce**
Here we can see selected data:
<img width="649" alt="Screen Shot 2022-08-20 at 15 21 28" src="https://user-images.githubusercontent.com/7046560/185736132-03b7bb67-308a-4316-888c-6685591e8b73.png">

but here there are no check mark for selected data 
<img width="687" alt="Screen Shot 2022-08-20 at 15 23 09" src="https://user-images.githubusercontent.com/7046560/185736179-2b107881-9ce3-4c76-90db-f92edf610d4e.png">

**Expected behavior**
I expect to see check mark in selected data just like when we create new data

**Screenshots or Videos**
<img width="591" alt="Screen Shot 2022-08-20 at 15 25 47" src="https://user-images.githubusercontent.com/7046560/185736245-1034470a-2200-42fb-ac89-076279e09d40.png">

**Desktop (If applicable, please complete the following information):**
 - WireUI Version: 1.X
 - Laravel Version: 9.25.1
 - Alpine.js Version: 3.X
 - Livewire Version: 2.X

**Comment by ph7jack** [comment]
@jonathanoeijoeng I'm not sure how to reproduce this error.

**Comment by joaopalopes24** [comment]
@jonathanoeijoeng I've seen this error, but it was a lack of configuration in the tailwind.config.js file. Check documentation [Installation](https://livewire-wireui.com/docs/get-started#installation) item 3.

**Comment by joaopalopes24** [comment]
@jonathanoeijoeng Please send us your tailwind.config.js file.

**Comment by joaopalopes24** [comment]
@jonathanoeijoeng I've seen this error when I didn't configure tailwind.config correctly.

But I will close this issue for being old, and for lack of response. In the most, I appreciate the use of the package, and feel free to tag me again in another doubt.

Thanks.
