### ISSUE TITLE
Localization nl_NL

### ISSUE THREAD

**Issue by petermaas** [PH7-Jack/livewire-ui#443]
**Describe the bug**
Due to the name of the language folder (nl_NL) the localisation is different from the app.php  'locale' => 'nl' and the Dutch translations are not visible.

**To Reproduce**
If 'locale' => 'nl' it doesn't work, but if I set  'locale' => 'nl_NL' is works fine but then other packages have an issue as they are set to 'nl'.

**Workaround
php artisan vendor:publish --tag='wireui.lang'

rename folder nl_NL => nl

**Desktop (If applicable, please complete the following information):**
 - Browser: chrome
 - WireUI Version: 1.14.1
 - Laravel Version: 9.25.1
 - Alpine.js Version: 3.10.3
 - Livewire Version: 2.10.7

**Comment by joaopalopes24** [comment]
@petermaas This is not a bug. Feel free to publish the translation files and change the folder name. Thank you in advance for your attention, and thank you for using the package.
