### ISSUE TITLE
A mask for date

### ISSUE THREAD

**Issue by aliqasemzadeh** [PH7-Jack/livewire-ui#445]
Hi
I need a mask for date for example "1368/06/02"  or 1369/10/25" or "1368/5/5"
Can you help me to make this mask?
Users can not enter other types.

**Comment by ph7jack** [comment]
@alighasemzadeh 
If you are using the datetime picker, you can use the date format
https://livewire-wireui.com/docs/datetime-picker#custom-format

but if you mean to have a date mask for the maskable input, it's not implemented at now, but you can use the mask `####/##/##` as well, and validates it in the backend

**Comment by jonathanoeijoeng** [comment]
> @alighasemzadeh 
> 
> If you are using the datetime picker, you can use the date format
> 
> https://livewire-wireui.com/docs/datetime-picker#custom-format
> 
> 
> 
> but if you mean to have a date mask for the maskable input, it's not implemented at now, but you can use the mask `####/##/##` as well, and validates it in the backend
> 
>  

Hi,

Can we use date only?

Thanks

**Comment by gbrits** [comment]
Hi @PH7-Jack - is it possible to make it so that you can type into the field too? 
I have a client that requires this (tabbing into the field & typing, not just selecting via UI) and while I love the WireUI datetime picker I may be forced to use an alternative if I can't get that request working :(

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
