### ISSUE TITLE
Add "checked" in checkbox and toogle

### ISSUE THREAD

**Issue by jonathanoeijoeng** [PH7-Jack/livewire-ui#448]
Is it possible to add "checked" in toggle or checkbox? Usually I use it in table and add script like @checked($user->is_active == 1) in laravel.

Thanks

**Comment by ph7jack** [comment]
@jonathanoeijoeng You can pass the attribute checked as you pass to a checkbox component
`:checked="$user->is_active == 1"`

The **@checked** directive cannot be used inside the blade component, the laravel doesn't support it
