### ISSUE TITLE
Heroicons v2

### ISSUE THREAD

**Issue by cloudstudio** [PH7-Jack/livewire-ui#449]
Hello! heroicons v2 is released https://heroicons.com/

Any option to have it in wireui by default ? this could be awesome!

**Comment by ph7jack** [comment]
I'm creating the update to heroicons v2 as a third-party package at https://github.com/wireui/heroicons

Just install the package and use it. When it's released I'll let you know

**Comment by ph7jack** [comment]
The heroicons v2 was released, but only the wireui v2 will use them.

If you want to have the heroicons, you can install the [package](https://github.com/wireui/heroicons)
Then, add a custom name to the heroicons alias, or rename the wireui icon component
Does that make sense?

**Comment by SebastianSchoeps** [comment]
@PH7-Jack May you please explain your last post a little bit more in detail? I don't get it to work.
Thanks!

**Comment by joshluongo** [comment]
> @PH7-Jack May you please explain your last post a little bit more in detail? I don't get it to work. Thanks!

You need to first publish the wireui configuration (`php artisan vendor:publish --tag='wireui.config'`), then you can edit alias used for the old icons.

Example:

```php
    'components' => [
        'icon' => [
            'class' => Components\Icon::class,
            'alias' => 'old-icon',
        ],
    ]
```

Then clear the view cache (`php artisan view:clear`), now `<x-icon` will use v2 icons from the [heroicons package](https://github.com/wireui/heroicons) and `<x-old-icon` will use v1 icons.

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

This feature was added in stable version 2. Check our documentation at: https://wireui.dev.
