### ISSUE TITLE
Make it possible to pre-populate non-standard inputs

### ISSUE THREAD

**Issue by lvltoni** [PH7-Jack/livewire-ui#457]
**Is your feature request related to a problem? Please describe.**
I use inputs in both create and edit forms for models. Many of the components provided do not seem to support pre-populating with values when the form is being used to edit a model. 

**Describe the solution you'd like**
For example, with multiselect, it would be great if passing 'value=["1", "2"]' to the input would render the component with the matching options selected and displayed to the user, or if adding the "selected" property to the options would do the same. 

Similarly with maskable inputs - it would be great if you could provide a value and have this formatted and displayed to the user. Instead, any value I try and provide is removed. 

Toggles and radios can be checked, if but if you want the checked property to be added to them conditionally with an "if" statement, it seems to break the component. 

I have not tested other inputs, but I assume this is the same for any component that isn't native/standard.

**Describe alternatives you've considered**
As it is, I've decided against using maskable inputs because they don't support this. I'm using custom JavaScript on page load to deal with multiselects.

**Comment by EthosLuke** [comment]
Unless I'm misunderstanding the request, I think you may need to consult Livewire Docs (https://laravel-livewire.com/docs/2.x/properties) as what you are asking is absolutely possible with the components as they are.

On the mount function of your edit form you should be setting the values of your models which will then inherently pre-populate the components you're using, so long as the values you're setting in your models matches the values you're passing to the select options. It's also important to set your multi-select variables as an array e.g. $multiselect = [];

If you're using the slot option for your multi-selects make sure to use :value if your value isn't a string, without the : then the value will always be passed as a string so may not match the value from your database.

Likewise for your checkboxes you should use the mount function to conditionally set them to true or false.

**Comment by ph7jack** [comment]
@lvltoni As the @EthosLuke said, all components are ready to get the default value pre-populated, it's based on the wire:model or the value attribute. Read the livewire documentation to understand how to use it.
I'm closing it now.
