### ISSUE TITLE
Custom Dialog not openable from Component Class

### ISSUE THREAD

**Issue by trippo** [PH7-Jack/livewire-ui#464]
**Describe the bug**
If you try to open a Custom Dialog through id on the Component controller open always the default dialog
<img width="496" alt="image" src="https://user-images.githubusercontent.com/497169/188266372-3fe0fa6f-81fc-443e-b103-8abe6a156238.png">

**To Reproduce**
1. Put in the blade file a custom dialog like:
```html
<x-dialog id="custom" title="User information" description="Complete your profile, give your name">
    <x-input label="What's your name?" placeholder="your name bro" x-model="name" />
</x-dialog>
```
2. try to call it from controller
```php
$this->dialog([
                'id' => 'custom',
                'style' => "center",
]);
```

**Expected behavior**
Open the custom dialog described on blade

**Dependencies**
 - WireUI Version: 1.15
 - Laravel Version: 9.25
 - Alpine.js Version: 3.X.X
 - Livewire Version: 2.X.X
 - Lang: en_US

**Comment by gbrits** [comment]
Also trying to figure this out - because there's no documentation on how to use a custom modal aside from the demo on the Documentation site.

**Comment by undjike** [comment]
Same issue.

**Comment by joaopalopes24** [comment]
@trippo @gbrits @undjike Good Morning. First of all, I apologize for the delay in responding. When calling the dialog via Livewire using id do this here:

```
$this->dialog()->id('custom')->show([
    'style' => "center",
]);
```

Thank you in advance, thank you.
