### ISSUE TITLE
Select events mentionned in the documentation don't trigger

### ISSUE THREAD

**Issue by t1m0t** [PH7-Jack/livewire-ui#467]
**Describe the bug**
Select events mentionned in the [documentation ](https://livewire-wireui.com/docs/select#select-events) don't trigger

**To Reproduce**
1. Create a select component
2. Add `wire:change="alert('selected/unselected option')"`
3. Select an item

**Expected behavior**
Alert window should show up.

**Dependencies**
 - WireUI Version: 1.15.1
 - Laravel Version: 9.27.0
 - Alpine.js Version: 3.10.3
 - Livewire Version: 2.10.7
 - Lang: fr_FR

**Desktop (If applicable, please complete the following information):**
 - OS: Windows
 - Browser: firefox
 - Version 104.0.1

**Comment by t1m0t** [comment]
I've opened a PR in docs for this.

**Comment by ph7jack** [comment]
@t1m0t Thanks bro
