### ISSUE TITLE
Currency Input Bug

### ISSUE THREAD

**Issue by Tiagospem** [PH7-Jack/livewire-ui#470]
Hi @PH7-Jack

The currency input field has a strange behavior, I've tried to format the values ​​to two decimal places but the problem persists

<x-w.inputs.currency readonly thousands="." precision="2" decimal="," />

https://user-images.githubusercontent.com/8459781/188775639-4ab6b682-80b3-4cad-8c5e-dbc681a37d5f.mp4

https://user-images.githubusercontent.com/8459781/188775661-12fb8d83-7170-4476-acab-8811e7d958d0.mp4

**Comment by ph7jack** [comment]
@Tiagospem Thanks for reporting, I'm looking for it to fix ASAP.

**Comment by ph7jack** [comment]
@Tiagospem Sorry for the long time to fix it. I hope it's now fixed, update to the latest release. 
If the error persists, let me know
