### ISSUE TITLE
Publishing not working

### ISSUE THREAD

**Issue by edux04** [PH7-Jack/livewire-ui#478]
I am trying for the first time this library which looks like a wonderful tool but by following the tutorial getting to the publishing part I run into this, all the following commands returns "No publishable resources for tag..." 

php artisan vendor:publish --tag='wireui.config'
php artisan vendor:publish --tag='wireui.resources'
php artisan vendor:publish --tag='wireui.lang'

**Comment by joaopalopes24** [comment]
Good afternoon @edux04, how are you?

I just ran the test here locally and it's working normally. Can you send us a print?

**Comment by edux04** [comment]
Hello, I'm good, hope you too. Thanks for your response, here the message I got.
<img width="422" alt="image" src="https://user-images.githubusercontent.com/73184362/191178820-ff221754-4c2e-4734-b670-cca8d60b4c64.png">

**Comment by edux04** [comment]
Hello, Now I try changing the single quotation mark for double and it works.
<img width="554" alt="image" src="https://user-images.githubusercontent.com/73184362/191179541-bea47629-50d1-4074-b8d7-ca85570b4396.png">

**Comment by joaopalopes24** [comment]
Thanks for the answer @edux04. It should probably be your terminal's compatibility. Otherwise, have fun with WireUI.

**Comment by arthurshlain** [comment]
In Laravel docs the `tag` value has no single qoutes (from v5.0):
https://laravel.com/docs/master/packages#public-assets

`php artisan vendor:publish --tag=wireui.config` OK
`php artisan vendor:publish --tag="wireui.config"` OK
`php artisan vendor:publish --tag='wireui.config'` No publishable resources for tag ['wireui.config'].  

I think the quotes can be removed from WireUI docs.
