### ISSUE TITLE
Problema com fechamento de Modal 

### ISSUE THREAD

**Issue by smilox** [PH7-Jack/livewire-ui#482]
no [v9.31.0](https://github.com/laravel/framework/releases/tag/v9.31.0)

**Describe the bug**
Ao fechar o modal ele retorna e não abre mais

**To Reproduce**
1. click no botão Open
2. Clicar no x ou clicar fora do modal
cdn.min.js:5 Uncaught (in promise) {isFromCancelledTransition: true}
window.Element._x_toggleAndCascadeWithTransitions @ cdn.min.js:5
cdn.min.js:5 Uncaught (in promise) {isFromCancelledTransition: true}
window.Element._x_toggleAndCascadeWithTransitions @ cdn.min.js:5
cdn.min.js:5 Uncaught (in promise) TypeError: u is not a function
cdn.min.js:5 Uncaught (in promise) TypeError: u is not a function
    at cdn.min.js:5:8935

**Dependencies**
 - WireUI Version: 1.X.X
 - Laravel Version: 9.31.0
 - Alpine.js Version: 3.0.6
 - Livewire Version: 2.X.X
 - Lang: pt_BR
 - 
"devDependencies": {
        "@tailwindcss/aspect-ratio": "^0.4.2",
        "@tailwindcss/forms": "^0.5.2",
        "@tailwindcss/typography": "^0.5.0",
        "alpinejs": "^3.0.6",
        "autoprefixer": "^10.4.7",
        "axios": "^0.27",
        "laravel-vite-plugin": "^0.6.0",
        "lodash": "^4.17.19",
        "postcss": "^8.4.14",
        "tailwindcss": "^3.1.0",
        "vite": "^3.0.0"
    }
**Additional context**

**Comment by joaopalopes24** [comment]
@smilox Please send us the code. I performed the local test, and it is working normally.

**Comment by joaopalopes24** [comment]
@smilox I just ran the test with this code here and it's working normally.

The Livewire Component:

```
use Livewire\Component;

class Test extends Component
{
    public bool $test = false;

    public function render()
    {
        return view('livewire.documentation.test');
    }
}
```

The Blade Component:

```
<div>
    <x-button onclick="$openModal('test')" :label="trans('Open')" primary />

    <x-modal blur wire:model.defer="test">
        <x-card title="Consent Terms">
            <p>
                Test
            </p>

            <x-slot name="footer">
                <div class="flex justify-end gap-x-4">
                    <x-button x-on:click="close" flat :label="trans('Cancel')" />
                    <x-button x-on:click="close" primary :label="trans('Save')" />
                </div>
            </x-slot>
        </x-card>
    </x-modal>
</div>
```

**Comment by joaopalopes24** [comment]
Therefore, I will close the issue because the modal is working normally.

**Comment by chris-lee-lb** [comment]
@joaopalopes24 I've also faced this problem (with your demo code), but with `Livewire PowerGrid`. Does your test case covered ?

Here is my version

`livewire/livewire` v2.10.7
`power-components/livewire-powergrid` v3.5.12
`wireui/wireui`  v1.17.7

**Comment by chris-lee-lb** [comment]
my `resources/views/layouts/app.blade.php`

```php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ config('app.name', 'Laravel') }}</title>
    @vite('resources/css/app.css')
    @livewireStyles
    @powerGridStyles
    @wireUiScripts
    <script defer src="//unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <script defer src="//unpkg.com/@alpinejs/focus@3.x.x/dist/cdn.min.js"></script>
</head>
<body class="antialiased flex justify-center items-center">
    {{ $slot }}
    @livewireScripts
    @powerGridScripts
    @livewire('livewire-ui-modal')
</body>
</html>
```

**Comment by joaopalopes24** [comment]
@chris-lee-lb This problema is with the Livewire Powergrid package. Remove the @powerGridScript and test now. Check This Issue in Livewire Powergrid github.
