### ISSUE TITLE
Select event not working

### ISSUE THREAD

**Issue by edux04** [PH7-Jack/livewire-ui#488]
**Describe the bug**
I'm using the select component and the select event is not working

![image](https://user-images.githubusercontent.com/73184362/193316996-06cdc4b2-8ebe-493c-8807-83b8b0784145.png)

**Expected behavior**
Select an option and alert a message

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Dependencies**
 - WireUI Version: 1.15
 - Laravel Version: 9.19
 - Alpine.js Version: 3.4.2
 - Livewire Version: 2.10
 - Lang: en_US

**Additional context**
same in edge and chrome

**Comment by t1m0t** [comment]
Please check [this](https://github.com/wireui/docs/pull/31)

**Comment by joaopalopes24** [comment]
Please check the documentation: [Select](https://livewire-wireui.com/docs/select#select-events)
