### ISSUE TITLE
Remove MD5 from ID

### ISSUE THREAD

**Issue by ph7jack** [PH7-Jack/livewire-ui#490]
Remove this MD5 to make the `id = name = wire:model`

![image](https://user-images.githubusercontent.com/38913462/193428538-896371db-38d5-497e-af15-e9dad7ae043e.png)

**Comment by neindk** [comment]
Currently, just playing with wireui. And This is what I was looking for. By removing md5, and we can mark up label and input element like below and lots of markup/design flexibility will arise.

```
<div>
    <div><label for="input1">Label</label></div>
    <div><x-input id="input1"/></div>
</div>
```

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

This feature was added in stable version 2. Check our documentation at: https://wireui.dev.
