### ISSUE TITLE
Mispelled function"getSelectedDysplayText()"

### ISSUE THREAD

**Issue by racerguy** [PH7-Jack/livewire-ui#497]
Alpine Expression Error: getSelectedDysplayText is not defined

Expression: "getSelectedDysplayText()"

**Comment by trapzpro** [comment]
This also popped up for me today - from what I can tell, likely related to #492  a few days ago? (I probably pulled in 1.16.1 last night)  Based on the PR , guessing maybe still another instance of the bad spelling elsewhere, and now not matching the fixed spelling?   Rolling back to 1.16.0 seems to have resolved for me in the meantime! :)

**Comment by ph7jack** [comment]
@racerguy @trapzpro 
This function name was written wrong, just publish the assets again to get it working

(if you don't modify the published views, you don't need to have it published)
