### ISSUE TITLE
Unable to go to next time input element using tab

### ISSUE THREAD

**Issue by labomatik** [PH7-Jack/livewire-ui#498]
Using tab on a time picker element doesn't go to other input (or link element)
seems to be related to that line:
https://github.com/wireui/wireui/blob/3f22e155c197b9676fa8207c28fb9380855a7af9/resources/views/components/time-picker.blade.php#L12

Not sure why it was added.

**Comment by labomatik** [comment]
It doesn't seems to fix the issue, i've tested on the demo page: https://livewire-wireui.com/docs/time-picker just focus the time field and hit tab 

if you do the same on the date field https://livewire-wireui.com/docs/datetime-picker you focus (and close the opened box) you can hit tab and go on another element.

**Comment by ph7jack** [comment]
@labomatik No, it's fixed. Just the documentation was using an outdated wireui version. Now I've updated the documentation wireui version.

**Comment by ph7jack** [comment]
Thanks for finding this issue
