### ISSUE TITLE
Select component overwrites selected value

### ISSUE THREAD

**Issue by judaemon** [PH7-Jack/livewire-ui#500]
I have this select component.
![image](https://user-images.githubusercontent.com/48901408/195378264-d1f0f890-a6a2-4c70-8832-a187c0c08864.png)

My problem is that the teacher has a value of 5
after the component renders (calls the API) it overwrites the value to the first option in this case 3

the components is on wire-elements/modal

this is my API.
![image](https://user-images.githubusercontent.com/48901408/195379058-55bcdcdc-a9fa-4587-82a9-a4b2dc370f48.png)

As you can see here, after opening the modal, it immediately calls the API and then overwrites the selected value, which was 5.
https://user-images.githubusercontent.com/48901408/195382594-9eeab3db-f7e7-45f2-911c-a7f8fbf0d3c8.mp4

**Comment by ph7jack** [comment]
@Judaemon Hello. Thanks for creating this issue.
The problem isn't the wire:elements modal or the wireui, your API not is configured properly
You can see more details [here](https://livewire-wireui.com/docs/select#async-search)
And you can see the real users API code on the wireui documentation [repository](https://github.com/wireui/docs/blob/main/app/Http/Controllers/Api/Users/Index.php)

In your API is missing the selected condition to be used on fetching data from model
