### ISSUE TITLE
add focus on input and selects

### ISSUE THREAD

**Issue by donatiss** [PH7-Jack/livewire-ui#501]
i'm recomending to add focus class on input and selects components like buttons have them.

`class="... focus:ring-2 focus:ring-offset-2 ring-slate-200 focus:border-0"`

**Comment by ph7jack** [comment]
@donatiss Could you add some examples? The input/select has a focus ring

**Comment by donatiss** [comment]
![image](https://user-images.githubusercontent.com/6832828/196376552-2f0f5826-03b1-49d1-b105-e06a329f7f76.png)

there is no classes `focus:ring-2 focus:ring-offset-2` 
then i'm recomend to remove primary border on focus and add `ring-slate-200` class

wire ui input now looks like:
![image](https://user-images.githubusercontent.com/6832828/196377212-24bbaedf-3689-41f1-98d0-55b693f3d18e.png)

my input with rewrited classes:
![image](https://user-images.githubusercontent.com/6832828/196377492-663ba5c9-9d18-4bc7-8eb7-9c76adfbf3b6.png)
![image](https://user-images.githubusercontent.com/6832828/196377587-80effaeb-dfc4-4d56-8bf8-58ec466c7f32.png)

the same is on x-native-select and x-textarea and x-select

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
