### ISSUE TITLE
V2 Roadmap

### ISSUE THREAD

**Issue by ph7jack** [PH7-Jack/livewire-ui#502]
Hello everyone, I'm now developing the new version of WireUI, this new version will be really better than the current.

### **New features will be delayed to the next major release (v2.0.0).**

The v1 will be supported for 2 years after the v2 is released. But security patches will be applied for 4 years.
More information about versioning and supporting in soon. Keep calm, the WireUI will support old releases for a long time.

I hope you understand it. 
Thanks for using WireUI ❤️

**Comment by flolanger** [comment]
Thanks for your work!
Do you plan or wait for Livewire V3 to support it in V2?

**Comment by ph7jack** [comment]
@flolanger Both versions will have support for the Livewire v3
I'll release the new wireui when I finish the changes, if the livewire v3 isn't released, I'll release it before.

**Comment by flolanger** [comment]
@PH7-Jack I'm currently planning a new project with WireUI. Do you think V2 will have a steep upgrade path and I should better wait for it or will it be easy to upgrade?

Thank you!

**Comment by ph7jack** [comment]
@flolanger No worries, upgrading to v2 will be easy.

**Comment by dominikgeimer** [comment]
Do you already have a rough release date in mind?

**Comment by ph7jack** [comment]
Hi @dominikgeimer 
If everything goes well, the new version will be released in **mid-February/2023.**
I can't add an exact date for now.

**Comment by dominikgeimer** [comment]
I hope you are doing well and wanted to check in and see if there might be a brief update from you regarding the release?

**Comment by joaopalopes24** [comment]
Hello @dominikgeimer. We are still working on v2, we are rewriting a lot of the code and fixing all possible bugs, and it was a bigger job than we imagined for 2 developers. We hope to launch as soon as possible, and we are making excellent progress.

**Comment by cloudstudio** [comment]
@joaopalopes24 if you create one branch, we are happy to help ! so you are not only 2 !! just let us know if you need help

**Comment by joaopalopes24** [comment]
@cloudstudio We already have a branch. Check this PR: https://github.com/wireui/wireui/pull/677

**Comment by KevinEscobarV** [comment]
Hello @PH7-Jack , What's new about V2?

**Comment by ph7jack** [comment]
Hello everyone, we are really close to release the new version.
https://wireui.dev

Add a schedule to your calendar, we will stream a live

**Comment by vlados** [comment]
Link to the stream? :)

**Comment by willmkt** [comment]
Where are the new docs for version 2?

**Comment by Sophist-UK** [comment]
https://wireui.dev/components ??

**Comment by joaopalopes24** [comment]
The version 2 beta is already available!

**Comment by jfvoliveira** [comment]
Any preview on the v2 stable release date?

**Comment by joaopalopes24** [comment]
Please, check this issue https://github.com/wireui/wireui/issues/857.

**Comment by holiq** [comment]
Where I can find navbar for mobile like on the [docs](https://wireui.dev/getting-started)?


![Screenshot_20240213_082544_Chrome](https://github.com/wireui/wireui/assets/30729921/b5068094-5da4-4602-9b93-6be5b5b67b01)

**Comment by theanadimukt** [comment]
Any update on v2 release date?

**Comment by joaopalopes24** [comment]
Version 2 stable has been released today. I thank everyone. We rewrote almost all of Typescript.

**Comment by Silomalo** [comment]
@ph7jack, @joaopalopes24  , I have been using v1 for a while and would like to upgrade to v2 but I see we have lots of breaking changes, kindly is their a codemode or a proper guide that can facilitate smooth transition.
Thank you.
