### ISSUE TITLE
Livewire Entangle Error: cardModal

### ISSUE THREAD

**Issue by timiosaze** [PH7-Jack/livewire-ui#509]
Livewire property 'cardModal' cannot be found
I am trying to use the cardModal 
`

                    <x-modal.card title="Edit Customer" blur wire:model.defer="cardModal">
                        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                            <div class="col-span-1 sm:col-span-2">
                                <x-textarea wire:model="comment" label="Comment" placeholder="Your comment" />
                            </div>
                        </div>
                        <x-slot name="footer">
                            <div class="flex justify-between gap-x-4">
                                <x-button flat negative label="Delete" wire:click="delete" />
                     
                                <div class="flex">
                                    <x-button flat label="Cancel" x-on:click="close" />
                                    <x-button primary label="Save" wire:click="save" />
                                </div>
                            </div>
                        </x-slot>
                    </x-modal.card>
`

the button is 

`
 <button onclick="$openModal('cardModal')"
                            class="block w-full text-start py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Edit</button>
`

**Comment by joaopalopes24** [comment]
@timiosaze Send me how is the `cardModal` variable in your Livewire component, please.

**Comment by joaopalopes24** [comment]
I tested it with the same code and it works fine. You probably didn't create the attribute in the component.

The Livewire Component:

```
use Livewire\Component;

class Test extends Component
{
    public bool $cardModal = false;

    public function render()
    {
        return view('livewire.documentation.test');
    }
}
```

The Blade Component:

```
<div>
    <x-modal.card :title="trans('Edit Customer')" blur wire:model.defer="cardModal">
        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div class="col-span-1 sm:col-span-2">
                <x-textarea wire:model="comment" label="Comment" placeholder="Your comment" />
            </div>
        </div>

        <x-slot name="footer">
            <div class="flex justify-between gap-x-4">
                <x-button flat negative label="Delete" wire:click="delete" />

                <div class="flex">
                    <x-button x-on:click="close" flat label="Cancel" />
                    <x-button wire:click="save" primary label="Save" />
                </div>
            </div>
        </x-slot>
    </x-modal.card>

    <button onclick="$openModal('cardModal')" class="block w-full px-4 py-2 text-start hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
        {{ trans('Edit') }}
    </button>
</div>
```

**Comment by joaopalopes24** [comment]
If you don't create the attribute in the Livewire component, it will actually give the error.

![image](https://user-images.githubusercontent.com/45684782/197091996-1b0728e4-705e-47ab-ad09-57131fabd773.png)

**Comment by joaopalopes24** [comment]
@timiosaze So, I will close this issue because the modal card is working normally.
