### ISSUE TITLE
Lots of toggles switch's on the page effect status of others

### ISSUE THREAD

**Issue by MickProPay** [PH7-Jack/livewire-ui#512]
**Describe the bug**
I have a systems page that contains a list of available systems inside the system. Each as a on/off state that im using the toggle component to represent. So now if I click on system 3 or 4 it would toggle system one's toggle and actual execute the code how this is happening as I'm assigned an individual info to each item. However if i seem to click on the actual center of the toggles "Head" is seems to work.

**Code**
<x-table.table-body-td-action>
                                            <livewire:component.systems.systems-toggle-component
                                                wire:key="{{ $system->id }}"
                                                :system-id="$system->id"
                                                :system-name="$system->system_name"
                                                :system-status="$system->system_status"
                                                :system-type="$system->type"
                                            />
                                        </x-table.table-body-td-action>

**To Reproduce**
1. Create a list of items with a toggle status
2. Toggle other items to see if it effects toggle  x 
https://www.awesomescreenshot.com/video/11986867?key=fa43f92d17273ab98ba4033408fc54d5

**Expected behavior**
Not have toggle x effect toggle y

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Dependencies**
 - WireUI Version:^1.17.1
 - Laravel Version: 9.36
 - Alpine.js Version: 3.0.6
 - Livewire Version: 2.10.7
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - Windows
 - chrome
 - latest

**Additional context**
Side question how do i set the toggle to read only?

**Comment by joaopalopes24** [comment]
@MickProPay Send us the code of the page where the toggle components are, please.

**Comment by ph7jack** [comment]
@MickProPay your toggle component is using the same name/id/wire:model?

**Comment by MickProPay** [comment]
@PH7-Jack  sorry for the very late reply didn't seem to get the notice that you posted.

```
@foreach($this->allSystems as $system)
                                    <tr>

                                        <x-table.table-body-td :first="true">
                                            {{ str($system->system_name)->replace('-', ' ')->ucfirst() }}
                                        </x-table.table-body-td>

                                        <x-table.table-body-td>
                                            {{ str($system->type)->ucfirst() }}
                                        </x-table.table-body-td>

                                        <x-table.table-body-td>
                                            {{ $system->system_description }}
                                        </x-table.table-body-td>

                                        <x-table.table-body-td-action>
                                            <livewire:component.systems.systems-toggle-component
                                                wire:key="{{ $system->id }}"
                                                :system-id="$system->id"
                                                :system-name="$system->system_name"
                                                :system-status="$system->system_status"
                                                :system-type="$system->type"
                                            />
                                        </x-table.table-body-td-action>

                                    </tr>
                                @endforeach
```

```
<x-toggle label="Label in Right" wire:model.defer="systemStatus" />
```

so foreach system i have a livewire comp that manages the updating of the state for each system on iets own and inside each i have the above.

Hope this makes sense and again sorry for the late reply.

**Comment by ph7jack** [comment]
@MickProPay I understand now. You have many toggles on the same page with the same name/id. 
The livewire doesn't have a separate DOM for each component (Livewire) like the Vue/React. 
You need to pass a custom id for each toggle.

`<x-toggle label="Label in Right" wire:model.defer="systemStatus" id="systemStatus.{{ $systemId }}" />`

In this way, the toggle will work fine because it has a unique id. 

Feel free to ask questions.

**Comment by MickProPay** [comment]
> @MickProPay I understand now. You have many toggles on the same page with the same name/id. The livewire doesn't have a separate DOM for each component (Livewire) like the Vue/React. You need to pass a custom id for each toggle.
> 
> `<x-toggle label="Label in Right" wire:model.defer="systemStatus" id="systemStatus.{{ $systemId }}" />`
> 
> In this way, the toggle will work fine because it has a unique id.
> 
> Feel free to ask questions.

0.o why didnt i think of that... Id field. Thanks ill have a look and confirm but you are probably correct ;P
