### ISSUE TITLE
Select doesn't work when using it dynamically

### ISSUE THREAD

**Issue by MarigonaHoxhaj** [PH7-Jack/livewire-ui#513]
Hi Pedro,

I am using WireUI select dynamically in my Livewire component. 
So whenever I press Add button, it adds a new select into my page.
Select looks like below:
![Screenshot 2022-10-27 at 08 42 33](https://user-images.githubusercontent.com/78410229/198210210-06fe3fdc-d221-45e5-a753-ebaf08888d28.png)

When I try to fetch the value, it shows an empty array.
It is worth to mention that it works with WireUI input, but not select. Also with other NOT WireUI selects works as well.
I republished the assets and run optimize:clear, but it seems still not working.

**Comment by joaopalopes24** [comment]
@MarigonaHoxhaj The wireUI custom select works using @entangle. In order to have this link via `wire:model`, the attribute must exist within the Livewire Component.

Example:

`public array $markingType = [];`

```
@php
    $values = [1,2,3,4,5,6];
@endphp

@foreach ($values as $key => $value)
    <div wire:key="value::{{ $key }}" class="grid grid-cols-8 gap-6">
        <div class="col-span-6 mt-2 sm:col-span-2">
            <x-select
                wire:key="marking::type::{{ $key }}"
                wire:model="markingType.{{ $key }}"
                placeholder="Select one status"
                :options="[
                    ['name' => __('Active'), 'id' => 'active'],
                    ['name' => __('Pending'), 'id' => 'pending'],
                    ['name' => __('Stuck'), 'id' => 'stuck'],
                    ['name' => __('Done'), 'id' => 'done'],
                ]"
                option-label="name"
                option-value="id"
            />
        </div>
    </div>
@endforeach
```

This won't work as the attributes don't work. But if you put it like this in the Livewire Component, it already works:

`public array $markingType = [null,null,null,null,null,null];`

**Comment by ph7jack** [comment]
@MarigonaHoxhaj To make sure, does using the native select work?
Like @joaopalopes24 said, the entangle requires that the property or the array key exists to work with.

**Comment by MarigonaHoxhaj** [comment]
Hi @PH7-Jack, 

@joaopalopes24 suggestion worked. 

Thank you very much!

**Comment by joaopalopes24** [comment]
@MarigonaHoxhaj I'm glad the solution worked. We are working to resolve this limitation of `@entangle`. I believe that in v2 it will already be solved.
