### ISSUE TITLE
Confirm dialog buttons can be fired multiple times

### ISSUE THREAD

**Issue by Krato** [PH7-Jack/livewire-ui#515]
**Describe the bug**
When showing confirm dialogs with buttons, buttons can be fired twice or more if you for example double click in the button. 

**To Reproduce**
1. Create a dialog with buttons
2. Open the dialog
3. Double click on button
4. Your function will be called twice

**Expected behavior**
Should be fire just one time, not multiple

**Screenshots or Videos**
https://user-images.githubusercontent.com/74367/199214408-ce2f751a-631d-4b71-b967-19decdd5cc96.mp4

**Dependencies**
 - WireUI Version: 1.17.1
 - Laravel Version: 9.36.4
 - Alpine.js Version: 3.10.0
 - Livewire Version: 2.10.7
 - Lang: en_US

**Comment by ph7jack** [comment]
Wow! Awesome catch. Thanks a lot 💪🏼

**Comment by Krato** [comment]
Hehehe thank you for your amazing work.🙌

We just found some queues firing twice after a confirmation. Then I started checking the problem and found it. 

☺️

**Comment by Krato** [comment]
@PH7-Jack Thank you!
