### ISSUE TITLE
Can't assign new color to buttons

### ISSUE THREAD

**Issue by jcerdan** [PH7-Jack/livewire-ui#516]
Hi,

I'm trying to add a new color to wireui buttons but all I have tried doesn't work. May be I'm missing something. Here's what I'm doing:

- in tailwind.config.js
```
 ...
 theme: {
        extend: {
            colors: {
                curious: {
                    '50': '#f2fafd',
                    '100': '#e6f5fa',
                   '200': '#bfe6f4',
                    '300': '#99d6ed',
                    '400': '#4db8df',
                    '500': '#0099D1',
                    '600': '#008abc',
                    '700': '#00739d',
                    '800': '#005c7d',
                    '900': '#004b66'
                },
                chathams: {
                    '50': '#f2f7f8',
                    '100': '#e6eef2',
                    '200': '#bfd5de',
                    '300': '#99bbcb',
                    '400': '#4d89a3',
                    '500': '#00567C',
                    '600': '#004d70',
                    '700': '#00415d',
                    '800': '#00344a',
                    '900': '#002a3d'
                },
            },
        },
    },
...
```

If I use this color in a Tailwind class tag it does work fine. For instance
```
<div class="bg-curious-500">...</div>
```
applies the right color.

But when trying to use it in wireui buttons, this doesn't work.
```
<x-button color="curious" label="button" />
```

Instead, basic Tailwind colors work as indicated in the docs or via the tag 'color', for instance:
```
<x-button color="red" label="button" />
```

I have seen there's a tailwind.config.js in ./vendor/wireui/wuire folder, but there's no way to publish this file and I don't know if the added color should be added here also...

I'm using those versions:
- wireui: 1.17.1
- laravel: 9.38
- AlpineJS: 3.10.3
- Livewire:  2.10.7
-  Tailwindcss: 3.2.1

I think it's possible to use custom colors in wireui but I'm maybe wrong. 
Is it possible? In that case, how am I supposed to add the new color?

**Comment by jcerdan** [comment]
I answer myself...
I think this is related to what I mean:
https://github.com/wireui/wireui/issues/234

It looks like we must use basic Tailwind colors and can't add new "names". I have set 'primary' and 'secondary' as my color palettes and now buttons have the right colors.
Is it the way to do that? Can someone confirm me we can't define new color names in WireUI?

Best,

**Comment by ph7jack** [comment]
Hi @jcerdan 
For now, it's not possible to add colors on the tailwind side, on the tailwind side is only possible to modify the default colors, like primary, and negative...

To add a new color to the button component you must extend the class and override it in the wireui configuration.

1. Publish the wireui config: `php artisan vendor:publish --tag='wireui.config'`
2. Create a Button class component: `php artisan make:component Button`
3. Extends the WireUI button in your new button class
4. Override the methods `outlineColors`, `flatColors` and `defaultColors` to add your new color
```php
public function defaultColors(): array
{
    $colors = parent::defaultColors();
    
    $colors['my-custom-color'] = 'css classes';
    
    return $colors;
}
```

**Comment by joaopalopes24** [comment]
@jcerdan The solution is found above, but there was no response, so we will be closing the Issue. Thank you in advance for your attention, and thank you for using the package.
