### ISSUE TITLE
Error related to select component since last update 1.17.2

### ISSUE THREAD

**Issue by t1m0t** [PH7-Jack/livewire-ui#519]
**Describe the bug**
le select component seems to be buggy since last update to 1.17.2 with this error message: `ReferenceError: position is not defined` or from alpine `Alpine Expression Error: position is not defined`. When I downgrade to 1.17.1, and clear cache, the error no longer happen.

**To Reproduce**
1. insert a select component
2. See error

**Expected behavior**
I expect no error because I haven't had an error for version anterior to 1.17.2

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/3594098/199996849-d679c3b1-8fd7-47c0-b2f9-4cbad034b6d7.png)

**Dependencies**
 - WireUI Version: 1.17.2
 - Laravel Version: 9.1.19
 - Alpine.js Version: 3.10.5
 - Livewire Version: 2.10.7
 - Lang: fr_FR

**Desktop (If applicable, please complete the following information):**
 - OS: [Windows]
 - Browser: [firefox]
 - Version [106.0.3]

**Additional context**

**Comment by ph7jack** [comment]
@t1m0t You have the views published, so you need to update them. 
Tip: If you don't modify anything, you don't need to publish it
