### ISSUE TITLE
Disabled property for buttons

### ISSUE THREAD

**Issue by markgoedegebure** [PH7-Jack/livewire-ui#523]
It would be a nice feature to have a disabled property for buttons. It doensn't seem to exist in the current button components.
I think something like `:disabled="true/false"` would do the trick.

**Comment by ph7jack** [comment]
Hi @markgoedegebure 
If you add the **disabled** attribute the button will be **disabled**. 
You can combine it with variables: `<x-button :disabled="$isDisabled"`
