### ISSUE TITLE
x-on:selected not working when deselecting

### ISSUE THREAD

**Issue by pablomadariaga** [PH7-Jack/livewire-ui#530]
In the select multiselect the `x-on:selected` event is not working when deselecting option

**Comment by ph7jack** [comment]
@pablomadariaga Could you record a video to show it not working in your project?
It's working here.

**Comment by ph7jack** [comment]
I recommend the https://jam.dev

**Comment by ph7jack** [comment]
Closing it. If your error persists, record a video and show the bug, or show some pieces of code. Thanks

**Comment by pablomadariaga** [comment]
This the Jam video.

https://jam.dev/c/9bc98585-76dc-4820-bdb3-128d2b200d67

This my code.

![image](https://user-images.githubusercontent.com/69119357/203469546-9c574481-a304-467b-b01e-38e7dc74d600.png)

**Comment by Bmohsen** [comment]
> In the select multiselect the `x-on:selected` event is not working when deselecting option

I found un-selected custom event in : https://github.com/wireui/wireui/blob/2cdba717cfeba4a49bfbbd39e8367fcdad79bca6/ts/components/select/index.ts#LL589C4-L589C4

and it solved my problem:
```blade
                         <x-select
                                label="select Brands"
                                wire:model.defer="selectedBrands"
                                multiselect
                                x-on:selected="generate_price_input"
                                x-on:un-selected="delete_price_input"
                                placeholder="select brands"
                                :options="$brands"
                                option-label="name"
                                option-value="id"
                            />
```
