### ISSUE TITLE
Unable to locate a class or view for component [badge] / [avatar]

### ISSUE THREAD

**Issue by petermaas** [PH7-Jack/livewire-ui#544]
**Describe the bug**
I get an error when using the badge or avatar component. There is no issue if I use a toggle or checkbox or form element.

**To Reproduce**
Add component on the page

**Expected behavior**
Display the avatar or badge

**Screenshots or Videos**
<img width="1418" alt="Screenshot 2022-11-20 at 10 12 15" src="https://user-images.githubusercontent.com/19660980/202894287-51a90937-00f0-4459-b52c-1f8521391982.png">

**Dependencies**
 - WireUI Version: 1.17.6
 - Laravel Version: 9.40.1
 - Alpine.js Version: 3.10.5
 - Livewire Version: 2.10.7
 - Lang: nl_NL

**Desktop (If applicable, please complete the following information):**
 - OS: macOS Monterey
 - Browser: Chrome
 - Version 107.0.5304.110

**Comment by ph7jack** [comment]
@petermaas If you are using the latest wireui version, and you have the config published, publish the config again to get the new components paths.

**Comment by petermaas** [comment]
Thank you for the quick reply and solution.... I'll keep that in mind for the next time.

ps. I really like WireUi, thank you for all yours efforts so far 👍
