### ISSUE TITLE
Select with async-data does not auto-select the real property value

### ISSUE THREAD

**Issue by frankiejarrett** [PH7-Jack/livewire-ui#549]
**Describe the bug**

Once the Select component loads its async data, the value is always forced to be the first item in the array (`foo`) even though the Livewire property is set to `bar` during mount.

At first I thought maybe a workaround could be explicitly setting the `value="{{ $product }}"` attribute, but that has no effect.

Everything works as you'd expect with the `:options` attribute, this only happens when using `:async-data`.

**To Reproduce**

**routes/web.php**
```php
Route::get('/products', function () {
    return [
        [
            'label' => 'Foo',
            'value' => 'foo',
        ],
        [
            'label' => 'Bar',
            'value' => 'bar',
        ],
        [
            'label' => 'Baz',
            'value' => 'baz',
        ],
    ];
})->name('products');
```

**app/Http/Livewire/Test.php**
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Test extends Component
{
    public $product;

    public function mount()
    {
        $this->product = 'bar';
    }

    public function render()
    {
        return view('livewire.test');
    }
}
```

**resources/views/livewire/test.blade.php**
```blade
<div class="flex max-w-md flex-col gap-8 p-8">
    <x-select label="Select a product"
              wire:model.defer="product"
              :async-data="route('products')"
              option-label="label"
              option-value="value" />

    <pre>
        Product: {{ $product }}
    </pre>
</div>

```

**Expected behavior**

I expect the component to auto-select the real property value (`bar`) after the async data is loaded.

For my use case this is for a stateful form that allows users to resume where they left off after a page reload.

**Screenshots or Videos**

When the page loads you see `Product: bar`, but the component selects`foo`.

<img width="417" alt="Screen Shot 2022-11-25 at 2 54 58 PM" src="https://user-images.githubusercontent.com/522158/204054555-5009107b-166c-494b-8aff-c91528a379e4.png">

If you remove `.defer` and just use `wire:model` the Select component will fire a model update, forcing the value to be `foo`:

https://user-images.githubusercontent.com/522158/204055219-811e7539-b85c-4efe-b97d-ed73ab1e793a.mov

**Dependencies**
 - WireUI Version: 1.17.6
 - Laravel Version: 9.41.0
 - Alpine.js Version: 3.10.5
 - Livewire Version: 2.10.7
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 107.0.5304.121

**Comment by joaopalopes24** [comment]
@fjarrett Your route must return the data when the select is checked. Check the documentation:

https://livewire-wireui.com/docs/select#async-search

https://github.com/wireui/docs/blob/main/app/Http/Controllers/Api/Users/Index.php

**Comment by joaopalopes24** [comment]
I performed the test locally and it is working normally. Thank you in advance for your attention, and if necessary, you can ask us again.

**Comment by frankiejarrett** [comment]
@joaopalopes24 wow, not sure how I missed that! thank you
