### ISSUE TITLE
x-transition doesn't work in notification component

### ISSUE THREAD

**Issue by Blinks44** [PH7-Jack/livewire-ui#553]
Hello! I'm trying to achieve x-transition to work in notification component, but with no luck... Even on documentation site, notifications just appears immediately, without transition. 

I think it doesn't work because in vendor/notification.blade.php component x-transition should use along with x-show/x-if, but i can't figure out how to modify template to do it :)

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
