### ISSUE TITLE
Time Picker and Datetime Picker option to include seconds

### ISSUE THREAD

**Issue by Alph44rchitect** [PH7-Jack/livewire-ui#554]
Hey Jack, first of all: I really like your time and datetime picker.

**Is your feature request related to a problem? Please describe.**
I need the possibility to select or at least set a time or datetime including seconds with the picker.

**Describe the solution you'd like**
Add option for including seconds selection.

Would be nice if you find some time.
Keep going, you doing well! :)

Greetings
Lars

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

This feature was added in stable version 2. Check our documentation at: https://wireui.dev.
