### ISSUE TITLE
MinTime and MaxTime on time-picker component

### ISSUE THREAD

**Issue by jrousan** [PH7-Jack/livewire-ui#559]
I'm using this component package and it works very well, but I can't figure out why the time-picker component doesn't also have a minTime and maxTime config option like the DateTime picker.

Feature is crucial for making time-picker useable in real world contexts.

Thanks

**Comment by jrousan** [comment]
Making the TypeScript files publishable would help.  Limited recourse to make the changes myself.

**Comment by stratoghost** [comment]
I second this

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
