### ISSUE TITLE
Blur on top of modal Webkit (iOS or Safari on mac)

### ISSUE THREAD

**Issue by racerguy** [PH7-Jack/livewire-ui#561]
**Describe the bug**
On chrome and Firefox, blur is always behind the modal. On anything using webkit it is on top covering the modal.  This only happens when page has overflow-y-auto on it. 

**To Reproduce**
create div with overflow-y-auto
put modal in 
test on safari or ios browser

**Expected behavior**
Blur Should be under modal 

**Screenshots or Videos**

**Dependencies**

**Desktop (If applicable, please complete the following information):**
Safari, iOS or Mac

**Smartphone (If applicable, please complete the following information):**
iPhone and iPad

**Additional context**

**Comment by ph7jack** [comment]
@racerguy Could you provide screenshots or video?

**Comment by bigstation17** [comment]
I have same problem.
On ios and Safari on Mac, if modal content is larger than viewport, modal background is in front.

**Comment by bigstation17** [comment]
This works for me:

```
div[wireui-modal] > div:first-child {
    z-index: -1;
}
```

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
