### ISSUE TITLE
Can't populate and pre-select a nested parameter in a non-async way

### ISSUE THREAD

**Issue by agharium** [PH7-Jack/livewire-ui#562]
**Describe the bug**
I just can't find a way to populate and pre-select an option using `wire-model` (nested parameter) in a **non-async** way

**To Reproduce**
1. Create a population array and a nested model parameter to be selected on Livewire component

```

public User $user;
public $roles;

protected $rules = [
    'user.access_level' => 'required|number',
];

public function mount()
{
    $this->user = User::find(1);
    $this->roles = UserRole::get();
}
```

2. On blade, create the select input and populate using `x-select-option`'s

```
<x-select
    label="Nível de acesso"
    placeholder="Selecione um nível"
    option-value="id"
    option-label="name"
    :options="roles" // or {{ $roles }}, won't work either way
    wire:model="user.access_level"
>
    @foreach($roles as $r)
        <x-select.option label="{{ $r->name }}" value="{{ $r->id }}"
        	@if ($r->id == $user->access_level) selected @endif /> // of course it won't work, it's just desperation really
    @endforeach
</x-select>
```

3. See error - select doesn't loads with pre selection as expected

**Expected behavior**
The select input should load with the wire:model corresponding option pre-selected.

**Dependencies**
 - WireUI Version: 1.17.5
 - Laravel Version: 8.75
 - Alpine.js Version: 3.10.5
 - Livewire Version: 2.10
 - Lang: pt_BR

**Additional context**
Now, I'm dead sure I'm doing a real ugly mistake haha. But I can't find a answer anywhere on docs or past issues.

Can you please help me? 😟 😁

And by the way..

Trabalho maravilhoso que vcs fizeram neste componente, caras.. Mataram a pau! Valeu demaisss

Thank you :)

**Comment by joaopalopes24** [comment]
From the moment the `options` attribute is used, there is no need to `foreach` the options inside the `select`. And if the parameter has already been filled in in the User Model, the `select` is already marked.

Check documentation: [Select](https://livewire-wireui.com/docs/select#custom-options)

**Comment by LukaTarkhn** [comment]
```
<x-select
    label="Nível de acesso"
    placeholder="Selecione um nível"
    option-value="id"
    option-label="name"
    :options="$roles" // this way works
    wire:model.defer="user.access_level" // or just access_level
/>
```
