### ISSUE TITLE
Select async search add headers

### ISSUE THREAD

**Issue by fisher926** [PH7-Jack/livewire-ui#568]
Hello!
How can I add headers to async data?

Ex. Authorization: Bearer <token>

 :async-data="[
    'api' => route('api.users.index'),
    'method' => 'POST', // default is GET
    'params' => ['ble' => 'baz'], // default is []
    'credentials' => 'include' // default is undefined,
    'headers' => [
        'Authorization: Bearer <token>'    
    ] ?
]"

**Comment by ph7jack** [comment]
@fisher926 If you need to fetch an endpoint in your current laravel application, just allow this middleware `https://github.com/wireui/docs/blob/main/app/Http/Kernel.php#L44`
The WireUI will inject the authentication by default to the request

**Comment by BMasquio** [comment]
> @fisher926 If you need to fetch an endpoint in your current laravel application, just allow this middleware `https://github.com/wireui/docs/blob/main/app/Http/Kernel.php#L44` The WireUI will inject the authentication by default to the request

What middleware? The url is broken.
