### ISSUE TITLE
select and date picker not consistently binding to array elements

### ISSUE THREAD

**Issue by judgej** [PH7-Jack/livewire-ui#574]
**Describe the bug**
A `x-datetime-picker` and `x-select` does not send updates to the server unless the bound element already exists. Simpler components such as `x-input` do work.

**To Reproduce**

In the component, set a public array to bind to:

    public array $details = [];

In a form, bind to elements of the array:

    <x-datetime-picker wire:model="details.date" ... />
    <x-select wire:model="details.name" ... />

When saving the form, or when updating either field, only tje `x-select` gets added to the array. The `x-datetime-picker` or `x-select` does not.

However, if the array is preloaded with a `null` element, then it does work:

    public array $details = ['date' => null];

There is no need to preload the `name` attribute in the same way.

If it weren't for the simple text box working, I would have put it down to a Livewire issue, but this does show that editing a field in the browser *can* create a matching array element in the component.

The `updated()` method in the component does not get triggered at all when a date is selected, *unless* the `date` element of the array exists, even if it's null.

**Expected behavior**

**Dependencies**
 - WireUI Version: 1.17.7
 - Laravel Version: 8.83.76
 - Alpine.js Version: 3.10.5
 - Livewire Version: 2.10.7
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: Win 10
 - Browser: FF
 - Version: latest

**Additional context**
None

**Comment by judgej** [comment]
I think the problem is related to the use of the `entangle` function/object/prototype/whatever-it-is in the datetime and select components, and probably others. Here I have a datetime-picker pointed at `wire:model="filterData.created_from"`. If I preset the `created_from` element in the component mount (`$this->filterData['created_from] = null;`) then I see no errors, and the datetime picker is bound to that array element on the back end.

If I *do not* preset the `filterData.created_from` array element, then the front end gets the following JavaScript error in the console on mounting the page. The datetime picker does *not* then get sent to the back end on changes.

```
Livewire Entangle Error: Livewire property 'filterData.created_from' cannot be found SupportAlpine.js:175:28
    interceptor SupportAlpine.js:175
    initialize module.esm.js:348
    recurse module.esm.js:332
    recurse module.esm.js:327
    initInterceptors module.esm.js:340
    <anonymous> module.esm.js:2600
    skipDuringClone module.esm.js:1138
    flushHandlers module.esm.js:539
    stopDeferring module.esm.js:544
    deferHandlingDirectives module.esm.js:547
    initTree module.esm.js:750
    start module.esm.js:710
    start module.esm.js:709
    <anonymous> app.js:4
    js app.js:40
    __webpack_require__ app.js:96
    <anonymous> app.js:238
    O app.js:130
    <anonymous> app.js:241
    <anonymous> app.js:243
```

Using a non-array public property on the component also works fine.

So it seems that LiveWire's `wire:model="foo.bar"` works fine when pointing at an array element that does not exist, and will create that element on-the-fly when it needs to. But add in an `entagle` here and it all breaks for an array with a missing element. I'm not sure at all where the problem is here - LiveWire, Alpine, WireUI - could be any of them, but I hope this helps to see where it is.

I'm not a JavaScript coder, but my hunch here is that Alpine is throwing an exception, after being told to look at data that does not exist by LiveWire, but WireUI should perhaps be catching that exception and filling in the missing data, or maybe filling in that missing data on the front end from the start, since it knows the front end is going to be expecting it.

**Comment by joaopalopes24** [comment]
@judgej This is not a bug, but a limitation of entagle. I hope it can be a fix for Livewire v3, but at the moment there is no way to fix it. Thank you in advance for using the package, thank you.

**Comment by judgej** [comment]
Should something be added to the documentation as a warning? It's not obvious to a developer that entangle is being used in the construction of the component. A single page that just takes binding, lists which components use entangle, and necessary workarounds if you want to bind to an array element would be good. I could write something up in the discussions to see what would be useful.

All I know is that if I'm left scratching my head for far too long, then others will be too. And future-me will go through it all again without a reminder ;-)
