### ISSUE TITLE
Undefined variable $_instance when i want to try modal wireui

### ISSUE THREAD

**Issue by garudaputro** [PH7-Jack/livewire-ui#577]
i just install wireui and ill try to using it.

i test to make modal with this component on wireui 

`<x-modal blur wire:model.defer="blurModal">
    ...
</x-modal>`
 but show error on my laravel  Undefined variable $_instance , what should I do for fix it?

**Comment by csarcrr** [comment]
What was the solution? I am having the same problem...

**Comment by Young1111Wei** [comment]
I am having the same problem too...

**Comment by csarcrr** [comment]
For anyone who stumbles upon this issue and has yet figured out why it shows this error.
My case was because I was trying to use a WireUI component outside of a Livewire component and it resulted in this error.
