### ISSUE TITLE
Using x-bind on input attributes has no effect

### ISSUE THREAD

**Issue by frankiejarrett** [PH7-Jack/livewire-ui#578]
**Describe the bug**

It's not possible to dynamically set input attributes with Alpine, like `suffix` or `corner-hint` for example.

Alpine does its job and dynamically sets the attribute in the DOM, but the input component doesn't render any changes.

Use case: It would be pretty handy to show users how many characters they have left as they type.

**To Reproduce**
```blade
<x-input label="Product name"
         maxlength="64"
         x-data="{
             suffix: null,
             setSuffix(n) {
                 this.suffix = n + ' / ' + $el.getAttribute('maxlength');
             },
         }"
         x-init="setSuffix($el.value.length)"
         x-on:input="setSuffix($event.target.value.length)"
         x-bind:suffix="suffix" />
```

**Expected behavior**

<img width="495" alt="Screen Shot 2022-12-18 at 4 47 26 PM" src="https://user-images.githubusercontent.com/522158/208323355-6ed2125a-f5d8-494c-968b-1308e20bfe65.png">

<img width="487" alt="Screen Shot 2022-12-18 at 5 37 41 PM" src="https://user-images.githubusercontent.com/522158/208325480-d9ac979f-147c-458b-9a56-7fadc1bb4f9c.png">

**Dependencies**
 - WireUI Version: 1.17.8
 - Laravel Version: 9.44.0
 - Alpine.js Version: 3.10.5
 - Livewire Version: 2.10.7
 - Lang: en_US

**Comment by joaopalopes24** [comment]
You can work with the append slot, and use alpine however you like. Here's an example:

```
<div x-data="{
        suffix: null,
        setSuffix(n) {
            this.suffix = n + ' / ' + $refs.test.getAttribute('maxlength');
        },
    }"
    x-init="setSuffix($refs.test.value.length)"
>
    <x-input label="Product name"
        class="!pr-18"
        x-ref="test"
        maxlength="64"
        x-on:input="setSuffix($event.target.value.length)"
    >
        <x-slot name="append">
            <div class="absolute inset-y-0 right-0 pr-2.5 flex items-center pointer-events-none text-secondary-400">
                <span x-text="suffix" class="flex items-center justify-center pr-1">
                    {{--  --}}
                </span>
            </div>
        </x-slot>
    </x-input>
</div>
```

**Comment by frankiejarrett** [comment]
@joaopalopes24 Thanks for the example! However, it should be noted that this still does not work for the `cornerHint` slot because the HTML is escaped.
