### ISSUE TITLE
Enabling a disabled number component fails to enable properly

### ISSUE THREAD

**Issue by judgej** [PH7-Jack/livewire-ui#579]
**Describe the bug**
Enabling a disabled number input leaves the up/down buttons still not working.

**To Reproduce**

1. This simple form item starts with `$someBoolean` mounted as `false`:

    <x-inputs.number  wire:model="model" :disabled="! $someBoolean" />

2. Do somerthing on the form to set `$someBoolean` to `true`, for example:

    <x-button label="Press me" wire:click="$set('someBoolean', true)" />

3. The central number in the number field can be clicked on, and a number can be types. However, it seems to be removed from the tab sequence, the keyboard up/down keys do nothing, and the +/- buttons show a "not active" mouse pointer with clicking on them doing nothing.

**Expected behavior**
There may be an alternative way to disable or enable the number field, but the expectation is that most "standard" approaches that work in general for livewire should work as expected.

Dependencies

    WireUI Version: 1.17.7
    Laravel Version: 8.83.76
    Alpine.js Version: 3.10.5
    Livewire Version: 2.10.7
    Lang: en_US

Desktop (If applicable, please complete the following information):

    OS: Win 10
    Browser: FF
    Version: latest

Additional context
None

**Comment by judgej** [comment]
I've tried using `wire:key` as a workaround to see if Livewire could be made to completely re-render the component, but it makes no difference. My guess is that something in the initial page render needs to be retriggered, but that's a guess.

```html
<span wire:key="{{ $someBoolean ? 'enabledThing' : 'disabledThing' }}">
    <x-inputs.number wire:model="selectedQuantity" :disabled="! $someBoolean" />
</span>
```

So my workaround for now is to leave the number component enabled all the time, even when other conditions on the page dictate that it should be disabled.

**Comment by joaopalopes24** [comment]
I just performed the test and it works normally. Preferably use a fixed wire:key. Code used for testing is below:

Component:

```
    public ?int $value = null;

    public bool $someBoolean = false;
```

Blade:

```
@dump($someBoolean)

<x-inputs.number wire:key="test" wire:model.defer="value" label="How many Burgers?" :disabled="$someBoolean" />

<x-button wire:click="$toggle('someBoolean')">
         Click me
</x-button>
```
