### ISSUE TITLE
Select with 50k+ data

### ISSUE THREAD

**Issue by gassema23** [PH7-Jack/livewire-ui#580]
**Describe the bug**
Is there a way to limit data to X number and on scroll down load more data. I have 50+ data in the select drop down.

**To Reproduce**
1. Table name project with project_no and project_name field
2. Seed 50k+ data
3. With ApiController
4. public function projects(Request $request): Collection
    {
        return Project::query()
            ->select('id', 'project_no', 'project_name')
            ->orderBy('project_no')
            ->when(
                $request->search,
                fn(Builder $query) => $query
                    ->where('project_no', 'like', "%{$request->search}%")
                    ->orWhere('project_name', 'like', "%{$request->search}%")
            )
            ->when(
                $request->exists('selected'),
                fn (Builder $query) => $query->whereIn('id', $request->input('selected', [])),
                //fn (Builder $query) => $query->limit(10)
            )
            ->get()
            ->map(function (Project $project) {
                return $project;
            });
    }
5. <x-select
                    :label="Str::ucfirst(__('generals.forms.project'))"
                    always-fetch
                    :placeholder="Str::ucfirst(__('generals.forms.selections'))"
                    :async-data="route('api.projects.index')"
                    option-label="project_no"
                    wire:model.defer="project_id"
                    option-value="id"
                    option-description="project_name"
                    hide-empty-message
                />

When i use limit 10, it only showing 10 but i want to render all data from project table.
If i'm not using limit query, it show all data but, browser stop working.

**Expected behavior**
limit data to X number (10) and on scrolling select loading more data

**Screenshots or Videos**

**Dependencies**
 - WireUI Version: 1.17.7
 - Laravel Version: 9.43.0
 - Alpine.js Version: 3.10.5
 - Livewire Version: 2.10.7
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - Browser: chrome
 - Version 108.0.5359.125 (Build officiel) (64 bits)

**Comment by joaopalopes24** [comment]
@gassema23 This will be implemented in version 2. Thanks in advance for using the package.

**Comment by oliverbj** [comment]
Can confirm I would also need this :)

**Comment by joaopalopes24** [comment]
@oliverbj We'll do that in v2, but we don't have any scheduled dates. This feature is not something of extreme importance, we have other priorities within the package.

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We currently have no intention of making this feature. Feel free to contribute and help us grow WireUi.
