### ISSUE TITLE
Cant close modal or dialog divs and errors

### ISSUE THREAD

**Issue by dbiss01** [PH7-Jack/livewire-ui#583]
**it may not be a problem, it may be I don't understand the error**

wireui works fine until close modal opened by close button or outside area click.
console log is:

`app.d426e523.js:32 Uncaught (in promise) TypeError: R is not a function
    at app.d426e523.js:32:9023
(anonymous) @ app.d426e523.js:32
Promise.catch (async)
(anonymous) @ app.d426e523.js:32
requestAnimationFrame (async)
(anonymous) @ app.d426e523.js:32
app.d426e523.js:32 Uncaught (in promise) TypeError: R is not a function
    at app.d426e523.js:32:9023
(anonymous) @ app.d426e523.js:32
Promise.catch (async)
(anonymous) @ app.d426e523.js:32
requestAnimationFrame (async)
(anonymous) @ app.d426e523.js:32
app.d426e523.js:32 Uncaught (in promise) {isFromCancelledTransition: true}isFromCancelledTransition: true[[Prototype]]: Object
(anonymous) @ app.d426e523.js:32
(anonymous) @ alpinejs:5
(anonymous) @ alpinejs:5
Me @ alpinejs:5
out @ alpinejs:5
(anonymous) @ app.d426e523.js:32
window.Element._x_toggleAndCascadeWithTransitions @ app.d426e523.js:32
(anonymous) @ app.d426e523.js:32
(anonymous) @ app.d426e523.js:32
(anonymous) @ app.d426e523.js:32
ii @ app.d426e523.js:32
(anonymous) @ app.d426e523.js:32
Mm @ app.d426e523.js:28
(anonymous) @ app.d426e523.js:32
i @ app.d426e523.js:32
xm @ app.d426e523.js:28
app.d426e523.js:32 Uncaught (in promise) {isFromCancelledTransition: true}
(anonymous) @ app.d426e523.js:32
(anonymous) @ alpinejs:5
(anonymous) @ alpinejs:5
Me @ alpinejs:5
out @ alpinejs:5
(anonymous) @ app.d426e523.js:32
window.Element._x_toggleAndCascadeWithTransitions @ app.d426e523.js:32
(anonymous) @ app.d426e523.js:32
(anonymous) @ app.d426e523.js:32
(anonymous) @ app.d426e523.js:32
ii @ app.d426e523.js:32
(anonymous) @ app.d426e523.js:32
Mm @ app.d426e523.js:28
(anonymous) @ app.d426e523.js:32
i @ app.d426e523.js:32
xm @ app.d426e523.js:28
app.d426e523.js:32 Uncaught (in promise) TypeError: R is not a function
    at app.d426e523.js:32:9023
    at async Promise.all (index 3)
(anonymous) @ app.d426e523.js:32
Promise.catch (async)
(anonymous) @ app.d426e523.js:32
requestAnimationFrame (async)
(anonymous) @ app.d426e523.js:32
app.d426e523.js:32 Uncaught (in promise) TypeError: R is not a function
    at app.d426e523.js:32:9023
(anonymous) @ app.d426e523.js:32
Promise.catch (async)
(anonymous) @ app.d426e523.js:32
requestAnimationFrame (async)
(anonymous) @ app.d426e523.js:32
`

LAYOUT:

`<wireui:scripts />
    <script src="//unpkg.com/alpinejs" defer></script>
    
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    
    @livewireStyles
</head>

<body class="font-sans antialiased">
    <x-notifications />
    <x-jet-banner />
    <x-dialog z-index="z-50" blur="md" align="center" />

    <div class="min-h-screen bg-gray-100">
        @livewire('admin-navigation-menu')

        
        @if (isset($header))
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>
        @endif

        
        <main>
            {{ $slot }}
        </main>
    </div>

    @stack('modals')

</body>
@livewireScripts

</html>`

THE CALL IN COMPONENT CLASS:

`public function delete($id)
    {
        $this->dialog()->confirm([
            'title'       => 'Tem certeza disso?',
            'description' => 'A conta e todos dados serão excluidos permanentemente?',
            'icon'        => 'warning',
            'accept'      => [
                'label'  => 'Sim',
                'method' => 'sureDelete',
                'params' => $id,
            ],
            'reject' => [
                'label'  => 'Cancelar',
                // 'method' => 'cancel',
            ],
        ]);
    }`

everything works ok, only when it closes by clicking outside or the "x" button

**Comment by joaopalopes24** [comment]
@dbiss01 Hello. Send us the dialog/modal blade code to check in addition to the livewire component code. I tested this functionality locally and it is bug free.

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
