### ISSUE TITLE
When `min` is provided and `value` is null, travel to the month of `min` on init

### ISSUE THREAD

**Issue by nickfls** [PH7-Jack/livewire-ui#598]
**Is your feature request related to a problem? Please describe.**
When initial value is not present and min value is provided, it requires the user to traverse calendar to min date before making a selection. 

For example using datepicker with : `:min="now()->addMonth(4)"` would require user to click 4 times before a selection can be made

**Describe the solution you'd like**
add a condition after checking the value presence - if min value is provided - travel to min value month.

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
