### ISSUE TITLE
Request for wireui/assets/scripts returns 500

### ISSUE THREAD

**Issue by mahdi-akbary** [PH7-Jack/livewire-ui#599]
**Describe the bug**
http://localhost:8000/wireui/assets/scripts?id=f8aeecf1fde84d48a56317eb457248d8 return 500 so the js files is not loaded which causes multiple errors like:
```

Alpine Expression Error: wireui_color_picker is not defined

Expression: "wireui_color_picker({
    colorNameAsValue: true,

            wireModifiers: JSON.parse(atob('eyJkZWZlciI6ZmFsc2UsImxhenkiOmZhbHNlLCJkZWJvdW5jZSI6eyJleGlzdHMiOmZhbHNlLCJkZWxheSI6Ijc1MCJ9fQ==')),
        wireModel: window.Livewire.find('XoEI3y7WtArh0z7keyLP').entangle('config.brand_color'),
    
    })"
```

**To Reproduce**
1. installed the wireui
2. add the <wireui:scripts /> before alpine in the head
3. updated tailwind.config.js as in the installation page
4. the packages are bundled via vitejs

**Expected behavior**
to works with out error and fullfill the request

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Dependencies**
 - WireUI Version: 1.17
 - Laravel Version: 9.19
 - Alpine.js Version: 3.0.6
 - Livewire Version: 2.5
 - vite:3.0
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: [IOS]

**Additional context**

**Comment by mahdi-akbary** [comment]
found out that the problem was with CORS so I will close it

**Comment by LuanHimmlisch** [comment]
@mahdi-akbary give a solution instead of just closing the issue
