### ISSUE TITLE
Unable to change text size

### ISSUE THREAD

**Issue by zxtanzxzx** [PH7-Jack/livewire-ui#603]
**Describe the bug**
I am trying to change the font size by applying _**text-6xl**_ tailwind class to a text input.  But its not working. 
But adding tailwind class like _**bg-black**_ or _**text-white**_

**To Reproduce**
1. Add a new WireUI input component
2. Add the class attribute to the component

**Expected behavior**
The text font size should change

**Screenshots or Videos**
My Button is using the tailwind class _**text-6xl**_ and it applied. While WireUI input did not have the changes applied.
![image](https://user-images.githubusercontent.com/12552846/213143600-7bc23929-572a-4bae-8e3b-aea31cbfca1e.png)

**Dependencies**
 - WireUI Version: 1.17
 - Laravel Version: 9.46.0
 - Alpine.js Version: 3.10.5
 - Livewire Version: 2.10.8
 - Tailwind Version: 3.2.4
 - Lang: en_US

**Additional context**
n/a

n/a

**Comment by zxtanzxzx** [comment]
After some more play around, my browser was detected as sm: . After adding sm: to the class that i added in wireui input. the text -6xl tailwind class applied.

**Comment by joaopalopes24** [comment]
I just performed the test and it works normally. Thanks in advance for using the package.

```
<x-button class="text-6xl">
    Text
</x-button>
```
