### ISSUE TITLE
I can't select time when change $datetime ! (Datetime Picker)

### ISSUE THREAD

**Issue by ramma-stack** [PH7-Jack/livewire-ui#606]
<h4>Describe Bug</h4>
This happens when I replace the <strong>$datetime</strong> in the controller with an event,</br>
I've tried all the ways, especially changing the date format.</br>
When I change <strong>$datetime</strong> like this the time setting container disappears!</br>
No problem with setting a date, just a problem with time!</br>
</br></br>

<p dir="auto"><strong>Screenshots</strong></p>
<ol>
<li>
<strong>It goes like this</strong><br>
<img src="https://user-images.githubusercontent.com/93214999/215497473-058f000a-8ca3-497c-84f5-865d6e3a9e5b.png" alt="" width="400px">
</li>
<br>
<li>
<strong>It gives an error when I type</strong><br>
<img src="https://user-images.githubusercontent.com/93214999/215497522-21bdab39-60eb-4689-9134-2ce603423518.png" alt="" width="400px"><br>
<img src="https://user-images.githubusercontent.com/93214999/215497534-6f1657f3-0f56-45b7-ad1d-c536f3cf55da.png" alt="" width="1000px">
</li>
</ol>

<br>
<p dir="auto"><strong>Dependencies</strong></p>
<ul dir="auto">
<li>WireUI Version: 1.17</li>
<li>Laravel Version: 9.19</li>
<li>Alpine.js Version: 3.10.4</li>
<li>Livewire Version: 2.10</li>
<li>Lang: en_US</li>
</ul>

**Comment by ph7jack** [comment]
Hello @ramma-stack, I apologize, but we no longer support v1 of wireui. Please consider upgrading to v2.
