### ISSUE TITLE
Date time picker at top of modal is not useable as renders above the field and picker is hidden 

### ISSUE THREAD

**Issue by craigvc** [PH7-Jack/livewire-ui#608]
We added the datetime picker component as the first field in a modal, the picker renders above the field - so its not useable - how can we render it underneath?

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
