### ISSUE TITLE
Documentation fix

### ISSUE THREAD

**Issue by pablozagni** [PH7-Jack/livewire-ui#609]
Publishing documentation says:

php artisan vendor:publish --tag='wireui.config'
php artisan vendor:publish --tag='wireui.resources'
php artisan vendor:publish --tag='wireui.lang'

And the correct sintax is:
php artisan vendor:publish --tag=wireui.config
php artisan vendor:publish --tag=wireui.resources
php artisan vendor:publish --tag=wireui.lang

(Without cuotes)

Sorry to report this here, tell me please if I'm wrong.
Thanks

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

This feature was added in stable version 2. Check our documentation at: https://wireui.dev.
