### ISSUE TITLE
Required option for input component

### ISSUE THREAD

**Issue by blockhunts** [PH7-Jack/livewire-ui#610]
**Is your feature request related to a problem? Please describe.**
Some of my input field is mandatory, thus I want to let know the users, which input is mandatory by some mark such as * or words

**Describe the solution you'd like**
A setting similar like placeholder command where we can type the desired string
Ex: required="*"
Ex: required="Mandatory"

**Additional context**
Not only input, but it's derivate component (date picker) (drop down) would benefit from this improvement

**Comment by abbasmashaddy72** [comment]
Currently, is there any alternative for that until feature is released

such as CSS @PH7-Jack @blockhunts

**Comment by blockhunts** [comment]
Currently all you can do is to edit the input component to add new parameter for required.

Note: If you updated the package, your custom component will be resetted to the new default.

**Comment by abbasmashaddy72** [comment]
Thanks

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
