### ISSUE TITLE
Monitorar modal

### ISSUE THREAD

**Issue by felipemartinspro** [PH7-Jack/livewire-ui#611]
Olá.
Primeiramente parabéns por essa criação de vocês. Gostaria de saber como faço para monitorar via Javascript se o modal da WireUI foi fechado, no caso de um usuário clicar fora do modal.
Na documentação da exemplo apenas de como abrir.
Muito obrigado desde já! ;)

**Comment by joaopalopes24** [comment]
Na versão 1 você pode os eventos do Modal.

Veja a documentação [aqui](https://v1.wireui.dev/docs/modal#modal-events).
