### ISSUE TITLE
select is not displaying the selected item properly

### ISSUE THREAD

**Issue by muhammadessam** [PH7-Jack/livewire-ui#612]
The select is not showing which item is selected with the right mark over the left of the selected item: 
```
               <x-select class="my-1" 
                          label="Search Specialization"
                          wire:model.defer="user.specialization_id"
                          placeholder="{{trans('Select Specialization')}}"
                          option-value="id"
                          :searchable="true"
                          :min-items-for-search="1"
                          option-label="title"
                          :options="\App\Models\Specialization::main()->get()">
                </x-select>
                <x-select label="Search Specialization"
                          :searchable="true"
                          :min-items-for-search="1"
                          wire:model.defer="role_id"
                          placeholder="{{trans('Select Role')}}" option-value="id"
                          option-label="name" :options="\Spatie\Permission\Models\Role::all()">
                </x-select>
```

the selected item doesn't show up as selected
![image](https://user-images.githubusercontent.com/14132452/217005810-3fe7acaf-ee4d-4a29-bae9-cd83bac68f7d.png)

**Comment by Kenny1291** [comment]
I am experiencing the same issue.

```
<x-select
  label="Assign to"
  placeholder="Select users"
  wire:model.defer="usersToAssign"
  multiselect
  :options="$this->users"
  option-label="name"
  option-value="id"
/>
```
![image](https://user-images.githubusercontent.com/53661492/222508328-99a3d2db-9f66-4b63-8918-022ffbb9f931.png)
![image](https://user-images.githubusercontent.com/53661492/222508466-1c080862-2598-418a-aa1e-c40f3193b5d8.png)

**Comment by 1andy11** [comment]
I have the same problem and found out that there is wrong order of calling functions in init function.
Function initOptionsObserver is calling before initWireModel. this.selected is initialized in initWireModel but is used in syncSelectedOptions which is called from initOptionsObserver so this.selected is not initialized yet.

**Comment by henk-hypershop** [comment]
Any update on this?

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
