### ISSUE TITLE
Bug in 'yesterday' 'today' button in datepicker component

### ISSUE THREAD

**Issue by blockhunts** [PH7-Jack/livewire-ui#614]
**Describe the bug**
:min date is tomorrow, but upper button (yesterday, today) will make current day and yesterday possible to pick

**To Reproduce**
1. Declare :min="now()->addDays(1)"
2. Click either 'yesterday' or 'today' button
3. See error

**Expected behavior**
Yesterday, and today button cannot be clicked, when it's not within date range

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/38546608/217146254-5648de49-5328-427c-8258-a39193ef2c8b.png)

**Dependencies**
 - WireUI Version: 1.17
 - Laravel Version: 9.19
 - Alpine.js Version: 3.0.6
 - Livewire Version: 2.5
 - Lang: JP

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
