### ISSUE TITLE
custom bg class didn't overwrite select component disabled bg class

### ISSUE THREAD

**Issue by blockhunts** [PH7-Jack/livewire-ui#616]
**Is your feature request related to a problem? Please describe.**
I want a darker background when the select component is disabled, currently it is not

**Describe the solution you'd like**
Customizable class for select component

**Describe alternatives you've considered**
A darker background for disabled state

**Additional context**
I want select component to be similar to datepicker component, where it's background color could be customized.

![image](https://user-images.githubusercontent.com/38546608/217746211-daab47c8-9fca-480d-9c1a-b8676e14075e.png)
![image](https://user-images.githubusercontent.com/38546608/217746238-de52c082-a160-4cc7-87a3-ddc322d1e71a.png)

![image](https://user-images.githubusercontent.com/38546608/217746283-ee0ebbf1-e433-4b37-a8a9-8875914376a7.png)

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
