### ISSUE TITLE
Livewire property cannot be found when using Select Form Component with array model name

### ISSUE THREAD

**Issue by achmedislamic** [PH7-Jack/livewire-ui#618]
**Describe the bug**
When using Select Form Component with array model name, an error occurred with message: 
`Livewire Entangle Error: Livewire property 'model.0' cannot be found`

This is only trigger when using Select Form Component, other component like input, textarea, and native select works fine

**To Reproduce**
1. Use Select Form Component. Don't forget to declare public property with the model name in Livewire class component.
2. Give the model name like "model.0", "model.1" etc
3. Go to console tab in the browser
4. Error will be displayed

**Expected behavior**
It should not thrown an error when using model name like this. I currently have dynamic form when user can input multiple Select. I can't use multiselect attribute in select form component because other input must be filled.

**Screenshots or Videos**
![wireui-bug](https://user-images.githubusercontent.com/25688207/218354025-830a9fc3-ab97-4b69-8217-7cc4674910d0.jpg)

**Dependencies**
 - WireUI Version: 1.17.9
 - Laravel Version: 9.51.0
 - Alpine.js Version: 3.11.1
 - Livewire Version: 2.11.2
 - Lang: en_US

_Sorry for my bad english_

**Comment by codenashwan** [comment]
Same issue 

https://user-images.githubusercontent.com/35005761/219935992-5ee6d64d-8324-4832-92a9-66b5e07fd18f.mp4

**Comment by joaopalopes24** [comment]
@achmedislamic This is not a bug, but a limitation of Livewire Entangle (check the Livewire documentation). You initialized the property with just an empty array.

See this issue: https://github.com/wireui/wireui/issues/513
