### ISSUE TITLE
Select automatic closing/toggle

### ISSUE THREAD

**Issue by Epitaffio** [PH7-Jack/livewire-ui#622]
**Describe the bug**
Sometimes after opening a select component, the component auto close itself. 
I have not published the resources files and I have already tried to clear the view/browser cache or update the dependencies.

Maybe linked with those other issues:
#572 
#416 

Video of the issue:
https://drive.google.com/file/d/1N_3RhQpKckC7EPqLn2TmMZXKY5QGR-Vr/view?usp=share_link

Code for the component used:

```
    <x-select
        placeholder="Cambia Azienda"
        wire:model="selectedCustomer"
        min-items-for-search="5"
        :clearable="false"
        class="mt-3"
        x-on:open="console.log('opened '+Date.now())"
        x-on:close="console.log('closed '+Date.now())"
        :options="[
            ['label' => 'test1', 'value' => 'test1'],
            ['label' => 'test2', 'value' => 'test2'],
            ['label' => 'test3', 'value' => 'test3'],
        ]"
        option-label="label"
        option-value="value"
    />
```

**Dependencies**
 - WireUI Version: 1.17.9
 - Laravel Version: 9.50.1
 - Alpine.js Version: 3.11.1
 - Livewire Version: 2.11.2
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: Win 11
 - Browser: Firefox
 - Version 109.0.1

Thanks in advance!

**Comment by Epitaffio** [comment]
Some updates after some tinkering:

If you comment out 

https://github.com/wireui/wireui/blob/main/resources/views/components/select.blade.php#L47

the component work as expected (without the focus functionality, of course).

It's seems like there is some issue with the position of the input with the x-* functionalities because the problem is arising when you click on the icon that share the same level with the input in the DOM.

Maybe an easy fix would we to move the x-* functions one level above?


BTW for now I was wondering if I can publish the views for only the select component and comment out this line, but when I launch the command to publish I get this:

   INFO  No publishable resources for tag ['wireui.resources'].

**Comment by Epitaffio** [comment]
Some updates after some days of tinkering.

My issue seems related to this:
https://github.com/livewire/livewire/issues/763

I haven't pinned out the exact point but I think the problem is with the use of conditions in my blade file and the rerender of livewire.
The click event handler is attacched two (or even more) times to the alpine component, so the select/dropdown effectively open and close when you click on it.

When I create a simple livewire component with no condition and I fire a rerender (like a pagination) the select component works as expected.


At this point I really don't know if the problem is in Livewire or in Alpine/diff dom or even if WireUi can do anything in this regards.

I will leave this issue open for now if anyone stumble in this. But feel free to close it if necessary.

**Comment by kennyelliott** [comment]
I too am running up against this but have not found a solution yet.

**Comment by themightysapien** [comment]
For me the issue was i was adding alpine js twice. I was using wireui with jetstream. Added wireui script along with alpine as shown in the docs but jetstream already includes alpine in their build. 
After removing it, worked flawlessly.

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
