### ISSUE TITLE
Wireui components collide with anonymous breeze components

### ISSUE THREAD

**Issue by bcbud** [PH7-Jack/livewire-ui#626]
**Describe the bug**
Breeze components have overlapping names as wireui components.  Anonymous components load after wireui components.  Causes breeze forms to stop working in default blade templates - labels disappear and submit buttons no longer fire.

**Expected behavior**
Anonymous components would override wireui (or be configurable ordering).

**Solution**
Publish the config/wireui.php file and prefix all aliases with a unique identifier (I just added wireui-* to all aliases and ).

(feel free to close, but just wanted to leave it here to help save the time of anyone trying to debug why their breeze auth scaffolding stopped working after installing wireui)

**Comment by Aaron1178** [comment]
@bcbud Thanks for this post, I just ran into the exact same issue. +1

**Comment by aaronjonesxyz** [comment]
I think this is what caused my Breeze profile dropdown to stop working, WireUI `<x-dropdown>` overrides the Blade version.
I've changed the aliases but it's still using the WireUI version, is there anything I need to do to load the new config?

**Comment by Mohsin1931** [comment]
i am facing same issue with jetstream components . did you find any solution for this??

**Comment by joaopalopes24** [comment]
Good morning. This isn't a bug, just a component conflitct. You can change the component alias in wireui config and clean the cache, or you can use the WireUi Components in Breeze, which is what I usually do.
