### ISSUE TITLE
Select async data break the request of component route with parameter

### ISSUE THREAD

**Issue by ghost** [PH7-Jack/livewire-ui#629]
my component render on all page with a route like  /route/{parameterID}

the select component render a list of users

`                                    <x-select
                                        label="Bombero"
                                        placeholder="Escribe para buscar mas bomberos"
                                        wire:model="userId"
                                        wire:change.debounce.400ms="getInscriptos"
                                        :async-data="[
                                          'api' => route('search.users', ['zona' => $curso->inscripcion_zonas()->get()->pluck('cuartel_id')->toArray()]),
                                          'params' => [$this->curso->id],
                                          'credentials' => 'include'
                                        ]"
                                        :template="[
                                            'name'   => 'user-option',
                                            'config' => ['src' => 'profile_image']
                                        ]"
                                        option-label="nombre_completo"
                                        option-value="id">
                                    </x-select>`

when I clicked the select to load the info, the main component render again but in the route "/route/{parameterID}" the parameter set with and undefined. 

I cant fix it issue.

Thanks!

**Comment by Uhasith** [comment]
Did you find a solution mate? I'm also having some serious issues with select fields

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
