### ISSUE TITLE
Specifying selected items

### ISSUE THREAD

**Issue by Kashorako** [PH7-Jack/livewire-ui#637]
Hi friend, i can't find a way to specify wether an item is selected or unselected using async_data,

For example i have a function that returns an array with values ['id', 'field1', 'field2']

But how can i specify that field1 is selected and in the other hand: id and field2 are not selected?

**Comment by Kashorako** [comment]
I can't make it to work.

I want to load some data via the async method of the selectes, and specify which one should be selected 

Just the way you did in the examples, but the info is not very clear, i'm sending the "selected" inside my $request, but it's not working
![image](https://user-images.githubusercontent.com/70036607/228342706-8cfaddd2-9704-4b2c-8ba0-f904e252d243.png)

**Comment by sJonatas** [comment]
Hey mate :D 
if you bind it to your component it should work 

`class ComponentForm extends Compoenent`
`{`
`    public $value = 0; // if you want it auto filled just set your id or instantiate it on yout mount method`
`    // -- other stubs`
`}`

them on your blade

`<x-select` 
`    label="Select an option"`
`    wire:model='value''`
`    :options=['id', 'field1', 'field2']`
`    value='$value'`
`/>`

**Comment by Kashorako** [comment]
Hi @sJonatas, the mistake was mine. The auto filled or auto select was not working in asyc-data because i was not using the $request->selected, that's why every time i was using the async method the selected value was always empty. (i also  was generating the select's options using a JSON column type)

Thanks!

**Comment by rabol** [comment]
@sJonatas 

```
<x-select
                label="Select country"
                placeholder="Select country"
                :options="\App\Models\Country::query()->select('id', 'name')->get()->toArray()"
                wire:model="companyCountry"
                option-label="name"
                option-value="id"
                value="$companyCountry"
            />
```
```$companyCountry``` do have a value

even if I hard code e.g. 2, there is nothing selected
