### ISSUE TITLE
Disabling and enabling the number input field leaves the "+" and "-" buttons disabled.

### ISSUE THREAD

**Issue by tariktokic** [PH7-Jack/livewire-ui#639]
**Describe the bug**
When using the `<x-inputs.number label="How many Burgers?" :disabled=$initDisabled />` type of inputs and setting the `$initDisabled` later to false, leaves the"+" and "-" buttons on both sides of the still disabled.

**To Reproduce**
1. Create the `<x-inputs.number label="How many Burgers?" :disabled=$initDisabled />` 
2. Set `:disabled=$initDisabled` later to false
3. Try to use the "+" and "-" buttons

**Expected behavior**
"+" and "-" should be enabled and clickable.

**Dependencies**
 - WireUI Version: 1.17.X
 - Laravel Version: 10.X.X
 - Alpine.js Version: 3.X.X
 - Livewire Version: 2.X.X

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
