### ISSUE TITLE
Using tab from input to next select allows typing in the select box

### ISSUE THREAD

**Issue by markgoedegebure** [PH7-Jack/livewire-ui#643]
**Describe the bug**
When i tab from a input field to the next select dropdown, the underlaying input field is focussed. I can enter any text, but is's not visible. After i tab again from the input to the select, the previously entered text is highlighted, but nog editable (see screenshot).

**To Reproduce**
1. add a x-input and x-select 
2. focus the input and enter some text. Hit tab to focus the select. type some random text
3. focus the input again and hit tab again
4. The previously enteren text in the select is highlighted

**Expected behavior**
focus on the select after tab, but not highlighted text is cant see

**Screenshots or Videos**
![afbeelding](https://user-images.githubusercontent.com/44771394/231784725-4d56cdd3-d1a8-4522-bb4d-ea727b77f546.png)

**Dependencies**
 - WireUI Version: 1.17.9
 - Laravel Version: 9.52.5
 - Alpine.js Version: 3.10.2
 - Livewire Version: 2.12.3
 - Lang: nl_NL

**Desktop (If applicable, please complete the following information):**
 - OS: windows
 - Browser: all browsers

**Additional context**

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
