### ISSUE TITLE
input is not defined  / wireui_inputs_maskable is not defined 

### ISSUE THREAD

**Issue by MCKLtech** [PH7-Jack/livewire-ui#646]
**Describe the bug**
When using maskable fields, a _wireui_inputs_maskable is not defined_ error is thrown by Alpine.

**To Reproduce**
1. Following code snippet:

```
<x-inputs.phone wire:model.defer="state.{{$key}}" wire:key="{{$key}}" mask="['(###) ####-####']"/>
```

2. Error is also visible on the doc pages: https://livewire-wireui.com/docs/phone-input

**Additional context**
Livewire and Alpine are fully updated, in addition to scripts and Tailwind configuration.

**Comment by MCKLtech** [comment]
Any update on this? Going by the doc pages this seems to be a widespread bug which makes the library basically unusable.

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
