### ISSUE TITLE
Floating Datetimepicker 

### ISSUE THREAD

**Issue by GBry** [PH7-Jack/livewire-ui#647]
In my project, the datetimepicker is inside a table's <td>, which is constrained in size. So, when I click on the datetime picker, it gets cut off.

I'd like it to be floating so that even though the space to select is small, the datepicker still shows in full.

**Comment by joaopalopes24** [comment]
Our components are floating, but your CSS might be clipping the popover:

Example: In my project, I was using the select with the parent `div` using `overflow-hidden`.

![image](https://github.com/wireui/wireui/assets/45684782/20e772a3-aab4-46ae-b690-9a14b894c36e)

If I remove `overflow-hidden`, the select work normally.

![image](https://github.com/wireui/wireui/assets/45684782/3774122d-34d2-40c4-8609-6a101096c1c4)

**Comment by joaopalopes24** [comment]
I know the it is error in your CSS. Thanks by use our package.

**Comment by andrecolza** [comment]
@joaopalopes24 I have the same need as @GBry : I have to insert a datepicker inside a `table` with the parent `div` using `overflow-auto`, so obviously the datetime picker is cut.
I tried to modify the popover blade component to move it elsewhere (in the body) using the `@teleport` directive: in this way the datetime picker appears intact but not positioned correctly, do you have any suggestions on how I can do it?
