### ISSUE TITLE
Can we have dark/light mode in our website?

### ISSUE THREAD

**Issue by aliqasemzadeh** [PH7-Jack/livewire-ui#648]
Can we have dark/light mode in our website?

**Comment by joaopalopes24** [comment]
@aliqasemzadeh All WireUI components have dark/light configuration. Just add the functionality to your site and the components work normally.

Thank you.

**Comment by spooksie** [comment]
Any pointers on how this can be done?

**Comment by joaopalopes24** [comment]
@spooksie Check the tailwind documentation.

https://tailwindcss.com/docs/dark-mode
