### ISSUE TITLE
Checkbox ID should be required

### ISSUE THREAD

**Issue by nicolaeFxBits** [PH7-Jack/livewire-ui#650]
Hi all. Today I faced a issue with multiple checkboxes on the same page (Permissions) and clicking on the label it was selected/deselected only first checkbox. Then I realised that all labels have `for="<FIRST ID>"`.
After setting `ID` for each `<x-checkbox>` everything is fine. 

I think `id` should be required to avoid this kind of issues.

**Comment by joaopalopes24** [comment]
Good morning. It will not be a good practice to require the ID, in these cases the correct thing is to set an ID for each checkbox.
