### ISSUE TITLE
livewire-wireui.com has expired

### ISSUE THREAD

**Issue by anhofmann** [PH7-Jack/livewire-ui#660]
**Describe the bug**
Visiting livewire-ui.com leads to this message by cloudflare:

livewire-wireui.com has expired.
If you are the owner, log in to Cloudflare for domain renewal options.

**To Reproduce**
1. Go to https://livewire-wireui.com
2. See error

**Comment by ph7jack** [comment]
It's now fixed. Thanks a lot for reporting.
You can access the website through an incognito window until the DNS is not refreshed.
