### ISSUE TITLE
Jetstream default button not working when run php artisan optimize:clear

### ISSUE THREAD

**Issue by madushancs** [PH7-Jack/livewire-ui#663]
**Describe the bug**
I just installed a fresh Laravel application and installed Jetstream & livewire. But once installed WireUi & run php artisan optimize:clear command, the Jetstream default button not working and the default theme little bit changed. Please find the attached pictures in below. I have marked in red color not working button. In the web browser console there are no any error messages 

**Dependencies**
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/jetstream": "^3.2",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "livewire/livewire": "^2.11",
        "wireui/wireui": "^1.17"

**Desktop**
 - OS: Win 11
 - Browser: Chrome, Brave 

**Screenshots or Videos**
![image](https://github.com/wireui/wireui/assets/45415384/a12882ab-fbb4-4dac-bca3-1ff62b530671)
![image](https://github.com/wireui/wireui/assets/45415384/dd365164-ec6c-41f4-8cd1-ae4e5d891e06)
![image](https://github.com/wireui/wireui/assets/45415384/a1b7d583-8387-4b5b-95c9-35707675b28c)

**Note**
In my Laravel 9 projects, I did not face this kind of any issue with Wire UI. Great package and helped a lot. Thank you

**Comment by joaopalopes24** [comment]
Good morning. This is not a problem, but a conflict as both WireUI and Jetstream have a component with the same name `x-button`.

**Comment by madushancs** [comment]
hi. Thank you. Would you happen to have a good solution for fixing this issue? I tried to change component names and It was a little bit difficult for me.

**Comment by joaopalopes24** [comment]
I would recommend passing all JetStream components to use the WireUI one.

**Comment by AnassGBNL** [comment]
I have the same issue, even passing jetstream components as wireui ones doenst work. is it not posible to change the prefix somewere in the config?

**Comment by Mohsin1931** [comment]
just change the component alias in the wire.php file and use it instead of x-[component] for wire ui components
then publish your wireui components and remove path from tailwind.config file 
![image](https://github.com/wireui/wireui/assets/77459858/cb2204ad-1da0-4747-8431-7d64fd2e3847)

**Comment by Mohsin1931** [comment]
> I have the same issue, even passing jetstream components as wireui ones doenst work. is it not posible to change the prefix somewere in the config?

you can change the alias in wireui.php config file

**Comment by AnassGBNL** [comment]
> just change the component alias in the wire.php file and use it instead of x-[component] for wire ui components then publish your wireui components and remove path from tailwind.config file ![image](https://user-images.githubusercontent.com/77459858/241570311-cb2204ad-1da0-4747-8431-7d64fd2e3847.png)

@Mohsin1931 you are the best. Jazaak Allah ou Khairan
