### ISSUE TITLE
string with html entities as labels does not work

### ISSUE THREAD

**Issue by rabol** [PH7-Jack/livewire-ui#664]
**Describe the bug**
When working with multi language web sites I use __('') to do translation of texts.

In the french language there is a lot of apostrophes accents etc. like this:

```
Créer un ticket d'assistance
```

and if one uses html entities to display strings

```
"Create support ticket": "Créer un ticket d&#39;assistance",

```

them the label / slot does not look correct.

![Screenshot 2023-05-21 at 12 36 07](https://github.com/wireui/wireui/assets/1177191/ea151c60-ec49-4ae7-9261-c5bdd17386e4)

**To Reproduce**
1.  create a button like this ```<x-button primary type="submit" >{{ __("Create support ticket") }} </x-button>```
2.  have a translation file e.g. /lang/fr.json with this entry ```"Create support ticket": "Créer un ticket d&#39;assistance",```
3. render

**Expected behavior**
That the label is correct.

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Dependencies**
 - WireUI Version: 1.17.9
 - Laravel Version: 10.11.0
 - Alpine.js Version: 3.12.1
 - Livewire Version: 2.12.3
 - Lang:  ca, da, de, en, es, fr, lt

**Comment by rabol** [comment]
I most have been sleeping.... second time I tried it worked - sorry

**Comment by rabol** [comment]
```
<x-select
            label="{!! __('Select subscription') !!}"
            :options="$subscriptions"
            option-value="id"
            option-label="name"
            placeholder="Select subscription"
            wire:model="selectedSubscription"
            id="subscriptions"
        />
        ```
this does not work

**Comment by joaopalopes24** [comment]
Good morning. I tested it locally and it worked normally. Thank you very much in advance.

**Comment by rabol** [comment]
Not sure why you close this issue

How did you test ?


```<x-button label="Créer un ticket d&#39;assistance" />```

will give you a button like this:

![Screenshot 2023-05-22 at 14 41 45](https://github.com/wireui/wireui/assets/1177191/bf41142e-2b56-4443-9b49-892d62140dd8)

but this write the text correct

```<span>Créer un ticket d&#39;assistance</span>```

![Screenshot 2023-05-22 at 14 43 21](https://github.com/wireui/wireui/assets/1177191/3cf3f3e8-ba58-407b-a158-670b4acf1352)

**Comment by joaopalopes24** [comment]
This is not a bug in WireUI. Try rendering this directly on your blade and see what the result is.

`{{ 'Créer un ticket d&#39;assistance' }}`

**Comment by joaopalopes24** [comment]
You are not handling HTML.

**Comment by rabol** [comment]
this works: html button

```
<button class="border border-gray-500 p-4">{{__('Create support ticket')}}</button>
```

this does not: wireui button
```
<x-button label="{{__('Create support ticket')}}" />

```

![Screenshot 2023-05-22 at 14 50 51](https://github.com/wireui/wireui/assets/1177191/e5ddbe6f-164e-4fc0-9045-e5dfe25838ca)

**Comment by joaopalopes24** [comment]
This isn't work:

`<button class="border border-gray-500 p-4">{{ __('Create support ticket') }}</button>`

Bus this is work:

`<button class="border border-gray-500 p-4">{!! __('Create support ticket') !!}</button>`

**Comment by joaopalopes24** [comment]
Via label it is just treated as string, not as HTML. This is a limitation of Components within Laravel.

**Comment by rabol** [comment]
for the future:

````

<div class="grid grid-cols-1">
    <div class="mt-2">
        <x-button red label="{!! __('Create support ticket')!!}" />
    </div>
    <div class="mt-2">
        <x-button red >{{ __('Create support ticket') }}</x-button>
    </div>
    <div class="mt-2">
        <x-button green>{!! __('Create support ticket') !!}</x-button>
    </div>
    
    <div class="mt-2">
        <button class="bg-green-500 border border-gray-500 p-4">{!! __('Create support ticket') !!}</button>
    </div>
    <div class="mt-2">
        <x-test class="bg-green-500" label="{{ __('Create support ticket') }}" />
    </div>
    <div class="mt-2">
        <x-test class="bg-green-500" >{!! __('Create support ticket') !!}</x-test>
    </div>
</div>

````

and the component that can handle html

```
@props(['label'])
<div  {{ $attributes->merge(['class' => '']) }}>
    @if(isset($label))
        {!! html_entity_decode($label) !!}
    @else
        {{ $slot }}
    @endif
</div>
```

and the fr.json

```
{
    "Create support ticket": "Créer un ticket d&#39;assistance"
}
```

the result:
![Screenshot 2023-05-22 at 15 59 50](https://github.com/wireui/wireui/assets/1177191/d4b5c95c-0d77-4e48-8da7-f358fc90b979)

**Comment by joaopalopes24** [comment]
One way is decoding to HTML, but this can be done before assigning to the label.
