### ISSUE TITLE
WireUI scripts error 500

### ISSUE THREAD

**Issue by caromatias** [PH7-Jack/livewire-ui#670]
**Describe the bug**
The wireui scripts.js file is causing a 500 error on the server, but it works fine locally.
I have already updated the URL in the .env file, and I also ran optimize:clear, but it still doesn't work.

**To Reproduce**
1. Upload project to server ubuntu.
2. Visit site
3. When the scripts.js file breaks, none of the wireui components work.

**Screenshots or Videos**
![image](https://github.com/wireui/wireui/assets/5713047/bb1bddd5-3d09-410a-918c-7ffa1822835f)

**Dependencies**
 - WireUI Version: 1.17
 - Laravel Version: 9.19
 - Alpine.js Version: 3.10.2
 - Livewire Version: 2.12
 - Lang: es_CL

**Desktop:**
 - OS: OSX, Windows
 - Browser: Chrome, Edge, Safari

Please Help.

**Comment by joaopalopes24** [comment]
@caromatias I use WireUi in my projects with no error. Do you put the APP_URL in the .env with or without https? How is your layout file?

![image](https://github.com/wireui/wireui/assets/45684782/3affbc61-b53d-46de-b2ab-493e501a5736)

**Comment by rabol** [comment]
I just started to see some errors as well in production environment 
like:
````
GET https://xx.xx.xx.xx/wireui/assets/scripts?id=3c15fb3b36f54e2baae1e97b6eb0015e net::ERR_CERT_COMMON_NAME_INVALID
```

**Comment by Rosendito** [comment]
@caromatias I had this problem yesterday, reviewing the logs i realized that the error was my host did not have `ignore_user_abort` enabled. Another functions that should be enabled are `proc_open` and `proc_close`

**Comment by eduardogpg** [comment]
@Rosendito thanks a lot, you save my deploy.

**Comment by joaopalopes24** [comment]
Hey there, thanks for reporting this issue.

Here it is working normally.
