### ISSUE TITLE
Selecting date in <x-datetime-picker > does not call updated() in livewire component

### ISSUE THREAD

**Issue by rabol** [PH7-Jack/livewire-ui#671]
**Describe the bug**
<x-datetime-picker does not call the Livewire components updated() method.

**To Reproduce**
1. add <x-datetime-picker> to a component
2. select a date
3. Log::debug($propertyname) in updated() of the livewire component
4. Nothing will be logged

**Expected behavior**
That the updated() and the validateOnly is called correctly

**Screenshots or Videos**

**Dependencies**
 - WireUI Version: 1.17.9
 - Laravel Version: 10.2.0
 - Alpine.js Version: ^3.42.2
 - Livewire Version: 2.12.3
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: macOs
 - Browser: chrome]

**Additional context**

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
