### ISSUE TITLE
Error when running test for pull request 

### ISSUE THREAD

**Issue by namumakwembo** [PH7-Jack/livewire-ui#673]
**Describe the bug**
i forked the wireui repo in order to add some features  , but I get an error when running tests locally , I also got error  when I tried to 
create a pull request after making some changed , can you please help me understand where I am getting it wrong ?

**To Reproduce**
1. run `./vendor/bin/pest`

**Expected behavior**
 on the browser test 'MinMaxLimits/Test.php:25' I get the the following error `Failed asserting that true matches expected false.`

**Screenshots or Videos**
 `
<img width="832" alt="Screen Shot 2023-06-04 at 09 16 39" src="https://github.com/wireui/wireui/assets/77463693/a297f66d-5a5e-477f-81cc-e8f447e5d5ef">

    From tests/Browser/DatetimePicker/MinMaxLimits/Test.php:25:
        23:                 ->click('[name="model"]')
        24:                 ->tap(fn () => $browser->assertScript(<<<EOT
      > 25:                     [...document.querySelectorAll('.picker-days button')]
        26:                         .find(day => day.innerText == {$day})
        27:                         .hasAttribute('disabled')

    JavaScript expression [return     [...document.querySelectorAll('.picker-days button')]
            .find(day => day.innerText == 8)
            .hasAttribute('disabled')] mismatched.
    Failed asserting that true matches expected false.
`

**Dependencies**
 - WireUI Version: 1.X.X
 - Laravel Version: 9.X.X
 - Alpine.js Version: 3.X.X
 - Livewire Version: 2.X.X
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - Browser: [e.g. chrome, safari]

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
