### ISSUE TITLE
Documentation fix : get-started with Laravel 10 (jetstream / livewire)

### ISSUE THREAD

**Issue by Cyrille37** [PH7-Jack/livewire-ui#676]
Hello
Thanks a lot for this really great awesome package <3

The documentation [Get Started section](https://livewire-wireui.com/docs/get-started) talk about stuff that are not in the Laravel 10  jetstream/livewire default project.

There is no `<script src="//unpkg.com/alpinejs" defer></script>` but `@vite(['resources/css/app.css', 'resources/js/app.js'])` (and `import Alpine from 'alpinejs';` in `resources/js/app.js`).

Thanks and cheers :-)

**Comment by Cyrille37** [comment]
Seems to not be the documentation only ...

see
- #663 
- #667

**Comment by Cyrille37** [comment]
After some tries I can reproduce a functional sequence to avoid conflict with Jetstream:

Require package and publish config
```
./sail composer require wireui/wireui
./sail artisan vendor:publish --tag='wireui.config'
```

Change button alias in `config/wireui.php`
```
        'button' => [
            'class' => Components\Button::class,
            'alias' => 'button.ui',
        ],
```

Add scripts in `resources/views/layout/app.blade.php`
```
  <!-- Scripts -->
  @wireUiScripts
  @vite(['resources/css/app.css', 'resources/js/app.js'])
```

Add styles as preset in `tailwind.config.js`
```
    presets: [
        require('./vendor/wireui/wireui/tailwind.config.js')
    ],
```

Then I can use the wireui button as `x-button-ui`
```
<x-button.ui wire:click="yeah" label="click me" primary spinner="yeah" />
```

You may replace many `alias` like `dropdown` that conflicts too ...

**Comment by joaopalopes24** [comment]
@Cyrille37 The way to import Alpine can be done both ways. Importing via CDN is not wrong, and the documentation shows the way to make WireUI work in a simple way, and not to adapt to other packages like Jetstream.

Thank you.

**Comment by geetpurwar** [comment]
@Cyrille37 Thats so much for the fix. Dropdown was conflicting and Jetstream profile was broken but renaming in config fixed that.

**Comment by madushancs** [comment]
> After some tries I can reproduce a functional sequence to avoid conflict with Jetstream:
> 
> Require package and publish config
> 
> ```
> ./sail composer require wireui/wireui
> ./sail artisan vendor:publish --tag='wireui.config'
> ```
> 
> Change button alias in `config/wireui.php`
> 
> ```
>         'button' => [
>             'class' => Components\Button::class,
>             'alias' => 'button.ui',
>         ],
> ```
> 
> Add scripts in `resources/views/layout/app.blade.php`
> 
> ```
>   
>   @wireUiScripts
>   @vite(['resources/css/app.css', 'resources/js/app.js'])
> ```
> 
> Add styles as preset in `tailwind.config.js`
> 
> ```
>     presets: [
>         require('./vendor/wireui/wireui/tailwind.config.js')
>     ],
> ```
> 
> Then I can use the wireui button as `x-button-ui`
> 
> ```
> <x-button.ui wire:click="yeah" label="click me" primary spinner="yeah" />
> ```
> 
> You may replace many `alias` like `dropdown` that conflicts too ...

Thank you so much. Very clear guide.
