### ISSUE TITLE
Select component duplicated options and weird behaviour with Powergrid Tables

### ISSUE THREAD

**Issue by maikezan** [PH7-Jack/livewire-ui#678]
**Describe the bug**
Select component gets duplicated options  alpine error arises  in console when used within Livewire Powergid tables as dynamic filter. We have opened a similiar issue in powergrid too since we are not sure where the problem is. We have tried every possible setup, went in debug mode but nothing worked. 
FIY: if you try to set only one dynamic filters it works correctly, but if you set the second dynamic filters you get the same errors.

**To Reproduce**
1. Create a powergrid table (we tested both on our project table and with the powergrid generated demo table) with  at least 2 filters set as dynamic with static array options as defined in the additional context below.
3. Select an option from a filter (it doesn't matter if the filter actually filters content correctly)
4. Remove the applied filter (the table should refresh)
5. The options are now duplicated (and also the select itself opens weirdly like it is coming from a corner of the screen...)

**Expected behavior**
I would expect options to not be duplicated.

**Screenshots or Videos**
This screenshot shows the filter applied and the console print of the values inside the <li> element in template
![image](https://github.com/wireui/wireui/assets/61838461/54c76912-cfd5-4639-ac12-e502eb0fff1a)

This other screenshot shows when I clear the above filter, look at the highlighted console.log result (almost every filter options looks duplicated):
![image](https://github.com/wireui/wireui/assets/61838461/8ff75ad9-29e7-4add-97e7-0dce1f70d5a2)

**Dependencies**
 - WireUI Version: 1.17.9
 - Laravel Version: 9.52.9
 - Alpine.js Version: 3.12.0
 - Livewire Version: 2.12.3
 - Powergrid: 4.8.0
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: Windows 10
 - Browser:  chrome v114.0.5735.110, firefox v114.0.1

**Additional context**
Filters to apply at the powergrid demo table:
```
public function filters(): array
    {
        return [
            Filter::inputText('name')
                ->operators(['contains']),
            //Filter::inputText('email'),
            Filter::dynamic('email', 'email')
                ->component('select')
                ->attributes([
                    'option-label'    => 'name',
                    'option-value'    => 'value',
                    'placeholder'     => 'Email',
                    'options'         => [
                        ['name' => 'esteban.schoen@example.org',  'value' => 'esteban.schoen@example.org'],
                        ['name' => 'wyman.effie@example.org',  'value' => 'wyman.effie@example.org'],
                        ['name' => 'emil.hansen@example.com',  'value' => 'emil.hansen@example.com'],
                    ],
                    'wire:model.lazy' => 'filters.select.email'
                ]),
            Filter::dynamic('laracon', 'laracon')
                ->component('select')
                ->attributes([
                    'option-label'    => 'name',
                    'option-value'    => 'value',
                    'placeholder'     => 'Laracon Visitor?',
                    'options'         => [
                        ['name' => 'Yes',  'value' => 'yes'],
                        ['name' => 'No',  'value' => 'no'],
                    ],
                   'wire:model.lazy' => 'filters.select.laracon'
                ]),
           /* Filter::boolean('laracon')
                ->label('Yes', 'No'),*/
        ];
    }
```

**Comment by maikezan** [comment]
Any chance to get feedback on this? 
For reference: we also have opened a request on Powergrid https://github.com/Power-Components/livewire-powergrid/issues/1024 and the issue is maybe better explained there with some additional info (issue arise when there are more than one filters present in the table).
They state there might be some issue with the component itself.

**Comment by luanfreitasdev** [comment]
I'm looking at this too

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
