### ISSUE TITLE
Select keeps refreshing on select without defer modifier

### ISSUE THREAD

**Issue by isaacdarcilla** [PH7-Jack/livewire-ui#681]
**Describe the bug**
Select keeps refreshing on select without defer modifier. I want to use `wire:model` only without the defer modifier.

**To Reproduce**
1. Use the `<x-select/>` component
2. Add `wire:model` without using defer

**Expected behavior**
Page should not refresh after selecting an option.

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Dependencies**
 - WireUI Version: 1.17.9
 - Laravel Version: 10.13.5
 - Alpine.js Version: 3.0.6
 - Livewire Version: 2.12.3
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Version: Latest

**Additional context**

> Component

![image](https://github.com/wireui/wireui/assets/22732118/5cfef56b-5374-4c39-8ad7-43226aba16f6)

> Class

![image](https://github.com/wireui/wireui/assets/22732118/9df2fddd-4b69-4fba-89c3-e7f9267725a0)

**Comment by isaacdarcilla** [comment]
Even the code below refreshes.

`x-on:selected="@this.region_code = 'Hello'"`

I need not to refresh the page because I have an address selection, so I want to update the selections base on the region/state.

I works on `<x-native-select>` but I want to use `<x-select>` for this feature

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
