### ISSUE TITLE
Wire:change doesnt work on the select input

### ISSUE THREAD

**Issue by skalero01** [PH7-Jack/livewire-ui#689]
**Describe the bug**
Whenever you try to use wire:change on the select input of wire ui it doesnt work. Example of code:

```
<x-select wire:model="example" :options="[0 => 'No', 1 => 'Yes']" wire:change="changeStatus()" option-key-value />
<select wire:model="example" wire:change="changeStatus()">
    <option value="1">Yes</option>
    <option value="0">No</option>
</select>
```

The wire ui component will no tringer the function, the second it will trigger. The function can just have a dd('Debug')

**To Reproduce**
1. Just copy the example besides on the view
2. Add example variable
3. Create a function called changeStatus() { dd('Access'); }

**Expected behavior**
Wire ui input should work exactly the same that the normal select behavior. Meaning that on both selects it should access to the changeStatus function on livewire

**Dependencies**
 - WireUI Version: 1.17.9
 - Laravel Version: 9.52.9
 - Alpine.js Version: 3.12.0
 - Livewire Version: 2.12.3
 - Lang: en_US

**Comment by mkts02** [comment]
no solution yet?

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
