### ISSUE TITLE
HTML escaped

### ISSUE THREAD

**Issue by CleversonTrevenzoli** [PH7-Jack/livewire-ui#696]
HTML escaped when use append and inputs.maskable

```
<x-inputs.maskable
    mask="#####-###"
    label="CEP"
    placeholder="_____-___"
    wire:model.defer="address.postcode" >
    <x-slot name="append">
        <div class="absolute inset-y-0 right-0 flex items-center p-0.5">
            <x-button
                class="h-full rounded-r-md"
                icon="search"
                primary
                flat
                squared
                wire:click="searchPostcode" />
        </div>
    </x-slot>
</x-inputs.maskable>
```

![wireui_bug](https://github.com/wireui/wireui/assets/93741557/cd90e9cb-5714-4203-883e-1abf04e36185)

**Dependencies**
 - WireUI Version: 1.17.9
 - Laravel Version: 10.14.1
 - Alpine.js Version: 3.12.3
 - Livewire Version: 2.12.3
 - Lang: pt_BR

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
