### ISSUE TITLE
Please support livewire v3

### ISSUE THREAD

**Issue by thienthanit04** [PH7-Jack/livewire-ui#701]
Livewire V3 have been released, So I'm appreciated if you guys should support V3 of livewire

**Comment by cheesegrits** [comment]
+1 for this, please.

**Comment by safwanAzman** [comment]
+1 for this, please.

**Comment by singlephon** [comment]
+1 for this, please.

**Comment by zeusmartinsoly** [comment]
+1 for this, please.

**Comment by ConfiaSouProfessor** [comment]
+1 for this, please.

**Comment by codenashwan** [comment]
+1 for this, please.

**Comment by madushancs** [comment]
+1 for this, please.

**Comment by madushancs** [comment]
Any updates

**Comment by josepueblaphcs** [comment]
+1 for this! :)

**Comment by mustaqim224** [comment]
+1 for this! :)

**Comment by C0chett0** [comment]
+1

**Comment by adetxt** [comment]
+1

**Comment by Umar-Farooq-Shafi** [comment]
+1

**Comment by kennyelliott** [comment]
+1

**Comment by cloudstudio** [comment]
Hello ! updates here? Is there a branch where we can all help? it would be interesting to update it @PH7-Jack

**Comment by PiahDoNeumann** [comment]
+1

**Comment by ph7jack** [comment]
Hi all, a branch was created a few weeks ago, but I'm still fixing some tests and components. This week we will have support for Livewire v3. Thanks for waiting

**Comment by madushancs** [comment]
Can't wait for the next release 🥰🥰

**Comment by rabol** [comment]
Any news on the update?

**Comment by zeusmartinsoly** [comment]
+1 for this, please.

**Comment by macorera** [comment]
+1 for this, please.

**Comment by isaacdarcilla** [comment]
+1. Any news about this?

**Comment by ph7jack** [comment]
Hi everyone!
Check out my comment [here](https://github.com/wireui/wireui/pull/710#issuecomment-1698459679) for more information.
A support branch was finished and is ready for testing

**Comment by ph7jack** [comment]
Hi everyone! It's now released. Check out this [release](https://github.com/wireui/wireui/releases/tag/v1.18.0)
