### ISSUE TITLE
Error of instalation with laravel 10 and Jetstream

### ISSUE THREAD

**Issue by Albert-Shelby97** [PH7-Jack/livewire-ui#708]
I just started a project with laravel 10 and jetstream v3, I installed wire ui but apparently the jetstream x-inputs stopped working, in the same way the x-button did not react and apparently they stopped being of type send

**Comment by joaopalopes24** [comment]
You can rename WireUI Components.

Look at this: https://github.com/wireui/wireui/issues/676
