### ISSUE TITLE
Multi-select rendering problems in Microsoft Edge

### ISSUE THREAD

**Issue by mostafa-rz** [PH7-Jack/livewire-ui#712]
**Describe the bug**
In the case that the options of a multi-select are too many, there are rendering problems in Microsoft Edge. For the same multi-select, I don't have any problem in Chrome and I expect to be the same in Edge. I attached a screenshot where you can see some of the options are not rendered however I scroll down and pass over them, but the options that are below them are already rendered.
There isn't any error in the console and it is just about rendering the templates.

**To Reproduce**
1. Make a multi-select with 600 options
2. Open the multi-select in Microsoft Edge and scroll down over the options or click the scroll bar to go somewhere in the middle of the list
3. The options are not rendered correctly(some of them rendered and some of them not)

**Expected behavior**
All the options must be rendered when scroll over them.

**Screenshots or Videos**

https://github.com/wireui/wireui/assets/71334549/b4796275-ed79-4054-b18c-64386c6c517b

![1](https://github.com/wireui/wireui/assets/71334549/b6e62c27-6879-4b00-be11-706da74274ce)

![2](https://github.com/wireui/wireui/assets/71334549/5a81ebf7-c191-4da9-add4-068f8983b694)

**Dependencies**
 - WireUI Version: 1.17.9
 - Laravel Version: 10.11.0
 - Alpine.js Version: 3.12.0
 - Livewire Version: 2.12.3
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version 116.0.1938.62 (Official build) (64-bit)

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
