### ISSUE TITLE
x-select use objects as value instead of id

### ISSUE THREAD

**Issue by KumaVolt** [PH7-Jack/livewire-ui#713]
Excuse me for my english in advance. 

**Is your feature request related to a problem? Please describe.**
I want to return an object as a value instead of an ID. However when doing so, the selection of x-select (with async-data) breaks as the input cannot compare the objects that are selected.

**Describe the solution you'd like**
I would like to have a callback option to manually handle the compare process, for example the Angular framework has the trackBy.

**Describe alternatives you've considered**
i have tried using id as value, however this does not fit our needs.

**Additional context**
Video of what happens when a refresh has occured, the selection is lost and the previous selection is ignored, which allows options the be reselected:
https://github.com/wireui/wireui/assets/15013036/6e00dd07-ba8e-448e-bd2f-e9ac662918f6

**Comment by mrqaidi** [comment]
@PH7-Jack  i need this future too . please add this

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
