### ISSUE TITLE
Composer update suport Livewire 3.

### ISSUE THREAD

**Issue by felipeArnold** [PH7-Jack/livewire-ui#718]
Good evening, everything okay?

When running composer update -W after updating livewire 3, it presents the following error, getting stuck in version 1.17 of wireui.

  Problem 1
     - Root composer.json requires wireui/wireui ^1.18, found wireui/wireui[dev-feature/v2-inputs, dev-feature/adding-input-slider, dev-feature/adjust-folders, dev-feature/adjusts-v2 , dev-main, dev-2.x-old, v0.0.1-alpha, ..., 0.x-dev, v1.0.0, ..., v1.17.9, 2.x-dev] but it does does not match the constraint.

**Comment by joaopalopes24** [comment]
Good afternoon @felipeArnold !

I tested here and it works normally.

![image](https://github.com/wireui/wireui/assets/45684782/1a2a6c48-f726-48f1-aee5-7161dbb6c352)

![Dependencies](https://github.com/wireui/wireui/assets/45684782/8b6a9784-2345-466b-910d-a4705ef76b14)
