### ISSUE TITLE
Maskable input does not render append or prepend.

### ISSUE THREAD

**Issue by ettiennelouw** [PH7-Jack/livewire-ui#720]
**Describe the bug**
Append does not work on maskable input component.

**To Reproduce**
`<x-inputs.maskable
            label="Maskable Input"
            mask="(###) ###-####"
            placeholder="Phone number"
        >
            <x-slot name="append">
                <div class="absolute inset-y-0 right-0 flex items-center p-0.5">
                    <x-button
                        class="h-full rounded-r-md border-l border-secondary-300"
                        icon="phone"
                        primary
                        flat
                        squared
                    />
                </div>
            </x-slot>
        </x-inputs.maskable>`

**Expected behavior**
To have a button at the end of the input box.

**Screenshots or Videos**
![Screenshot 2023-09-12 at 11 15 22](https://github.com/wireui/wireui/assets/1754421/27bf3edb-d59f-4611-ab99-d70c321ce4ca)
![Screenshot 2023-09-12 at 11 18 57](https://github.com/wireui/wireui/assets/1754421/0faae752-8641-456a-bdd6-0bceb65830b4)

**Dependencies**
 - WireUI Version: 1.17.9
 - Laravel Version: 9.25.15
 - Alpine.js Version: 3.0.6
 - Livewire Version: 2.12.6
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - Browser: [e.g. chrome, safari]

**Smartphone (If applicable, please complete the following information):**
 - Device: Mac
 - OS: Ventura 13.5.2
 - Browser brave
 - Version v1.57.62

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
