### ISSUE TITLE
x-notifications and x-dialog conflict with alpine inject from livewire

### ISSUE THREAD

**Issue by taqiussa** [PH7-Jack/livewire-ui#726]
**Describe the bug**
i am using livewire v3 and when using notification and dialog component as usually like using livewire v2 it is has bug conflict with alpinejs configuration from livewire v3

**Expected behavior**
it should just fine using notification and dialog as usually, but with livewire v3 it will show error on console log like so on picture i provide. and when trigered notification and dialog will launch twice. 

**Screenshots or Videos**
![Screenshot_20230919_175625](https://github.com/wireui/wireui/assets/85477999/ee130aeb-f5b4-4566-a5bf-a6d0d05f043e)

app.blade as layouts configuration

![Screenshot_20230919_180634](https://github.com/wireui/wireui/assets/85477999/1015f937-6a8a-4953-a1d8-4b37be1f89f2)

**Dependencies**
 - WireUI Version: 1.18.1
 - Laravel Version:  10.10.1
 - Alpine.js Version: 3.4.2
 - Livewire Version: 3.0
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: windows 11
 - Browser: firefox
 - Version 102.15.01sr

**Additional context**

**Comment by dwainscheeren** [comment]
I'm not sure if its related but when I use the confirm dialog button in my livewire blade I get error `Illegal invocation`

**Comment by Skreng** [comment]
The same problem with Livewire 2 and WireUi 1.17.9 :(

**Comment by coreyfreeman82** [comment]
Any update @PH7-Jack? Still having the same problem with Livewire 3 and WireUi 1.18.9

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
