### ISSUE TITLE
Resource wireui/assets/styles get 404 Not found

### ISSUE THREAD

**Issue by BoGnY** [PH7-Jack/livewire-ui#733]
**Describe the bug**
Loading WireUI assets styles get 404 not found.
The problem is that styles are loaded from `localhost` (without subdomain) instead `subdomain.localhost`.

**To Reproduce**
1. IDK

**Expected behavior**
WireUI assets styles get 200 Ok.

**Screenshots or Videos**
WireUI scripts is loaded correctly:
![image](https://github.com/wireui/wireui/assets/11542801/a9d91baf-3799-4355-8ddb-8994ccc9ba0e)

WireUI styles not found:
![image](https://github.com/wireui/wireui/assets/11542801/38e324c8-467b-4751-a720-8560860e8cc5)

But domain is:
![image](https://github.com/wireui/wireui/assets/11542801/b7be29d2-1157-44a0-9190-97b040b843e3)

This is the html head of layout:
![image](https://github.com/wireui/wireui/assets/11542801/a1f7e355-6e59-4508-89e3-a4340c949c6e)

**Dependencies**
 - WireUI Version: 1.18.1
 - Laravel Version: 10.22.0
 - Alpine.js Version: 3.12.3
 - Livewire Version: 3.0.4
 - Lang: it_IT

**Desktop (If applicable, please complete the following information):**
 - OS: Windows 10 PRO
 - Browser: Brave
 - Version: 1.58.131 (chromium based 117.0.5938.92)

**Comment by BoGnY** [comment]
I think problem is with `@wireUiStyles`...

On documentation only `@wireUiScripts` is required... Is confirmed that??
If yes, why `@wireUiStyles` exists???

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
