### ISSUE TITLE
Collision with $icon shared to view

### ISSUE THREAD

**Issue by arthurshlain** [PH7-Jack/livewire-ui#738]
I make website for SVG icons library and the `$icon` variables everywhere in my project.

Collision happens with components that use own icons when my controller contains `view()->share('icon', $icon)`:

`Unable to locate a class or view for component`

`[wireui::icons.outline.&quot;id&quot;:84,&quot;icon_term_id&quot;:86,&quot;icon_style_id&quot;:2…`

`resources/views/vendor/wireui/components/input.blade.php:33`

```blade
@if ($icon)
    <x-dynamic-component
        :component="WireUi::component('icon')"
        :name="$icon" <------------
        class="w-5 h-5"
    />
```

My current workaround:

```blade
@php
    $icon_temp = $icon ?? null;
    view()->share('icon', ''); // reset value
@endphp

<x-color-picker />

@php
    view()->share('icon', $icon_temp); // restore value
@endphp
```

 - WireUI Version: 1.18.1
 - Laravel Version: 10.25.2
 - Alpine.js Version: 3.0.6
 - Livewire Version: 3.0.5
 - Lang: en_US

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
