### ISSUE TITLE
MODAL NOT WORKING IN LIVEWIRE 3 (module.esm.js:538 Alpine Expression Error: Cannot read properties of undefined (reading 'find'))

### ISSUE THREAD

**Issue by resujentoezequiel** [PH7-Jack/livewire-ui#740]
Good day,

After I upgraded to Livewire 3, the wire modal is not working; please see the image below.

![image](https://github.com/wireui/wireui/assets/43774016/79a490da-a851-41d9-8e99-33d983125a81)

![image](https://github.com/wireui/wireui/assets/43774016/99ccb057-8aa9-45ce-9990-6efbbedda1ff)

![image](https://github.com/wireui/wireui/assets/43774016/7da53909-a757-4756-8b50-69de92e053da)

![image](https://github.com/wireui/wireui/assets/43774016/4971eccb-fe69-4924-ba03-9a5b3a5210e6)

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
