### ISSUE TITLE
Multi Select options not showing as ticked in dropdown

### ISSUE THREAD

**Issue by gRoberts84** [PH7-Jack/livewire-ui#741]
**Describe the bug**
When populating the form with existing content, the `<x-select :multiselect="true" />` it will show the correct values within the closed select but when clicking on it, none of the options are ticked.

<img width="250" alt="image" src="https://github.com/wireui/wireui/assets/348184/427e1093-349f-4e32-a885-f87564996df6">
<img width="1025" alt="image" src="https://github.com/wireui/wireui/assets/348184/1f408053-c880-48c5-be97-35fe43878bb0">

**To Reproduce**
1. Popular multi-select with options.
2. Render with property containing values that exist in options.
3. See error

**Expected behavior**
When the bound property has values that exist in options, they should be showing as ticked when expanding the dropdown.

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Dependencies**
 - WireUI Version: 1.18.1
 - Laravel Version: 10.24.0
 - Alpine.js Version: 3.13
 - Livewire Version: 3.0.5
 - Lang: en_GB

**Desktop (If applicable, please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: Version 117.0.5938.132 (Official Build) (x86_64)

**Additional context**

```
<x-select wire:model="packages.{{ $packageModalOpen }}.sections" :multiselect="true" :options="array_filter($packages, fn($p) => !empty($p['name']))" option-description="null" option-value="id" option-label="name" />
```

If the bound `sections` property is empty and I select values, it correctly shows them as ticked etc however if it's already populated when rendering, it does not appear to be.

**Comment by cakanm** [comment]
I have the same issue but without console errors. Options are selected in input field but the tick is missing on dropdown. I've updated dependencies but that didn't help.

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
