### ISSUE TITLE
wireui Select clear from DOM element

### ISSUE THREAD

**Issue by rivalex** [PH7-Jack/livewire-ui#742]
i i'm using wireui select as a filter for datatable ... very simple ...
`<x-select
        id="qualification::{{$this->getId()}}"
        placeholder="Select User type"
        :options="$qualifications"
        :clearable="true"
        option-label="qualification"
        option-value="value"
        x-on:clear="@this.resetQualification"
        wire:model.live="uq"
/>`

it works fine, but i have a problem clearing selected value out oh the component.
I list all filter active on table and i'm trying to clear the select from a simple button ... something like this

`<x-badge.badge-close class="space-x-1" wire:click=" << Clear qualification Select >>">
        <span>Qualification:</span>
        <strong>{{ $qualifications[$uq]['qualification'] }}</strong>
</x-badge.badge-close>`

I make a Livewire function that clear the vafiable ... but the select still not update

can anyone help? thx in advance

**Comment by rivalex** [comment]
hi guys, any idea for this problem? thx

**Comment by joaopalopes24** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository, commit the code that reproduces the issue as one separate commit on the main/master branch and share the repository here?

Also include which version is being used.
