### ISSUE TITLE
Uncaught Error: The wire:model value must be an array to use the select as multiselect

### ISSUE THREAD

**Issue by arthurshlain** [PH7-Jack/livewire-ui#743]
**Describe the bug**

Uncaught Error: The wire:model value must be an array to use the select as multiselect

**To Reproduce**

https://github.com/arthurshlain/livewire-test

(npm update, composer install, php artisan serve)

1. Go to `http://127.0.0.1:8000/select-test`
2. Click on 'Add Item' button
3. Click on 'Remove' (at right side)
4. See error in console

**Dependencies**
 - WireUI Version: 1.18.1
 - Laravel Version: 10.25.2
 - Alpine.js Version: Livewire 3 ships with AlpineJS by default.
 - Livewire Version: 3.0.5
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 117.0.5938.132

**Additional context**
Demo component files location:
- app/Livewire/ItemUploadWireUi.php
- resources/views/livewire/item-upload-wire-ui.blade.php

Related Livewire issues:
- https://github.com/livewire/livewire/discussions/6931
- https://github.com/livewire/livewire/discussions/6955

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
