### ISSUE TITLE
datetime-picker not working on Chrome browsers

### ISSUE THREAD

**Issue by devsquad-gabriel-ramos** [PH7-Jack/livewire-ui#744]
**Describe the bug**
After the latest Chrome release, the datetime-picker isn't showing all dates properly. Other browsers, such as Firefox and Safari are working as expected.

**To Reproduce**
1. Using the latest Chrome version
2. Open a datetime-picker
3. The dates are off, showing negative numbers and over 30 or 31 where they should end the month

**Expected behavior**
It should show the dates starting on the 1st and ending on the 30th or 31st.

**Screenshots or Videos**
- Screenshot from the [docs](https://livewire-wireui.com/docs/datetime-picker)' page
<img width="900" alt="Screenshot 2023-10-05 at 14 57 50" src="https://github.com/wireui/wireui/assets/102561610/81f6c17b-c57d-482e-b31e-658f873e26d2">

**Dependencies**
 - WireUI Version: 1.17.9
 - Laravel Version: 10.26.2
 - Alpine.js Version: 3.13.1
 - Livewire Version: 2.12.6
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: MacOS Sonoma v14.0
 - Browser: Chrome v117.0.5938.149

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
