### ISSUE TITLE
Confirm Dialog not displaying title or description

### ISSUE THREAD

**Issue by ElrondIT** [PH7-Jack/livewire-ui#745]
**Describe the bug**
The confirm dialog is not displaying the title or description. The dialog appears with the buttons and the icon.

The code I've used is:

        $this->dialog()->confirm([
                                     'title'       => 'Are you Sure ?',
                                     'description' => 'Delete country?',
                                     'acceptLabel' => 'Yes, delete it',
                                     'method'      => 'destroy',
                                     'params'      => 'Deleted',
                                 ]);

**Expected behavior**
The dialog opens but is missing content

**Screenshots or Videos**
The output on screen is:
![image](https://github.com/wireui/wireui/assets/36861894/7d6617fa-738c-45af-bf2f-fa0482d159e8)

**Dependencies**
 - WireUI Version: 1.18.1
 - Laravel Version: 10.26.2
 - Alpine.js Version: - bundled with livewire
 - Livewire Version: 3.0.5
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: Windows 11
 - Docker using WSL2
 - Browser: Latest versions of Microsoft Edge and Firefox

**Additional context**

**Comment by ElrondIT** [comment]
I forgot to mention <x-dialog.ui /> is in the blade template.
The .ui alias was added in the config wireui as the system is also using JetStream.
Notifications are working perfectly.

**Comment by joaopalopes24** [comment]
This is working normally. See an example in version 2 [here](https://wireui.dev/actions/dialogs#confirm-dialog) and version 1 [here](https://v1.wireui.dev/docs/dialogs#confirm-dialog).
