### ISSUE TITLE
x-select is duplicating options when click on browser back button with full page components

### ISSUE THREAD

**Issue by zooni7054** [PH7-Jack/livewire-ui#750]
**Describe the bug**
I am using livewire 3 full page components. I have x-select in a modal form. I navigate to the other page by clicking the menu. When I click brower back button, x-select show the duplicate values (blank). I can also see the following error in console when click browser back button.

Alpine Expression Error: index is not defined

Expression: "index"

**To Reproduce**
1. Open a page which has the x-select and option.
2. Move to any other page
3. click on browser back button
4. you would see the error.

**Expected behavior**
x-select should have the options given in the array, it should not add or duplicate options.

**Screenshots or Videos**

https://github.com/wireui/wireui/assets/14364018/b6b53997-db01-4316-98c2-b264b199c634

**Dependencies**
 - WireUI Version: 1.18
 - Laravel Version: 10.10
 - Livewire Version: 3.0
 - Lang: en_US

**Comment by zooni7054** [comment]
Any update on this?

**Comment by vlados** [comment]
I also have the same problem

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
