### ISSUE TITLE
Native Select Value

### ISSUE THREAD

**Issue by OlyaK95** [PH7-Jack/livewire-ui#753]
**Describe the bug**
`<x-native-select>` works well only without placeholder, I can't define selected value.

**More about problem**
I have two `<x-native-selects>`: one for divisions and second depended select for subdivisions of selected division.
Select for divisions working perfect.
Select for subdivisions working only if I delete placeholder.

My code:
````
<x-native-select wire:model.live="form.division_id" wire:change="resetSubdivisions()" label="Division"
 placeholder="Select division" class="text-sm" :options="$divisions" option-label="name" option-value="id"
 id="updateDivisionId" />
<x-native-select wire:model.blur="form.subdivision_id" label="Subdivision" placeholder="Select subdivision"
 class="text-sm" :options="$subdivisions" option-label="name" option-value="id" :disabled="!$subdivisions"
 id="updateSubdivisionId" />
````
Video:
https://github.com/wireui/wireui/assets/129214474/7f895dfb-a73d-4cd3-b5c6-fdb923add48e

My edited code:
````
<x-native-select wire:model.live="form.division_id" wire:change="resetSubdivisions()" label="Division"
 class="text-sm" :options="$divisions" option-label="name" option-value="id"
 id="updateDivisionId" />
<x-native-select wire:model.blur="form.subdivision_id" label="Subdivision"
 class="text-sm" :options="$subdivisions" option-label="name" option-value="id" :disabled="!$subdivisions"
 id="updateSubdivisionId" />
````
Video:
https://github.com/wireui/wireui/assets/129214474/a7ef2abf-477c-4edc-9fb1-23ae4ad58a21

**Dependencies**
 - WireUI Version: 1.18
 - Laravel Version: 10.28.0
 - Livewire Version: 3.0.8

**Desktop (If applicable, please complete the following information):**
 - OS: Windows 11 22H2
 - Browser: Chrome
 - Version 118.0.5993.71

**Comment by OlyaK95** [comment]
My bad with `$subdivisions ` query. Sorry.

**Comment by OlyaK95** [comment]
I was wrong, placeholders don't matter.
Without placeholders I just have autoselect first item in subdivisions.

Select for subdivisions working only with this query:
```
$this->divisions = Division::query()
->select("id", "name")
->get()
->toArray();

$this->subdivisions = Subdivision::query()
->select("id", "name")
->get()
->toArray();
```

But I need 
```
$this->divisions = Division::query()
->select("id", "name")
->get()
->toArray();

$this->subdivisions = Subdivision::query()
->select("id", "name")
->where("division_id", "=", $this->form->division_id)
->get()
->toArray();
```

What can I do?

My query work well with `<x-select>` but I need `<x-native-select>`.

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
