### ISSUE TITLE
Issue: Error When Input Year Value at Datetime Picker

### ISSUE THREAD

**Issue by mukhlish32** [PH7-Jack/livewire-ui#765]
**Describe the bug**
I got this bug when I tried to input the year manually and input it slowly which exceeded the interval (10 milliseconds?) thus making the year invalid causing the calendar to only display 1 or 2 weeks. The error occurs when the year value is only 3 digits.

**To Reproduce**
1. Go to documentation of datetime picker or click [this](https://livewire-wireui.com/docs/datetime-picker) ;
2. Click the calendar icon;
3. Input the year manually and slowly (or write the year with only 3 digits)
4. See error (the calendar only display 1 or 2 weeks / invalid calendar). And after this the calendar won't change even I reinput to the correct year.

**Expected behavior**
Show a valid and correct calendar.

**Screenshots or Videos**
![image](https://github.com/wireui/wireui/assets/85531251/91a6bb1e-7dd2-4154-90d7-6dccd052e99d)
Video: https://www.loom.com/share/c435a14a1f764e779eed1fd12a5a3581

**Dependencies**
 - WireUI Version: 1.17.9
 - Laravel Version: 9.52.5
 - Alpine.js Version: [3.13.2](https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js)
 - Livewire Version: 2.12.3
 - Lang: en_US

**Additional context**

**Comment by uyab** [comment]
My client found the same issue yesterday, after year long development and testing 😀 

Will try to dive in this weekend, hopefully can find the root cause.

**Comment by uyab** [comment]
Updated: it is only happened when using Chrome

**Comment by mukhlish32** [comment]
Thank you for the information, @uyab . I finally found the solution to make it work in Chrome as well. I conducted tests in Firefox and encountered no issues. It appears that the calendar updates only when the year value is a four-digit. So I added a condition to validate the year value when the input event is executed, ensuring it contains exactly four digits before triggering the `fillPickerDates` function.

![imageg](https://github.com/wireui/wireui/assets/85531251/227394d2-2a82-4841-9946-68af09233305)

**Comment by uyab** [comment]
@mukhlish32 which file did you edit?

**Comment by mukhlish32** [comment]
@uyab I edited the [datetime-picker.blade.php](https://github.com/wireui/wireui/blob/main/resources/views/components/datetime-picker.blade.php) file in the components folder. I added a condition to check and trigger if the year variable has a length of 4 characters and set it on x-on event listeners to prevent errors in the application.

**Comment by mukhlish32** [comment]
Thank you for the update, and sorry to inform so late, I also just found it yesterday, but I found another problem when I clicked the monthPicker component, and next/previous month component when the year digit still != 4. And it give the invalid result like above. 

![Screenshot 2023-10-28 204228](https://github.com/wireui/wireui/assets/85531251/887753a2-1261-4a30-80d3-e7a02d6cd6ef)

So to make sure that's not gonna happen again, I also add condition **if (year.length === 4)** on **x-on:click** as well. This was my edit.

![image](https://github.com/wireui/wireui/assets/85531251/2e17c451-5874-42d6-8c44-7397fc521fd0)
![image](https://github.com/wireui/wireui/assets/85531251/98e406fc-c440-41b8-a227-2e92f7f65c3f)

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
