### ISSUE TITLE
Buttons no longer rendering class content

### ISSUE THREAD

**Issue by titonova** [PH7-Jack/livewire-ui#767]
In the commit committed about 50 minutes ago (for v1.18.5 [Latest](https://github.com/wireui/wireui/releases/latest)), it causes a bug such that buttons no longer render appropriately.

Doing:

`<x-button primary label="Button"/>` now returns 

```blade
<button wire:loading.attr="disabled" wire:loading.class="!cursor-wait" type="button" primary="primary">
    <!--[if BLOCK]><![endif]--> <!--[if ENDBLOCK]><![endif]-->

    Button

    <!--[if BLOCK]><![endif]--> <!--[if ENDBLOCK]><![endif]-->

    <!--[if BLOCK]><![endif]--> <!--[if ENDBLOCK]><![endif]-->
</button>
```

As you can see, rather than it giving it the appropriate classes that correspond to the `primary` attribute, it simply renders the attribute as `primary="primary"`. 

It's most likely something related to:

![image](https://github.com/wireui/wireui/assets/41286822/3989f9b8-3b0f-4660-aa84-26b7cc9e1daf)

**Comment by ph7jack** [comment]
Thanks for reporting, it is fixed now 
Check https://github.com/wireui/wireui/releases/tag/v1.18.6

**Comment by titonova** [comment]
Thanks 🙏🏾.

Lol committed, pushed, bug reported, bug fixed, re-pushed, all in 1 hour
