### ISSUE TITLE
Starting in 1.18.5: Alpine Expression Error: Invalid or unexpected token

### ISSUE THREAD

**Issue by thsteinmetz** [PH7-Jack/livewire-ui#769]
Just wanted to start a quick issue to let you know that starting today, with 1.18.5 I am seeing the following errors across the board on all the components:

```
Alpine Expression Error: Invalid or unexpected token

Expression: "wireui_select({
                    wireModel: @entangle($attributes->wire('model')),
})"
````

Downgrading to 1.18.4 and the issue goes away.

**Comment by BoGnY** [comment]
Me too.. I've updated from 1.18.1 to 1.18.6 and have the same issue (50+ errors on each page).

**Comment by ph7jack** [comment]
Same error in the latest release?

**Comment by thsteinmetz** [comment]
@PH7-Jack , yes, also on the latest.

**Comment by ph7jack** [comment]
Fixed by reverting the changes
