### ISSUE TITLE
Clearing Multiselect after form submission

### ISSUE THREAD

**Issue by paaqwesilowelltetteh** [PH7-Jack/livewire-ui#771]
Would like to request the ability to clear the the multiselect feature after form submission in livewire

**Comment by ph7jack** [comment]
Hi, you can clear the select model direct from livewire, then, the multiselect will be clean.
Do it in your "save" method.
`$this->yourModel = [];`

**Comment by paaqwesilowelltetteh** [comment]
Alright. Thank you. I have another use case where I am submitting form using javascript form submission. Is there a way I can clear the multi select and select components?
