### ISSUE TITLE
Entangle crashes on array (Livewire bug)

### ISSUE THREAD

**Issue by satoved** [PH7-Jack/livewire-ui#776]
`@entangle` currently creates an unexpected behavior (a bug on Livewire side).

They suggest using AlpineJS `$wire.$entangle()` instead.

See https://github.com/livewire/livewire/pull/6833#issuecomment-1750349102

`@entanglable` from your package follows the same issue.

Would you consider using AlpineJS's `$wire.$entangle()` to bind values?

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
