### ISSUE TITLE
classes missing in 1.18.5 and up

### ISSUE THREAD

**Issue by patrickweh** [PH7-Jack/livewire-ui#777]
**Describe the bug**
When upgrading to 1.18.5 or higher all buttons are missing their classes except mb-4. propably there are more issues i havent seen yet

<img width="920" alt="image" src="https://github.com/wireui/wireui/assets/40495041/4c283165-f273-4387-87df-4253b980521e">

**Comment by ph7jack** [comment]
Have you cleaned your app cache?

**Comment by ph7jack** [comment]
Closing it, it was fixed
