### ISSUE TITLE
Styles not loading: Colors of X-Button

### ISSUE THREAD

**Issue by GBry** [PH7-Jack/livewire-ui#779]
As titled, colors and styles not loading.

The install guide tells us to load WireUI before Alpine, but we don't need to load Alpine since LW 3.0.

**Screenshots or Videos**
![image](https://github.com/wireui/wireui/assets/12200922/2ce9ac4b-c827-4a0f-a9bb-286ffd0fd32e)

**Dependencies**
 - WireUI Version: 1.18.8
 - Laravel Version: 100.29.0
 - Alpine.js Version: Bundled with Livewire
 - Livewire Version: 3.0.10
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 118.0.5993.89

Blade code:
```
<tr>
                <td colspan=10>
                <x-button style="width:100%;" label="Add Row" primary right-icon="plus" wire:click="addRow"/>
                </td>
            </tr>
            <tr>
                <td colspan=10>
                    <x-button style="width:100%;"  label="Submit Documents" type="submit" positive right-icon="arrow-up" />
                    <div wire:loading>
                        Processing...
                    </div>
                    {{ $submitstatus }}    
                </td>
            </tr>
            <tr>
                <td colspan=10>
                <x-button style="width:100%;" label="Recalculate Hours" primary right-icon="clock" wire:click="calc_expiry"/>
                </td>
            </tr>
```

**Comment by ph7jack** [comment]
Fixed in the latest release
