### ISSUE TITLE
Input Async Search Broken

### ISSUE THREAD

**Issue by GBry** [PH7-Jack/livewire-ui#780]
Errors popping:
`Alpine Expression Error: Unexpected token ':'
Expression: "WireUi::component('input')"`

`Alpine Expression Error: trans is not defined
Expression: "trans('wireui::messages.searchHere')"`

The search box doesn't appear, but the first 10 items that gets returned from the API do (before actually doing the search)
![image](https://github.com/wireui/wireui/assets/12200922/c5d31e08-d09e-416d-b1e5-747506111335)

Dependencies

WireUI Version: 1.18.8
Laravel Version: 100.29.0
Alpine.js Version: Bundled with Livewire
Livewire Version: 3.0.10
Lang: en_US
Desktop (If applicable, please complete the following information):

OS: Windows 10
Browser: Chrome
Version 118.0.5993.89

**Comment by skoTner** [comment]
Have the same issue, but occured first after upgrading to Livewire v3.
![Screenshot 2023-10-25 at 14 44 14](https://github.com/wireui/wireui/assets/2727377/9063ec22-eb3d-4dd7-85c1-7c4673b038fa)

**Comment by ph7jack** [comment]
It's happening because both of you have published the views. This bug was fixed, however you need to publish the views again to make an effect.
If you don't have changed anything in the published views, you don't need to have them published. Just delete the folder.

**Comment by carbtest** [comment]
If the views have been published, what is the best resolution?

**Comment by carbtest** [comment]
@ph7jack if the views have been published, what is the best resolution? NOTE: I am still using v1.17 with livewire 2.12
