### ISSUE TITLE
Dialogs Not Working Overflow Issue

### ISSUE THREAD

**Issue by abbasmashaddy72** [PH7-Jack/livewire-ui#781]
**Describe the bug**
After implementing the code as instructed in the Layout File, I encountered an unexpected issue. The code resulted in a full-page overlay that prevents me from interacting with the webpage. Unfortunately, this issue is preventing the dialog from functioning as intended, and I'm currently unable to use it as expected.

```
<x-dialog />
        or
<x-dialog z-index="z-50" blur="md" align="center" />
````

**Expected behavior**
The following code is meant to display a dialog, but it seems to be causing an issue with an overlay that prevents me from interacting with it. This overlay is hindering my ability to engage with the dialog as intended.
```
$this->dialog()->show([
    'title'       => 'Profile saved!',
    'description' => 'Your profile was successfully saved',
    'icon'        => 'success'
]);
```

**Screenshots or Videos**
![image](https://github.com/wireui/wireui/assets/55267488/445dfe73-2b01-4ced-ac04-3cd194930f52)

**Dependencies**
 - WireUI Version: 1.17.8
 - Laravel Version: 9.46
 - Alpine.js Version: 3.4.2
 - Livewire Version: 2.10.8
 - Lang: en_US

**Additional context**
I am already using forms & notifications, which works fine without any issues.

**Comment by abbasmashaddy72** [comment]
When I remove `.overflow-y-auto and z-50` then it works but not showing the dialog on top when enabled again it shows on top

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
