### ISSUE TITLE
Modal card not extending all options

### ISSUE THREAD

**Issue by patrickweh** [PH7-Jack/livewire-ui#783]
According the docs the Modal Card Extension all Modal options but the name is not passed which meqns the magic $openModal cant be used.

Would be nice if this could be added :) 

In my case i need a fullscreen Modal (which is only possible with card Modal) that can be opened using only alpine, no livewire.

Thanks!

**Comment by joaopalopes24** [comment]
@patrickweh Hello. Which the version?

**Comment by patrickweh** [comment]
Hey,

Current version of v1

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
