### ISSUE TITLE
select options drawer does not display full input width 

### ISSUE THREAD

**Issue by DiegoAlonso27** [PH7-Jack/livewire-ui#784]
**Describe the bug**

in the new version, the select options drawer does not occupy the full width of the input. 

**To Reproduce**

**Expected behavior**

![image](https://github.com/wireui/wireui/assets/74083184/3753bd02-0f0c-419d-9dab-6aa2f0734e2a)

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.
![image](https://github.com/wireui/wireui/assets/74083184/7c495c39-8449-44c3-8c77-d17b79638f82)

**Dependencies**
 - WireUI Version: 1.18
 - Laravel Version: 10.10
 - Alpine.js Version: 3.0
 - Livewire Version: 3.0
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - Browser: [e.g. chrome, safari]

**Smartphone (If applicable, please complete the following information):**

**Additional context**

**Comment by tariktokic** [comment]
Same error here! 
wireui v1.18.9

**Comment by ph7jack** [comment]
It was intentional... However, it doesn't looks good in larger width

**Comment by tariktokic** [comment]
You are right. But it does not only affect select fields. Datepicker looks also a little bit off. Before the picker was centered and now it is aligned to the right side. See before and after screenshots.

Before the update:
<img width="535" alt="Datepicker-before" src="https://github.com/wireui/wireui/assets/22153538/052b216c-abb8-4981-8bfe-883574d2d1f7">

After the update:
<img width="539" alt="Datepicker-after" src="https://github.com/wireui/wireui/assets/22153538/295b9634-a8c1-418a-8ce4-576c58ae266c">

Thank you very much for your efforts!

**Comment by ph7jack** [comment]
Yes, all components using the popover were updated to look similar, aligning the popover to the trigger button.
I'll check it and plan a better way to fit the popover, using it on a larger width is challenging for ui/ux.

The select component is more simple, however, datepicker and color picker can look weird

**Comment by tariktokic** [comment]
If I may suggest, just leave it the way it was before (revert the changes). The way it was looking in the past was almost the same as the standard HTML components, which is what the common user knows and is used to.

**Comment by Joemires** [comment]
Add the below css to your css file and you should have the popover on full width again
```css
.w-full + [x-ref="popover"] {
    width: 100% !important;
}

[x-show="popover"][x-ref="popover"] > div:last-child {
    max-width: 100% !important;
    width: 100% !important;
}
```

I really like the full width display tho

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
