### ISSUE TITLE
Datepicker javascript errors

### ISSUE THREAD

**Issue by caiochami** [PH7-Jack/livewire-ui#788]
**Describe the bug**
Javascript errors are triggered wherever there's a datepicker input. I tried copying and pasting a code snippet from the docs but I had no success.

Error is gone if I remove the x-datetime-picker component

**To Reproduce**
1. Install wireui
2. Use the datepicker component

**Expected behavior**
No javascript errors in the console log. Datepicker input should work as usual.

**Screenshots or Videos**
![image](https://github.com/wireui/wireui/assets/17772351/58d0eeb6-d2cf-436e-b0df-bf9e0b4a83a5)

**Dependencies**
 - WireUI Version: v1.17.12
 - Laravel Version: ^10.10
 - Alpine.js Version: ^3.0.6
 - Livewire Version: ^2.11
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - Browser: [e.g. chrome, safari]

**Smartphone (If applicable, please complete the following information):**

**Additional context**

**Comment by DiegoAlonso27** [comment]
have you tried upgrading livewire, installation requires livewire version 3

![image](https://github.com/wireui/wireui/assets/74083184/3a5c309a-7505-4fb4-a726-540a41ecbd87)

**Comment by caiochami** [comment]
The issue is resolved. I downgraded the package to the 1.17.9 version
