### ISSUE TITLE
modal max-width question

### ISSUE THREAD

**Issue by ElrondIT** [PH7-Jack/livewire-ui#79]
I've been trying to alter the size of a modal on the screen using the "max-width" property but was finding that 2xl->6xl were all the same width. Looking modal.php code the "getMaxWidth" function seems to set the max-width to max-w-2xl for everything everything from 2xl-6xl.
Is this correct or should they set the max width to the icoming string (ie. 3xl=> sm:max-w-3xl, 4xl => sm:max-w-4xl, etc.) ?

**Comment by ph7jack** [comment]
Yes, it's a bug, I'm refactoring all components to make them smaller and faster.
In this refactoration I found some bugs to fix. In this weekend I will release a new version

**Comment by ElrondIT** [comment]
Thank you for letting me know, I'll await the update.

**Comment by ph7jack** [comment]
@ElrondIT it is now fixed, thanks
