### ISSUE TITLE
Initial modal loading issue

### ISSUE THREAD

**Issue by meysamhosseini1995** [PH7-Jack/livewire-ui#792]
**Describe the bug**
When I use the modal component, it automatically opens upon page load. After some investigation, I realized that the 'x-clock' is being removed after the component is rendered, whereas in normal components like an HTML tag, it remains hidden.

I am using these versions:

"php": "^8.1",
       "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "livewire/livewire": "^3.0",
        "wireui/wireui": "^1.18"

**Screenshots or Videos**

![Screenshot from 2023-11-02 10-00-36](https://github.com/wireui/wireui/assets/46355788/12fcbe6d-8510-4ea3-9886-8da20706a107)
![Screenshot from 2023-11-02 10-03-49](https://github.com/wireui/wireui/assets/46355788/55b4b055-91e1-4386-999e-bbc2e76c6c16)
![Screenshot from 2023-11-02 10-25-15](https://github.com/wireui/wireui/assets/46355788/5e3bec3d-43f5-47b2-beb4-388d88a45861)

**Desktop (If applicable, please complete the following information):**
 - Browser: [e.g. chrome, safari]

**Smartphone (If applicable, please complete the following information):**
 - Device: desktop
 - OS: ubuntu
 - Browser Google Chrome
 - Version 118.0.5993.117 (Official Build) (64-bit)

**Comment by DiegoAlonso27** [comment]
have you verified in which state is cardModal, if when loading the page it is true or false, since you are assigning this value to be shown or not.

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
