### ISSUE TITLE
Maskable Inputs does not function

### ISSUE THREAD

**Issue by DiegoAlonso27** [PH7-Jack/livewire-ui#796]
**Describe the bug**

when trying to use Maskable Inputs it only lets you enter one number and if you add another one the previous one is deleted and only the last one you entered is left but it only remains in one digit.

**To Reproduce**
<x-wire-inputs.maskable label="Maskable Input" mask="####-####-####-####"
                            placeholder="Credit Card Number" />

**Expected behavior**

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.
![image](https://github.com/wireui/wireui/assets/74083184/509e70a5-0e08-4e10-aa92-ba0cf988dfce)

https://github.com/wireui/wireui/assets/74083184/0c16cc3a-879a-40ed-b991-23574d9cd6fb

**Dependencies**
 - WireUI Version: 1.18
 - Laravel Version: 10.10
 - Alpine.js Version: 3.0
 - Livewire Version: 3.0
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - Browser: [e.g. chrome, safari]

**Smartphone (If applicable, please complete the following information):**

**Additional context**

**Comment by coxta** [comment]
Same for `<x-password />`

**Comment by DiegoAlonso27** [comment]
> Same for `<x-password />`

the password works normally for me, maybe it is for another reason, have you checked the installed version?

**Comment by coxta** [comment]
@DiegoAlonso27 - yes, sorry I'm using v2.0-beta just ignore me ;-) 

BTW - very excited about v2, y'all keep up the great work!

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
