### ISSUE TITLE
x-phone multiple mask

### ISSUE THREAD

**Issue by Artessan** [PH7-Jack/livewire-ui#802]
**Describe the bug**
x-phone component: when a multiple mask the array is handle as one string

**To Reproduce**
```
<div class="col-span-2 lg:col-span-1">
    <x-phone id="multiple-mask" label="{{__('Phone')}}" mask="['(+##) ### ## ## ##, ### ## ## ##']"
             wire:model="contactForm.phone"/>
</div>
```

produce: ['(+12) 345 67 89 12, 345 67 89 12']

**Expected behavior**
(+12) 345 67 89 12

**Dependencies**
 - WireUI Version: 2-beta
 - Laravel Version: 10.X.X
 - Alpine.js Version: 3.X.X
 - Livewire Version: 3.X.X

**Comment by django-wong** [comment]
Did you try `['(+12) 345 67 89 12', '345 67 89 12']` ?

**Comment by Artessan** [comment]
Hey, tested, the result is the same. 

after checking some parts of the code I think the problem is this: 

this is the render data on the div

`wireui_inputs_maskable({isBlur:false,model:null,emitFormatted:false,mask:'[\'(+##) ### ## ## ##\', \'### ## ## ##\']',})`

the mask is echoing as string  and in 

```
ts/utils/masker/index.ts

export const applyMask: ApplyMask = (mask, value, masked = true): string | null => {
  return Array.isArray(mask)
    ? dynamicMasker(mask, str(value), masked)
    : singleMasker(mask, str(value), masked)
}
```

before this The mask is never checked, parse or split as array; So the isArray method  is always false using single mask

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
