### ISSUE TITLE
Add the "errorless" property on components other than input-texts [WIP]

### ISSUE THREAD

**Issue by BoGnY** [PH7-Jack/livewire-ui#808]
**Is your feature request related to a problem? Please describe.**
I want to use `x-errors` component to show errors because more beautiful, but it is only possible on input text.
Toggle, checkbox, radio, select, don't have this proprerty, so if I want to use `x-errors` it show double error "section".
![image](https://github.com/wireui/wireui/assets/11542801/a76f5899-3511-471b-9e67-efdae91fbde0)

**Describe the solution you'd like**
Add errorless property on other components.

**Additional context**
This is related to #75 but this PR has added 'errorless' property only on input text.

I'm working on this PR 👍🏻 

**EDIT**: I'm not sure, in which branch I will do PR??

**Comment by DiegoAlonso27** [comment]
I think it would be for version 2 since they said they would no longer add features to version 1 but only fix bugs.

**Comment by BoGnY** [comment]
Ok I wait for confirmation from @PH7-Jack and in case I'll change branch 👍🏻

**Comment by joaopalopes24** [comment]
We have no plans to add this in version 1, and we already have this option in version 2.
