### ISSUE TITLE
Modal parameters not working properly

### ISSUE THREAD

**Issue by Piteus** [PH7-Jack/livewire-ui#811]
When I open the page modal is default open, i try setting show="false" but nothing change.
I want to open the modal only after button click.

**Dependencies**
 - WireUI Version: 1.18.9
 - Laravel Version: 10
 - Livewire Version: 3.1
 - Lang: en_US

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
