### ISSUE TITLE
View password in the password component

### ISSUE THREAD

**Issue by felipeArnold** [PH7-Jack/livewire-ui#815]
**Describe the bug**
When clicking on the view password icon, two problems occur.

1st: The button being used submits the form.
2nd: When adding a type button or changing it to a div or span, the input cannot have the appropriate behavior.
3rd: When using more password components, I didn't even find a way to separate the component's state change with a prefix, for example: when adding 3 inputs for changing the password in the same component they can get lost and show the password of all 3 or none.

**Screenshots or Videos**
![Captura de tela de 2023-11-12 20-56-24](https://github.com/wireui/wireui/assets/44820260/7965d4e5-1889-4308-8728-f8ee1d7bc6ff)
![Captura de tela de 2023-11-12 20-56-57](https://github.com/wireui/wireui/assets/44820260/ef6c7097-7797-48e5-b1f7-856167f2b9d5)

**Dependencies**
 - WireUI Version: 2.X.X
 - Laravel Version: 10.X.X
 - Alpine.js Version: 3.X.X
 - Livewire Version: 3.X.X
 - Lang: pt_BR

**Desktop (If applicable, please complete the following information):**
 - Linux: Ubuntu
 - Browser: [chrome]
 - Version [23:10]

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
