### ISSUE TITLE
x select shows numbers (ids) when I click on bottom-right

### ISSUE THREAD

**Issue by rhmorlans** [PH7-Jack/livewire-ui#816]
I have an issue with wire ui x-select component.
When I click on the select (only on a specific area), some numeric values are shown instead of the :options content.

Is a component issue?
Thanks a lot.

<img width="244" alt="image" src="https://github.com/wireui/wireui/assets/23193579/07d538a0-85e2-47e0-a69a-fc04fbc34c96">

**Comment by DiegoAlonso27** [comment]
Could you better upload a video?

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
