### ISSUE TITLE
Confirm Directive after wire:navigate

### ISSUE THREAD

**Issue by hdahon** [PH7-Jack/livewire-ui#818]
**Describe the bug**
The Confirm Directive does not work anymore after a wire:navigate, the click on the button do nothing.

<x-button label="Delete"
    x-on:confirm="{
        title: 'Sure Delete?',
        icon: 'warning',
        method: 'delete',
        params: 1
    }"
/>

**Dependencies**
 - WireUI Version: 1.18.9
 - Laravel Version: 10.31.0
 - Alpine.js Livewire version
 - Livewire Version: 3.1.0
 - Lang: fr_FR

**Desktop (If applicable, please complete the following information):**
 - OS:MacOs
 - Browser: chrome,safari

**Comment by hdahon** [comment]
I managed to make it work by adding the event livewire:navigated in /wireui/wireui/ts/directives/confirm.ts

```
document.addEventListener('livewire:navigated', () => { 
  initialize(document.body)
})
```

But that might not be the best solution ?

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
