### ISSUE TITLE
[V2] Unable to locate a class or view for component [wrapper] when using personal wireui prefix.

### ISSUE THREAD

**Issue by BoGnY** [PH7-Jack/livewire-ui#819]
**Describe the bug**
This bug is very strange, because I fix it by removing prefix on all prefixed component in the blade file, and setting config `wireui.prefix` to `null`.
After manually visiting the page via browser, I can set again `wireui.prefix` to `'wui-'` and replacing back all unprefixed component to prefixed component, and the page works 😵‍💫 ....
But I have to do manually on ONE page which have the prefixed component, doing it with one page, it fix same prefixed component on all other pages.

Seems like something is cached, I've runned `php artisan optimize:clear` which remove all cached files but without success.

**To Reproduce**
1. Upgrade to 2.0
2. Set `wireui.prefix` to `'wui-'`
3. Use prefixed component

**Expected behavior**
No errors.

**Screenshots or Videos**
![image](https://github.com/wireui/wireui/assets/11542801/6b3f4ede-58d8-48c1-9d91-3f404ed49b2d)

**Dependencies**
 - WireUI Version: 2.0.0-beta.0
 - Laravel Version: 10.31.0
 - Alpine.js Version: 3.13.2
 - Livewire Version: 3.1.0
 - Lang: it_IT

**Desktop (If applicable, please complete the following information):**
 - OS: Windows PRO 11
 - Browser: Brave
 - Version 1.60.114

**Additional context**

**Comment by BoGnY** [comment]
Also give the error for `Unable to locate a class or view for component [wrapper.switcher].`

**Comment by minhtamwebmaster** [comment]
same issue

**Comment by levipeto** [comment]
same issue.

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.

**Comment by divdax** [comment]
Same here when using `x-wireui.toggle` with v2

**Comment by joaopalopes24** [comment]
@divdax Did you update the WireUi? This was adjusted.
