### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by itepifanio** [PH7-Jack/livewire-ui#82]
Please add a file ` CONTRIBUTING.md ` to the root of the project. It would be very helpful to know how to install and run the project.

**Comment by ph7jack** [comment]
@itepifanio Thanks. I'm tweaking the documentation, I'm going to put this as a priority, and add a guide on how to contribute.

**Comment by ph7jack** [comment]
@itepifanio  thanks for the contribution.
