### ISSUE TITLE
button submit not reacting till second click

### ISSUE THREAD

**Issue by mkts02** [PH7-Jack/livewire-ui#821]
i have to press the save button to submit my form multiples times to make it work, i was thinking it was my code or something but when i press the button it doesnt reach the controller until the second attempt, is working fine with a normal button.

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
