### ISSUE TITLE
Cannot user $parent for wire:model binding with DateTimePicker or Select.

### ISSUE THREAD

**Issue by Aaron1178** [PH7-Jack/livewire-ui#823]
**Describe the bug**
I cannot bind data from the DateTimePicker or Select WireUI components to my parent livewire component using $parent. 

**Expected behavior**
I expected the data bindings to work as per any other input field using the $parent method.

**Dependencies**
 - WireUI Version: 1.18
 - Laravel Version: 10.10
 - Livewire Version: 3.0
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: Windoes
 - Browser: Chrome
 - Version 119.0.6045.10

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
