### ISSUE TITLE
Select - First Option Auto Select

### ISSUE THREAD

**Issue by davidwhicker** [PH7-Jack/livewire-ui#824]
Unless I've missed it, I want the first option when typing on a select to be auto selected so when I push enter it will select that option and fire off the event. 

Further info I am Async search. All works fine apart from auto selecting first option.

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We need more information about the aforementioned request. We will close the issue and once information is added, tag us in the comments so we can reopen the issue.
