### ISSUE TITLE
Reference to dist/wireui.js

### ISSUE THREAD

**Issue by sclause2412** [PH7-Jack/livewire-ui#826]
**Describe the bug**
I get this output in my web browser console:
`GET http://localhost/wireui/assets/scripts net::ERR_ABORTED 500 (Internal Server Error)`
This happens because the files **webpack.mix.js** and **WireUiAssetsController.php** refer to the folder **dist** which is not available in V2 anymore.

**To Reproduce**
1. Use WireUI v2

**Expected behavior**
Reference to dist folder should be removed.

**Screenshots or Videos**
![image](https://github.com/wireui/wireui/assets/36406078/30a03f50-d317-48a6-bb48-1b431fb52351)

**Dependencies**
 - WireUI Version: 2.X.X

**Desktop:**
 - OS: Arch Linux
 - Browser: Brave

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
