### ISSUE TITLE
icon 'academic-cap' in dark mode shows white background

### ISSUE THREAD

**Issue by winavin** [PH7-Jack/livewire-ui#832]
using V1
```
<x-icon name="academic-cap" class="w-5 h-5" />
```
output in dark mode attached image.

![Screenshot 2023-11-30 002728](https://github.com/wireui/wireui/assets/83947656/c5c4d576-8cdb-44fd-9838-04041d7e0afc)

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
