### ISSUE TITLE
V2 Multi Select with wire:model.live does not react on changes

### ISSUE THREAD

**Issue by nastoychev** [PH7-Jack/livewire-ui#833]
**Describe the bug**
V2 Multi Select with wire:model.live does not react on changes
**To Reproduce**

  **TestComponent.php**

```
<?php

namespace App\Livewire;

use Livewire\Component;

class TestComponent extends Component
{
    public array $options = [];

    public function checkOptions(): void {
        dump($this->option);
    }

    public function render()
    {
        return view('livewire.test-component');
    }
}
```

**bookie-selector.blade.php**
```

<div>
        <form wire:submit="checkOptions">
        <x-select
            wire:model.live="options"
            label="Select Statuses"
            placeholder="Select many statuses"
            multiselect
            :options="['Active', 'Pending', 'Stuck', 'Done']"
        />
        <button type="submit">Submit</button>
    </form>
</div>
```
**Expected behavior**

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Dependencies**
 - WireUI Version: 2.0.0
 - Laravel Version: 10.X.X
 - Alpine.js Version: 3.X.X
 - Livewire Version: 3.X.X
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: Windows 11
 - Browser: edge

**Smartphone (If applicable, please complete the following information):**

**Comment by viliusvsx** [comment]
@nastoychev I think the problem is how you wrote this line: `wire:model.live="'$options'"`

You should write it like this: `wire:model.live="options"`

**Comment by nastoychev** [comment]
> @nastoychev I think the problem is how you wrote this line: `wire:model.live="'$options'"`
> 
> You should write it like this: `wire:model.live="options"`

No, it does not work.
  
P.p.  This reproduction example is one of the many attempts to be copied.  I will change the description.

Thank you for that suggestion.

**Comment by viliusvsx** [comment]
@nastoychev I don't understand why you wrote a dollar sign in `wire:model.live`. As I can see in your updated code version, an error will still occur if you do not remove the dollar sign

**Comment by nastoychev** [comment]
> @nastoychev I don't understand why you wrote a dollar sign in `wire:model.live`. As I can see in your updated code version, an error will still occur if you do not remove the dollar sign

Thanks a lot for your review and taking care of the correctness. Now I edited again the example where I added simple submit button which check the $this->options.
Still not filling it with chosen options.

Perhaps I saw that in the documentation page there are no examples to the selects with wire:model.live and if it's not integrated we need to know and take care of it.  I guess the problem is deeper, because our components are pretty complicated behind the scene. 
So if @PH7-Jack  write also some suggestions will be helpful. 
![image](https://github.com/wireui/wireui/assets/41673191/82852622-0674-4c2a-ac43-e1379b999d1b)

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
