### ISSUE TITLE
Problem viewing content below the select component

### ISSUE THREAD

**Issue by felipeArnold** [PH7-Jack/livewire-ui#835]
**Describe the bug**
When clicking on the select component to view the options, it only displays a preview and disappears, generating an error in the console as shown in the image, the same happens in the dropdown and datetime picker components

**Expected behavior**

**Screenshots or Videos**
![image](https://github.com/wireui/wireui/assets/44820260/80d4bfd2-944a-47f0-9084-38227754b926)

**Dependencies**
 - WireUI Version: 2.X.X
 - Laravel Version: 10.X.X
 - Alpine.js Version: 3.X.X
 - Livewire Version: 3.X.X
 - Lang: pt-Br

**Comment by viliusvsx** [comment]
@felipeArnold Can you show your components code?

**Comment by felipeArnold** [comment]
Checked and found the problem, alpine in version 3 of livewire is automatically included, and there was a call in the app.
