### ISSUE TITLE
V2 - View [components.outline.x] not found.

### ISSUE THREAD

**Issue by gbrits** [PH7-Jack/livewire-ui#837]
I'm getting 

```
View [components.outline.x] not found.
```

I tried to publish all relevant assets? Is there something to check here?
Thanks for all the work @PH7-Jack & crew

**Comment by viliusvsx** [comment]
Which component you are trying to access?

**Comment by viliusvsx** [comment]
@gbrits Which component you are trying to access?

**Comment by titonova** [comment]
@gbrits That's because v2 uses [heroicon v2](https://heroicons.com/), which replaced the `x` icon with `x-mark`

![image](https://github.com/wireui/wireui/assets/41286822/ff839798-1595-4cee-9662-83d1653bf985)

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
