### ISSUE TITLE
The URL is not implemented correctly while using @wireUiScript and @wireUiStyles

### ISSUE THREAD

**Issue by oliveflow** [PH7-Jack/livewire-ui#84]
**Describe the bug**
When I use @wireUiScripts and @ @wireUiStyles the URL output is as following pic.
![image](https://user-images.githubusercontent.com/82707769/135752860-f07dc0d7-f63f-45b4-8bbf-952ee12baa83.png)

URL Demo = http://localhost:8000/http://:/wireui/assets/scripts#?id=321b1add183dd4202271

there is extra "http://:/" in url.

It's same for styles in <head>
Please help me.

**To Reproduce**
1. Create new Laravel project.
2. Add "@wireUiScripts" and "@wireUiStlyles" in app.blade.php.
3. open in browser.
4. Inspect at place of "@wireUiScripts" and "@wireUiStlyles"

**Expected behavior**
The URL should be "http://localhost:8000/wireui/assets/scripts#?id=321b1add183dd4202271"

**Screenshots**
![image](https://user-images.githubusercontent.com/82707769/135753021-b9ddcbd6-6ed9-498d-933a-3aa8d02cdce8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
I tried in almost every browser like Firefox, etc.

**Comment by ph7jack** [comment]
Hello @Kevinjn0123 
Can you test the route in the tinker?
` route('wireui.assets.scripts')`

**Comment by oliveflow** [comment]
It outputs correct path,
`"http://localhost:8000/wireui/assets/scripts"`.

Thanks. But can you please tell what is causing the problem.

**Comment by Kevinjn0123** [comment]
It is causing errors, 
![image](https://user-images.githubusercontent.com/82707769/135847692-3487b9ec-d9eb-47a6-9e4a-a7f8801394ca.png)

**Comment by Kevinjn0123** [comment]
It ouputs error,

![image](https://user-images.githubusercontent.com/82707769/135849557-7f4ba82f-3873-4c67-abb0-e9de30731056.png)


![image](https://user-images.githubusercontent.com/82707769/135849748-cdf0fb28-55e2-42d4-b647-ab0485c8f115.png)

**Comment by oliveflow** [comment]
@PH7-Jack 
It ouputs error,

![image](https://user-images.githubusercontent.com/82707769/135849557-7f4ba82f-3873-4c67-abb0-e9de30731056.png)


![image](https://user-images.githubusercontent.com/82707769/135849748-cdf0fb28-55e2-42d4-b647-ab0485c8f115.png)

**Comment by trippo** [comment]
Also for me the blade directive print https://www.domain.com/wireui/assets/js/wireui.js?id=ed17caacb0a44cec1adb and the route('wireui.assets.scripts') print https://www.domain.com/wireui/assets/scripts

**Comment by trippo** [comment]
There was the view cache, i resolved with `php artisan view:clear`

**Comment by oliveflow** [comment]
Thanks!..👍

**Comment by ph7jack** [comment]
@trippo thanks you
