### ISSUE TITLE
V2 laggy and slow on chrome without hardware acceleration

### ISSUE THREAD

**Issue by anhofmann** [PH7-Jack/livewire-ui#840]
**Describe the bug**
When the blink engine (chrome, vivaldi, edge etc.) runs without hardware acceleration, the V2 website is almost unusable. This is the only website, where I saw my browser render with such low fps.

**To Reproduce**
1. Disable hardware acceleration on a blink browser
2. watch how https://wireui.dev renders slooooow

**Expected behavior**
Since all other websites on the internet render with good, or okayish fps, I'm concerned that the upgrade to V2 will slow the websites down, where I'm using wireui. 

**Screenshots or Videos**
See Video: https://youtu.be/d3d9wP2gw5Q
The video is made on a beefy laptop (Intel i7-12700H, 32 GB RAM, nvme storage), and as one can see, other websites render fine. Even on the filament website, all the animations are rendered with good enough fps.

**Dependencies**
 - WireUI Version: 2

**Desktop (If applicable, please complete the following information):**
 - OS: linux, kernel 6.1, wayland
 - Browser: chrome
 - Version 119

**Additional context**
I love wireUI and I hope that the solution to this ticket is something like "oh, there is some javascript loop going rogue on the website, it has nothing to do with wireui V2" :-)

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.

**Comment by anhofmann** [comment]
Thank you for your work on WireUI and releasing version 2!

I went to https://wireui.dev/ with my gpu-rendering disabled browser and the website shows the same laggy behavior.
