### ISSUE TITLE
[V2] Unable to locate some components

### ISSUE THREAD

**Issue by buenojosias** [PH7-Jack/livewire-ui#843]
Some components and icons are not available in version 3. Below are some examples.
I saw that they are in the Vendor folder, but they are still not recognized.

Unable to locate a class or view for component [wireui::icons.outline.cloud-arrow-up].
Unable to locate a class or view for component [modal-card].
Unable to locate a class or view for component [alert].

**Comment by abbasmashaddy72** [comment]
Password is also showing same:

`Unable to locate a class or view for component [password]`

It is working when I am using `inputs.password`

**Comment by buenojosias** [comment]
Eu descobri a causa do problema.
Ao acessar o site oficial do pacote, somos direcionados à documentação da versão 2. Porém ao executar o comando `composer require wireui/wireui` é instalada a versão 1, que não possui a maioria dos componentes da versão 2.
