### ISSUE TITLE
Link to Docs is broken on md

### ISSUE THREAD

**Issue by dfikeda** [PH7-Jack/livewire-ui#845]
A Link to the documentation is broken:
Please visit our [Get Started](https://wireui.dev/docs/get-started) page for requirements and a step-by-step installation guide.

Currectly:
Please visit our [Get Started](https://v1.wireui.dev/docs/get-started) page for requirements and a step-by-step installation guide for V1 (recomended use) or;
Visit our [Documentation](https://wireui.dev/getting-started) page for V2 (This is a work in progress).

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
