### ISSUE TITLE
Alpine Expression Error: wireui_modal is not defined  Expression: "wireui_modal({         show: false,                     model:     JSON.parse(atob('eyJuYW1lIjoibW9kZWwiLCJkaXJlY3RpdmUiOiJ3aXJlOm1vZGVsLmRlZmVyIiwidmFsdWUiOiJjcmVhdGVNb2RhbCJ9'))            })"

### ISSUE THREAD

**Issue by rahmannudn** [PH7-Jack/livewire-ui#847]
I have installed wireUI and followed all the steps from https://v1.wireui.dev/docs/get-started.

After the page loads, the modal that I use automatically shows, and after I close it, I cannot open it anymore. Anyone can please tell me the problem.🙏

Here's the error message on the console. 
<img width="960" alt="image" src="https://github.com/wireui/wireui/assets/52528984/7e4d362e-6e97-47af-8874-3eb439b84485">

the blade file : 
<img width="717" alt="image" src="https://github.com/wireui/wireui/assets/52528984/d1b3c464-e9b6-4d59-8601-45d62a4fd9a1">

app.blade.php (inside head tag)
  ```
 @livewireStyles
    @wireUiScripts
    <script src="//unpkg.com/alpinejs" defer></script>

    @vite(['resources/css/app.css', 'resources/js/app.js'])
    @livewireScripts
```
    
code inside app.js :
`import "./bootstrap";
import "flowbite";
import "./../../vendor/power-components/livewire-powergrid/dist/powergrid";
import "./../../vendor/power-components/livewire-powergrid/dist/tailwind.css";
`

**Comment by woweya** [comment]
Same problem as you, did you find out?

**Comment by rahmannudn** [comment]
just delete the alpine js script tag and make sure you follow this step https://v1.wireui.dev/docs/get-started correctly

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
