### ISSUE TITLE
Search in async-search is not working on views

### ISSUE THREAD

**Issue by mmuqiitf** [PH7-Jack/livewire-ui#849]
**Describe the bug**
Hello, i have a problem when i use async search the search in API is working, but the response is not applied to option select and still all options is appeared

**To Reproduce**
1. Create API like this :
![image](https://github.com/wireui/wireui/assets/24507383/a6d81cc2-e204-4400-851e-2b25b41a589d)

2. The response is good
![image](https://github.com/wireui/wireui/assets/24507383/6a442dc2-ba41-4e52-af87-c9b60f2edee3)

3. The option select is still like this :
![image](https://github.com/wireui/wireui/assets/24507383/ed8a35b1-3ef8-41a4-a6d2-3018af48ab00)

**Expected behavior**
It should appeared a select option based on response

**Dependencies**
 - WireUI Version: ^1.18
 - Laravel Version: ^10.10
 - Alpine.js Version: ^3.4.2
 - Livewire Version: ^3.0
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 120.0.2210.133

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
