### ISSUE TITLE
Select component rendered, but dropdown list not showing up

### ISSUE THREAD

**Issue by ldommer** [PH7-Jack/livewire-ui#850]
**Describe the bug**
Pretty much the title.

I installed WireUI as described in the docs and tested the select simple options example by copy and pasting it.

The Select component is rendered in my app, but the dropdown list is not showing up. Or to be more precise: I think it's showing up, because there's a slight flickering if I click the select field, but it seems to have no height or immediately flickering away. No errors in the logs and no errors in the browser console.

**Screenshots or Videos**
![select](https://github.com/wireui/wireui/assets/65616313/0c79c453-4066-4c42-acd7-8c0d290155e4)

**Dependencies**
 - WireUI Version: 1.18.9
 - Laravel Version: 10.39.0
 - Alpine.js Version: 3.13.3
 - Livewire Version: 3.3.5
 - Lang: de_DE

**Desktop**
 - OS: Pop!_OS (Version 22.04)
 - Browser: Firefox, Chromium

**Additional context**
No other JavaScript libraries included than Axios and not much frontend stuff yet, maybe causing an interaction responsible for this. Only some TailwindUI components with some Alpine and a page level Alpine component for the mobile sidebar menu. I already removed it for testing without any effect.

**Comment by dfikeda** [comment]
Can you send part of the code so we can help?

**Comment by dfikeda** [comment]
It is important to note that you are using version 1, please check whether the doc you are viewing is from V1 or V2. For V1 visit:
https://v1.wireui.dev/docs/get-started

**Comment by shamil8124** [comment]
This happens with extra browser extensions. Try it in incognito.

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
