### ISSUE TITLE
How pass parameters to modal?

### ISSUE THREAD

**Issue by LeoMachado94** [PH7-Jack/livewire-ui#855]
I need pass parameters to modal, and I tried many ways to this, but without success.

**Comment by dfikeda** [comment]
Prease verify if the documentation if it is relative for your version.
The default instalation, installs the V1, and documentation is default for v2.
Additionally, you must fill in the information in order to assist you in what you are actually trying to do, for example, what are these parameters?

**Comment by LeoMachado94** [comment]
Right, I installed it as the v2 documentation asks, and in my composer I have "wireui/wireui": "^1.18".
@dfikeda The documentation says that we can invoke $openModal('modal-name'). In this scenario, I have a modal that is used to exclude users, and I would like to use the same modal just informing the user's ID. I wouldn't like to have 10 exclusion modes for a list of 10 users, I understand that there would be too many unnecessary components.
I would like to do something like $openModal('delete-users', $userId).

**Comment by LeoMachado94** [comment]
At the moment I am using it as shown in the image below, but I understand that it would be much better to have 1 deletion modal component that would be reused for any user that needs to be removed, and not 10 components (1 for each user).
<img width="921" alt="Screenshot 2024-01-20 at 21 45 16" src="https://github.com/wireui/wireui/assets/11590935/162c5ae7-b68c-42c9-9bfa-01d7894b6484">

**Comment by dfikeda** [comment]
You can use this package to dinamic modal:
https://github.com/wire-elements/modal

**Comment by LeoMachado94** [comment]
I thought about using it, I already use it in other projects. But ideally, wireui would do this too.
Do you see any performance problems using it as shown in the image?

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
