### ISSUE TITLE
We come back!

### ISSUE THREAD

**Issue by joaopalopes24** [PH7-Jack/livewire-ui#857]
The year 2023 was a year of a lot of learning, but a very difficult year for us at WireUi. Pedro and I went through family problems and exhaustion at work too. We are returning to our activities with full force, and I thank all those who still use and believe in our product.

Thank you!

**Comment by buenojosias** [comment]
Que bom ter notícias! Estou realmente muito entusiasmado para o lançamento da nova versão.
Tentei usar outras bibliotecas, mas WireUI é a melhor.

**Comment by holiq** [comment]
Where can I find the checkbox component?
