### ISSUE TITLE
Inputs showing touble outlines in Firfox

### ISSUE THREAD

**Issue by sohailsarwar101** [PH7-Jack/livewire-ui#860]
"wireui/wireui": "^2.0.0-beta.0"

![Screenshot 2024-02-02 125209](https://github.com/wireui/wireui/assets/7429069/27051a44-cd19-456c-a4b1-6a87f7bb5cff)

**Comment by buenojosias** [comment]
Same in Edge

**Comment by felipeArnold** [comment]
This problem has already been fixed, I believe it will be updated soon.

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
