### ISSUE TITLE
Datetime picker doesn't get a value

### ISSUE THREAD

**Issue by ariss100** [PH7-Jack/livewire-ui#863]
**Describe the bug**
I am adding a datimepicker 

`        <x-datetime-picker without-time label="Start Date" placeholder="Start Date" wire:model="startDate" />`

I select the date in any way -> button or date pick and the livewire value from dd or from {{ $startDate  }}
is always null 

I also noticed that the same behavior happens on the wireui.dev website in the datetime picker component.

![image](https://github.com/wireui/wireui/assets/52317563/9d066dd6-b4e8-46b1-be4d-3967812efa28)

Event though the date / time is selected the model is null.  

**Dependencies**
 - WireUI Version: 2.0.0-beta.0
 - Laravel Version: 10.10
 - Livewire Version: 3.3.5
 - Lang: en_US

**Desktop**
 - OS: Windows 11 Version 23H2 (Build 22631.3085)
 - Browser: chrome
 - Version 121.0.6167.139 (Official Build) (64-bit) (cohort: Stable)

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
