### ISSUE TITLE
Default selected value not working

### ISSUE THREAD

**Issue by ffaouzif** [PH7-Jack/livewire-ui#867]
**Describe the bug**
A select component does not display selected values from livewire model component.
And not make any change to the binded property.

View : 
```blade.php
<x-select placeholder="Guard" :options="['Web', 'API']" wire:model="guard_name"  />
```

Component :

```php
<?php

namespace App\Http\Livewire;
use Livewire\Component;

class Edit extends Component
{
    public $guard_name = "Web";

    public function render()
    {
        return view('livewire.edit');
    }
}
```

**Expected behavior**
It should select "Web" option, but it does not.

![Capture d’écran du 2024-02-25 02-21-19](https://github.com/wireui/wireui/assets/30390958/49b3dd74-9827-4ea7-a2f6-6ddcdd001b60)

![Capture d’écran du 2024-02-25 02-22-13-2](https://github.com/wireui/wireui/assets/30390958/378ac10e-5054-4427-8629-d1625197e865)

**Dependencies**
 - WireUI Version: 2.X.X
 - Laravel Version: 10.X.X
 - Livewire Version: 3.X.X

**Comment by vlados** [comment]
Any ideas why this bug occur? Possible solution?

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.

**Comment by Umar-Farooq-Shafi** [comment]
Default value is not working

**Comment by Umar-Farooq-Shafi** [comment]
it always selects the first option even the wire:model property has a different value on the mount

**Comment by Uhasith** [comment]
```
 public $workspaces, $workspaceId;
    public function mount()
    {
        $this->workspaces = Auth::user()->currentTeam->owner->workspaces;
        $this->workspaceId = Auth::user()->current_workspace_id;
    }
 ```
 ```
    <div >
    <x-wui-select placeholder="Select a workspace" wire:model="workspaceId">
        @foreach ($workspaces as $workspace)
            <x-wui-select.option label="{{ $workspace['name'] }}" value="{{ $workspace['id'] }}"  />
        @endforeach
    </x-wui-select>
</div>
```

Same Problem here. The default value has not been selected.  @joaopalopes24

**Comment by carbtest** [comment]
closed complete? issue persists

**Comment by ph7jack** [comment]
@carbtest  It was closed because the issue was not identified on our end. We would be happy if you could provide more information on how to reproduce the issue.
