### ISSUE TITLE
Page Scroll To Top Automatically After Selected

### ISSUE THREAD

**Issue by tranhuungan1990** [PH7-Jack/livewire-ui#874]
![chrome-capture-2024-3-19](https://github.com/wireui/wireui/assets/42708336/14a60e6c-ab13-4143-885c-27de50899672)

Livewire Component
```
public array $quanhuyen = [];
$tinhthanh = Province::get()->toArray();

public function updatedTinhThanh()
{
    $this->quanhuyen = District::select('id', 'name')->where('province_id', $this->tinh_thanh)->get()->toArray();
}
```

Blade View
```
<x-select
    label="Tỉnh/Thành phố"
    wire:model.live="tinh_thanh"
    :options="$tinhthanh"
    option-label="name"
    option-value="id"
/>
```
How to stop automatically scrolling to the top of the page? Thank you!

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.

**Comment by oti215** [comment]
this is still happening in Livewire V3 + Laravel 11 + Tailwindcss 3
