### ISSUE TITLE
DateTimepicker  Error date is not defined

### ISSUE THREAD

**Issue by Jhamnerx** [PH7-Jack/livewire-ui#879]
**Describe the bug**

![image](https://github.com/wireui/wireui/assets/30221273/b1e8d2d3-54aa-496e-9744-c7d305fb6b67)
I get the following error when opening the modal containing the datetimepicker component

**To Reproduce**
![image](https://github.com/wireui/wireui/assets/30221273/5885c129-3ebc-4771-9e30-db82ca893f8a)

**Dependencies**
 - WireUI Version:  v1.19.0  
 - Laravel Version: 10.48.4
 - Alpine.js Version: include in livewire
 - Livewire Version: v3.4.9  
 - Lang: en_US

**Comment by kennyelliott** [comment]
I'm having the same issue with the datetime picker.

**Comment by Jhamnerx** [comment]
The error only happens when in a modal that is opened from livewire

**Comment by django-wong** [comment]
Maybe a workaround here if you are using `wire:model="show_my_modal"` with the modal component.

Firstly, use the live modifier `wire:model.live="show_my_modal"`

Then wrap your content that contains the date picker with a `@if` statement like:

```blade
<x-wireui-modal.card wire:model.live="show_my_modal">
    @if($show_my_modal) 
        <<x-wireui-datetime-picker />
    @endif
</x-wireui-modal.card>
```

**Comment by Jhamnerx** [comment]
I am using wire:model.live.
I'm going to try with @if

**Comment by KevinEscobarV** [comment]
In fact, the error occurs when trying to update the date from the backend, does anyone have a solution to this?

**Comment by caiochami** [comment]
I have the same issue. It started to happen after upgrading Livewire to "v3.4.11"  from "v3.4.4".

![image](https://github.com/wireui/wireui/assets/17772351/6c334324-45f9-425a-8826-2deeea9e4c26)

![image](https://github.com/wireui/wireui/assets/17772351/146bdeb6-af37-41fb-9246-379df2c50d1e)

![image](https://github.com/wireui/wireui/assets/17772351/3eaf0751-1a18-4b49-a5e1-696a30525118)

![image](https://github.com/wireui/wireui/assets/17772351/b54452bf-dab0-4c2c-9a70-35b45e9ad077)

**Comment by caiochami** [comment]
Any updates on this?

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
