### ISSUE TITLE
There aren't alerts components

### ISSUE THREAD

**Issue by gatubela3008** [PH7-Jack/livewire-ui#885]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Dependencies**
 - WireUI Version: 1.X.X
 - Laravel Version: 9.X.X
 - Alpine.js Version: 3.X.X
 - Livewire Version: 2.X.X
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - Browser: [e.g. chrome, safari]

**Smartphone (If applicable, please complete the following information):**

**Additional context**

**Comment by asciende** [comment]
I'm experiencing the same issue, <x-alert title="Success Message!" positive flat /> presents the following error: 'unable to locate a class or view for component [alert].' Other components work correctly.
i'm using laravel 11

**Comment by joaopalopes24** [comment]
The alert component has only in version 2.
