### ISSUE TITLE
Inline Error Message persists in Combination w/ Livewire

### ISSUE THREAD

**Issue by smnmsr** [PH7-Jack/livewire-ui#886]
**Describe the bug**
When using WireUI in combination with Livewire, I'm encountering problems with the inline validation message. Whenever the Validation error is resolved, the corresponding input correctly is reformatted to an error free state. However, the validation error message persists.

**To Reproduce**
1. Go to [this site](https://hfm.rt25.ch/sportlerin-werden)
2. Enter some invalid email address in the field *E-Mail* (e.g. "john@doe.")
3. See the inline validation message "Bitte gib eine gültige E-Mail-Adresse ein." and the field being formatted red
4. Enter a valid email address instead (e.g. "john@doe.com")
5. See the field being reformatted to normal but the message *persisting*.

**Expected behavior**
As soon as the validation error is resolved, the validation error message should disappear.

**Dependencies**
 - WireUI Version: 1.19.0
 - Laravel Version: 11.7.0
 - Alpine.js Version: 3.13.10
 - Livewire Version: 3.4.12
 - Lang: de_DE

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
