### ISSUE TITLE
Datetime picker doesn't get value if property array

### ISSUE THREAD

**Issue by Akhmami** [PH7-Jack/livewire-ui#887]
**Describe the bug**
Datetime picker doesn't get value if property array

**To Reproduce**
// my form object component
`public $data = [];`

// blade 
`<x-datetime-picker wire:model="form.data.date" />`

**Dependencies**
 - WireUI Version: 1.19
 - Laravel Version: 11.0
 - Alpine.js Version: 3.4.2
 - Livewire Version: 3.4

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
