### ISSUE TITLE
Add css class to select slot

### ISSUE THREAD

**Issue by willmkt** [PH7-Jack/livewire-ui#892]
Is there a way to add css class to a select slot?

Something like this: 
            <x-select label="Associar com DRE"
                      placeholder="Select one status"
                      wire:model.defer="category.dre">
                <x-select.option class"!bg-green-300 !text-green-600"
                                 label=""
                                 value="1" />
            </x-select>

This code does not work

Example:
<img width="282" alt="Screenshot 2024-05-29 at 00 01 44" src="https://github.com/wireui/wireui/assets/4371439/e3530d04-b6f6-4d6c-bc38-1b5e1443be40">

Thanks

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.
