### ISSUE TITLE
Unable to locate a class or view for component [alert].

### ISSUE THREAD

**Issue by mostafa-amine** [PH7-Jack/livewire-ui#895]
I installed the package properly but i get this error Unable to locate a class or view for component [alert].

Here is the link of the [error](https://flareapp.io/share/v5perW2m).

**Comment by mostafa-amine** [comment]
Code used:
```html
<x-app-layout>
    <x-alert title="Any Message!" />
</x-app-layout>
```

**Comment by mostafa-amine** [comment]
I just searched in the vendor folder for an alert component and found nothing

Is it a version issue ?.

![image](https://github.com/wireui/wireui/assets/90805670/70d18971-9e4c-4d83-88f3-e9e1149144f0)

**Comment by joaopalopes24** [comment]
The alert component has only in version 2.
