### ISSUE TITLE
Wrong text color in native-select and textarea in dark mode

### ISSUE THREAD

**Issue by Luoti** [PH7-Jack/livewire-ui#906]
**Describe the bug**
In dark mode the textarea and native-select have dark text too.

**To Reproduce**
Check here with dark mode: https://wireui.dev/components/native-select
![image](https://github.com/wireui/wireui/assets/1344148/7e6cce3d-dd37-4b12-833f-02b779b4c4e7)

Check here with dark mode: https://wireui.dev/components/textarea
![image](https://github.com/wireui/wireui/assets/1344148/9417e7da-1169-4507-86f0-4e0a7cfaf5e7)

**Expected behavior**
Text color should be same as with other inputs.

**Dependencies**
 - WireUI Version: 2.0

**Desktop (If applicable, please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version 125
 - 
**Additional context**

I can try to make a PR for this, but I think it's such an easy fix that it will be fixed before that. 😁

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

I will try to fix this bug in the next version.

**Comment by Luoti** [comment]
Thank you for creating the project! 🙏
