### ISSUE TITLE
Can't use multiple maskable inputs

### ISSUE THREAD

**Issue by caiochami** [PH7-Jack/livewire-ui#913]
**Describe the bug**
The format of values displayed by all maskable inputs is the same.

**To Reproduce**
1. Add multiple maskable inputs in the page like so
```
<x-phone
                emit-formatted
                wire:loading.attr="disabled"
                :disabled="! $can"
                :label="__('Phone number')"
                name="form.phone_number"
                wire:model="form.phone_number"
                :placeholder="__('Enter a phone number')"
                :mask="['(##) ####-####', '(##) # ####-####']"
            />

<x-maskable
                    wire:loading.attr="disabled"
                    :label="__('Postal code')"
                    name="form.address.postal_code"
                    wire:model.blur="form.address.postal_code"
                    :mask="'#####-###'"
                    :disabled="! $can"
                    placeholder="00000-000"
                />
```

**Expected behavior**
Every input should have values in a unique format.

**Screenshots or Videos**
![image](https://github.com/wireui/wireui/assets/17772351/c8ab509a-6545-4b0c-a983-ff42414d597d)

**Dependencies**
 - WireUI Version: 2.0.2
 - Laravel Version: 11.11.1
 - Livewire Version: 3.5.1
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: Ubuntu
 - Browser:Chrome

**Comment by ph7jack** [comment]
Thanks for contributing. It is now fixed. Update to the latest release.
