### ISSUE TITLE
Update getting started documentation

### ISSUE THREAD

**Issue by cristhianjhlcom** [PH7-Jack/livewire-ui#915]
I did a fresh installation of Laravel with Livewire and Breeze, and I also followed the step-by-step installation of WireUI. However, some components like colors were not rendering correctly.

After investigating, I realized that my `tailwind.config.js` was missing an import in the `content[]` array: `./vendor/wireui/wireui/resources/**/*.blade.php`. Is this missing for a specific reason, or did I do something wrong?

If necessary, you can add this import line to the documentation.

![image](https://github.com/wireui/wireui/assets/68720424/e542f2ef-1662-4943-a6f6-f361ea67ac05)

## Before resources blade line

![image](https://github.com/wireui/wireui/assets/68720424/f5045ced-d2dd-4dd4-ac60-42118707cb88)

## After resources blade line

![image](https://github.com/wireui/wireui/assets/68720424/b8834a8d-80c3-4ee1-85cc-fa4f42f360f6)

![image](https://github.com/wireui/wireui/assets/68720424/e0d1bb79-76f5-481b-a241-3d58845ba9b2)

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

It's probably some configuration in your project, as this resources folder does not exist in version 2.
