### ISSUE TITLE
Mentioning Users using @ symbol

### ISSUE THREAD

**Issue by Uhasith** [PH7-Jack/livewire-ui#916]
**Feature Request: User Mentioning Inside an Input Text Field**

Is your feature request related to a problem? Please describe.
I'm always frustrated when I can't easily mention users inside an input text field in our application. It makes communication and collaboration less efficient because users have to manually type out usernames or other identifiers.

**Describe the solution you'd like**

I would like to have a feature that allows users to mention other users inside an input text field by typing "@" followed by the user's name. This feature should provide an autocomplete dropdown with a list of users that match the typed characters. Once a user is selected from the dropdown, their name should be inserted into the input field at the current cursor position.

**Describe alternatives you've considered**

Using a Textarea: Implementing this feature in a textarea instead of an input field. However, this doesn't meet the requirements for certain use cases where only a single line input is appropriate.
External Libraries: Utilizing external libraries for mentions, but they might not integrate well with Livewire and Alpine.js.

Ex :-  [https://gist.github.com/fotrino/2c2dfb35a581612da0de68299150d5da](url)

**Comment by joaopalopes24** [comment]
Thanks for your pull request to WireUi!

We think this feature is not essential for WireUi. You can add this feature to your own code, or we further describe the actual need for this feature.
