### ISSUE TITLE
WireUi not working in the server!

### ISSUE THREAD

**Issue by Minhazul-Islam18** [PH7-Jack/livewire-ui#917]
Hello, I'm using WireUi for the first time and it's great. But after uploading to the live server, I've found something strange.

Local environment & Mozilla or Edge: Modal, Dropdown & everything from WireUi working
![image](https://github.com/wireui/wireui/assets/85400832/3d98f0a7-41e4-45ca-822d-a1e9bf4e7dc0)

& it's live server with Edge: Modal, Dropdown & nothing from WireUi working
![image](https://github.com/wireui/wireui/assets/85400832/299546be-5d86-408d-8cd9-df99b530c116)

**Dependencies**
 - WireUI Version: "^1.18"
 - Laravel Version: "^10.10"
 - Alpine.js Version: Shipped with Livewire
 - Livewire Version: "^3.3.3"
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: [Windows]
 - Browser: [chrome, edge]
 - Version [latest]

**Comment by ph7jack** [comment]
Could you please update the latest WireUi v1 version?

**Comment by Minhazul-Islam18** [comment]
I upgraded it to "^1.19.2" and it's still same, not working!!


https://github.com/wireui/wireui/assets/85400832/e403e9a3-772d-4bab-a554-6b3414748a48



Working in Local:
![image](https://github.com/wireui/wireui/assets/85400832/b1b99068-163d-498e-ae1c-26ed98b2bc38)

Not working in the live:
![image](https://github.com/wireui/wireui/assets/85400832/a807b55b-b90f-4905-966a-9ce615c84208)

**Comment by Minhazul-Islam18** [comment]
Jetstream Profile page (Local and Server Everywhere):
[console-export-2024-6-27_0-14-28.txt](https://github.com/user-attachments/files/15993645/console-export-2024-6-27_0-14-28.txt)

**Comment by joaopalopes24** [comment]
Does it work normally in the local environment?

**Comment by Minhazul-Islam18** [comment]
> Does it work normally in the local environment?

Yes, it is ok in the Local environment! You can check my previous attachments.

**Comment by joaopalopes24** [comment]
Have you checked to see if the script file is showing up in production?

Open the WireUi scripts link.

**Comment by ph7jack** [comment]
Are you importing wireui on the page head?

**Comment by Minhazul-Islam18** [comment]
> Are you importing wireui on the page head?

Yes, I did.



> Have you checked to see if the script file is showing up in production?
> 
> Open the WireUi scripts link.

Yes, You can check. [link: -> view-source:https://easyems.rctseba.com/school/collect-fees]

**Comment by ph7jack** [comment]
@Minhazul-Islam18 Wireui routes works in your project, but I've not found the script import in the <head> section.
https://v1.wireui.dev/docs/get-started

**Comment by Minhazul-Islam18** [comment]
> @Minhazul-Islam18 Wireui routes works in your project, but I've not found the script import in the section. https://v1.wireui.dev/docs/get-started

### layout.blade.php
```php
<!DOCTYPE html>
<html lang="en" data-layout="horizontal" data-topbar-color="dark">

<head>
    <meta charset="utf-8" />
    <title>{{ $title ?? config('app.name') }} - {{ config('app.name') }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="/storage/{{ setting('favicon') }}" />

    {{-- <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.13.3/dist/cdn.min.js"></script> --}}
    <!-- App css -->
    <link href="{{ asset('backend/assets/css/app.min.css') }}" rel="stylesheet" type="text/css" />

    <!-- Icons css -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/7.2.96/css/materialdesignicons.min.css"
        integrity="sha512-LX0YV/MWBEn2dwXCYgQHrpa9HJkwB+S+bnBpifSOTO1No27TqNMKYoAn6ff2FBh03THAzAiiCwQ+aPX+/Qt/Ow=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Theme Config Js -->
    <script src="{{ asset('backend/assets/js/config.js') }}"></script>
    @vite('resources/css/app.css')
    @livewireStyles
    @stack('page-style')
    <wireui:scripts />
</head>

<body>
    <div class="flex wrapper">
        <div class="app-menu">
            <!--- Menu -->
            @include('layouts.backend.admin.sections.simplebar')
        </div>
        <!-- ============================================================== -->
        <!-- Page Content here -->
        <!-- ============================================================== -->

        <div class="page-content">
            <!-- Topbar Start -->
            @include('layouts.backend.admin.sections.header')
            <!-- Topbar End -->

            {{ $slot }}

            <!-- Footer Start -->
            @include('layouts.backend.admin.sections.footer')
            <!-- Footer End -->
        </div>


        <!-- ============================================================== -->
        <!-- End Page content -->
        <!-- ============================================================== -->
    </div>

    <!-- Theme Settings -->
    <div>
        <!-- Theme Settings Offcanvas -->
        @include('layouts.backend.admin.sections.customizer')
    </div>
    <!-- Plugin Js -->
    <script>
        window.addEventListener('beforeunload', function(e) {
            sessionStorage.clear();
        });
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
        integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/simplebar/6.2.5/simplebar.min.js"
        integrity="sha512-HV1U44HR4mYVDcsxzJpghYyGEy2PvbePe9UFXlV3vnzf4yFhbKA9QNpnhy4VWwnaC2jKzijITVWHPZBCOuc51g=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://unpkg.com/lucide@latest"></script>
    <script src="{{ asset('backend/assets/libs/%40frostui/tailwindcss/frostui.js') }}"></script>

    <!-- App Js -->
    <script src="{{ asset('backend/assets/js/app.js') }}"></script>

    <!-- Dashboard App js -->
    {{-- <script src="{{ asset('backend/assets/js/pages/dashboard.init.js') }}"></script> --}}
    @livewireScripts
    @livewire('livewire-ui-modal')
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <x-livewire-alert::scripts />
    @stack('page-script')
</body>

</html>
```

**Comment by joaopalopes24** [comment]
Put WireUi scripts after `@stack('page-script')`, please.

**Comment by Minhazul-Islam18** [comment]
Wow! It works.  @joaopalopes24  Thank you.

But Docs mentioned to put this script inside Head!

**Comment by joaopalopes24** [comment]
Most front-end tools today recommend inserting styles and scripts in the head. The WireUi script is ideally placed after the Livewire script.
