### ISSUE TITLE
[v2] DateTimePicker cannot changed to 24h time format

### ISSUE THREAD

**Issue by maatien** [PH7-Jack/livewire-ui#919]
**Describe the bug**

According to the documentation, the `time-format` can be changed from 12 to 24 hours.
Unfortunately, settings this property has no effect on the time picker, as it remains on 12 hours with AM/PM switch.

**To Reproduce**
```html
<x-ui-datetime-picker time-format="24" label="Start" wire:model="entry.event_date_start"/>
```

```html
<x-ui-datetime-picker :time-format="24" label="Start" wire:model="entry.event_date_start"/>
```

**Expected behavior**
The time picker should switch to 24 hours.

**Dependencies**
 - WireUI Version: 2.0.3
 - Laravel Version: 11.12.0
 - Alpine.js Version: 3.14.1
 - Livewire Version: 3.5.1
 - Lang: de_DE

**Desktop (If applicable, please complete the following information):**
 - OS: MacOS 14.5
 - Browser: Chrome
 - Version 126

**Comment by ph7jack** [comment]
Hi @maatien , in the v2 we are using the attribute `military-time` instead. Thanks
