### ISSUE TITLE
How to close or dismiss a dialog

### ISSUE THREAD

**Issue by willmkt** [PH7-Jack/livewire-ui#922]
**Describe the bug**
I need to close the dialog by firing a event, but I can't find anything on how to do it.

**To Reproduce**
```
                    window.$wireui.confirmDialog({
                        title: info.event.title,
                        description: customHtml,
                        icon: 'question',
                        accept: {
                            label: 'Agenda Paciente',
                            url: info.event.extendedProps.url,
                        },
                        reject: {
                            label: 'Fechar',
                        },

                    })

```
**Expected behavior**

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Dependencies**
 - WireUI Version: 1.X.X
 - Laravel Version: 9.X.X
 - Alpine.js Version: 3.X.X
 - Livewire Version: 2.X.X
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - Browser: [e.g. chrome, safari]

**Smartphone (If applicable, please complete the following information):**

**Additional context**

**Comment by ph7jack** [comment]
Hi @willmkt , you cannot close a dialog from an event, use the `accept` and `reject` actions to perform an action and close.
The dialog is used to have an action confirmation from the user, if you need to manually open and close, use a modal instead
