### ISSUE TITLE
Tailwind build error

### ISSUE THREAD

**Issue by MdBayzidAman** [PH7-Jack/livewire-ui#924]
**Describe the bug**
I followed the installation process from the documentation. But after installation, running `npm run dev` or `npm run build` returns the error below.

```
.../resources/css/app.css:3:1: The `bg-secondary-200` class does not exist. If `bg-secondary-200` is a custom class, make sure it is defined within a `@layer` directive.
  Plugin: vite:css
```

**To Reproduce**
Here is my tailwind.config.js code.

import defaultTheme from "tailwindcss/defaultTheme";
import forms from "@tailwindcss/forms";
import typography from "@tailwindcss/typography";

```
/** @type {import('tailwindcss').Config} */
export default {
    presets: [require("./vendor/wireui/wireui/tailwind.config.js")],
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./vendor/laravel/jetstream/**/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",

        "./vendor/wireui/wireui/src/*.php",
        "./vendor/wireui/wireui/ts/**/*.ts",
        "./vendor/wireui/wireui/src/WireUi/**/*.php",
        "./vendor/wireui/wireui/src/Components/**/*.php",
    ],
...

```

**Expected behavior**

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Dependencies**
 - WireUI Version: 2.0.3
 - Laravel Version: 10.48.2
 - Alpine.js Version: 3.X.X
 - Livewire Version: 3.5.1
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: Windows
 - Browser: [e.g. chrome, safari]

**Smartphone (If applicable, please complete the following information):**

**Additional context**

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We carried out tests and this feature is working normally, please check the documentation at:

https://wireui.dev/getting-started#installation
https://wireui.dev/customize#colors

**Comment by web2soft** [comment]
same error for me

**Comment by MdBayzidAman** [comment]
@web2soft 
Apologies for the late response, hopefully, this will also help others.

I solved this by modifying my main tailwind config, like this

```
    theme: {
        extend: {
            colors: {
                // WireUi
                primary: colors.indigo,
                secondary: colors.slate,
                positive: colors.emerald,
                negative: colors.red,
                warning: colors.amber,
                info: colors.blue,

               //  your others config...
```
