### ISSUE TITLE
Numbers: Minus button deactivated for "min" attribute

### ISSUE THREAD

**Issue by TiboriusDev** [PH7-Jack/livewire-ui#933]
```html
<x-number label="Max. chambers" min="1" wire:model="max_chambers" placeholder="" />
```

When specifying the "min" attribute, the minus button is deactivated. Only when I click once on the plus button can I use the minus button again.

![image](https://github.com/wireui/wireui/assets/39419335/7f4f2868-70e0-47de-9ab8-62f9591611a4)

**Dependencies**
 - WireUI Version: v2.0.1 
 - Laravel Version: v11.10.0
 - Livewire Version: v3.5.0

**Comment by joaopalopes24** [comment]
Thank you for using WireUi! We fixed this issue.

**Comment by MattiaMarchiorato** [comment]
This is happening else when manually change the value, for example: 

https://github.com/user-attachments/assets/3249361b-61f4-4dfe-854e-4b8b76cc7dbb
