### ISSUE TITLE
[v2] PHPStorm doesnt recognize the components

### ISSUE THREAD

**Issue by patrickweh** [PH7-Jack/livewire-ui#934]
**Describe the bug**
I updated to to wireui v2 in a pretty big project. After the update PHPstorm tells me that all the wireui components are unknown blade components.

**To Reproduce**
just install wireui v2

**Expected behavior**
Propably the ide.json is wrong with v2

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Dependencies**
 - WireUI Version: 2.0.5
 - Laravel Version: 11.15
 - Alpine.js Version: 3
 - Livewire Version: 3
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 126

<img width="566" alt="image" src="https://github.com/wireui/wireui/assets/40495041/50874122-d1c2-43d6-b46c-77efa6021e34">

**Comment by PontifexCert** [comment]
I have the same issue, not sure it helps but some extra info: x-icon does work, the other components do not. 

They render fine in browser, it's just not recognized in IDE and auto-complete doesnt work. Except for Icon.

**Comment by PontifexCert** [comment]
@patrickweh you can temporary fix it like this:
in your config/wireui.php

Comment out:
'components' => Config::defaultComponents([]),

Add:
'components' => [
        'alert' => [
            'class' => Components\Alert\Index::class,
            'alias' => 'alert',
        ],
        'avatar' => [
            'class' => Components\Avatar\Index::class,
            'alias' => 'avatar',
        ],
        'badge' => [
            'class' => Components\Badge\Base::class,
            'alias' => 'badge',
        ],
        'mini-badge' => [
            'class' => Components\Badge\Mini::class,
            'alias' => 'mini-badge',
        ],
        'button' => [
            'class' => Components\Button\Base::class,
            'alias' => 'button',
        ],
        'mini-button' => [
            'class' => Components\Button\Mini::class,
            'alias' => 'mini-button',
        ],
        'card' => [
            'class' => Components\Card\Index::class,
            'alias' => 'card',
        ],
        'checkbox' => [
            'class' => Components\Switcher\Checkbox::class,
            'alias' => 'checkbox',
        ],
        'color-picker' => [
            'class' => Components\ColorPicker\Picker::class,
            'alias' => 'color-picker',
        ],
        'datetime-picker' => [
            'class' => Components\DatetimePicker\Picker::class,
            'alias' => 'datetime-picker',
        ],
        'dialog' => [
            'class' => Components\Dialog\Index::class,
            'alias' => 'dialog',
        ],
        'dropdown' => [
            'class' => Components\Dropdown\Base::class,
            'alias' => 'dropdown',
        ],
        'dropdown.item' => [
            'class' => Components\Dropdown\Item::class,
            'alias' => 'dropdown.item',
        ],
        'dropdown.header' => [
            'class' => Components\Dropdown\Header::class,
            'alias' => 'dropdown.header',
        ],
        'error' => [
            'class' => Components\Errors\Single::class,
            'alias' => 'error',
        ],
        'errors' => [
            'class' => Components\Errors\Multiple::class,
            'alias' => 'errors',
        ],
        'icon' => [
            'class' => Components\Icon\Index::class,
            'alias' => 'icon',
        ],
        'input' => [
            'class' => Components\TextField\Input::class,
            'alias' => 'input',
        ],
        'currency' => [
            'class' => Components\TextField\Currency::class,
            'alias' => 'currency',
        ],
        'maskable' => [
            'class' => Components\TextField\Maskable::class,
            'alias' => 'maskable',
        ],
        'number' => [
            'class' => Components\TextField\Number::class,
            'alias' => 'number',
        ],
        'password' => [
            'class' => Components\TextField\Password::class,
            'alias' => 'password',
        ],
        'phone' => [
            'class' => Components\TextField\Phone::class,
            'alias' => 'phone',
        ],
        'label' => [
            'class' => Components\Label\Index::class,
            'alias' => 'label',
        ],
        'link' => [
            'class' => Components\Link\Index::class,
            'alias' => 'link',
        ],
        'modal' => [
            'class' => Components\Modal\Index::class,
            'alias' => 'modal',
        ],
        'modal-card' => [
            'class' => Components\Modal\Card::class,
            'alias' => 'modal-card',
        ],
        'native-select' => [
            'class' => Components\Select\Native::class,
            'alias' => 'native-select',
        ],
        'notifications' => [
            'class' => Components\Notifications\Index::class,
            'alias' => 'notifications',
        ],
        'radio' => [
            'class' => Components\Switcher\Radio::class,
            'alias' => 'radio',
        ],
        'select' => [
            'class' => Components\Select\Base::class,
            'alias' => 'select',
        ],
        'select.option' => [
            'class' => Components\Select\Option::class,
            'alias' => 'select.option',
        ],
        'select.user-option' => [
            'class' => Components\Select\UserOption::class,
            'alias' => 'select.user-option',
        ],
        'textarea' => [
            'class' => Components\TextField\Textarea::class,
            'alias' => 'textarea',
        ],
        'time-picker' => [
            'class' => Components\TimePicker\Picker::class,
            'alias' => 'time-picker',
        ],
        'time-selector' => [
            'class' => Components\TimePicker\Selector::class,
            'alias' => 'time-selector',
        ],
        'toggle' => [
            'class' => Components\Switcher\Toggle::class,
            'alias' => 'toggle',
        ],
        'popover' => [
            'class' => Components\Popover\Index::class,
            'alias' => 'popover',
        ],
        'switcher' => [
            'class' => Components\Wrapper\Switcher::class,
            'alias' => 'switcher',
        ],
        'text-field' => [
            'class' => Components\Wrapper\TextField::class,
            'alias' => 'text-field',
        ],
    ],

**Comment by ph7jack** [comment]
Hi all, I'll be in touch with the Laravel Idea maintainer to check a way to update it.

**Comment by elicordero111** [comment]
` x-textarea` still doesn't recognize it

**Comment by elicordero111** [comment]
@PontifexCert `x-textarea` still doesn't recognize it

Thank you

**Comment by scripness** [comment]
> Hi all, I'll be in touch with the Laravel Idea maintainer to check a way to update it.

Hi! Any updates on this matter?

**Comment by codifyer** [comment]
I'm seeing the same issue. Any update?

**Comment by ph7jack** [comment]
See the updates here https://github.com/laravel-idea/plugin/issues/947

**Comment by igorvolgin** [comment]
I can confirm that when in config we have 'components' => Config::defaultComponents() - it doesn't work, but when we do 'components' => [
        'alert' => [
            'class' => Alert\Index::class,
            'alias' => 'alert',
        ], ...] - works fine
        
I see one more issue - with prefix. Let's say we have 
    'prefix' => 'wireui',
in that case here IDE will be aware of x-wireui-* components, but it will be an error in render, as render expects x-wireui*...
So if set 'prefix' => 'wireui-' IDE will expect x-wireui--*, render will expect x-wireui-*

**Comment by ph7jack** [comment]
Hi everyone, thanks for waiting.
I've created a PR with [adelf](https://github.com/adelf) suggestion, which looks great. 
Unfortunately, the component properties are not suggested yet, but I believe it will soon be possible.

In the latest release, we will be able to have code completion for wireui components. 
PS: if you use a components prefix/have components renamed, you must run this command: `php artisan wireui:generate-ide-helper-code`
