### ISSUE TITLE
Issues with wireui javascript components

### ISSUE THREAD

**Issue by sloan58** [PH7-Jack/livewire-ui#945]
I've noticed that when using certain wireui components that leverage js under the hood, I'm experiencing some breakage in two situations:

1) Initial login to the application
2) When using wire:navigate to replace a Livewire component in the UI

**To Reproduce**
Login to the application and if there are wireui components using js on the initial page, wireui does not mount correctly and throws console errors.  I've tested with select and time-picker.  The initial page could be the dashboard if this is a fresh login, or another page if the user's session timed out and they are redirected back to their previous page.  The only js file that is fetched in this situation is `http://app.test/wireui/assets/scripts?id=<hash>`.  I'm guessing the subsequent calls to fetch the other js files are prevented due to the console errors.

If you refresh the page manually everything starts working correctly, even wire:navigate.  It's only on the first page load that this happens.  My included repo has two buttons, one that does a full page refresh and one that uses wire:navigate.  If you continue to use wire:navigate after the initial login the wireui components never work, but after one hard refresh or using a nav link that does a full page refresh, everything works.

**Expected behavior**
That the wireui components load successfully on login.

**Screenshots or Videos**
<img width="2368" alt="image" src="https://github.com/user-attachments/assets/1af8a5e2-e512-44a0-80d5-043f6d38b3fb">

<img width="2551" alt="image" src="https://github.com/user-attachments/assets/633f1271-2a68-4c8c-a44d-48b35f45ec93">

**Dependencies**
 - WireUI Version: 2.6.1
 - Laravel Version: 11.2.0
 - Alpine.js Version: 3.14.1
 - Livewire Version: 3.5.4
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: macOS
 - Browser: Chrome and Firefox
 - Version Sonoma 14.5

**Additional context**
There's a sample repo here:

https://github.com/sloan58/tshoot-wireui

It's a basic Laravel setup with Breeze, Livewire and WireUI.  There are two pages, Dashboard and Dashboard-2.  They both have the select and time-picker components.  On login, 99% of the time (there have been a few random instances where the js console throws errors but then seems to recover) the wireui components don't mount properly.  Using the wire:navigate buttons maintains the issue between pages.  Hard reloading the page or using the buttons without wire:navigate causes the js to load properly and then everything works okay.

**Comment by mdjaman** [comment]
Same issue

OS: macOS
Browser: Chrome 
Version Sonoma 14.5

**Comment by sloan58** [comment]
Sorry, this was user error.  I did not include the `<wireui:scripts />` tag in my guest layout, which was also using wire:navigate to push the user to the authenticated page which then never loaded the `<wireui:scripts />` tag.

There are two ways to fix this:

1) Add the `<wireui:scripts />` tag to your guest layout
2) Remove the `navigate: true` option from the `redirectIntended` call in `login.blade.php`. 

```php
    /**
     * Handle an incoming authentication request.
     */
    public function login(): void
    {
        $this->validate();

        $this->form->authenticate();

        Session::regenerate();

        $this->redirectIntended(default: route('dashboard', absolute: false), navigate: true);
    }
    ```

**Comment by mateoetchepare** [comment]
> Sorry, this was user error. I did not include the `<wireui:scripts />` tag in my guest layout, which was also using wire:navigate to push the user to the authenticated page which then never loaded the `<wireui:scripts />` tag.
> 
> There are two ways to fix this:
> 
> 1. Add the `<wireui:scripts />` tag to your guest layout
> 2. Remove the `navigate: true` option from the `redirectIntended` call in `login.blade.php`.
> 
> ```
>     /**
>      * Handle an incoming authentication request.
>      */
>     public function login(): void
>     {
>         $this->validate();
> 
>         $this->form->authenticate();
> 
>         Session::regenerate();
> 
>         $this->redirectIntended(default: route('dashboard', absolute: false), navigate: true);
>     }
>     ```
> ```

thank you very much! i've been like 3 hours searching all across the internet for this lol
