### ISSUE TITLE
Docs Website

### ISSUE THREAD

**Issue by skillcraft-io** [PH7-Jack/livewire-ui#96]
**Not Exactly A Bug **
Trying to access the docs website but the homepage is throwing a 500 and the docs path loads Japanese  site?

**To Reproduce**
1. Go to https://livewire-wireui.com
2. Go To https://livewire-wireui.com/docs

**Expected behavior**
To be able to see the documentation to utilize the package

**Screenshots**
![image](https://user-images.githubusercontent.com/41481716/137741524-9e243943-90e9-4ad7-bd09-d06af1d96aed.png)
![image](https://user-images.githubusercontent.com/41481716/137741591-e9d4c60f-3e0d-4334-95f2-2563618ec6aa.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome & Edge
 - Version Latest

**Comment by ph7jack** [comment]
@zhxscript thanks for reporting this, i will fix it now

**Comment by ph7jack** [comment]
The site is now online
https://livewire-wireui.com

**Comment by ph7jack** [comment]
I apologize for the inconvenience
