### ISSUE TITLE
Number Field - Float Values Validation Issue

### ISSUE THREAD

**Issue by Uhasith** [PH7-Jack/livewire-ui#960]
**Describe the bug**

I am using the WireUI Number component to capture numeric input from users, including floating-point values. However, when a user enters a float, a validation error is triggered. I have already added `step="0.01"` to the input field, but the issue persists.

```
 <x-wui-number label="Small" wire:model="shippings.{{ $key }}.small" placeholder="0"
                            step="0.01" min="0" />
       $rules = [
            'shippings.*.small' => ['required', 'numeric'],
            'shippings.*.letter_box' => ['required', 'numeric'],
            'shippings.*.length' => ['required', 'numeric'],
        ];
```

**Screenshots or Videos**
<img width="610" alt="Screenshot 2024-09-11 at 10 39 48" src="https://github.com/user-attachments/assets/7ee9db2e-aae0-4fa9-ae2a-216a96d10bcb">

**Dependencies**
 - WireUI Version: 2.1.2
 - Laravel Version: 11.22.0
 - Livewire Version: 3.5.6
 - Lang: en_US

**Comment by nguhy** [comment]
I Downgraded to version 2.0.5 to get the expect behavior for the x-input component `<x-input type="number" step=".01"/>`

**Comment by nguhy** [comment]
I Downgraded to version 2.0.5 to get the expect behavior for the x-input component `<x-input type="number" step=".01" ... `

**Comment by ghost** [comment]
I downgraded to version 2.0.5 to get the expected behavior for the x-input component <x-input type="number" step=".01" ...

**Comment by Uhasith** [comment]
Did you able to slove this problem ? @nguhy

**Comment by joaopalopes24** [comment]
Thank you for using WireUi! We fixed this issue.
